<?php
    $companyForm = $this->companyForm;
    $companyForm->prepare();

    $dependentForm = $this->dependentForm;
//    $dependentForm->prepare();
?>

<div class="portlet-body form">
    <?php $companyForm->prepare(); echo $this->form(null, null)->openTag($companyForm) ?>
    <div class="form-body">

        <h4 class="form-section">Identificação</h4>
        <div class="row">
            <div class="col-md-4"><?php echo $this->formRow($companyForm->get('cnpj')); ?></div>
            <div class="col-md-4"><?php echo $this->formRow($companyForm->get('name')); ?></div>
            <div class="col-md-4"><?php echo $this->formRow($companyForm->get('social_reason')); ?></div>
        </div>

        <h4 class="form-section">Endereço</h4>
        <div class="row">
            <div class="col-md-4">
                <div class="form-group <?php echo $companyForm->get('cep')->getMessages() ? "has-error" : ""; ?>">
                    <label class="control-label" for=""><?php echo $companyForm->get('cep')->getLabel();  ?><span class="required"> * </span></label>
                    <div class="input-group cep"
                         data-url-cep="<?php echo $this->url('util_cep'); ?>"
                         data-form=".user-form">
                        <?php echo $this->formElement($companyForm->get('cep')); ?>
                        <span class="input-group-btn">
								<button id="searchcep" class="btn btn-success " type="button">
									<i class="fa fa fa-search fa-fw"></i> Buscar</button>
							</span>
                    </div>
                    <?php echo $this->formElementErrors($companyForm->get('cep')); ?>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6"><?php echo $this->formRow($companyForm->get('address')); ?></div>
            <div class="col-md-2"><?php echo $this->formRow($companyForm->get('number')); ?></div>
            <div class="col-md-4"><?php echo $this->formRow($companyForm->get('district')); ?></div>
        </div>
        <div class="row state-cities"
             data-url="<?php echo $this->url('util_cities'); ?>"
             data-state-element="#state"
             data-city-element="#city">
            <div class="col-md-4"><?php echo $this->formRow($companyForm->get('state')); ?></div>
            <div class="col-md-4"><?php echo $this->formRow($companyForm->get('city')); ?></div>
            <div class="col-md-4"><?php echo $this->formRow($companyForm->get('complement')); ?></div>
        </div>

        <h4>Contato</h4>
        <div class="row">
            <div class="col-md-12">
                <table class="table table-hover table-light admin-phone">
                    <thead>
                    <tr>
                        <th width="8%">DDD</th>
                        <th>Número</th>
                        <th>Nome do Contato</th>
                        <th>Tipo</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php if($this->user->getCompany()): ?>
                        <?php foreach ($this->user->getCompany()->getPhones() as $phone):  ?>
                            <tr data-row="<?php echo $phone->getId(); ?>">
                                <td><?php echo $phone->getDDD(); ?></td>
                                <td><?php echo $phone->getNumber(); ?></td>
                                <td><?php echo $phone->getContactName(); ?></td>
                                <td><?php echo \Application\Entity\Phone\PhoneType::get($phone->getType()); ?></td>
                                <td>
                                    <a href="#" class="btn btn-sm btn-default admin-phone-remove" data-remove="<?php echo $phone->getId(); ?>">
                                        <i class="fa fa-close"></i>
                                    </a>
                                    <input type="hidden" name="phones[<?php echo $phone->getId() ?>][ddd]" value="<?php echo $phone->getDDD(); ?>">
                                    <input type="hidden" name="phones[<?php echo $phone->getId() ?>][number]" value="<?php echo $phone->getNumber(); ?>">
                                    <input type="hidden" name="phones[<?php echo $phone->getId() ?>][contact_name]" value="<?php echo $phone->getContactName(); ?>">
                                    <input type="hidden" name="phones[<?php echo $phone->getId() ?>][type]" value="<?php echo $phone->getType(); ?>">

                                </td>
                            </tr>
                        <?php endforeach; ?>
                    <?php endif; ?>
                    <tr id="admin-phone-form">
                        <td><?php echo $this->formElement($phoneForm->get('phone[ddd]')); ?></td>
                        <td><?php echo $this->formElement($phoneForm->get('phone[number]')); ?></td>
                        <td><?php echo $this->formElement($phoneForm->get('phone[contact_name]')); ?></td>
                        <td><?php echo $this->formElement($phoneForm->get('phone[type]')); ?></td>
                        <td><button class="btn btn-sm btn-success admin-phone-add" type="button">
                                <i class="fa fa-plus"></i> Adicionar</button></td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>

        <h4 class="form-section">Outros</h4>
        <div class="row">
            <div class="col-md-4"><?php echo $this->formRow($companyForm->get('email')); ?></div>
            <div class="col-md-4"><?php echo $this->formRow($companyForm->get('site')); ?></div>
        </div>

    </div>
    <div class="form-actions">
        <div class="btn-set pull-right">
            <button type="submit" name="save" class="btn blue btn-lg" value="Salvar">
                <span class="fa fa-fa fa-check"></span> Salvar
            </button>
        </div>
    </div>
    <?php echo $this->form()->closeTag() ?>

</div>
