<?php $form = $this->form; ?>
<table class="table table-striped table-bordered table-hover">
    <thead>
    <tr role="row" class="heading">
        <th width="2%">#</th>
        <th width="15%">CPF, CNPJ ou Passaporte</th>
        <th width="30%">Nome</th>
        <th width="30%">Email</th>
        <th width="10%">Ações</th>
    </tr>
    <tr role="row" class="filter">
        <?php $form->prepare(); echo $this->form()->openTag($form); ?>
        <td></td>
        <td><?php echo $this->formelement($form->get('identifier')); ?></td>
        <td><?php echo $this->formelement($form->get('name')); ?></td>
        <td><?php echo $this->formelement($form->get('email')); ?></td>
        <td>
            <div class="margin-bottom-5">
                <button class="btn btn-sm blue filter-submit margin-bottom"><i class="fa fa-search"></i> Pesquisar</button>
            </div>
            <button class="btn btn-sm btn-default filter-cancel"><i class="fa fa-times"></i> Limpar</button>
        </td>
        <?php echo $this->form()->closeTag(); ?>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($this->users as $user):
        $updateUrl = $this->url('admin/default', [
            'controller' => 'user',
            'action'=>'update',
            'id'=>$user->getId()
        ]);

        $removeUrl = $this->url('admin/default', [
            'controller' => 'user',
            'action'=>'delete',
            'id'=>$user->getId(),
        ]);
        ?>
        <tr>
            <td></td>
            <td><a href="<?php echo $updateUrl; ?>"><?php echo $user->getIdentifier(); ?></a></td>
            <td><?php echo $user->getName() ?></td>
            <td><?php echo $user->getEmail(); ?></td>
            <td>
                <a href="<?php echo  $updateUrl; ?>" class="btn btn-sm btn-default">
                    <i class="fa fa-edit"></i> Editar
                </a>
                <a href="<?php echo $removeUrl; ?>" class="btn btn-sm btn-default post-list-remove">
                    <i class="fa fa-close"></i> Excluir
                </a>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<div class="table-paginator">
    <?php echo $this->paginationcontrol(
        $this->users,
        'sliding',
        'admin/partials/paginator.phtml',
        array(
            'route'=>'admin/default',
            'route_options' => array('controller'=>'user'),
            'route_query_options' => ['query'=>$this->searchData])
    ); ?>
</div>