<div class="modal fade" id="recover_pass" tabindex="-1" role="basic" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                <h4 class="modal-title">Recuperar senha</h4>
            </div>
            <div class="modal-body">As instruções para recuperação da senha será enviado para <b><?php echo $this->user->getEmail(); ?></b>
                <br /> <br />Certifique-se que o e-mail cadastrado está correto. Para alter acesse o cadastro do usuário</div>
            <div class="modal-footer">
                <button type="button" class="btn dark btn-outline" data-dismiss="modal">Não enviar</button>
                <a href="<?php echo $this->url('admin/default', ['controller'=>'user', 'action'=>'validate-user', 'id'=>$this->user->getId()]) ?>" type="button" class="btn green">Enviar</a>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>