<div class="modal-dialog modal-lg">
<div class="modal-content">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
        <h4 class="modal-title">Usuários</h4>
    </div>
    <div class="modal-body">

        <?php if(!empty($this->user)): ?>
        <div class="portlet light portlet-fit bordered">
            <div class="portlet-title">
                <div class="caption"><i class="fa fa-edit"></i><?php echo $this->user->getName(); ?></div>
            </div>
            <div class="portlet-body form">
                <form role="form" class="form-horizontal">
                    <div class="form-body">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="control-label col-md-3"><strong>Identificador:</strong></label>
                                    <div class="col-md-9">
                                        <p class="form-control-static"> <?php echo $this->user->getIdentifier(); ?> </p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="control-label col-md-3"><strong>Data de nascimento:</strong></label>
                                    <div class="col-md-9">
                                        <p class="form-control-static"> <?php echo $this->user->getBirthDate()?$this->user->getBirthDate()->format('d/m/Y'):""; ?> </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="control-label col-md-3"><strong>E-mail:</strong></label>
                                    <div class="col-md-9">
                                        <p class="form-control-static"> <?php echo $this->user->getEmail(); ?> </p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="control-label col-md-3"><strong>Contatos:</strong></label>
                                    <div class="col-md-9">
                                        <?php
                                            $userArray = $this->user->_toArray();
                                            $phones = [];
                                            foreach ($userArray['phones'] as $p) {
                                                $phones[] = implode(' - ', $p);
                                            }
                                        ?>
                                        <p class="form-control-static"> <?php echo implode('; ', $phones); ?> </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="control-label col-md-3"><strong>Endereço:</strong></label>
                                    <div class="col-md-9">
                                        <p class="form-control-static"> <?php echo $this->user->getFullAddress(); ?> </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <?php endif; ?>

        <?php if(!$this->viewOnly): ?>
            <div class="row">
            <div class="col-md-12">
                <?php $form = $this->searchForm; ?>
                <?php $form->prepare(); echo $this->form()->openTag($form); ?>
                <table class="table table-striped table-bordered table-hover">
                    <thead>
                    <tr role="row" class="heading">
                        <th width="12%">CPF, CNPJ ou Passaporte</th>
                        <th width="30%">Nome</th>
                        <th width="25%">Email</th>
                        <th width="15%">Ações</th>
                    </tr>
                    <tr role="row" class="filter">
                        <td><?php echo $this->formelement($form->get('identifier')); ?></td>
                        <td><?php echo $this->formelement($form->get('name')); ?></td>
                        <td><?php echo $this->formelement($form->get('email')); ?></td>
                        <td>
                            <button type="submit" class="btn btn-sm blue filter-submit margin-bottom"><i class="fa fa-search"></i> Pesquisar</button>
                            <button class="btn btn-sm btn-default filter-cancel"><i class="fa fa-times"></i> Limpar</button>
                        </td>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($this->users as $u): ?>
                        <tr>
                            <td><?php echo $u->getIdentifier(); ?></td>
                            <td>
                                <?php echo $u->getName() ?>
                                <?php if($u->hasDependents()): ?>
                                <br/><b>Dependentes:</b>
                                <?php foreach ($u->getDependents() as $dep): ?>
                                    <tr>
                                        <td>
                                            <?php echo $dep->getName() ?>
                                            <a href="#"
                                               data-id="<?php echo $dep->getId(); ?>"
                                               data-name="<?php echo $dep->getName()  ?>"
                                               class="btn btn-sm user-modal-select">
                                                <i class="fa fa-edit"></i> Selecionar
                                            </a>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                                <?php ?>
                            </td>
                            <td><?php echo $u->getEmail(); ?></td>
                            <td>
                                <a
                                    href="#"
                                    data-id="<?php echo $u->getId(); ?>"
                                    data-name="<?php echo $u->getName()  ?>"
                                    class="btn btn-sm btn-default user-modal-select">
                                    <i class="fa fa-edit"></i> Selecionar
                                </a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
                <?php echo $this->form()->closeTag(); ?>

                <div class="table-paginator" id="user-modal-paginator">
                    <?php if(count($this->users)) {
                        echo $this->paginationcontrol(
                            $this->users,
                            'sliding',
                            'admin/partials/paginator.phtml',
                            array(
                                'route'=>'admin/default',
                                'route_options' => array('controller'=>'user', 'action'=>'modal'),
                                'route_query_options' => ['query'=>$this->searchData])
                        );
                    } ?>
                </div>
            </div>
        </div>
        <?php endif; ?>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn default" data-dismiss="modal">Sair</button>
    </div>
</div>
</div>