<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
    <h4 class="modal-title">Usuários</h4>
</div>
<div class="modal-body">

    <?php if(!empty($this->user)): ?>
    <div class="portlet light portlet-fit bordered">
        <div class="portlet-title">
            <div class="caption"><i class="fa fa-edit"></i><?php echo $this->user->getName(); ?></div>
            <div class="portlet-body">

            </div>
        </div>
    </div>
    <?php endif; ?>

    <div class="row">
        <div class="col-md-12">
            <?php $form = $this->searchForm; ?>
            <table class="table table-striped table-bordered table-hover">
                <thead>
                <tr role="row" class="heading">
                    <th width="12%">CPF, CNPJ ou Passaporte</th>
                    <th width="30%">Nome</th>
                    <th width="25%">Email</th>
                    <th width="15%">Ações</th>
                </tr>
                <tr role="row" class="filter">
                    <?php $form->prepare(); echo $this->form()->openTag($form); ?>
                    <td><?php echo $this->formelement($form->get('identifier')); ?></td>
                    <td><?php echo $this->formelement($form->get('name')); ?></td>
                    <td><?php echo $this->formelement($form->get('email')); ?></td>
                    <td>
                        <button class="btn btn-sm blue filter-submit margin-bottom"><i class="fa fa-search"></i> Pesquisar</button>
                        <button class="btn btn-sm btn-default filter-cancel"><i class="fa fa-times"></i> Limpar</button>
                    </td>
                    <?php echo $this->form()->closeTag(); ?>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($this->users as $user):
                    $updateUrl = $this->url('admin/default', [
                        'controller' => 'user',
                        'action'=>'update',
                        'id'=>$user->getId()
                    ]);

                    $removeUrl = $this->url('admin/default', [
                        'controller' => 'user',
                        'action'=>'delete',
                        'id'=>$user->getId(),
                    ]);
                    ?>
                    <tr>
                        <td><?php echo $user->getIdentifier(); ?></td>
                        <td><?php echo $user->getName() ?></td>
                        <td><?php echo $user->getEmail(); ?></td>
                        <td>
                            <a href="#" class="btn btn-sm btn-default">
                                <i class="fa fa-edit"></i> Selecionar
                            </a>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>

            <div class="table-paginator" id="user-modal-paginator">
                <?php if(count($this->users)) {
                    echo $this->paginationcontrol(
                        $this->users,
                        'sliding',
                        'admin/partials/paginator.phtml',
                        array(
                            'route'=>'admin/default',
                            'route_options' => array('controller'=>'user', 'action'=>'modal'),
                            'route_query_options' => ['query'=>$this->searchData])
                    );
                } ?>
            </div>
        </div>
    </div>
</div>
<div class="modal-footer">
    <button type="button" class="btn default" data-dismiss="modal">Sair</button>
</div>