<div class="row post page">
<div class="col-md-12">
	<div class="portlet light portlet-fit bordered">
		<div class="portlet-title">
			<div class="caption">
				<i class="fa fa-file-o"></i>Editar Usuário
			</div>
			<div class="actions">
				<a href="<?php echo $this->url('admin/default', ['controller'=>'user']); ?>"
				   class="btn btn-default">
					<i class="icon-action-undo"></i>
					<span class="hidden-xs"> Voltar </span>
				</a>
			</div>
		</div>
		<div class="portlet-body">

			<?php if($this->user->getChangePasswordRequired() || !$this->user->getConfirmedRegister()): ?>
				<div class="note note-info">
					<h4>Atenção</h4>
					<ul>
					<?php if($this->user->getChangePasswordRequired()): ?>
						<li>Atualização de senha obrigatória está pendente</li>
					<?php endif; ?>

					<?php if(!$this->user->getConfirmedRegister()): ?>
						<li>Confirmação de cadastro está pendente</li>
					<?php endif; ?>

                    <?php if(!$this->user->getUpdateRegisterRequired()): ?>
                        <li>Atualização de cadastro está pendente</li>
                    <?php endif; ?>
					</ul>
				</div>
			<?php endif; ?>

			<div class="tabbable-bordered">
				<ul class="nav nav-tabs">
					<li class="active">
						<a href="#tab_form" data-toggle="tab" aria-expanded="true"> Cadastro </a>
					</li>
					<li>
						<a href="#tab_pass" data-toggle="tab" aria-expanded="false"> Senha </a>
					</li>
                    <li>
                        <a href="#tab_conf" data-toggle="tab" aria-expanded="false"> Confirmação de Cadastro </a>
                    </li>
					<li>
						<a href="#tab_history" data-toggle="tab" aria-expanded="false"> Histórico </a>
					</li>
				</ul>
				<div class="tab-content">
					<div class="tab-pane active" id="tab_form">
						<?php echo $this->partial('admin/user/_form.phtml', [
                            'form' => $this->form,
                            'user'=>$this->user,
                            'phoneForm'=>$this->phoneForm,
                            'dependentForm' => $this->dependentForm
                        ]); ?>
					</div>

					<div class="tab-pane" id="tab_pass">
						<div class="portlet">
							<div class="portlet-body form">
								<?php
									$passForm = $this->passForm;
									$passForm->setAttribute(
										'action',
										$this->url('admin/default', [
											'controller'=>'user',
											'action' => 'change-password',
											'id' => $this->user->getId()
										])
									);
									$passForm->prepare();
									echo $this->form(null, null)->openTag($passForm);
								?>
								<div class="body">
									<h4 class="form-section">Alterar Senha</h4>
									<div class="note">
										<p>O usuário será obrigado a alterar a senha quando efetuar o login. Sem a
										atualização da senha, o mesmo ficará impossibilitado de acessar o sistema.</p>
										<p>Uma notificação será enviado ao email cadastrado informando sobre essa modificação.</p>
									</div>
									<div class="row">
										<div class="col-md-6 password-generator" data-url="<?php echo $this->url('util_password'); ?>">
											<?php echo $this->formRow($passForm->get('temp_password')); ?>
										</div>
									</div>
								</div>

								<div class="form-actions">
									<button type="submit" class="btn blue btn-lg" value="Salvar">
										<span class="fa fa-fa fa-check"></span> Salvar
									</button>
								</div>

								<?php echo $this->form()->closeTag() ?>

							</div>
						</div>
					</div>

                    <div class="tab-pane" id="tab_conf">
                        <div class="portlet">
                            <div class="portlet-body form">
                                <div class="body">
                                    <h4 class="form-section">Confirmação de Cadastro</h4>
                                    <div class="row">
                                        <div class="col-md-6">
                                            <?php if($this->user->getConfirmedRegister()): ?>
                                                <div class="note note-info">
                                                    <p>O usuário confirmou o cadastro</p>
                                                </div>
                                            <?php else: ?>
                                                <div class="note note-danger">
                                                    <h4>Não confirmado</h4>
                                                    <a href="#myModal1" role="button" class="btn red" data-toggle="modal">Confirmar cadastro</a>
                                                </div>
                                            <?php endif; ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

					<div class="tab-pane" id="tab_history">
						<div class="portlet">
							<div class="portlet-body">

								<h4 class="form-section">Logs</h4>
								<div class="table-scrollable">
									<table class="table table-hover">
										<thead>
										<tr>
											<th width="15%"> # </th>
											<th> Mensagem </th>
										</tr>
										</thead>
										<tbody>
										<?php foreach($this->user->getLogs() as $log): ?>
										<tr>
											<td> <?php echo $log->getCreatedAt()->format('d/m/Y H:i:s') ?> </td>
											<td> <?php echo $log->getLog(); ?> </td>
										</tr>
										<?php endforeach; ?>
										</tbody>
									</table>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
</div>