<section class="main__wrapper">
    <header class="main-header">
        <h1 class="main-title"><?php echo $this->post->getTitle(); ?></h1>
    </header>
    <div class="news__list">
        <?php foreach ($this->events as $event): ?>
            <article class="news__item">
                <header class="news__header">
                    <h1 class="news__title"><?php echo $event->getFullName(); ?></h1>
                </header>
                <a href="<?php echo $this->url("mostratiradentes/edition", ['id'=>$event->getId()]) ?>" class="news__link readmore-2">Leia mais</a>
            </article>
        <?php endforeach; ?>
    </div>
</section>