<?php if($post->getCover()): ?>
<div class="site__cover">
    <img src="<?php echo $post->getCover() ?>" alt="">
</div>
<?php endif; ?>

<?php if($this->breadcrumbs): ?>
    <?php echo $this->partial('arquivoemcartaz/partials/_breadcrumbs.phtml', ['breadcrumbs'=>$this->breadcrumbs]); ?>
<?php endif; ?>

<main class="main">
    <div class="main__wrapper">
        <section class="main__section">
            <header class="main__header">
                <h1 class="main__title"><?php echo $post->getTitle(); ?></h1>
            </header>
            <h2 class="main__subtitle"><?php echo $post->getSubtitle(); ?></h2>
            <?php echo $post->getContent(); ?>
        </section>
    </div>
</main>