<?php if($this->breadcrumbs): ?>
    <?php echo $this->partial('arquivoemcartaz/partials/_breadcrumbs.phtml', ['breadcrumbs'=>$this->breadcrumbs]); ?>
<?php endif; ?>

<main class="main">
    <div class="main__wrapper">
        <section class="main__section">
            <header class="main__header">
                <h1 class="main__title">Newsletter</h1>
            </header>
            <p>Cadastro realizado com sucesso!</p>
        </section>
    </div>
</main>