<?php $this->headScript()->captureStart() ?>
    (function() {
        var cx = '004056108255715595582:mjja8vbgwt8';
        var gcse = document.createElement('script'); gcse.type = 'text/javascript'; gcse.async = true;
        gcse.src = (document.location.protocol == 'https:' ? 'https:' : 'http:') +
                '//www.google.com/cse/cse.js?cx=' + cx;
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(gcse, s);
    })();
<?php $this->headScript()->captureEnd() ?>

<?php if($this->breadcrumbs): ?>
    <?php echo $this->partial('arquivoemcartaz/partials/_breadcrumbs.phtml', ['breadcrumbs'=>$this->breadcrumbs]); ?>
<?php endif; ?>

<main class="main">
    <div class="main__wrapper">
        <section class="main__section">
            <header class="main__header">
                <h1 class="main__title"><?php echo $post->getTitle(); ?></h1>
            </header>
            <gcse:searchresults-only></gcse:searchresults-only>
        </section>
    </div>
</main>