<?php if($post->getMeta('_cover')) $this->placeholder("is_header_dark")->set(true); ?>

<div class="<?php echo $post->getMeta('_cover') ? 'main-bg' : 'main-no-bg'; ?>"
     style="<?php echo $post->getMeta('_cover') ? 'background-image:url('.$post->getMeta('_cover').')' : ''; ?>">
    <header class="main-header">
        <div class="main-wrapper">
            <h1 class="main-title"><?php echo $post->getTitle(); ?></h1>
        </div>
    </header>
</div>

<section class="main-section">
    <div class="main-wrapper">
        <?php if(!empty($post->getContent())): ?>
            <div class="main-content">
                <?php echo $post->getContent(); ?>
                <div class="main-separator"></div>
            </div>
        <?php endif; ?>
    </div>

    <?php if($this->projects): $css = 'project--no-caroucel'; ?>
        <div class="project <?php echo $css ?>">
            <div class="project-wrapper">
                <div class="project-header"><h2 class="project-title">Projetos</h2></div>
                <div class="project-list <?php echo $css=='project--caroucel' ? 'owl-carousel' : ''; ?>">
                    <?php foreach ($this->projects as $p): ?>
                    <div class="project-item">
                        <a href="<?php echo rawurldecode($this->url('universoproducao/default', ['slug'=>$p->getRelativeUrl()])) ?>" class="project-link">
                            <?php if($p->hasMeta('_thumb')): ?>
                                <img src="<?php echo  $this->thumbor()->url($p->getMeta('_thumb'))->resize(640, 427); ?>" alt="">
                            <?php endif; ?>
                            <div class="project-desc">
                                <p><?php echo $p->getTitle(); ?></p>
                            </div>
                        </a>
                    </div>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
    <?php endif; ?>

    <div class="main-wrapper">
        <div class="main-content">
            <div class="share">
                <span class="share-title">Compartilhe:</span>
                <ul class="share-items">
                    <ul class="share-items">
                        <li class="share-item"><a target="_blank" href="http://www.facebook.com/share.php?u=<?php echo $this->serverUrl(true) ?>&display=popup&title=<?php echo $post->getTitle(); ?>" class="share-link"><span class="icon-facebook"></span></a></li>
                        <li class="share-item"><a target="_blank" href="https://twitter.com/intent/tweet?status=<?php echo $post->getTitle(); ?>+<?php echo $this->serverUrl(true) ?>" class="share-link"><span class="icon-twitter"></span></a></li>
                    </ul>
                </ul>
            </div>

            <div class="main-separator"></div>
        </div>
    </div>

</section>