<div class="container">

    <h2>Minhas inscrições</h2>

    <div class="row">
        <div class="portlet box blue-hoki">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-gift"></i>Filmes</div>
                <div class="actions">
                </div>
            </div>
            <div class="portlet-body">
                <p>Nenhum filme cadastrado</p>
            </div>
        </div>
    </div>
</div>