<!--<div class="breadcrumbs">-->
<!--	<ul class="breadcrumbs__list">-->
<!--		<li class="breadcrumbs__list-item"><a class="breadcrumbs__link" href="--><?php //echo $this->url('cineop') ?><!--">Página Inicial</a></li>-->
<!--		<li class="breadcrumbs__list-item"><a class="breadcrumbs__link" href="">Notícias</a></li>-->
<!--	</ul>-->
<!--</div>-->
<div class="breadcrumbs"></div>
<header class="main__header">
	<h1 class="main__title">Arte</h1>
	<!--<time class="main__date">28 Jan 2015</time>-->
</header>

<!--<div class="main__bg">-->
<!--	<figure>-->
<!--		<img class="main__bg-img" src="images/main-bg.jpg" alt="">-->
<!--		<figcaption>Apresentação Sons & Imagens com a Associação Francesa Double Cadence</figcaption>-->
<!--	</figure>-->
<!--</div>-->

<div class="main__wrapper">

<div class="seminarioslist">

	<?php
	$dbh=mysql_connect ("162.243.253.29", "ricardo", "ag51www");
	//$dbh=mysql_connect ("127.0.0.1", "root", "");
	if (!$dbh) {
		echo "Não foi possível conectar ao banco de dados: " . mysql_error();
		exit;
	}
	if (!mysql_select_db("universoproducao")) {
		echo "Não foi possível selecionar universoproducao: " . mysql_error();
		exit;
	}
	function databr($valor)
	{
		$valor = substr($valor,8,2) . "/" . substr($valor,5,2) . "/" . substr($valor,0,4);
		return $valor;
	}

	function databr2($valor)
	{
		$valor = substr($valor,8,2) . "." . substr($valor,5,2) . "." . substr($valor,0,4);
		return $valor;
	}

	function data_USA($valor1){
		$valor1 = substr($valor1,6,4) . "-" . substr($valor1,3,2) . "-" . substr($valor1,0,2);
		return $valor1;
	}
	function hora($valor)
	{
		if ($valor == '00:00:00') {
			$texto = "";
		} else {
			$texto = date('H:i', strtotime($valor));
			$texto = str_replace(':','h',$texto);
			$texto = str_replace('h00','h',$texto);
		}
		return $texto;
	}
	function formata_data_extenso($strDate)
	{
		// Array com os dia da semana em português;
		$arrDaysOfWeek = array('domingo', 'segunda', 'terça', 'quarta', 'quinta', 'sexta', 'sábado');
		// Array com os meses do ano em português;
		$arrMonthsOfYear = array(1 => '01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12');
		// Descobre o dia da semana
		$intDayOfWeek = date('w',strtotime($strDate));
		// Descobre o dia do mês
		$intDayOfMonth = date('d',strtotime($strDate));
		// Descobre o mês
		$intMonthOfYear = date('n',strtotime($strDate));
		// Descobre o ano
		$intYear = date('Y',strtotime($strDate));
		// Formato a ser retornado
		return $arrDaysOfWeek[$intDayOfWeek];
	}
	function is_utf8($str)
	{
		$c=0; $b=0;
		$bits=0;
		$len=strlen($str);
		for($i=0; $i<$len; $i++)
		{
			$c=ord($str[$i]);
			if($c > 128)
			{
				if(($c >= 254)) return false;
				elseif($c >= 252) $bits=6;
				elseif($c >= 248) $bits=5;
				elseif($c >= 240) $bits=4;
				elseif($c >= 224) $bits=3;
				elseif($c >= 192) $bits=2;
				else return false;
				if(($i+$bits) > $len) return false;
				while($bits > 1)
				{
					$i++;
					$b=ord($str[$i]);
					if($b < 128 || $b > 191) return false;
					$bits--;
				}
			}
		}
		return true;
	}

	function utf8($string)
	{
		if (is_utf8($string))
		{
			return $string;
		} else {
			return utf8_encode($string);
		}
	}

	$mostra = 1068;
	$lg = '';
	$url = '';
	$fc = $fl = $sub = $subMostra = $fSub1 = $fSub2 = $fSub3 = '';
	//$limitCurta = 0;
	$Dir = "Direção";
	?>

	<?php
	$consulta ="select CodArte, TitArte, TitArteIng, CodCatArte, DescArte, DescArteIng, ImgArte,
			CodItemProg, CategoriaProg, Local, Data, HoraManhaInicial 
			from tb_arte Left Join tb_programacaoevento On tb_programacaoevento.CodItemProg = tb_arte.CodArte
			where tb_arte.CodMostra = $mostra AND tb_programacaoevento.CategoriaProg = 'AR' order by Data asc, HoraManhaInicial asc";
	$result = mysql_query($consulta);
	if (!$result) {
		echo "Não foi possível executar a consulta ($sql) no banco de dados:<br /> " . mysql_error();
		exit;
	}
	?>
	<?php
	$linhas = mysql_num_rows($result);
	if ( $linhas > 0 ){
		$i=0;
		while ($row = mysql_fetch_object($result)) {
			$CodArte = $row->CodArte;
			$CodCatArte = $row->CodCatArte;

			$TitAr = $lg=='Ing' ? "TitArteIng" : "TitArte";
			$TitArte = utf8($row->$TitAr);

			$DescAr = $lg=='Ing' ? "DescArteIng" : "DescArte";
			$Descricao	= utf8($row->$DescAr);

			$ImgArte = $row->ImgArte;
			$caminhoFoto = "../../admin/mostra_tiradentes/imagens/artes/".$ImgArte;

			?>
			<h2><strong><?php echo $TitArte?></strong></h2>

			<?php if ($ImgArte != "") { ?>
				<div class="fotoRight">
					<div class="imgFoto">
						<img src="show_image_full.php?filename=<?php echo $caminhoFoto?>&width=200&height=200" alt="<?php echo utf8($NomeOp)?>" border="0" />

					</div>
				</div>
			<?php } ?>

			<?php echo $Descricao?>

			<?php
			$resultProg  = mysql_query("SELECT CodItemProg, CategoriaProg, Local, Data, HoraManhaInicial FROM tb_programacaoevento WHERE CodItemProg = $CodArte AND CategoriaProg = 'AR'");

			$linhas = mysql_num_rows($resultProg);
			if ( $linhas > 0 ){

				if ( $linhas == 1 ){

					$dataOrig = mysql_result($resultProg,0,"Data");
					$data = databr($dataOrig);
					$data2 = explode("/", $data);

					$horaArte = mysql_result($resultProg,0,"HoraManhaInicial");

					if ($horaArte == '24:30:00'){
						$hora = "00h30";
					} else {
						if ($lg=='Ing'){
							$hora = horaIng($horaArte);
						} else {
							$hora = hora($horaArte);
						}
					}

					if ($lg=='Ing'){
						$dataFinal = $data2[1]."-".$data2[0];
						$diaSemana = utf8(formata_data_extensoIng(".$dataOrig."));
					} else {
						$dataFinal = $data2[0]."/".$data2[1];
						$diaSemana = utf8(formata_data_extenso(".$dataOrig."));
					}


					$local = mysql_result($resultProg,0,"Local");
					if ($local != "") {
						$SqlLoc = "SELECT TitLocal, TitLocalIng FROM tb_local WHERE CodLocal = $local";
						$resultLoc  = mysql_query($SqlLoc);
						$linhas = mysql_num_rows($resultLoc);
						if ( $linhas > 0 ){
							$local	= utf8(mysql_result($resultLoc,0,"TitLocal".$lg.""));
						}
					}
					?>
					<p>&nbsp;</p>
					<?php echo $dataFinal?> | <?php echo $diaSemana?><br />
					<?php echo $hora?><br />
					<?php echo $local?>
					</p>
					<?php
				} else {
					?>

					<p>&nbsp;</p>
					<ul class="listaPadrao">
					<?php
					$i=0;
					while ($row = mysql_fetch_object($resultProg)) {
						$dataOrig = $row->Data;
						$data = databr($dataOrig);
						$data2 = explode("/", $data);
						if ($lg=='Ing'){
							$dataFinal = $data2[1]."-".$data2[0];
							$hora = horaIng($row->HoraManhaInicial);
							$diaSemana = utf8(formata_data_extenso(".$dataOrig."));
						} else {
							$dataFinal = $data2[0]."/".$data2[1];
							$hora = hora($row->HoraManhaInicial);
							$diaSemana = utf8(formata_data_extenso(".$dataOrig."));
						}



						$local = $row->Local;
						if ($local != "") {
							$SqlLoc = "SELECT TitLocal, TitLocalIng FROM tb_local WHERE CodLocal = $local";
							$resultLoc  = mysql_query($SqlLoc);
							$linhas = mysql_num_rows($resultLoc);
							if ( $linhas > 0 ){
								$local	= utf8(mysql_result($resultLoc,0,"TitLocal".$lg.""));
							}
						}

						?>
						<li><?php echo $dataFinal?> | <?php echo $diaSemana?> • <?php echo $hora?><br />
							<?php echo $local?>
						</li>

						<?php
					}
				}
			}

			mysql_free_result($resultProg);
			?>
			</ul>



			<p class="pontHor">&nbsp;</p>
			<?php
		}
	}else{
		echo "<li>Nenhum item cadastrado</li>";
	}
	mysql_free_result($result);
	?>


</div>
</div>