<!doctype html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>12a CineOP</title>

    <style>
        html {
            height: 100%;
        }
        body {
            background-color: #fef9ee;
            overflow: hidden;
            min-height: 100vh;
        }
        .bgc {
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            -ms-transform: translate(-50%, -50%); /* IE 9 */
            -webkit-transform: translate(-50%, -50%); /* Safari */
        }
    </style>

</head>
<body>
    <div class="bgc">
        <img id="Image-Maps-Com-image-maps-2017-04-06-084058" src="<?php echo $this->basePath("assets/cineop/dist/images/cineophotsite.jpg"); ?>" border="0" width="900" height="675" orgWidth="900" orgHeight="675" usemap="#image-maps-2017-04-06-084058" alt="" />
        <map name="image-maps-2017-04-06-084058" id="ImageMapsCom-image-maps-2017-04-06-084058">
            <area  alt="" title="" href="http://www.universoproducao.com.br/site/inscricoes.php?menu=ins" shape="rect" coords="572,247,864,613" style="outline:none;" target="_self"     />
            <area  alt="" title="" href="http://www.cineop.com.br/inicio" shape="rect" coords="695,616,872,664" style="outline:none;" target="_self"     />
        </map>

    </div>
</body>
</html>