<div class="home-slider">
	<div class="home-slider__box">
		<div class="home-slider__markers-container">
			<!--<li class="home-slider__marker"><a href=""></a></li>-->
			<!--<li class="home-slider__marker"><a href=""></a></li>-->
		</div>
	</div>
	<div class="home-slider__container">
		<ul class="home-slider__list">
			<?php foreach ($this->banners as $b): ?>
				<li class="home-slider__list-item">
					<div class="home-slider__image">
						<img src="<?php echo $this->thumbor()->url($b->getFile())->resize(808, 456); ?>">
						<?php if($b->getCredits()): ?>
							<span class="home-slider__caption"><?php echo $b->getCredits(); ?></span>
						<?php endif; ?>
					</div>
					<p class="home-slider__title">
						<a class="home-slider__link" href=""><?php echo $b->getTitle(); ?></a>
						<!--<time class="home-slider__date">
							<?php /*if($b->getStartDate()): */?>
								<?php /*echo $b->getStartDate()->format('d m Y') */?>
							<?php /*endif; */?>
						</time>-->
					</p>
				</li>
			<?php endforeach; ?>
		</ul>
	</div>
</div>


<section class="news">
	<header class="main__header main__header--block news__header">
		<a href="<?php echo $this->url('cineop'); ?>noticias" class="main__header-wrapper">
			<h1 class="main__title news__title">
				Notícias
				<p class="main__title-small">Ver Todas <span class="icon icon-arrow-right"></span></p>
			</h1>
		</a>
	</header>

	<?php $cont=1; foreach ($this->news as $n):
		if($cont == 1) $newsPosition = '--left';
		elseif($cont == 2) $newsPosition = '--right';
		else $newsPosition = '--top';
		$cont++;
		?>
		<article class="news__item news__item<?php echo $newsPosition; ?>">
			<a href="<?php echo $this->url('cineop'); ?>noticia/<?php echo $n->getSlug(); ?>" class="news__item-link">
				<div class="news__item-thumb">
					<img src="<?php echo  $this->thumbor()->url($n->getThumb())->resize(396, 396); ?>" alt="">
				</div>
				<header class="news__item-header">
					<h1 class="news__item-title"><?php echo $n->getTitle(); ?></h1>
					<?php if(!empty($n->getSubtitle()) && $newsPosition != '--top'): ?>
					<p class="news__item-intro"><?php echo  $n->getSubtitle() ?></p>
					<?php endif; ?>
					<time class="news__item-date"><?php echo $n->getPostDate()->format('d m Y') ?></time>
				</header>
			</a>
		</article>
	<?php endforeach; ?>

	<p class="news__read-more">
		<a class="news__read-more-link" target="_blanck" href="http://www.universoproducao.com.br/site/noticia_detalhe.php?menu=not&id=445">Acompanhe também, as notícias da Universo Produção</a>
	</p>

</section>

<?php if(!empty($this->programHighLight) && !empty($this->programns) && count($this->programns)): ?>
<section class="program">
	<div class="program__left">
		<header class="program__header">
			<h1 class="main__title">
				Programação
				<p><a class="main__title-small" href="<?php echo $this->url('cineop') ?>/programacao">Programação Completa <span class="icon icon-arrow-right"></span></a></p>
			</h1>
		</header>
		<?php if(!empty($this->programHighLight)): ?>
		<div class="program__highlight program__highlight--home">
			<figure class="program__figure"><img src="<?php echo  $this->thumbor()->url($this->programHighLight->getPhoto())->resize(746, 648); ?>" alt=""></figure>
			<div class="program__item  program__item--highlight">
				<div class="program__date">
					<span class="program__date-day"><?php echo $this->programHighLight->getDate()->format('d') ?></span>
					<span class="program__date-month-year">
						<span class="program__date-month"><?php echo $this->programHighLight->getDate()->format('M') ?></span>
						<span class="program__date-year"><?php echo $this->programHighLight->getDate()->format('Y') ?></span>
					</span>
				</div>
				<div class="program__details">
					<div class="program__details-title">
						<p class="program__title"><a style="color: #d43829;" href="<?php echo $this->programHighLight->getUrl() ?>"><?php echo $this->programHighLight->getTitle() ?></a></p>
						<p class="program__subtitle"><a style="color: #d43829;" href="<?php echo $this->programHighLight->getUrl() ?>"><?php echo $this->programHighLight->getSubtitle() ?></a></p>
					</div>
					<div class="program__details-place">
						<p class="program__place"><?php echo $this->programHighLight->getPlace() ?></p>
						<p class="program__time"><?php echo $this->programHighLight->getHour() ?></p>
					</div>
				</div>
			</div>
		</div>
		<?php endif; ?>
	</div>

	<div class="program__right">
		<ul class="program__items">
			<?php foreach ($this->programns as $high): ?>
				<li class="program__item">
					<a href="<?php echo $high->getUrl(); ?>">
						<div class="program__date">
							<span class="program__date-day"><?php echo $high->getDate()->format('d'); ?></span>
							<span class="program__date-month-year">
								<span class="program__date-month"><?php echo $high->getDate()->format('M'); ?></span>
								<span class="program__date-year"><?php echo $high->getDate()->format('Y'); ?></span>
							</span>
						</div>
						<div class="program__details">
							<p class="program__title"><?php echo $high->getTitle(); ?></p>
							<p class="program__subtitle"><?php echo $high->getSubtitle(); ?></p>
							<p class="program__place"><?php echo $high->getPlace(); ?></p>
							<p class="program__time"><?php echo $high->getHour(); ?></p>
						</div>
					</a>
				</li>
			<?php endforeach; ?>
		</ul>
	</div>
</section>
<?php endif; ?>

<section class="tv">
	<div class="tv__wrapper">
		<header class="tv__header main__header">
			<h1 class="tv__header-title main__title">
				Tv Mostra
				<p class="main__title-small"><a class="" href="<?php echo $this->url('cineop') ?>tv-mostra">Ver todos os Vídeos<span class="icon icon-arrow-right"></span></a></p>
			</h1>
		</header>

		<div class="tv__content">
			<div class="tv__days">
				<p class="tv__days-title">Assista Também</p>
				<ul class="tv__days-items">
					<?php foreach ($lastDaysVideos as $day): ?>
					<li class="tv__days-item"><a href="<?php echo $this->url('cineop') ?>tv-mostra/<?php echo $day->getDate()->format('d-m-Y') ?>" class="tv__days-link">Dia <?php echo $day->getDate()->format('d'); ?></a></li>
					<?php endforeach; ?>
				</ul>
			</div>
			<div class="tv__video">
				<div class="tv__video-content">
					<iframe width="100%" height="456px" src="<?php echo $this->youtubeEmbed($this->video->getYoutube()); ?>" frameborder="0" allowfullscreen></iframe>
				</div>
				<p class="tv__title"><?php echo $this->video->getCaption(); ?>
					<spam class="tv__date"><?php echo $this->video->getDate()->format('d/m/Y'); ?></spam></p>
			</div>
		</div>
	</div>
</section>

<section class="gallery">

	<header class="main__header main__header--block gallery__item gallery__item--header gallery__item--main">
		<a target="_blank" href="https://www.flickr.com/photos/universoproducao/collections/72157667511378190/" class="main__header-wrapper main__header-wrapper--bgmain">
			<h1 class="main__title main__title--negative">
				Galeria
				<p class="main__title-small">Ver Galeria Completa<span class="icon icon-arrow-right"></span></p>
			</h1>
		</a>
	</header>

	<?php $cont=0; foreach ($this->gallery as $gall):
		$cont++;
		if($cont==1 || $cont==4) {
			$class = 'gallery__item--big';
			$width = 808; $height = 372;
		}
		else {
			$class = '';
			$width = 396; $height = 372;
		}
		?>
		<div class="gallery__item <?php echo $class; ?>">
			<a class="gallery__link" href="#">
				<img class="gallery__img" src="<?php echo  $this->thumbor()->url($gall->getFile())->resize($width, $height); ?>" alt="<?php echo $gall->getDescription(); ?>">
			</a>
		</div>
		<?php if($cont == 3): ?>
			<div class="gallery__item gallery__item--header gallery__item--flicker">
				<a target="_blank" class="gallery__link header__title-link" href="">
					<div class="header__wrapper">
						<div class="center__title">
							<a target="_blank" href="https://www.flickr.com/photos/universoproducao/">
								<h1 class="header__title">Acompanhe as fotos da Universo Produção</h1>
								<p class="header__icon"><span class="icon icon-flicker"></span>flickr</p>
								<span class="icon icon-arrow-right"></span>
							</a>
						</div>
					</div>
				</a>
			</div>
		<?php endif; ?>
	<?php endforeach; ?>
</section>

<section class="guide" style="background-image: url('<?php echo $this->basePath('assets/cineop/dist/images/guide-bg.jpg') ?>');">
	<div class="guide__wrapper">
		<header class="guide__header">
			<div class="guide__header--wrapper">
				<h1 class="main__title">Guia</h1>
				<p class="guide__intro">Vivêncie a sétima arte em uma das cidades históricas mais encantadoras de Minas Gerais e Patrimônio Cultural da Humanidade pela Unesco</p>
			</div>
		</header>

		<?php foreach ($this->guides as $guide): ?>
		<article class="guide__item">
			<header class="guide__header">
				<a class="guide__link" href="<?php echo $this->url('cineop'); ?>guia/<?php echo $guide->getSlug(); ?>">
					<figure class="guide__thumb">
						<img class="guide__img" src="<?php echo  $this->thumbor()->url($guide->getThumb())->resize(396, 396); ?>" alt="">
					</figure>
					<h1 class="guide__title"><?php echo $guide->getTitle(); ?><span class="icon icon-arrow-right"></span></h1>
				</a>
			</header>
		</article>
		<?php endforeach; ?>
	</div>
</section>

<section class="sponsor">
	<div class="sponsor__block sponsor__block--1">
		<ul class="sponsor__list sponsor__list--no-border">
			<li class="sponsor__item"><span class="sprite sprite-sponsor-fundo-nacional"></span></li>
			<li class="sponsor__item"><span class="sprite sprite-sponsor-lei-do-incentivo"></span></li>
		</ul>
	</div>

	<div class="sponsor__block sponsor__block--2">
		<p class="sponsor__title">Patrocínio Master</p>
		<ul class="sponsor__list">
			<li class="sponsor__item"><span class="sprite sprite-sponsor-bnds"></span></li>
		</ul>
	</div>

	<div class="sponsor__block sponsor__block--3">
		<p class="sponsor__title">Patrocínio</p>
		<ul class="sponsor__list">
			<li class="sponsor__item"><span class="sprite sprite-sponsor-cemig"></span></li>
			<li class="sponsor__item"><span class="sprite sprite-sponsor-codemig"></span></li>
			<li class="sponsor__item"><span class="sprite sprite-sponsor-governo-de-minas "></span></li>
		</ul>
	</div>

	<div class="sponsor__block  sponsor__block--1 sponsor__block--help"></div>

	<div class="sponsor__block  sponsor__block--2">
		<p class="sponsor__title">Parceria</p>
		<ul class="sponsor__list">
			<li class="sponsor__item"><span class="sprite sprite-sponsor-ufop"></span></li>
		</ul>
	</div>

	<div class="sponsor__block sponsor__block--3">
		<p class="sponsor__title">Apoio Master</p>
		<ul class="sponsor__list">
			<li class="sponsor__item"><span class="sprite sprite-sponsor-3-coracoes"></span></li>
			<li class="sponsor__item"><span class="sprite sprite-sponsor-coca-cola"></span></li>
			<li class="sponsor__item"><span class="sprite sprite-sponsor-heineken"></span></li>
		</ul>
	</div>

	<div class="sponsor__block  sponsor__block--full">
		<p class="sponsor__title">Apoio</p>
		<ul class="sponsor__list">
			<li class="sponsor__item"><span class="sprite sprite-sponsor-universo-cultural"></span></li>
			<li class="sponsor__item"><span class="sprite sprite-sponsor-localiza"></span></li>
			<li class="sponsor__item"><span class="sprite sprite-sponsor-globo"></span></li>
			<li class="sponsor__item"><span class="sprite sprite-sponsor-canal-brasil"></span></li>
			<li class="sponsor__item"><span class="sprite sprite-sponsor-protv"></span></li>
			<li class="sponsor__item"><span class="sprite sprite-sponsor-pref-ouro-preto"></span></li>
			<li class="sponsor__item"><span class="sprite sprite-sponsor-adop-parque"></span></li>
			<li class="sponsor__item"><span class="sprite sprite-sponsor-nova-era-silicon"></span></li>
		</ul>
	</div>

	<div class="sponsor__block  sponsor__block--1 sponsor__block--help"></div>

	<div class="sponsor__block">
		<p class="sponsor__title">Realização</p>
		<ul class="sponsor__list">
			<li class="sponsor__item"><span class="sprite sprite-sponsor-universo"></span></li>
			<li class="sponsor__item mobile-hide"><span class="sprite sprite-sponsor-governo-do-brasil"></span></li>
			<li class="sponsor__item mobile-show"><span class="sprite sprite-sponsor-governo-do-brasil-mobile"></span></li>
		</ul>
	</div>
</section>
