<!--<div class="breadcrumbs">-->
<!--	<ul class="breadcrumbs__list">-->
<!--		<li class="breadcrumbs__list-item"><a class="breadcrumbs__link" href="--><?php //echo $this->url('cineop') ?><!--">Página Inicial</a></li>-->
<!--		<li class="breadcrumbs__list-item"><a class="breadcrumbs__link" href="">Notícias</a></li>-->
<!--	</ul>-->
<!--</div>-->
<div class="breadcrumbs"></div>
<header class="main__header">
	<h1 class="main__title">Obrigado!</h1>
</header>

<!--<div class="main__bg">-->
<!--	<figure>-->
<!--		<img class="main__bg-img" src="images/main-bg.jpg" alt="">-->
<!--		<figcaption>Apresentação Sons & Imagens com a Associação Francesa Double Cadence</figcaption>-->
<!--	</figure>-->
<!--</div>-->

<div class="main__wrapper">
	<p><strong>Você foi cadastrado com sucesso.</strong></p>
</div>