<!--<div class="breadcrumbs">-->
<!--	<ul class="breadcrumbs__list">-->
<!--		<li class="breadcrumbs__list-item"><a class="breadcrumbs__link" href="--><?php //echo $this->url('cineop') ?><!--">Página Inicial</a></li>-->
<!--		<li class="breadcrumbs__list-item"><a class="breadcrumbs__link" href="">Notícias</a></li>-->
<!--	</ul>-->
<!--</div>-->
<div class="breadcrumbs"></div>
<header class="main__header">
	<h1 class="main__title">TV Mostra</h1>
</header>

<!--<div class="main__bg">-->
<!--	<figure>-->
<!--		<img class="main__bg-img" src="images/main-bg.jpg" alt="">-->
<!--		<figcaption>Apresentação Sons & Imagens com a Associação Francesa Double Cadence</figcaption>-->
<!--	</figure>-->
<!--</div>-->

<div class="main__wrapper">
	<ul class="tv__list">
	<?php foreach ($this->videos as $video): ?>
		<li class="tv__list-item">
			<div class="tv__video-content">
				<iframe width="100%" height="300px" src="<?php echo $this->youtubeEmbed($video->getYoutube()); ?>" frameborder="0" allowfullscreen=""></iframe>
			</div>
			<p class="tv__title"><?php echo $video->getCaption(); ?>
				<spam class="tv__date"><?php echo $video->getDate()->format('d/m/Y'); ?></spam></p>
		</li>
	<?php endforeach; ?>
	</ul>
</div>