<?php if($post->getMeta('_cover')) $this->placeholder("is_header_dark")->set(true); ?>

<div class="<?php echo $post->getMeta('_cover') ? 'main-bg' : 'main-no-bg'; ?>"
     style="<?php echo $post->getMeta('_cover') ? 'background-image:url('.$post->getMeta('_cover').')' : ''; ?>">
    <header class="main-header">
        <div class="main-wrapper">
            <h1 class="main-title"><?php echo $post->getTitle(); ?></h1>
        </div>
    </header>
</div>

<section class="main-section">
    <div class="main-wrapper">

        <div class="news">
            <ul class="news-list news-list--highlight">
                <?php foreach ($this->newsList as $news): ?>
                    <li class="news-item">
                        <a href="<?php echo $this->url('universoproducao/news', ['slug'=>$news->getSlug()])?>" class="news-link">
                            <?php if($news->hasMeta('_thumb')): ?>
                                <figure class="news-figure">
                                    <img src="<?php echo  $this->thumbor()->url($news->getMeta('_thumb'))->resize(384, 288); ?>" alt="">
                                </figure>
                            <?php endif; ?>
                            <article class="news-article">
                                <header class="news-header">
                                    <h1><?php echo $news->getTitle(); ?></h1>
                                </header>
                            </article>
                        </a>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>

        <?php echo $this->paginationcontrol(
            $this->newsList,
            'sliding',
            'application/partials/paginator.phtml',
            array(
                'route'=>'universoproducao/default',
                'route_options' => array('slug'=>'noticias'))); ?>

        <div class="share">
            <span class="share-title">Compartilhe:</span>
            <ul class="share-items">
                <ul class="share-items">
                    <li class="share-item"><a target="_blank" href="http://www.facebook.com/share.php?u=<?php echo $this->serverUrl(true) ?>&display=popup&title=<?php echo $post->getTitle(); ?>" class="share-link"><span class="icon-facebook"></span></a></li>
                    <li class="share-item"><a target="_blank" href="https://twitter.com/intent/tweet?status=<?php echo $post->getTitle(); ?>+<?php echo $this->serverUrl(true) ?>" class="share-link"><span class="icon-twitter"></span></a></li>
                </ul>
            </ul>
        </div>

        <div class="main-separator"></div>
    </div>
</section>