<?php $form = $this->form; ?>
<div class="row post guide">
<div class="col-md-12">
	<?php $form->prepare(); echo $this->form(null, null)->openTag($form) ?>

	<div class="portlet light portlet-fit bordered">
		<div class="portlet-title">
			<div class="caption">
				<?php if($this->notify->getId()): ?>
				<i class="fa fa-edit"></i>
				Editar mensagem
				<?php else: ?>
				<i class="fa fa-file-o"></i>
				Nova mensagem
				<?php endif; ?>
			</div>
			<div class="actions">
				<a href="<?php echo $this->url('admin/default', ['controller'=>'notify']); ?>"
				   class="btn btn-default">
					<i class="icon-action-undo"></i>
					<span class="hidden-xs"> Voltar </span>
				</a>
                <a href="<?php echo $this->url('admin/default', ['controller'=>'notify', 'action'=>'create']); ?>"
                   class="btn btn-default">
                    <i class="fa fa-plus"></i>
                    <span class="hidden-xs"> Nova mensagem </span>
                </a>
			</div>
		</div>
		<div class="portlet-body">
			<div class="portlet">
                <div class="portlet-body form">
                    <div class="form-body">
                        <?php
                            echo $this->formRow($form->get('name'));
                            echo $this->formRow($form->get('type'));
                            echo $this->formRow($form->get('status'));
                            echo $this->formRow($form->get('subject')); ?>

                        <div class="row">
                            <div class="col-md-4 col-md-offset-3">
                                <div class="portlet light portlet-fit bordered">
                                    <div class="portlet-title">Variáveis disponíveis</div>
                                    <div class="portlet-body">
                                    </div>
                                </div>
                            </div>
                        </div>

                        <?php echo $this->formRow($form->get('message')); ?>
                    </div>
                    <div class="form-actions">
                        <div class="row">
                            <div class="col-md-offset-3 col-md-9">
                                <button type="submit" class="btn blue btn-lg action-save">Salvar</button>
                                <a href="<?php echo $this->url('admin/default', ['controller'=>'notify']); ?>" class="btn red btn-lg action cancel">Descartar</a>
                            </div>
                        </div>
                    </div>
                </div>
			</div>
		</div>
	</div>
	<?php echo $this->form()->closeTag() ?>
</div>
</div>