<!doctype html>
<html lang="">
<head>
    <meta charset="utf-8">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>CineOP - 14ª Mostra de Cinema de Ouro Preto</title>

    <link rel="apple-touch-icon" href="apple-touch-icon.png">
    <link rel="stylesheet" href="<?php echo $this->basePath('assets/cineop2019/dist') ?>/styles/main.css?v=20200429094800">
    <link rel="stylesheet" href="<?php echo $this->basePath('assets/cineop2019/dist') ?>/styles/vendor.css">

</head>
<body>
<!--[if lt IE 10]>
<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
<![endif]-->

<header class="header">
    <div class="header-bgc header-desk">
        <img src="<?php echo $this->basePath('assets/cineop2019/dist') ?>/images/2019/header-image.jpg" alt="">
    </div>
    <div class="header-bgc header-mobile">
        <img src="<?php echo $this->basePath('assets/cineop2019/dist') ?>/images/2019/header-image-mobile.jpg" alt="">
    </div>

    <nav class="header-navigation">
        <?php $this
            ->navigation('Cineop2019Navigation')
            ->menu()->setPartial("cineop2019/partials/navigation.phtml");

        echo $this
            ->navigation('Cineop2019Navigation')
            ->menu()
            ->render(); ?>
    </nav>
    <div class="header-wrapper-mobile">
        <a class="mainmenu-mobile-btn" href="#"><span class="icon-menu7"></span></a>
    </div>

</header>

<?php echo $this->content; ?>

<footer class="footer">
    <div class="footer-wrapper">
        <div class="footer-clear">
            <div class="footer-contact">
                <p class="footer-title">Contate-nos:</p>
                <span class="icon icon-universo-producao"></span>
                <span class="footer-add">+ 55 31 3282-2366<br>
                            cineop@universoproducao.com.br<br>
                            Rua Pirapetinga, 567 - Serra<br>
                            30220-150, Belo Horizonte | MG</span>
            </div>
            <div class="footer-social">
                <p class="footer-title">Siga-nos:</p>
                <ul class="footer-socialitems">
                    <li class="footer-socialitem"><a target="_blank" class="footer-socialink" href="https://www.facebook.com/cineop"><span class="icon icon-facebook"></span></a></li>
                    <li class="footer-socialitem"><a target="_blank" class="footer-socialink" href="http://twitter.com/universoprod"><span class="icon icon-twitter"></span></a></li>
                    <li class="footer-socialitem"><a target="_blank" class="footer-socialink" href="http://instagram.com/universoproducao"><span class="icon icon-instagram"></span></a></li>
                    <li class="footer-socialitem"><a target="_blank" class="footer-socialink" href="http://www.flickr.com/photos/universoproducao"><span class="icon icon-flickr"></span></a></li>
                    <li class="footer-socialitem"><a target="_blank" class="footer-socialink" href="http://www.youtube.com/user/universoproducao/featured"><span class="icon icon-youtube"></span></a></li>
                </ul>
            </div>
        </div>
        <p class="footer-title footer-copy">Copyright © 2020. Universo Produção - Todos os direitos reservados.</p>
    </div>
</footer>


<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="/bower_components/jquery/dist/jquery.min.js"><\/script>')</script>
<script src="<?php echo $this->basePath('assets/cineop2019/dist') ?>/scripts/vendor.js"></script>
<script src="<?php echo $this->basePath('assets/cineop2019/dist') ?>/scripts/main.js"></script>

<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-10028533-4', 'auto');
    ga('send', 'pageview');

</script>

</body>
</html>
