<div class="portlet light" id="form_wizard_1">
    <div class="portlet-body form">
        <?php $form = $this->form;
        $form->prepare();
        echo $this->form(null, null)->openTag($form); ?>

        <?php if($form->getMessages()): ?>
            <div class="note note-danger">
                <button type="button" class="close" data-dismiss="alert"></button>
                <h4 class="block">Atenção, ocorreram erros! </h4>
                <p>Por favor, confira os dados enviados e verifique se todos os campos obrigatórios foram preenchidos</p>
            </div>
        <?php endif; ?>

        <div class="form-wizard">
            <div class="form-body">
                <ul class="nav nav-pills nav-justified steps">
                    <li>
                        <a href="#tab_regulation" data-toggle="tab" class="step">
                            <span class="number"> 1 </span>
                            <span class="desc"><i class="glyphicon glyphicon-ok"></i> Regulamento </span>
                        </a>
                    </li>
                    <li>
                        <a href="#tab2" data-toggle="tab" class="step">
                            <span class="number"> 2 </span>
                            <span class="desc"><i class="glyphicon glyphicon-ok"></i> Ficha técnica </span>
                        </a>
                    </li>
                    <li>
                        <a href="#tab3" data-toggle="tab" class="step">
                            <span class="number"> 3 </span>
                            <span class="desc"><i class="glyphicon glyphicon-ok"></i> Produção/Direção </span>
                        </a>
                    </li>
                    <li>
                        <a href="#tab4" data-toggle="tab" class="step">
                            <span class="number"> 4 </span>
                            <span class="desc"><i class="glyphicon glyphicon-ok"></i> Multimídia </span>
                        </a>
                    </li>
                </ul>
                <div id="bar" class="progress progress-striped" role="progressbar">
                    <div class="progress-bar progress-bar-success"> </div>
                </div>

                <div class="tab-content">
                    <div class="tab-pane active" id="tab_regulation">
                        <h3 class="h3 block">Regulamento</h3>
                        <div class="portlet light bordered bg-inverse">
                            <div class="portlet-title">
                                <div class="caption">
                                    <span class="caption-subject bold uppercase"> Cinema sem fronteiras - 1 etapa</span>
                                </div>
                                <div class="actions">
                                    <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
                                </div>
                            </div>
                            <div class="portlet-body movie-regulation">
                                <div class="scroller" style="height:300px" data-rail-visible="1" data-rail-color="yellow" data-handle-color="#a1b2bd">
                                    <?php echo $this->reg->getRegulation(); ?>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-12">
                                <div class="movie-multi-check">
                        <?php echo $this->formRow($form->get('accept_regulation')); ?>
                                </div>
                            </div>
                        </div>

                        <h3 class="h3 form-section">Mostras</h3>

                        <div class="row">
                            <div class="col-md-12">
                                <div class="movie-multi-check">
                                    <?php echo $this->formRow($form->get('events')) ?>
                                </div>
                            </div>
                        </div>

                    </div>
                    <div class="tab-pane" id="tab2">
                        <?php echo $this->formRow($form->get('title')) ?>
                        <?php echo $this->formRow($form->get('title_english')) ?>
                        <?php echo $this->formRow($form->get('end_date_year')) ?>
                        <?php echo $this->formRow($form->get('end_date_month')) ?>
                        <?php echo $this->formRow($form->get('duration')) ?>
                        <?php echo $this->formRow($form->get('has_official_classification')) ?>
                        <?php echo $this->formRow($form->get('classification')) ?>
                        <?php echo $this->formRow($form->get('format')) ?>
                        <?php echo $this->formRow($form->get('category')) ?>
                        <?php echo $this->formRow($form->get('window')) ?>
                        <?php echo $this->formRow($form->get('sound')) ?>
                        <?php echo $this->formRow($form->get('color')) ?>
                        <?php echo $this->formRow($form->get('genre')) ?>
                        <?php echo $this->formRow($form->get('accessibility')) ?>
                        <?php echo $this->formRow($form->get('subtitles_languages')) ?>
                        <?php echo $this->formRow($form->get('conversations_list_languages')) ?>
                        <?php echo $this->formRow($form->get('other_festivals')) ?>
                    </div>
                    <div class="tab-pane" id="tab3">
                        <?php echo $this->formRow($form->get('direction')) ?>
                        <?php echo $this->formRow($form->get('script')) ?>
                        <?php echo $this->formRow($form->get('production_company')) ?>
                        <?php echo $this->formRow($form->get('direction_production')) ?>
                        <?php echo $this->formRow($form->get('direction_photography')) ?>
                        <?php echo $this->formRow($form->get('direction_art')) ?>
                        <?php echo $this->formRow($form->get('editing_assembly')) ?>
                        <?php echo $this->formRow($form->get('direct_sound')) ?>
                        <?php echo $this->formRow($form->get('scenography')) ?>
                        <?php echo $this->formRow($form->get('costume')) ?>
                        <?php echo $this->formRow($form->get('cast')) ?>
                        <?php echo $this->formRow($form->get('synopsis')) ?>
                        <?php echo $this->formRow($form->get('filmography_director')) ?>
                    </div>
                    <div class="tab-pane" id="tab4">
                        <?php echo $this->formRow($form->get('movie_link')) ?>
                        <?php echo $this->formRow($form->get('movie_password')) ?>
                        <?php echo $this->formRow($form->get('movie_divulgation')) ?>

                        <h3 class="h3 form-section">Imagens</h3>

                        <div class="clearfix margin-top-10">
                            <span class="label label-danger">Atenção!</span> Formatos válidos: JPG, JPEG e PNG. Tamanho máximo de 1MB por imagem.
                        </div>

                        <p>&nbsp;</p>

                        <div class="form-group ">
                            <label class="control-label col-md-4">Imagem 1</label>
                            <div class="col-md-6">
                                <div class="fileinput fileinput-new" data-provides="fileinput">
                                    <div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 200px; height: 150px;"> </div>
                                    <?php echo $this->formElement($form->get('media_caption[1]')) ?>
                                    <div>
                                            <span class="btn red btn-outline btn-file">
                                                <span class="fileinput-new"> Selecionar imagem </span>
                                                <span class="fileinput-exists"> Alterar </span>
                                                <?php echo $this->formElement($form->get('media[1]')); ?>
                                            </span>
                                        <a href="javascript:;" class="btn red fileinput-exists" data-dismiss="fileinput"> Remover </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group ">
                            <label class="control-label col-md-4">Imagem 2</label>
                            <div class="col-md-6">
                                <div class="fileinput fileinput-new" data-provides="fileinput">
                                    <div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 200px; height: 150px;"> </div>
                                    <div>
                                        <?php echo $this->formElement($form->get('media_caption[2]')) ?>
                                        <span class="btn red btn-outline btn-file">
                                                <span class="fileinput-new"> Selecionar imagem </span>
                                                <span class="fileinput-exists"> Alterar </span>
                                            <?php echo $this->formElement($form->get('media[2]')); ?>
                                            </span>
                                        <a href="javascript:;" class="btn red fileinput-exists" data-dismiss="fileinput"> Remover </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group ">
                            <label class="control-label col-md-4">Imagem 3</label>
                            <div class="col-md-6">
                                <div class="fileinput fileinput-new" data-provides="fileinput">
                                    <div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 200px; height: 150px;"> </div>
                                    <div>
                                        <?php echo $this->formElement($form->get('media_caption[3]')) ?>
                                        <span class="btn red btn-outline btn-file">
                                                <span class="fileinput-new"> Selecionar imagem </span>
                                                <span class="fileinput-exists"> Alterar </span>
                                            <?php echo $this->formElement($form->get('media[3]')); ?>
                                            </span>
                                        <a href="javascript:;" class="btn red fileinput-exists" data-dismiss="fileinput"> Remover </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-actions">
                <div class="row">
                    <div class="col-md-offset-3 col-md-9">
                        <a href="javascript:;" class="btn default button-previous">
                            <i class="glyphicon glyphicon-chevron-left"></i> Voltar </a>
                        <a href="javascript:;" class="btn btn-outline green button-next"> Continuar
                            <i class="glyphicon glyphicon-chevron-right"></i>
                        </a>
                        <button type="submit" class="btn green button-submit"> Cadastrar
                            <i class="glyphicon glyphicon-ok"></i>
                        </button>
                    </div>
                </div>
            </div>
        </div>
        <?php echo $this->form()->closeTag() ?>
    </div>
</div>