<?php
/** @var \Application\Entity\Movie\Movie $movie */
$movie = $this->movie;
?>

<div class="container">
    <p class="meuuniverso-brand meuuniverso-brand--center"><strong>Meu</strong>Universo | Inscrição de filmes</p>

    <div class="portlet light" id="form_wizard_1">
        <div class="portlet-body form">
            <form class="form-horizontal form-bordered" action="">
                <div class="form-body">
                    <p>Filmes cadastros que podem ser inscritos nesse processo de seleção: <br><br></p>
                </div>

                <table class="table table-hover table-light table-movie">
                    <thead>
                    <tr>
                        <th> ID </th>
                        <th> Título </th>
                        <th width="20%"> Data de cadastro </th>
                        <th width="30%"> Inscrições </th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($this->movies as $key => $mV): $m = $mV['movie']; ?>
                        <tr>
                            <td><?php echo $m->getId(); ?></td>
                            <td><?php echo $m->getTitle(); ?></td>
                            <td><?php echo $m->getCreatedAt()->format('d/m/Y \à\s H:i') ?></td>
                            <td>
                                <table class="table table-in-td">
                                    <tbody>
                                    <?php foreach ($m->getSubscriptions() as $sub): ?>
                                        <tr>
                                            <td><?php echo $sub->getEvent()->getShortName(); ?></td>
                                            <td><?php echo $this->labelStatus($sub->getStatus()); ?></td>
                                        </tr>
                                    <?php endforeach; ?>

                                    <?php foreach ($mV['events'] as $evType => $ev): ?>
                                    <tr>
                                        <td><?php echo $ev->getShortName(); ?></td>
                                        <td><?php $subUrl = $this->url('meu-universo/movie', [
                                                'id_reg'=>$this->reg->getHash(),
                                                'action'=>'editar-inscricao'
                                            ], ['query'=>[
                                                'event' => $ev->getId(),
                                                'movie' => $m->getId()
                                            ]]); ?>
                                            <a class="btn btn-default" href="<?php echo $subUrl ?>">Fazer inscrição</a></td>
                                    </tr>
                                    <?php endforeach; ?>
                                    </tbody>
                                </table>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
                <a href="<?php echo $this->url('meu-universo/movie', ['id_reg'=>$reg->getHash(), 'action'=>'novo']);?>" class="btn btn-lg green">Nova inscrição</a>
            </form>


        </div>
    </div>

</div>