<div class="container">
    <p class="meuuniverso-brand meuuniverso-brand--center"><strong>Meu</strong>Universo | Cadastrar filme</p>

    <div class="portlet light" id="form_wizard_1">
        <div class="portlet-body form">
            <?php $form = $this->form;
            $form->prepare();
            echo $this->form(null, null)->openTag($form); ?>
            <div class="form-wizard">
                <div class="form-body">
                    <ul class="nav nav-pills nav-justified steps">
                        <li>
                            <a href="#tab_regulation" data-toggle="tab" class="step">
                                <span class="number"> 1 </span>
                                <span class="desc"><i class="glyphicon glyphicon-ok"></i> Regulamento </span>
                            </a>
                        </li>
                        <li>
                            <a href="#tab2" data-toggle="tab" class="step">
                                <span class="number"> 2 </span>
                                <span class="desc"><i class="glyphicon glyphicon-ok"></i> Ficha técnica </span>
                            </a>
                        </li>
                        <li>
                            <a href="#tab3" data-toggle="tab" class="step">
                                <span class="number"> 3 </span>
                                <span class="desc"><i class="glyphicon glyphicon-ok"></i> Produção/Direção </span>
                            </a>
                        </li>
                        <li>
                            <a href="#tab4" data-toggle="tab" class="step">
                                <span class="number"> 4 </span>
                                <span class="desc"><i class="glyphicon glyphicon-ok"></i> Multimídia </span>
                            </a>
                        </li>
                    </ul>
                    <div id="bar" class="progress progress-striped" role="progressbar">
                        <div class="progress-bar progress-bar-success"> </div>
                    </div>

                    <div class="tab-content">
                        <div class="tab-pane active" id="tab_regulation">
                            <h3 class="block">Regulamento</h3>
                            <div class="portlet light bordered">
                                <div class="portlet-title">
                                    <div class="caption">
                                        <span class="caption-subject bold uppercase"> Cinema sem fronteiras - 1 etapa</span>
                                    </div>
                                    <div class="actions">
                                        <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
                                    </div>
                                </div>
                                <div class="portlet-body">
                                    <div class="scroller" style="height:300px" data-rail-visible="1" data-rail-color="yellow" data-handle-color="#a1b2bd">
                                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam maximus ullamcorper est, non tincidunt tortor pulvinar vel. Curabitur at pretium ipsum. Integer porta, mi eget sollicitudin lacinia, tellus dui imperdiet magna, eget elementum odio odio quis neque. Donec quis consequat mi. Suspendisse vel sem odio. Ut nulla velit, imperdiet ut arcu non, convallis ornare mauris. Pellentesque nec mauris posuere tellus volutpat semper. Nunc eget purus maximus, fringilla neque ac, vulputate urna. Maecenas eu gravida risus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean a auctor libero. Phasellus eu posuere nisl.</p>
                                        <p>Quisque pulvinar a nisi non egestas. Vivamus molestie fermentum diam. Suspendisse rutrum est sit amet nulla mollis, sed pretium tortor vehicula. Cras blandit elementum nibh sit amet hendrerit. Sed tempus metus sit amet lectus tincidunt, eget blandit tortor ultrices. In at semper odio. Mauris imperdiet accumsan mauris, eget blandit metus lacinia vitae. Nulla a dignissim risus. Nulla ac enim mattis, aliquet magna et, rutrum purus. Suspendisse eget lorem eu eros vehicula malesuada. Nunc dictum ante ut augue tristique, ac pulvinar lacus laoreet.</p>
                                        <p>Nulla facilisi. Praesent eu justo vel risus pharetra posuere sed id arcu. Vestibulum enim arcu, fringilla a feugiat egestas, cursus eget eros. Nullam sapien eros, cursus quis turpis nec, scelerisque gravida nisl. Nulla in elit arcu. Sed a neque ullamcorper, porta quam et, sodales lectus. Mauris sagittis facilisis quam non vehicula. Nam sapien velit, placerat non lacinia eget, ullamcorper tincidunt leo.</p>
                                    </div>
                                </div>
                            </div>

                            <div class="">
                                <label>
                                    <input required type="checkbox" value="1" name="accept_regulation"> Eu li e estou de acordo com as condições descritas no regulamento de inscrições de filmes
                                </label>
                            </div>

                            <h3 class="form-section">Mostras</h3>

                            <div class="form-group">
                                <label class="col-md-3 control-label">Checkboxes</label>
                                <div class="col-md-9">
                                    <div class="checkbox-list">
                                        <label>
                                            <input type="checkbox"> Checkbox 1 </label>
                                        <label>
                                            <input type="checkbox"> Checkbox 1 </label>
                                        <label>
                                            <input type="checkbox" disabled> Disabled </label>
                                    </div>
                                </div>
                            </div>

                            <div class="">
                                <label>
                                    <input required type="checkbox" value="1" name="event[1]"> Autorizo a inscrição do filme para a seleção da 11ª CineBH - Mostra de Cinema de Belo Horizonte
                                </label>
                            </div>

                        </div>
                        <div class="tab-pane" id="tab2">
                            <?php echo $this->formRow($form->get('title')) ?>
                            <?php echo $this->formRow($form->get('title_english')) ?>
                            <?php echo $this->formRow($form->get('end_date_year')) ?>
                            <?php echo $this->formRow($form->get('end_date_month')) ?>
                            <?php echo $this->formRow($form->get('duration')) ?>
                            <?php echo $this->formRow($form->get('has_official_classification')) ?>
                            <?php echo $this->formRow($form->get('movie_option_classification')) ?>
                            <?php echo $this->formRow($form->get('movie_option_format')) ?>
                            <?php echo $this->formRow($form->get('movie_option_category')) ?>
                            <?php echo $this->formRow($form->get('movie_option_window')) ?>
                            <?php echo $this->formRow($form->get('movie_option_sound')) ?>
                            <?php echo $this->formRow($form->get('movie_option_color')) ?>
                            <?php echo $this->formRow($form->get('movie_option_genre')) ?>
                            <?php echo $this->formRow($form->get('movie_option_accessibility')) ?>
                            <?php echo $this->formRow($form->get('subtitles_languages')) ?>
                            <?php echo $this->formRow($form->get('conversations_list_languages')) ?>
                            <?php echo $this->formRow($form->get('other_festivals')) ?>
                        </div>
                        <div class="tab-pane" id="tab3">
                            <?php echo $this->formRow($form->get('direction')) ?>
                            <?php echo $this->formRow($form->get('script')) ?>
                            <?php echo $this->formRow($form->get('production_company')) ?>
                            <?php echo $this->formRow($form->get('direction_production')) ?>
                            <?php echo $this->formRow($form->get('direction_photography')) ?>
                            <?php echo $this->formRow($form->get('direction_art')) ?>
                            <?php echo $this->formRow($form->get('editing_assembly')) ?>
                            <?php echo $this->formRow($form->get('direct_sound')) ?>
                            <?php echo $this->formRow($form->get('scenography')) ?>
                            <?php echo $this->formRow($form->get('costume')) ?>
                            <?php echo $this->formRow($form->get('cast')) ?>
                            <?php echo $this->formRow($form->get('synopsis')) ?>
                            <?php echo $this->formRow($form->get('filmography_director')) ?>
                        </div>
                        <div class="tab-pane" id="tab4">
                            <?php echo $this->formRow($form->get('movie_link')) ?>
                            <?php echo $this->formRow($form->get('movie_password')) ?>
                            <?php echo $this->formRow($form->get('movie_divulgation')) ?>

                            <h3 class="form-section">Imagens</h3>

                            <div class="clearfix margin-top-10">
                                <span class="label label-danger">Atenção!</span> Formatos válidos: JPG, JPEG e PNG. Tamanho máximo de 1MB por imagem.
                            </div>

                            <p>&nbsp;</p>

                            <div class="form-group ">
                                <label class="control-label col-md-4">Imagem 1</label>
                                <div class="col-md-6">
                                    <div class="fileinput fileinput-new" data-provides="fileinput">
                                        <div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 200px; height: 150px;"> </div>
                                        <?php echo $this->formElement($form->get('media_caption[1]')) ?>
                                        <div>
                                            <span class="btn red btn-outline btn-file">
                                                <span class="fileinput-new"> Selecionar imagem </span>
                                                <span class="fileinput-exists"> Alterar </span>
                                                <?php echo $this->formElement($form->get('media[1]')); ?>
                                            </span>
                                            <a href="javascript:;" class="btn red fileinput-exists" data-dismiss="fileinput"> Remover </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group ">
                                <label class="control-label col-md-4">Imagem 2</label>
                                <div class="col-md-6">
                                    <div class="fileinput fileinput-new" data-provides="fileinput">
                                        <div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 200px; height: 150px;"> </div>
                                        <div>
                                            <?php echo $this->formElement($form->get('media_caption[2]')) ?>
                                            <span class="btn red btn-outline btn-file">
                                                <span class="fileinput-new"> Selecionar imagem </span>
                                                <span class="fileinput-exists"> Alterar </span>
                                                <?php echo $this->formElement($form->get('media[2]')); ?>
                                            </span>
                                            <a href="javascript:;" class="btn red fileinput-exists" data-dismiss="fileinput"> Remover </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group ">
                                <label class="control-label col-md-4">Imagem 3</label>
                                <div class="col-md-6">
                                    <div class="fileinput fileinput-new" data-provides="fileinput">
                                        <div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 200px; height: 150px;"> </div>
                                        <div>
                                            <?php echo $this->formElement($form->get('media_caption[3]')) ?>
                                            <span class="btn red btn-outline btn-file">
                                                <span class="fileinput-new"> Selecionar imagem </span>
                                                <span class="fileinput-exists"> Alterar </span>
                                                <?php echo $this->formElement($form->get('media[3]')); ?>
                                            </span>
                                            <a href="javascript:;" class="btn red fileinput-exists" data-dismiss="fileinput"> Remover </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-actions">
                    <div class="row">
                        <div class="col-md-offset-3 col-md-9">
                            <a href="javascript:;" class="btn default button-previous">
                                <i class="glyphicon glyphicon-chevron-left"></i> Voltar </a>
                            <a href="javascript:;" class="btn btn-outline green button-next"> Continuar
                                <i class="glyphicon glyphicon-chevron-right"></i>
                            </a>
                            <a href="javascript:;" class="btn green button-submit"> Cadastrar
                                <i class="glyphicon glyphicon-ok"></i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <?php echo $this->form()->closeTag() ?>
        </div>
    </div>
</div>
