<?php
/** @var \Application\Entity\Movie\Movie $movie */
$movie = $this->movie;
?>

<div class="container">
    <p class="meuuniverso-brand meuuniverso-brand--center"><strong>Meu</strong>Universo | Visualizar filme</p>

    <div class="portlet light" id="form_wizard_1">
        <div class="portlet-body form">
            <form class="form-readonly" action="">
                <div class="form-body">
                    <h3 class="h3 form-section">Ficha técnica</h3>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="control-label">Título:</label>
                                <p class="form-control-static"> <?php echo $movie->getTitle(); ?> </p>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="control-label">Título em inglês:</label>
                                <p class="form-control-static"> <?php echo $movie->getTitleEnglish(); ?> </p>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="control-label">País de produção:</label>
                                <p class="form-control-static"> <?php $movie->getProductionCoutry(); ?> </p>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="control-label">Estado de produção:</label>
                                <p class="form-control-static"> <?php echo $movie->getProductionState(); ?> </p>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="control-label">Ano de finalização:</label>
                                <p class="form-control-static"> <?php echo $movie->getEndDateYear(); ?> </p>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="control-label">Mês de finalização:</label>
                                <p class="form-control-static"> <?php echo $movie->getEndDateMonth(); ?> </p>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label class="control-label">Duração exata:</label>
                                <p class="form-control-static"> <?php echo $movie->getDuration()->format('H:i:s'); ?> </p>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="control-label">O filme possui CPB?</label>
                                <p class="form-control-static"> <?php echo $movie->getHasCpb()==1 ? "Sim" : "Não"; ?> </p>
                            </div>
                        </div>
                        <?php if($movie->getHasCpb()): ?>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="control-label">Número do CPB:</label>
                                <p class="form-control-static"> <?php echo $movie->getCpb(); ?> </p>
                            </div>
                        </div>
                        <?php endif; ?>
                    </div>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="control-label">O filme possui classificação indicativa oficial emitida pelo Ministério da Justiça?</label>
                                <p class="form-control-static"> <?php echo $movie->getHasOfficialClassification()==1 ? "Sim" : "Não"; ?> </p>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="control-label"><?php echo $movie->getHasOfficialClassification()==1 ? "Classificação indicativa:" : "Indique a classificação indicativa sugerida:"; ?></label>
                                <p class="form-control-static">
                                    <?php if($cla = $movie->getOption(\Application\Entity\Movie\OptionsType::CLASSIFICATION)) {
                                        echo $cla->getName();
                                    } ?>
                                </p>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="control-label">Formato em que o filme foi finalizado:</label>
                                <p class="form-control-static">
                                    <?php if($for = $movie->getOption(\Application\Entity\Movie\OptionsType::FORMAT_COMPLETED)) {
                                        echo $for->getName();
                                    } ?>
                                </p>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="control-label">Janela final para exibição:</label>
                                <p class="form-control-static">
                                    <?php if($win = $movie->getOption(\Application\Entity\Movie\OptionsType::WINDOW)) {
                                        echo $win->getName();
                                    } ?>
                                </p>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="control-label">Som:</label>
                                <p class="form-control-static">
                                    <?php if($sou = $movie->getOption(\Application\Entity\Movie\OptionsType::SOUND)) {
                                        echo $sou->getName();
                                    } ?>
                                </p>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="control-label">Cor:</label>
                                <p class="form-control-static">
                                    <?php if($cor = $movie->getOption(\Application\Entity\Movie\OptionsType::COLOR)) {
                                        echo $cor->getName();
                                    } ?>
                                </p>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="control-label">Gênero:</label>
                                <p class="form-control-static">
                                    <?php if($gen = $movie->getOption(\Application\Entity\Movie\OptionsType::GENRE)) {
                                        echo $gen->getName();
                                    } ?>
                                </p>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="control-label">Acessibilidade para pessoas com necessidades especiais:</label>
                                <p class="form-control-static">
                                    <?php if($acc = $movie->getOption(\Application\Entity\Movie\OptionsType::ACCESSIBILITY)) {
                                        $str = "";
                                        if(count($acc) > 1) {
                                            foreach ($acc as $a) {
                                                $str.= $a->getName() . ', ';
                                            }
                                        } else {
                                            $str = $acc->getName();
                                        }

                                        echo rtrim($str, ',');
                                    } ?>
                                </p>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="control-label">SE O FILME FOR LONGA, indique quantos LONGAS metragens o diretor já dirigiu:</label>
                                <p class="form-control-static">
                                    <?php if($fea = $movie->getOption(\Application\Entity\Movie\OptionsType::FEATURE_DIRECTED)) {
                                        echo $fea->getName();
                                    } ?>
                                </p>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="control-label">Para curta, indique se ele se enquadra em uma das categorias:</label>
                                <p class="form-control-static">
                                    <?php if($short = $movie->getOption(\Application\Entity\Movie\OptionsType::SHORT_MOVIE_CATEGORY)) {
                                        echo $short->getName();
                                    } ?>
                                </p>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="control-label">O filme possui diálogos?</label>
                                <p class="form-control-static"> <?php echo $movie->getHasConversationsLanguages()==1 ? "Sim" : "Não"; ?> </p>
                            </div>
                        </div>
                        <?php if($movie->getHasConversationsLanguages()): ?>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="control-label">Informe em qual(is) idioma(s):</label>
                                    <p class="form-control-static"> <?php echo $movie->getConversationsLanguages(); ?> </p>
                                </div>
                            </div>
                        <?php endif; ?>
                    </div>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="control-label">O filme possui cópia legendada?</label>
                                <p class="form-control-static"> <?php echo $movie->getHasSubtitlesLanguages()==1 ? "Sim" : "Não"; ?> </p>
                            </div>
                        </div>
                        <?php if($movie->getHasSubtitlesLanguages()): ?>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="control-label">Informe em qual(is) idioma(s):</label>
                                    <p class="form-control-static"> <?php echo $movie->getSubtitlesLanguages(); ?> </p>
                                </div>
                            </div>
                        <?php endif; ?>
                    </div>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="control-label">O filme possui lista de diálogos?</label>
                                <p class="form-control-static"> <?php echo $movie->getHasConversationsListLanguages()==1 ? "Sim" : "Não"; ?> </p>
                            </div>
                        </div>
                        <?php if($movie->getHasConversationsListLanguages()): ?>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="control-label">Informe em qual(is) idioma(s):</label>
                                    <p class="form-control-static"> <?php echo $movie->getConversationsListLanguages(); ?> </p>
                                </div>
                            </div>
                        <?php endif; ?>
                    </div>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="control-label">O filme já participou de outros festivais?</label>
                                <p class="form-control-static"> <?php echo $movie->getHasParticipatedOtherFestivals()==1 ? "Sim" : "Não"; ?> </p>
                            </div>
                        </div>
                        <?php if($movie->getHasParticipatedOtherFestivals()): ?>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="control-label">Cite os festivais e prêmios recebidos:</label>
                                    <p class="form-control-static"> <?php echo $movie->getOtherFestivals(); ?> </p>
                                </div>
                            </div>
                        <?php endif; ?>
                    </div>

                    <h3 class="h3 form-section">Produção/Direção</h3>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="control-label">Direção:</label>
                                <p class="form-control-static"> <?php echo $movie->getDirection() ?> </p>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="control-label">Roteiro:</label>
                                <p class="form-control-static"> <?php echo $movie->getScript() ?> </p>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="control-label">Empresa produtora:</label>
                                <p class="form-control-static"> <?php echo $movie->getProductionCompany() ?> </p>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="control-label">Co-produção:</label>
                                <p class="form-control-static"> <?php echo $movie->getCoProduction() ?> </p>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="control-label">Produção executiva</label>
                                <p class="form-control-static"> <?php echo $movie->getExecutiveProduction() ?> </p>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="control-label">Direção de produção:</label>
                                <p class="form-control-static"> <?php echo $movie->getDirectionProduction() ?> </p>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="control-label">Montagem:</label>
                                <p class="form-control-static"> <?php echo $movie->getEditingAssembly() ?> </p>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="control-label">Fotografia:</label>
                                <p class="form-control-static"> <?php echo $movie->getPhotography() ?> </p>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="control-label">Direção de arte:</label>
                                <p class="form-control-static"> <?php echo $movie->getDirectionArt() ?> </p>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="control-label">Trilha sonora:</label>
                                <p class="form-control-static"> <?php echo $movie->getSoundtrack() ?> </p>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="control-label">Mixagem:</label>
                                <p class="form-control-static"> <?php echo $movie->getMixing() ?> </p>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="control-label">Som direto:</label>
                                <p class="form-control-static"> <?php echo $movie->getDirectSound() ?> </p>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="control-label">Edição de som:</label>
                                <p class="form-control-static"> <?php echo $movie->getSoundEditing() ?> </p>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="control-label">Cenografia:</label>
                                <p class="form-control-static"> <?php echo $movie->getScenography() ?> </p>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="control-label">Figurino:</label>
                                <p class="form-control-static"> <?php echo $movie->getCostume() ?> </p>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="control-label">Elenco:</label>
                                <p class="form-control-static"> <?php echo $movie->getCast() ?> </p>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="control-label">Sinopse:</label>
                                <p class="form-control-static"> <?php echo $movie->getSynopsis() ?> </p>
                            </div>
                        </div>
                    </div>

                    <h3 class="h3 form-section">Multimídia</h3>
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label class="control-label">Link de acesso ao filme:</label>
                                <p class="form-control-static"> <?php echo $movie->getMovieLink() ?> </p>
                            </div>
                        </div>

                        <div class="col-md-4">
                            <div class="form-group">
                                <label class="control-label">Senha de acesso ao filme:</label>
                                <p class="form-control-static"> <?php echo $movie->getMoviePassword() ?> </p>
                            </div>
                        </div>

                        <div class="col-md-4">
                            <div class="form-group">
                                <label class="control-label">Link de divulgação:</label>
                                <p class="form-control-static"> <?php echo $movie->getMovieDivulgation() ?> </p>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <?php foreach ($movie->getMedias() as $key=>$media): ?>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label class="control-label">Créditos da foto:<?php echo $media->getCredits(); ?></label>
                                <p class="form-control-static">
                                    <img width="200" src="<?php echo $this->fileManipulation()->url($media->getSrc()); ?>" alt="">
                                </p>
                            </div>
                        </div>
                        <?php endforeach; ?>
                    </div>

                    <h3 class="h3 form-section">Regulamento</h3>
                    <div class="portlet light bordered bg-inverse">
                        <div class="portlet-title">
                            <div class="caption">
                                <span class="caption-subject bold uppercase"><?php echo $this->reg->getName(); ?></span>
                            </div>
                            <div class="actions">
                                <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
                            </div>
                        </div>
                        <div class="portlet-body movie-regulation">
                            <div class="scroller" style="height:300px" data-rail-visible="1" data-rail-color="yellow" data-handle-color="#a1b2bd">
                                <?php echo $this->reg->getRegulation(); ?>
                            </div>
                        </div>
                    </div>

                </div>
            </form>
        </div>
    </div>

</div>