<?php $form = $this->searchForm; ?>

<div class="row">
	<div class="col-md-12">
		<div class="portlet light portlet-fit portlet-datatable bordered">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-th-list"></i>
					Configurações
				</div>
				<div class="actions">
					<a href="<?php echo $this->url('admin/default', ['controller'=>'movie-options', 'action'=>'create']); ?>"
					   class="btn blue btn-lg">
						<i class="fa fa-plus"></i>
						<span class="hidden-xs"> Novo item  </span>
					</a>
				</div>
			</div>

			<div class="portlet-body">
				<div class="table-container post-list">
					<table class="table table-striped table-bordered table-hover">
						<thead>
							<tr role="row" class="heading">
								<th width="2%">#</th>
								<th width="15%">Nome</th>
								<th width="15%">Tipo</th>
								<th width="15%">Status</th>
								<th width="10%">Ações</th>
							</tr>
                            <tr role="row" class="filter">
                                <?php $form->prepare(); echo $this->form()->openTag($form); ?>
                                    <td></td>
                                    <td><?php echo $this->formelement($form->get('name')); ?></td>
                                    <td><?php echo $this->formelement($form->get('type')); ?></td>
                                    <td><?php echo $this->formelement($form->get('status')); ?></td>
                                    <td>
                                        <div class="margin-bottom-5">
                                            <button class="btn btn-sm blue filter-submit margin-bottom"><i class="fa fa-search"></i> Pesquisar</button>
                                        </div>
                                        <button class="btn btn-sm btn-default filter-cancel"><i class="fa fa-times"></i> Limpar</button>
                                    </td>
                                <?php echo $this->form()->closeTag(); ?>
                            </tr>
						</thead>
						<tbody>
						<?php foreach ($this->items as $item):
							$updateUrl = $this->url('admin/default', [
								'controller' => 'movie-options',
								'action'=>'update',
								'id'=>$item->getId()
							]);

							$removeUrl = $this->url('admin/default', [
								'controller' => 'movie-options',
								'action'=>'delete',
								'id'=>$item->getId()
							]);

							$restoreUrl = $this->url('admin/default', [
								'controller' => 'movie-options',
								'action'=>'restore',
								'id'=>$item->getId()
							]);

							?>
							<tr>
								<td></td>
								<td><a href="<?php echo $updateUrl; ?>"><?php echo $item->getName(); ?></a></td>
								<td><?php echo $item->getTypeName(); ?></td>
								<td>
                                    <?php if($item->getStatus()): ?>
                                        <span class="label label-success"> <i class="fa fa-check"></i> Habilitado</span>
                                    <?php else: ?>
                                        <span class="label label-danger"> <i class="fa fa-close"></i> Desabilitado</span>
                                    <?php endif; ?>
                                </td>
								<td>
									<a href="<?php echo  $updateUrl; ?>" class="btn btn-sm btn-default">
										<i class="fa fa-edit"></i> Editar
									</a>
									<a href="<?php echo $removeUrl; ?>" class="btn btn-sm btn-default post-list-remove">
										<i class="fa fa-trash-o"></i> Excluir
									</a>
								</td>
							</tr>
						<?php endforeach; ?>
						</tbody>
					</table>
                    <div class="table-paginator">
                        <?php echo $this->paginationcontrol(
                            $this->items,
                            'sliding',
                            'admin/partials/paginator.phtml',
                            array(
                                'route'=>'admin/default',
                                'route_options' => [
                                        'controller' => 'movie-options'
                                ]
                            )
                        ); ?>
                    </div>

				</div>
			</div>
		</div>
	</div>
</div>
