<div class="main-wrapper main-content">
    <header class="main-header">
        <h1 class="main-title"><?php echo $post->getTitle() ?></h1>
    </header>

    <div class="programing">
        <table class="programing-grid diferent" style="width: 100%">
            <?php foreach ($this->programing as $pro): ?>
                <tr class="programing-item programing-item--title">
                    <td colspan="2" class="programing-date">
                        <span>
                            <?php echo str_replace('-feira', '', $this->dateFormat($pro['date'], null, null, "pt_BR", "dd/MM | cccc")); ?>
                        </span>
                    </td>
                </tr>
                <?php foreach ($pro['items'] as $item): ?>
                    <tr class="programing-item">
                        <td class="programing-item--left">
                            <span class="programing-time"><?php echo $item['time']; ?></span>
                            <span class="programing-place"><?php echo $item['place']; ?></span>
                        </td>
                        <td class="programing-item--right">
                            <span class="programing-item-title"><?php echo $item['title']; ?></span>
                            <?php foreach ($item['events'] as $event): ?>
                                <?php if(isset($event['title'])): ?>
                                    <a class="programing-event" href="#"><?php echo $event['title']; ?></a>
                                <?php elseif(isset($event['description'])): ?>
                                    <div class="programation-desc">
                                        <?php echo $event['description'] ?>
                                    </div>
                                <?php endif; ?>
                            <?php endforeach; ?>

                            <?php if(isset($item['info'])): ?>
                                <span class="progamation-info"><?php echo $item['info']; ?></span>
                            <?php endif; ?>

                        </td>
                    </tr>
                <?php endforeach; ?>
            <?php endforeach; ?>
        </table>
    </div>
</div>