<?php error_reporting(0); ?>
<section class="main-wrapper main-content">
    <header class="main-header">
        <h1 class="main-title"><?php echo $this->post->getTitle(); ?></h1>
    </header>



    <?php
    $dbh=mysql_connect ("universoprod2.mysql.dbaas.com.br", "universoprod2", "ag51www");
    //$dbh=mysql_connect ("127.0.0.1", "root", "");
    if (!$dbh) {
        echo "Não foi possível conectar ao banco de dados: " . mysql_error();
        exit;
    }
    if (!mysql_select_db("universoprod2")) {
        echo "Não foi possível selecionar universoproducao: " . mysql_error();
        exit;
    }
    function databr($valor)
    {
        $valor = substr($valor,8,2) . "/" . substr($valor,5,2) . "/" . substr($valor,0,4);
        return $valor;
    }

    function databr2($valor)
    {
        $valor = substr($valor,8,2) . "." . substr($valor,5,2) . "." . substr($valor,0,4);
        return $valor;
    }

    function data_USA($valor1){
        $valor1 = substr($valor1,6,4) . "-" . substr($valor1,3,2) . "-" . substr($valor1,0,2);
        return $valor1;
    }
    function hora($valor)
    {
        if ($valor == '00:00:00') {
            $texto = "";
        } else {
            $texto = date('H:i', strtotime($valor));
            $texto = str_replace(':','h',$texto);
            $texto = str_replace('h00','h',$texto);
        }
        return $texto;
    }
    function formata_data_extenso($strDate)
    {
        // Array com os dia da semana em português;
        $arrDaysOfWeek = array('domingo', 'segunda', 'terça', 'quarta', 'quinta', 'sexta', 'sábado');
        // Array com os meses do ano em português;
        $arrMonthsOfYear = array(1 => '01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12');
        // Descobre o dia da semana
        $intDayOfWeek = date('w',strtotime($strDate));
        // Descobre o dia do mês
        $intDayOfMonth = date('d',strtotime($strDate));
        // Descobre o mês
        $intMonthOfYear = date('n',strtotime($strDate));
        // Descobre o ano
        $intYear = date('Y',strtotime($strDate));
        // Formato a ser retornado
        return $arrDaysOfWeek[$intDayOfWeek];
    }
    function is_utf8($str)
    {
        if(!is_string($str))
            return true;

        $c=0; $b=0;
        $bits=0;
        $len=strlen($str);
        for($i=0; $i<$len; $i++)
        {
            $c=ord($str[$i]);
            if($c > 128)
            {
                if(($c >= 254)) return false;
                elseif($c >= 252) $bits=6;
                elseif($c >= 248) $bits=5;
                elseif($c >= 240) $bits=4;
                elseif($c >= 224) $bits=3;
                elseif($c >= 192) $bits=2;
                else return false;
                if(($i+$bits) > $len) return false;
                while($bits > 1)
                {
                    $i++;
                    $b=ord($str[$i]);
                    if($b < 128 || $b > 191) return false;
                    $bits--;
                }
            }
        }
        return true;
    }

    function utf8($string)
    {
        if (is_utf8($string))
        {
            return $string;
        } else {
            return utf8_encode($string);
        }
    }

    $mostra = 1075;
    $lg = '';
    $url = '';
    $fc = $fl = $sub = $subMostra = $fSub1 = $fSub2 = $fSub3 = '';
    //$limitCurta = 0;
    $Dir = "Direção";
    $subMostra = isset($_GET['subMostra']) ? $_GET['subMostra'] : null;
    ?>


    <h2 class="subTitProgramacao">Programação por data</h2>

    <div id="menuProgramacao">
        <?php
        $filtroDia = "";
        $filtroCat = "";
        $filtroLoc = "";
        $filtroSem = "";

        $filtroSub = "";

        if (isset($_GET['fd'])) {
            $fd = $_GET['fd'];
            $filtroDia = "AND PR.Data = '".$fd."'";
        }
        if (isset($_GET['fc'])) {
            $fc = $_GET['fc'];
            switch($fc){
                case 'AB': $filtroCat = "AND PR.CategoriaProg = 'AB'";  break;
                case 'FI': $filtroCat = "AND PR.CategoriaProg = 'FI'";  break;
                case 'SCE': $filtroCat = "AND PR.CategoriaProg = 'SCE'";  break;
                case 'MO': $filtroCat = "AND PR.CategoriaProg = 'MO'";  break;
                case 'SE': $filtroCat = "AND PR.CategoriaProg = 'SE'";  break;
                case 'AR': $filtroCat = "AND PR.CategoriaProg = 'AR'";  break;
                case 'EN': $filtroCat = "AND PR.CategoriaProg = 'EN'";  break;
                case 'EX': $filtroCat = "AND PR.CategoriaProg = 'EX'";  break;
            }

        }
        if (isset($_GET['fl'])) {
            $fl = $_GET['fl'];
            if ($fl == "") {
                $filtroLoc = "";
            } else {
                $filtroLoc = "AND PR.Local = ".$fl;
            }
        }

        if(isset($_GET['subMostra'])) {
            $sub = $_GET['subMostra'];
            if ($sub == "") {
                $fSub1 = "";
                $fSub2 = "";
                $fSub3 = "";
            } else {
                $fSub1 = ", FM.SubMostra, O.SubMostra";
                $fSub2 = " inner join tb_obras O ON O.codObra = PR.CodItemProg left join tb_filmemostra FM ON FM.CodFilme = PR.CodItemProg ";
                $fSub3 = "AND PR.CategoriaProg = 'FI' AND (O.SubMostra = $sub OR FM.SubMostra = $sub)";
            }
        }

        //echo "<p>FD: ".$fd."</p>";
        $SqlMenuProg = mysql_query("Select distinct Data, CodMostra from tb_programacaoevento where CodMostra = $mostra and CategoriaProg <> 'FI' order by Data");
        ?>

        <?php
        while($Dado = mysql_fetch_array($SqlMenuProg)) {
            $data = databr($Dado["Data"]);
            $data2 = explode("/", $data);
            $dia = $data2[0];
            ?>
            <a class="form__button" href="<?php echo $this->url('cinebh')?>programacao/programacao-completa?fd=<?php echo $Dado["Data"]?>"><?php echo $lg=='Ing' ? "" : "DIA"; ?> <?php echo $dia ?><?php echo $lg=='Ing' ? "TH" : ""; ?></a>
        <?php } ?>

    </div>
    <br />
    <form class="form-filtro" action="" method="get" name="form">

        <select class="form__input" name="fc" id="fc">

            <?php if ($lg=='Ing'){ ?>
                <option value="">-- CATEGORY --</option>
                <option value="AB">OPENING</option>
                <option value="FI">FILMS</option>
                <option value="MO">CINEMA LITTLE EXHIBIT</option>
                <option value="SE">BRASIL CINEMUNDI</option>
                <option value="AR">ART</option>
                <option value="EX">EXPOSITION</option>
                <option value="EN">CLOSING</option>

            <?php } else { ?>
                <option value="">CATEGORIA</option>
                <option value="AB" <?php echo $fc == "AB" ? "selected='selected'" : "";?>>ABERTURA</option>
                <option value="FI" <?php echo $fc == "FI" ? "selected='selected'" : "";?>>FILMES</option>
                <option value="MO" <?php echo $fc == "MO" ? "selected='selected'" : "";?>>MOSTRINHA</option>
                <option value="SCE" <?php echo $fc == "SCE" ? "selected='selected'" : "";?>>CINE-ESCOLA</option>
                <option value="SE" <?php echo $fc == "SE" ? "selected='selected'" : "";?>>SEMINÁRIO</option>
                <option value="AR" <?php echo $fc == "AR" ? "selected='selected'" : "";?>>ARTE</option>
                <option value="EX" <?php echo $fc == "EX" ? "selected='selected'" : "";?>>EXPOSIÇÃO</option>
                <option value="EN" <?php echo $fc == "EN" ? "selected='selected'" : "";?>>ENCERRAMENTO</option>
            <?php } ?>

        </select>
        <select class="form__input" name="subMostra" id="subMostra">
            <option value=""><?php echo $lg=='Ing' ? "SUB-MOSTRA" : "SUB-MOSTRA"; ?></option>
            <?php
            $resultCatMostra = mysql_query("SELECT * FROM tb_cat_filme WHERE CodMostra='$mostra' ORDER BY posicao");

            if ($lg == 'Ing') {
                while($rowCat = mysql_fetch_object($resultCatMostra)) {
                    if($rowCat->NomeHomIng != "") {
                        ?>
                        <option value="<?php echo $rowCat->CodCat?>"> <?php echo utf8($rowCat->NomeHomIng)?> </option>
                        <?php
                    }
                }
            } else {
                while($rowCat = mysql_fetch_object($resultCatMostra)) {
                    ?>
                    <option value="<?php echo $rowCat->CodCat?>" <?php echo $subMostra == $rowCat->CodCat ? "selected='selected'" : "";?>> <?php echo utf8($rowCat->NomeHom) ?> </option>
                    <?php
                }
            }
            ?>
        </select>
        <select class="form__input" name="fl" id="fl" >
            <option value=""><?php echo $lg=='Ing' ? "SPOTS" : "LOCAL"; ?></option>
            <?php
            $result = mysql_query("SELECT CodLocal, TitLocal, TitLocalIng FROM tb_local where CodMostra = $mostra order by TitLocal");
            while ($row = mysql_fetch_object($result)) {
                $TitLoc = $lg=='Ing' ? "TitLocalIng" : "TitLocal";?>
                <option value="<?php echo $row->CodLocal?>" <?php echo $fl == $row->CodLocal ? "selected='selected'" : "";?>><?php echo utf8($row->$TitLoc)?></option>
                <?php
            }
            mysql_free_result($result);

            ?>
        </select>
        <button type="submit" class="form__button" class="form__button">Filtrar</button>

        <input name="lg" type="hidden" value="<?php echo $lg?>" />
        <input name="menu" type="hidden" value="prog" />
        <input name="sub" type="hidden" value="pc" />

    </form>
    <!--<p><a href="<?php /*echo $this->basePath("assets/cinebh/programacao-completa.pdf") */?>" target="_blank">Faça o download da programação</a></p>-->

    <?php
    if (isset($_GET['fd']) || isset($_GET['fc']) || isset($_GET['fl'])  ) {
        ?>
        <h4 style="font-size: 12px; margin: 7px 0;"><a href="<?php echo $this->url('mostratiradentes')?>programacao/programacao-completa">&gt; <?php echo $lg=='Ing' ? "SHOW ENTIRE PROGRAM" : "EXIBIR TODA A PROGRAMAÇÃO"; ?></a></h4>
    <?php } ?>


    <!-- LISTA DE FILMES -->

    <?php
    $sqlProg = "select PR.CodProgEvento, PR.CodItemProg, PR.CategoriaProg, PR.Local, PR.order, PR.Data, PR.HoraManhaInicial, PR.HoraManhaFinal,
        PR.HoraTardeInicial, PR.HoraTardeFinal, PR.HoraNoiteInicial, PR.HoraNoiteFinal, PR.status, PR.mostraClassificacao, PR.preNacional, PR.preMundial, PR.infoAdicional $fSub1
        from tb_programacaoevento PR $fSub2
        where PR.CodMostra = $mostra AND (PR.CategoriaProg <> 'OF' && PR.CategoriaProg <> 'CE') $filtroDia $filtroCat $filtroLoc $fSub3
        order by Data, HoraManhaInicial, HoraManhaFinal, HoraTardeInicial, HoraTardeFinal, PR.order asc, HoraNoiteInicial, HoraNoiteFinal, status";




    /*if(isset($_GET["fc"]) && $_GET["fc"] == "SE" && empty($_GET['subMostra']))
    {
        $sqlProg = "(select PR.CodItemProg, PR.CodProgEvento, PR.CategoriaProg, PR.Local, PR.Data, PR.HoraManhaInicial, PR.HoraManhaFinal, 
        PR.HoraTardeInicial, PR.HoraTardeFinal, PR.HoraNoiteInicial, PR.HoraNoiteFinal, PR.status, PR.mostraClassificacao, PR.preNacional, PR.preMundial, PR.infoAdicional 
        from tb_programacaoevento PR
        where PR.CodMostra = $mostra AND PR.CategoriaProg <> 'OF' AND PR.CategoriaProg <> 'CE' AND PR.SessCurtas <> 999 $filtroDia $filtroCat $filtroLoc 
        order by Data, HoraManhaInicial, HoraManhaFinal, HoraTardeInicial, HoraTardeFinal, HoraNoiteInicial, HoraNoiteFinal, status)
        UNION
        (select PR.CodItemProg, PR.CodProgEvento, PR.CategoriaProg, PR.Local, PR.Data, PR.HoraManhaInicial, PR.HoraManhaFinal, 
        PR.HoraTardeInicial, PR.HoraTardeFinal, PR.HoraNoiteInicial, PR.HoraNoiteFinal, PR.status, PR.mostraClassificacao, PR.preNacional, PR.preMundial, PR.infoAdicional 
        from tb_programacaoevento PR
        INNER JOIN tb_obras OB ON OB.codObra = PR.CodItemProg AND OB.SubMostra=92 
        where PR.CodMostra = $mostra AND PR.CategoriaProg <> 'OF' AND PR.CategoriaProg <> 'CE' AND PR.SessCurtas <> 999 $filtroDia $filtroLoc 
        order by Data, HoraManhaInicial, HoraManhaFinal, HoraTardeInicial, HoraTardeFinal, HoraNoiteInicial, HoraNoiteFinal, status)";
    }
    else
    {
        $sqlProg = "select PR.CodItemProg, PR.CodProgEvento, PR.CategoriaProg, PR.Local, PR.Data, PR.HoraManhaInicial, PR.HoraManhaFinal, 
        PR.HoraTardeInicial, PR.HoraTardeFinal, PR.HoraNoiteInicial, PR.HoraNoiteFinal, PR.status, PR.mostraClassificacao, PR.preNacional, PR.preMundial, PR.infoAdicional 
        from tb_programacaoevento PR
        $filtroSub 
        where PR.CodMostra = $mostra AND PR.CategoriaProg <> 'OF' AND PR.CategoriaProg <> 'CE' AND PR.SessCurtas <> 999 $filtroDia $filtroCat $filtroLoc 
        order by Data, HoraManhaInicial, HoraManhaFinal, HoraTardeInicial, HoraTardeFinal, HoraNoiteInicial, HoraNoiteFinal, status";
    }*/


    //echo "<p>SQL: ".$sqlProg."</p>";

    $resultProg = mysql_query($sqlProg);
    $dataAnterior = "";
    $horaAnterior = "";
    $localAnterior = "";
    $categoriaAnterior = "";
    $countCurta = 0;
    $countAbertura = 0;
    $limitCurta = 0;
    $url = "#";
    $horarioFim = "";
    $horarioFimImp = "";
    $dia23 = false;
    ?>
    <table cellpadding="0" cellspacing="0" class="programacao" width="100%">

        <tr>



            <?php while ($rowProg = mysql_fetch_object($resultProg)) {


            if($rowProg->CodItemProg == 209) {
            ?>
        </tr>
        <tr style="">
            <th valign="top">
                <h5> 20h30 </h5>
                <span style="font-size: 9px;">CINE VILA RICA</span>
            </th>
            <td valign="top">
                <h5 >ABERTURA OFICIAL</h5>
                <h6><a href="arte-detalhe.php?menu=programacao&amp;item=arte&amp;CodArte=209"><strong>PERFORMANCE AUDIOVISUAL</strong></a></h6><br />

                <p style="font-size: 14px">
                    Tema Central da 11a CineOP: <strong>CINEMA, TV E EDUCAÇÃO</strong><br />
                    Direção: Chico de Paula <br />
                    Participações especiais: Leri Faria e atrizes  <br />
                    Trilha ao vivo: Rafael no som
                </p>

                <h5 >Homenagens</h5>
                <p style="font-size: 14px">
                    <br />AO RESTAURADOR <strong>CHICO MOREIRA</strong> (in memoriam)	<br />
                    AO CINEASTA <strong>EDUARDO COUTINHO</strong> (in memoriam)
                </p>

                <br />

            </td>
        </tr>


        <?php
        continue;
        }



        $dataOrig = $rowProg->Data;
        $data	 = databr($dataOrig);



        $horarioFim = $rowProg->HoraManhaFinal;

        if ($rowProg->HoraManhaInicial == '24:30:00'){
            $horarioImp = "00h30";
        } else if ($rowProg->HoraManhaInicial == '20:29:00' OR $rowProg->HoraManhaInicial == '20:30:00'){
            $horarioImp = "20h30";
        } else if ($rowProg->HoraManhaInicial == '20:59:00'){
            $horarioImp = "21h";
        } else {


            if ($lg=='Ing'){
                $horarioImp = horaIng($rowProg->HoraManhaInicial);
            } else {
                $horarioImp = hora($rowProg->HoraManhaInicial);
                //$horario = $rowProg->HoraManhaInicial;
            }

            $horario = hora($rowProg->HoraManhaInicial);


            if ($horarioFim != ""){

                if ($horarioFim != "00:00:00"){



                    if ($lg=='Ing'){
                        $horarioFimImp = " - ".horaIng($horarioFim);
                    } else {
                        $horarioFimImp = " às ".hora($horarioFim);
                    }

                    $horarioFim = " às ".hora($horarioFim);
                }
            }
        }

        $ccc = $rowProg->CategoriaProg;
        switch($rowProg->CategoriaProg){
            case 'FI': $SqlTit = "select TituloObra, TituloObraIng, classeObra, FilmeConvidado, 
                        CategoriaConvidado, DirecaoObra, SubMostra, preEstreia, FaixaEtaria1, FaixaEtaria2 from tb_obras where codObra = $rowProg->CodItemProg";

                $nomeSub = "";

                $resultTit  = mysql_query($SqlTit);

                @$titulo	= mysql_result($resultTit,0,"TituloObra".$lg."");
                @$direcao	= mysql_result($resultTit,0,"DirecaoObra");
                @$preEstreia = mysql_result($resultTit,0,"preEstreia");
                @$con	= mysql_result($resultTit,0,"FilmeConvidado");
                @$subM	= mysql_result($resultTit,0,"SubMostra");

                @$faixaEtaria1	= mysql_result($resultTit,0,"FaixaEtaria1");
                @$faixaEtaria2	= mysql_result($resultTit,0,"FaixaEtaria2");
                if ($con == 1) {
                    @$cat	= mysql_result($resultTit,0,"CategoriaConvidado");

                    if ($subM <> 0) {
                        @$SqlSub = "select CodCat, NomeHom, NomeHomIng from tb_cat_filme where CodCat = $subM";
                        @$resultSub  = mysql_query($SqlSub);
                        @$nomeSub	= utf8(mysql_result($resultSub,0,"NomeHom".$lg.""));

                        if ($nomeSub == "PRINCIPAL" || $nomeSub == "MOSTRA PRINCIPAL") {
                            $subMostra = "";
                        } else {
                            $subMostra = $nomeSub." • ";
                        }

                    } else {
                        $subMostra = "";
                    }

                } else {

                    @$SqlSub = "select tb_filmemostra.SubMostra from tb_obras, tb_filmemostra where tb_obras.codObra = $rowProg->CodItemProg and tb_obras.codObra = tb_filmemostra.CodFilme and tb_filmemostra.CodMostra = $mostra";
                    @$resultSub  = mysql_query($SqlSub);
                    @$subM	= mysql_result($resultSub,0,"SubMostra");

                    @$cat	= mysql_result($resultTit,0,"classeObra");

                    if ($subM <> 0) {
                        $SqlSub = "select CodCat, NomeHom, NomeHomIng from tb_cat_filme where CodCat = $subM";
                        $resultSub  = mysql_query($SqlSub);
                        $nomeSub	= utf8(mysql_result($resultSub,0,"NomeHom".$lg.""));

                        if ($nomeSub == "PRINCIPAL" || $nomeSub == "MOSTRA PRINCIPAL") {
                            $subMostra = "";
                        } else {
                            $subMostra = $nomeSub." • ";
                        }

                    } else {
                        $subMostra = "";
                    }


                    switch($cat){
                        case 1: $cat = "Longa";  break;
                        case 2: $cat = "Media";  break;
                        case 3: $cat = "Curta";  break;
                    }


                }

                if ($cat == "Curta") {
                    $cat = "Sessão de Curtas";
                    $catIng = "Short Film Session";
                }

                $url = $this->url('mostratiradentes/movie', ['id'=>$rowProg->CodItemProg]);

                if ($lg=='Ing'){
                    switch($cat){
                        case "Longa" : $catIng = 'FEATURES'; break;
                        case "Media" : $catIng = 'MEDIUN-FORMAT'; break;
                        case "Curta" : $catIng = 'SHORT FILMS'; break;
                    }
                    $categoria = "FILM • ".$subMostra.$catIng;
                } else {
                    $categoria = "FILME • ".$subMostra.$cat;
                }



                break;


            case 'SCE': $categoria = "SESSÃO CINE-ESCOLA";
                $categoria = $lg=='Ing' ? "CINE-SCHOOL SESSION" : "SESSÃO CINE-ESCOLA";

                $resultSess = mysql_query("select idFilme from tb_sessoes_ce WHERE idSessao = '".$rowProg->CodItemProg."' ORDER BY Ordem ASC");

                $titulo = array();
                $direcao = array();
                $preEstreia = array();
                //$faixaEtaria1 = array();
                //$faixaEtaria2 = array();
                $url = array();
                while($linhaSess = mysql_fetch_object($resultSess))
                {
                    $SqlTit = "select TituloObra, TituloObraIng, DirecaoObra, preEstreia, FaixaEtaria1, FaixaEtaria2 from tb_obras where codObra = $linhaSess->idFilme";

                    $resultTit  = mysql_query($SqlTit);

                    if(mysql_num_rows($resultTit) > 0)
                    {
                        $r=mysql_fetch_array($resultTit);
                        $titulo[]	= $r["TituloObra".$lg];
                        $direcao[]	= $r["DirecaoObra"];
                        $preEstreia[] = $r["preEstreia"];
                        //$faixaEtaria1[]	= $r["FaixaEtaria1"];
                        //$faixaEtaria2[]	= $r["FaixaEtaria2"];
                        $faixaEtaria1	= $r["FaixaEtaria1"];
                        $faixaEtaria2	= $r["FaixaEtaria2"];
                        //$url = "cine-escola-detalhe.php?menu=prog&sub=cinescol&cat=$categoria&CodFilme=$linhaSess->idFilme";
                        $url = $this->url('mostratiradentes/movie', ['id'=>$linhaSess->idFilme]);
                    }
                }


                break;

            case 'MO': $SqlTit = "select TituloObra, TituloObraIng, classeObra, FilmeConvidado, CategoriaConvidado, DirecaoObra, preEstreia, FaixaEtaria1, FaixaEtaria2 
                        from tb_obras where codObra = $rowProg->CodItemProg";
                $resultTit  = mysql_query($SqlTit);
                $titulo	= mysql_result($resultTit,0,"TituloObra".$lg."");
                $direcao	= mysql_result($resultTit,0,"DirecaoObra");
                $preEstreia = mysql_result($resultTit,0,"preEstreia");
                $faixaEtaria1	= mysql_result($resultTit,0,"FaixaEtaria1");
                $faixaEtaria2	= mysql_result($resultTit,0,"FaixaEtaria2");
                $con	= mysql_result($resultTit,0,"FilmeConvidado");
                if ($con == 1) {
                    $cat	= mysql_result($resultTit,0,"CategoriaConvidado");
                } else {
                    $cat	= mysql_result($resultTit,0,"classeObra");
                    switch($cat){
                        case 1: $cat = "Longa";  break;
                        case 2: $cat = "Media";  break;
                        case 3: $cat = "Curta";  break;
                    }

                }
                if ($cat == "Curta") {
                    $cat = "Sessão de Curtas";
                    $catIng = "Short Film Session";
                }
                //$url = "filme-detalhe.php?menu=programacao&item=filmes&cat=$cat&mostrinha=1&CodFilme=$rowProg->CodItemProg";
                $url = $this->url('mostratiradentes/movie', ['id'=>$rowProg->CodItemProg]);

                if ($lg=='Ing'){
                    switch($cat){
                        case "Longa" : $catIng = 'FEATURES'; break;
                        case "Media" : $catIng = 'MEDIUN-FORMAT'; break;
                        case "Curta" : $catIng = 'SHORT FILMS'; break;
                    }
                    $categoria = "CINEMA LITTLE EXHIBIT • ".$catIng;
                } else {
                    $categoria = "MOSTRINHA • ".$cat;
                }

                break;

            case 'SE': $categoria = "SEMINÁRIO";
                $categoria = $lg=='Ing' ? "SEMINARS" : "SEMINÁRIO";

                /*if ($rowProg->CodItemProg == 60) {
                    $categoria = $categoria." - ABERTURA OFICIAL";
                }*/

                $SqlTit = "select tituloSeminario, tituloSeminarioIng, tematica from tb_seminarios 
                                    where codSeminario = $rowProg->CodItemProg";
                @$resultTit  = mysql_query($SqlTit);
                @$titulo	= mysql_result($resultTit,0,"tituloSeminario".$lg."");
                @$tematica	= mysql_result($resultTit,0,"tematica");

                if($tematica != 0)
                {
                    $SqlTem = "select titTematica from tb_tematica where codTematica = $tematica";
                    $resultTem  = mysql_query($SqlTem);
                    $TitTematica	= utf8(mysql_result($resultTem,0,"titTematica"));
                    $categoria .= " • ".$TitTematica;
                }

                //$url = "seminario-detalhe.php?menu=programacao&item=seminario&CodSem=$rowProg->CodItemProg";
                $url = $this->url('mostratiradentes/seminar', ['id'=>$rowProg->CodItemProg]);
                break;
            case 'AR': $SqlTit = "select TitArte, TitArteIng, CodCatArte from tb_arte where CodArte = $rowProg->CodItemProg";
                $resultTit  = mysql_query($SqlTit);
                $titulo	= mysql_result($resultTit,0,"TitArte".$lg."");
                $CodCatArte	= mysql_result($resultTit,0,"CodCatArte");
                @$resultCat  = mysql_query($SqlCat);
                @$cat = utf8(mysql_result($resultCat,0,"TitCatArte"));
                $categoria = $lg=='Ing' ? "ART" : "ARTE • ".$cat;
                //$url = "arte-detalhe.php?menu=programacao&item=arte&CodArte=$rowProg->CodItemProg";
                $url = $this->url('mostratiradentes') . 'arte/'.$rowProg->CodItemProg.'?CodArte='.$rowProg->CodItemProg;
                $preEstreia = "";
                break;
            case 'AB': $categoria = "ABERTURA";
                $categoria = $lg=='Ing' ? "OPENING" : "ABERTURA";
                $SqlTit = "select TitAbertura, TitAberturaIng, DescAbertura, DescAberturaIng from tb_abertura 
                                    where CodAbertura = $rowProg->CodItemProg";
                $resultTit  = mysql_query($SqlTit);
                $titulo	= mysql_result($resultTit,0,"TitAbertura".$lg."");
                $descricao	= mysql_result($resultTit,0,"DescAbertura".$lg."");
                $url = $this->url('mostratiradentes') . 'abertura/';
                break;
            case 'EX': $categoria = "EXPOSIÇÃO";
                $categoria = $lg=='Ing' ? "EXPOSITION" : "EXPOSIÇÃO";
                $SqlTit = "select TitExpo, TitExpoIng from tb_exposicao where CodExpo = $rowProg->CodItemProg";
                $resultTit  = mysql_query($SqlTit);
                $titulo	= mysql_result($resultTit,0,"TitExpo".$lg."");
                $url = $this->url('mostratiradentes') . 'exposicao/';
                $preEstreia = "";
                break;
            case 'EN': $categoria = "ENCERRAMENTO";
                $categoria = $lg=='Ing' ? "CLOSING" : "ENCERRAMENTO";
                $SqlTit = "select TitEnc, TitEncIng, DescEnc, DescEncIng from tb_encerramento 
                                    where CodEnc = $rowProg->CodItemProg";

                $resultTit  = mysql_query($SqlTit);
                $titulo	= mysql_result($resultTit,0,"TitEnc".$lg."");

                $descricao	= mysql_result($resultTit,0,"DescEnc".$lg."");
                $url = $this->url('mostratiradentes') . 'encerramento/';
                $preEstreia = "";
                break;
        }

        $titulo = isset($titulo) ? utf8($titulo) : '';
        $direcao = isset($direcao) ? utf8($direcao) : '';

        /*if(isset($preEstreia)) {
            if($preEstreia) {
                $titulo .= " - PRÉ-ESTREIA NACIONAL";
            }
        }*/

        $local = $rowProg->Local;
        if ($local != "") {
            $SqlLoc = "SELECT TitLocal, TitLocalIng FROM tb_local WHERE CodLocal = $local";
            $resultLoc  = mysql_query($SqlLoc);
            $linhas = mysql_num_rows($resultLoc);
            if ( $linhas > 0 ){
                $localImp	= utf8(mysql_result($resultLoc,0,"TitLocal".$lg.""));
                $local	= utf8(mysql_result($resultLoc,0,"TitLocal"));
            }
        }
        ?>

        <?php
        $data2 = explode("/", $data);
        if ($lg=='Ing'){
            $dataFinalImp = $data2[1]."-".$data2[0];
            $diaSemanaImp = utf8(formata_data_extensoIng(".$dataOrig."));
        } else {
            $dataFinalImp = $data2[0]."/".$data2[1];
            $diaSemanaImp = utf8(formata_data_extenso(".$dataOrig."));
        }

        $dataFinal = $data2[0]."/".$data2[1];
        $diaSemana = utf8(formata_data_extenso(".$dataOrig."));
        ?>

        <?php if ($dataFinal != $dataAnterior) { ?>
            <tr>
                <td colspan="2" class="titListaProg" style="padding-top: 15px; border-left: none;">
                    <?php echo $dataFinalImp?> | <?php echo $diaSemanaImp?>
                </td>
            </tr>
            <?php
            $dataAnterior = $dataFinal;
        }
        ?>




        <?php
        $cat = isset($cat) ? $cat : "";

        if ($cat == "Sessão de Curtas" || $cat == "Media") {
            $countCurta = $countCurta+1;
        } else {
            $countCurta = 0;
        }


        if ($dataFinal == '21/01' && $horario == '16h30') {
            $limitCurta = 5;
        } elseif ($dataFinal == '21/01' && $horario == '18h30'){
            $limitCurta = 3;
        } elseif ($dataFinal == '21/01' && $horario == '22h' && $rowProg->CodItemProg == 20802){
            $countCurta = 1;
            $limitCurta = 2;
        } elseif ($dataFinal == '22/01' && $horario == '15h30'){
            $limitCurta = 4;
        }  elseif ($dataFinal == '22/01' && $horario == '17h'){
            $limitCurta = 5;
        } elseif ($dataFinal == '22/01' && $horario == '18h30'){
            $limitCurta = 8;
        } elseif ($dataFinal == '23/01' && $horario == '16h30'){
            $limitCurta = 4;
        } elseif ($dataFinal == '23/01' && $horario == '21h'){
            $limitCurta = 3;
        } elseif ($dataFinal == '23/01' && $horario == '22h30'){
            $limitCurta = 7;
        }elseif ($dataFinal == '24/01' && $horario == '21h'){
            $limitCurta = 3;
        } elseif ($dataFinal == '24/01' && $horario == '22h30'){
            $limitCurta = 7;
        } elseif ($dataFinal == '25/01' && $horario == '16h30'){
            $limitCurta = 15;
        }elseif ($dataFinal == '25/01' && $horario == '17h30'){
            $limitCurta = 19;
        } elseif ($dataFinal == '25/01' && $horario == '21h'){
            $limitCurta = 3;
        } elseif ($dataFinal == '25/01' && $horario == '22h30'){
            $limitCurta = 6;
        } elseif ($dataFinal == '26/01' && $horario == '16h30'){
            $limitCurta = 13;
        }elseif ($dataFinal == '27/01' && $horario == '16h30'){
            $limitCurta = 3;
        }elseif ($dataFinal == '28/01' && $horario == '10h30'){
            $limitCurta = 5;
        }elseif ($dataFinal == '28/01' && $horario == '15h'){
            $limitCurta = 11;
        }elseif ($dataFinal == '28/01' && $horario == '17h40'){
            $limitCurta = 1;
        }elseif ($dataFinal == '28/01' && $horario == '18h'){
            $limitCurta = 5;
        }

        /*elseif ($dataFinal == '25/06' && $horario == '16h'){

            if($rowProg->CodItemProg == 19493) {
                $countCurta = 1;
                $limitCurta = 1;
            } else {
                $countCurta = 1;
                $limitCurta = 2;
            }
        }elseif ($dataFinal == '25/06' && $horario == '18h30'){
            $limitCurta = 3;
        }elseif ($dataFinal == '25/06' && $horario == '19h15'){
            $limitCurta = 15;
        }elseif ($dataFinal == '25/06' && $horario == '23h30'){
            $limitCurta = 4;
        }elseif ($dataFinal == '26/06' && $horario == '11h'){
            $limitCurta = 4;
        }elseif ($dataFinal == '26/06' && $horario == '17h'){
            $limitCurta = 1;
        }elseif ($dataFinal == '26/06' && ($rowProg->CodItemProg == 19406 || $rowProg->CodItemProg == 19360 || $rowProg->CodItemProg == 19460 || $rowProg->CodItemProg == 18322)){
            $limitCurta = 6;
        } elseif ($dataFinal == '26/06' && $horario == '20h'){
            $limitCurta = 2;
        } elseif ($dataFinal == '26/06' && $horario == '22h'){
            $limitCurta = 10;
        } elseif ($dataFinal == '27/06' && $horario == '17h30'){
            $limitCurta = 4;
        } elseif ($dataFinal == '27/06' && $horario == '17h30'){
            $limitCurta = 4;
        }elseif ($dataFinal == '27/06' && $horario == '19h30'){
            $limitCurta = 3;
        }*/









        // if ($cat == "Sessão de Curtas" && $rowProg->CodItemProg == 12050) {
        // 	$countCurta = 0;
        // }

        ?>
        <tr
            <?php
            if( ($countCurta > 0 && $countCurta < $limitCurta)
                ||($rowProg->CategoriaProg == "AB")
                //||($rowProg->CodProgEvento == 3090)
                //||($rowProg->CodProgEvento == 3108)
                //||($rowProg->CodProgEvento == 3132)

                /*||($rowProg->CodItemProg == 13028)
                ||($rowProg->CodItemProg == 12638)
                ||($rowProg->CodItemProg == 13136 && $local=="CINE SANTA TEREZA") */
                ||($rowProg->CategoriaProg == "EN")
                //||($rowProg->CategoriaProg == "EX" && $rowProg->CodItemProg == 13 && $dataFinal == '01/10' && $horario == '10h')
            )
            {
                echo "style='border: none;'";
            }

            ?> >


            <th valign="top">
                <h5>
                    <?php //if($rowProg->CodProgEvento == 18177){$horarioImp = ""; $horarioFimImp="";}?>
                    <?php if (($horaAnterior != $horario || $localAnterior != $local) || $rowProg->CategoriaProg == "EN" ) { ?>

                        <?php if ($rowProg->CodItemProg != 18177) { ?>
                            <?php echo $horarioImp?><?php echo $horarioFimImp?>
                        <?php } ?>
                        <?php

                    }
                    ?>
                </h5>
                <span style="font-size: 12px;">

                <?php if (($horaAnterior != $horario || $localAnterior != $local) || $rowProg->CodItemProg == 13028 || $rowProg->CodItemProg == 71 || $rowProg->CategoriaProg == "EN") { ?>
                    <?php if ($rowProg->CodItemProg != 18177) { ?>
                        <?php echo $localImp?>
                    <?php } ?>
                <?php } ?>
                </span>
            </th>

            <td valign="top">

                <?php //echo "contCurta: " . $countCurta . " | limiteCurta: " . $limitCurta . " | horaAnterior: $horaAnterior | horario: $horario | LocalAnterior: $localAnterior | Local: $local | CodProg: $rowProg->CodItemProg "; ?>
                <?php if($cat == "Sessão de Curtas")
                { echo "<a name='curta'></a>";
                }?>

                <?php if (($horaAnterior != $horario
                        || $localAnterior != $local
                        || $cat != "Sessão de Curtas"
                        || $rowProg->CodItemProg == 12030
                    ) and $rowProg->CodItemProg != 17970 && $rowProg->CodItemProg != 18179 && $rowProg->CodItemProg != 17634 && $rowProg->CodItemProg != 18039)
                {?>



                    <h5 <?php if($cat == "Sessão de Curtas")

                    { echo "style='margin-bottom:10px;'"; }?>>



                        <?php

                        //if($rowProg->CategoriaProg == "SE" && $rowProg->CodItemProg == 199)
                        //	{
                        //		echo "<p>DEBATE INAUGURAL</p>";
                        //	}

                        if ($rowProg->CategoriaProg == 'AB' || $rowProg->CategoriaProg == 'EN' || $rowProg->CodProgEvento == 3138)
                        {
                            echo "<span style='color:#000;'>".$categoria."</span>";
                        }
                        /*elseif ($titulo == 'ENCERRAMENTO')
                            {
                                echo "ENCERRAMENTO";
                            }*/
                        else
                        {
                            if($rowProg->CodProgEvento != 17970)
                            {


                                ?>

                                <?php

                                if ($rowProg->preMundial == 1) {

                                    $pe = " • PRÉ-ESTREIA MUNDIAL";
                                } else if ($rowProg->preNacional == 1) {
                                    $pe = " • PRÉ-ESTREIA NACIONAL";
                                } else {
                                    $pe = "";
                                }

                                if($rowProg->CodItemProg == 213 && $horario == "23h" ){$pe="SHOW MUSICAL";}
                                elseif($rowProg->CodItemProg == 17970 && $horario != "20h30" ){$categoria = "";}
                                elseif($rowProg->CodItemProg == 18178 && $horario != "20h30" ){$categoria = "HISTÓRICA • CURTA E LONGA";}
                                elseif($rowProg->CodItemProg == 17986){$categoria = "CONTEMPORÂNEA • MEDIAS";}
                                elseif($rowProg->CodItemProg == 18179 && $horario != "20h30" ){$categoria = "";}
                                elseif($rowProg->CategoriaProg == "SE"){$pe = "";}
                                elseif($rowProg->CategoriaProg == "EN"){$categoria = "ENCERRAMENTO";}
                                elseif($rowProg->CategoriaProg == "FI" && $rowProg->CodItemProg == 14053){$pe = "";}
                                if($rowProg->CodProgEvento == 3090 || $rowProg->CodProgEvento == 3102 || $rowProg->CodProgEvento == 3108 || $rowProg->CodProgEvento == 3109){$categoria = str_replace("Sessão de Curtas", "Curta", $categoria);}
                                ?>

                                <a href="<?php echo !empty($url)&&is_string($url) ? $url : "" ?>"><?php echo $categoria; ?> <?php echo $pe;?>
                                    <?php if($cat == "Sessão de Curtas" && $dataFinal == '22/10' && $horario == '19h30') {?>
                                        - Recomendado para maiores de 16 anos
                                    <?php } ?>
                                    <?php if($cat == "Sessão de Curtas" && $dataFinal == '23/10' && $horario == '20h') {?>
                                        - Série Especial
                                    <?php } ?>
                                    <?php if($rowProg->CategoriaProg == 'FI' && $dataFinal == '24/10' && $horario == '17h') {?>
                                        - Sessão Família
                                    <?php } ?>
                                </a>
                            <?php } }				?>
                    </h5>
                <?php } ?>
                <h6>
                    <?php if ($rowProg->CategoriaProg == 'AB' || $rowProg->CategoriaProg == 'EN') {
                        echo $descricao;
                    } else if(is_array($titulo))
                    {
                        $a = count($titulo);
                        for($i = 0; $i < $a; $i++)
                        {
                            ?><a href="<?php echo $url?>"><strong><?php echo utf8($titulo[$i])?></strong></a> |

                            <?php
                            if ($lg=='Ing'){
                                $direc = str_replace(' e ',' and ',$direcao[$i]);
                            }else{$direc = $direcao[$i];}

                            if($direc != ""){
                                ?>
                                <span class="subItemListaMenor" style="font-size: 10px;"><?php echo isset($Dir) ? $Dir : '' ?>: <?php echo utf8($direc)?></span><br /><br />

                            <?php }
                        }
                        unset($titulo);
                        unset($url);
                        unset($direcao);



                    } else if ($rowProg->CodProgEvento == 3138) {
                        echo $titulo;
                    } else { ?>
                        <a href="<?php echo $url?>"><strong><?php echo $titulo?></strong></a>
                        <?php if ($rowProg->CategoriaProg == 'FI' || $rowProg->CategoriaProg == 'SCE' || $rowProg->CategoriaProg == 'MO') { ?>
                            |
                            <?php
                            if ($lg=='Ing'){
                                $direcao = str_replace(' e ',' and ',$direcao);
                            }
                            ?>
                            <span class="subItemListaMenor" style="font-size: 10px;"><?php echo isset($Dir) ? $Dir : ''?>: <?php echo $direcao?></span>
                        <?php }
                        ?>
                    <?php } ?>
                </h6>

                <!-- FAIXA ETÁRIAS -->
                <?php

                if($rowProg->infoAdicional != "" ){ echo "<span class='subItemListaMenor'><strong style='font-size: 11px;'>(".$rowProg->infoAdicional.")</strong></span>";}


                $frase = $lg=='Ing' ? "Recommended for ages" : "* Faixa etária sugerida: a partir de";
                $anos = $lg=='Ing' ? "older" : "anos";
                $texto = "<br /><span class='subItemListaMenor'><strong style='font-size: 10px; font-style: italic;'>$frase ";
                if(isset($faixaEtaria1) && $faixaEtaria1 != "" && $faixaEtaria1 != "0") {

                    if($rowProg->mostraClassificacao == 1 ){echo $texto . $faixaEtaria1 . " $anos</strong></span>";}

                }

                if($rowProg->CodProgEvento == 3156) {
                    echo $texto . "12 anos</strong></span>";
                }



                if($rowProg->CodProgEvento == 3157) {
                    echo $texto . "12 anos</strong></span>";
                }


                ?>

            </td>
        </tr>
        <?php
        $horaAnterior = $horario;
        $localAnterior = $local;
        $horarioFim = "";
        $horarioFimImp = "";
        }
        ?>
    </table>
</section>