<!--<ul class="page-breadcrumb">
	<li>
		<a href="index.html">Home</a>
		<i class="fa fa-circle"></i>
	</li>
	<li>
		<span>Page Layouts</span>
	</li>
</ul>-->
<?php $container = $this->navigation()->breadcrumbs()  ?>
<?php /* @var $container \Zend\View\Helper\Navigation\Breadcrumbs */ ?>
<?php $navigation = $container->getContainer() ?>
<?php /* @var $navigation \Zend\Navigation\Navigation */ ?>

<ul class="page-breadcrumb">
	<li>
		<a href="<?php echo $this->url('admin/default', ['controller' => 'index']) ?>">Dashboard</a>
		<i class="fa fa-circle"></i>
	</li>
	<?php foreach($this->pages as $page): ?>
		<?php /* @var $page \Zend\Navigation\Page\Mvc */ ?>
		<?php if( ! $page->isActive()): ?>
			<li>
				<a href="<?php echo $page->getHref() ?>"><?php echo $page->getLabel() ?></a>
				<i class="fa fa-circle"></i>
			</li>
		<?php else: ?>
			<li class="active">
				<?php if($container->getLinkLast()): ?>
					<a href="<?php echo $page->getHref() ?>"><?php endif ?>
					<span><?php echo $page->getLabel() ?></span>
					<?php if($container->getLinkLast()): ?></a><?php endif ?>
			</li>
		<?php endif ?>
	<?php endforeach ?>
</ul>