<div class="page-footer">
	<div class="page-footer-inner"> <?php echo date('Y') ?> &copy; Universo Produção
		<a href="http://universoproducao.com.br" title="Universo Produção" target="_blank">Universo Produção</a>
	</div>
	<div class="scroll-to-top">
		<i class="icon-arrow-up"></i>
	</div>
</div>

<div class="modal fade" id="report_result" tabindex="-1" role="basic" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                <h4 class="modal-title">Relatório</h4>
            </div>
            <div class="modal-body">
                O relatório está pronto. Efetuei o download clicando nos botões abaixo.
            </div>
            <div class="modal-footer">
                <button type="button" class="btn dark btn-outline" data-dismiss="modal">Sair</button>
                <a target="_blank" href="" class="btn green report-result-action download"><i class="fa fa-download"></i> Download</a>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>