<?php $container = $this->container; ?>

<div class="page-sidebar-wrapper">
	<!-- BEGIN SIDEBAR -->
	<div class="page-sidebar navbar-collapse collapse">
		<ul class="<?php echo $this->navigation($container)->menu()->getUlClass(); ?>" data-keep-expanded="false" data-auto-scroll="true" data-slide-speed="200" style="padding-top: 20px">
			<li class="sidebar-toggler-wrapper hide">
				<!-- BEGIN SIDEBAR TOGGLER BUTTON -->
				<div class="sidebar-toggler"> </div>
				<!-- END SIDEBAR TOGGLER BUTTON -->
			</li>
			<?php foreach ($container as $page): ?>
				<?php if (!$this->navigation()->accept($page)) continue; ?>
				<?php /* @var $page Zend\Navigation\Page\Mvc */ ?>
				<?php $hasChildren = $page->hasPages() ?>
				<?php if (!$hasChildren): ?>
					<?php if($page->get('heading')): ?>
						<li class="heading">
							<h3 class="uppercase">
								<?php echo $this->escapeHtml($this->translate($page->getLabel(), $this->navigation($container)->getTranslatorTextDomain())); ?>
							</h3>
						</li>
					<?php else: ?>
						<li class="nav-item <?php if ($page->isActive()) echo 'active' ?> <?php echo $page->getClass(); ?>">
							<a class="nav-link"
								href="<?php echo $page->getHref() ?>"
								<?php if ($page->getTarget() != ""): ?>
									target="<?php echo $page->getTarget(); ?>"
								<?php endif; ?>>

								<?php if ($page->get("icon") !== ""): ?>
									<i class="<?php echo $page->get("icon"); ?>"></i>
								<?php endif; ?>

								<span class="title">
									<?php echo $this->escapeHtml($this->translate($page->getLabel(), $this->navigation($container)->getTranslatorTextDomain())); ?>
								</span>

								<?php if ($page->isActive()): ?>
									<span class="selected"></span>
								<?php endif; ?>
							</a>
						</li>
					<?php endif; ?>
				<?php else: ?>
					<?php
					//check if access is allowed at least one item
					$access = false;
					foreach ($page->getPages() as $child) {
						if ($this->navigation()->accept($child) && $child->get("separator") !== true) {
							$access = true;
						}
					}
					if ($access) : ?>
						<li class="nav-item <?php if ($page->isActive(true)) echo ' active' ?>">
							<a class="nav-link nav-toggle" href="javascript:;">

								<?php if ($page->get("icon") !== ""): ?>
									<i class="<?php echo $page->get("icon"); ?>"></i>
								<?php endif; ?>

								<span class="title"><?php echo $this->escapeHtml($this->translate($page->getLabel(),$this->navigation($container)->getTranslatorTextDomain())); ?></span>

								<?php if ($page->isActive(true)): ?>
									<span class="selected"></span>
								<?php endif; ?>

								<span class="arrow"></span>
							</a>
							<ul class="sub-menu">
								<?php foreach ($page->getPages() as $child): ?>
									<?php if (!$this->navigation()->accept($child)) continue; ?>
									<?php if ($child->get("separator") === true): ?>
										<li class="divider"></li>
										<?php
										continue;
									endif;
									?>
									<li class="nav-item <?php if ($child->isActive()) echo ' active' ?>">
										<a class="nav-link "
											href="<?php echo $child->getHref() ?>"
											<?php if ($child->getTarget() != ""): ?>
												target="<?php echo $child->getTarget(); ?>"
											<?php endif; ?> >

											<!--<?php if ($child->get("icon") !== ""): ?>
												<i class="<?php echo $child->get("icon"); ?>"></i>
											<?php endif; ?>-->

											<span class="title"><?php echo $this->escapeHtml($this->translate($child->getLabel(),$this->navigation($container)->getTranslatorTextDomain())); ?></span>
										</a>
									</li>
								<?php endforeach ?>
							</ul>
						</li>
					<?php endif; ?>
				<?php endif ?>
			<?php endforeach ?>
		</ul>
	</div>
</div>