<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
	<!--<![endif]-->
	<!-- BEGIN HEAD -->
	<head>
		<meta charset="utf-8" />
		<title>SISAdmin | Universo Produção</title>
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta content="width=device-width, initial-scale=1" name="viewport" />
		<meta content="" name="description" />
		<meta content="" name="author" />

		<base href="<?php echo $this->basePath(); ?>">

		<!-- BEGIN GLOBAL MANDATORY STYLES -->
		<link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css" />
		<link rel="stylesheet" type="text/css" href="<?php echo $this->basepath('assets/admin/dev/css/global.css')?>" />

		<!-- END GLOBAL MANDATORY STYLES -->
		<!-- BEGIN THEME GLOBAL STYLES -->
		<link href="<?php echo $this->adminTemplateBasePath('assets/global/css/components.min.css')?>" rel="stylesheet" id="style_components" type="text/css" />
		<link href="<?php echo $this->adminTemplateBasePath('assets/global/css/plugins.min.css')?>" rel="stylesheet" type="text/css" />
		<!-- END THEME GLOBAL STYLES -->

		<!-- BEGIN THEME LAYOUT STYLES -->
		<link href="<?php echo $this->adminTemplateBasePath('assets/layouts/layout/css/layout.min.css');?>" rel="stylesheet" type="text/css" />
		<link href="<?php echo $this->adminTemplateBasePath('assets/layouts/layout/css/themes/default.min.css');?>" rel="stylesheet" type="text/css" id="style_color" />
		<!-- END THEME LAYOUT STYLES -->

		<link rel="stylesheet" type="text/css" href="<?php echo $this->basepath('assets/admin/dev/css/custon.css')?>" />

		<script type="text/javascript" src='<?php echo $this->basePath('assets/admin/dev/js/vendor/tinymce/js/tinymce/tinymce.min.js'); ?>'></script>
		<script type="text/javascript" src='<?php echo $this->basePath('assets/admin/dev/js/vendor/tinymce/js/tinymce/jquery.tinymce.min.js'); ?>'></script>

		<link rel="shortcut icon" href="favicon.ico" /> </head>
	<!-- END HEAD -->

	<body class="page-header-fixed page-sidebar-closed-hide-logo page-content-white">
		<!-- BEGIN HEADER -->
		<?php echo $this->partial('layout/_pageheader.phtml')?>
		<!-- END HEADER -->
		<!-- BEGIN HEADER & CONTENT DIVIDER -->
		<div class="clearfix"> </div>
		<!-- END HEADER & CONTENT DIVIDER -->
		<!-- BEGIN CONTAINER -->
		<div class="page-container">
			<!-- BEGIN SIDEBAR -->
			<?php  echo $this
				->navigation('navigation')
				->menu()
				->setUlClass('page-sidebar-menu  page-header-fixed ')
				->setPartial('layout/_mainmenu.phtml');  ?>
			<!-- END SIDEBAR -->
			<!-- BEGIN CONTENT -->
			<div class="page-content-wrapper">
				<!-- BEGIN CONTENT BODY -->
				<div class="page-content">
					<!-- BEGIN PAGE HEADER-->
					<?php //echo $this->partial('layout/_themeoptions.phtml')?>
					<!-- BEGIN PAGE BAR -->
					<div class="page-bar">
					<?php echo $this
						->navigation('navigation')
						->breadcrumbs()
						->setMinDepth(0)
						->setPartial('layout/_breadcrumbs.phtml'); ?>
					</div>
					<!-- END PAGE BAR -->

					<!-- PAGE CONTENT -->

					<h3 class="page-title">Páginas
						<small>Edição de páginas</small>
					</h3>

					<?php echo $this->messages(); ?>

					<?php echo $this->content; ?>
					<!-- END PAGE CONTENT -->

				</div>
				<!-- END CONTENT BODY -->
			</div>
			<!-- END CONTENT -->
			<!-- BEGIN QUICK SIDEBAR -->
			<?php //echo $this->partial('layout/_quicksidebar.phtml'); ?>
			<!-- END QUICK SIDEBAR -->
		</div>

		<?php echo $this->partial('layout/_modal-responsivefilemanager.phtml'); ?>

		<!-- END CONTAINER -->
		<!-- BEGIN FOOTER -->
		<?php echo $this->partial('admin/footer'); ?>
		<!-- END FOOTER -->

		<!--[if lt IE 9]>
		<script src="<?php echo $this->adminTemplateBasePath('assets/global/plugins/respond.min.js'); ?>"></script>
		<script src="<?php echo $this->adminTemplateBasePath('assets/global/plugins/excanvas.min.js'); ?>"></script>
		<![endif]-->

		<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
		<script>window.jQuery || document.write('<script src="<?php echo $this->basepath('assets/global/js/vendor/jquery-1.11.2.min.js')?>"><\/script>')</script>
		<script src="<?php echo $this->basepath('assets/admin/dev/js/footer.js')?>" type="text/javascript"></script>
		<script src="<?php echo $this->basepath('assets/admin/dev/js/custom.js')?>" type="text/javascript"></script>
        <?php echo $this->inlineScript(); ?>
	</body>
</html>