<div class="panel-group accordion admin-menu-add" id="accordion1">
	<div class="panel panel-default admin-menu-add-page">
		<div class="panel-heading">
			<h4 class="panel-title">
				<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion1" href="#collapse_pages"> Páginas </a>
			</h4>
		</div>
		<div id="collapse_pages" class="panel-collapse in">
			<div class="panel-body">
				<form action="" name="admin-menu-add-page-form">

					<input type="hidden" name="type" value="post">

					<div class="tabbable-custom nav-justified">
						<ul class="nav nav-tabs nav-justified">
							<li class="active"><a href="#tab_all_pages" data-toggle="tab"> Ver tudo </a></li>
							<li><a href="#tab_search_pages" data-toggle="tab"> Pesquisar </a></li>
						</ul>
						<div class="tab-content">
							<div class="tab-pane active" id="tab_all_pages">
								<div class="panel-body" style="height:200px; overflow-y:auto;">
									<div class="form-group">
										<div class="page-list">
											<?php echo $this->adminMenuPages($this->pages); ?>
										</div>
									</div>
								</div>
							</div>
							<div class="tab-pane" id="tab_search_pages">
								<div class="panel-body" style="height:200px; overflow-y:auto;">
									<div class="form-group">
										<div class="input-group">
											<input class="form-control" type="text" name="str-search-page">
											<span class="input-group-btn">
												<button class="btn btn-success search-page-action" type="button">
													<i class="fa fa-search fa-fw"></i> Pesquisar</button>
											</span>
										</div>
									</div>

									<div class="form-group">
										<div class="page-list">
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>

					<div class="form-group">
						<div class="action  pull-right">
							<a class="btn icheckcontrol">Selecionar todos</a>
							<button class="btn btn-default action-add">Adicionar ao menu</button>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div> <!-- Final panel -->

	<div class="panel panel-default admin-menu-add-external-url">
		<div class="panel-heading">
			<h4 class="panel-title">
				<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion1" href="#collapse_linkspersonalizados"> Links Personalizados </a>
			</h4>
		</div>
		<div id="collapse_linkspersonalizados" class="panel-collapse collapse">
			<div class="panel-body">
				<div class="form">
					<form action="" name="admin-menu-add-external-url-form">

						<input type="hidden" name="type" value="external">

						<div class="form-group">
							<label for="">URL</label>
							<input type="text" class="form-control" name="url" required="required" value="" placeholder="http://">
						</div>

						<div class="form-group">
							<label for="">Texto do Link</label>
							<input type="text" class="form-control" name="label" required="required" placeholder="Item do menu">
						</div>

						<div class="form-group form-actions">
							<button class="btn btn-default pull-right action-add">Adicionar ao menu</button>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div> <!-- final panel -->

</div> <!-- Final panel-group -->