<?php $form = $this->form; ?>
<div class="row post news">
	<div class="col-md-12">
		<?php $form->prepare(); echo $this->form(null, null)->openTag($form) ?>
		<div class="portlet light portlet-fit bordered">
			<div class="portlet-title">
				<div class="caption">
					<?php if($this->category->getId()): ?>
					<i class="fa fa-edit"></i>
					Editar Categoria
					<?php else: ?>
					<i class="fa fa-file-o"></i>
					Cadastrar Categoria
					<?php endif; ?>
				</div>
				<div class="actions">
					<a href="<?php echo $this->url('admin/default', ['controller'=>'educational-project-category']); ?>"
					   class="btn btn-default">
						<i class="icon-action-undo"></i>
						<span class="hidden-xs"> Voltar </span>
					</a>
                    <a href="<?php echo $this->url('admin/default', ['controller'=>'educational-project-category', 'action'=>'create']); ?>"
                       class="btn blue btn-lg">
                        <i class="fa fa-plus"></i>
                        <span class="hidden-xs"> Nova Categoria  </span>
                    </a>
				</div>
			</div>
			<div class="portlet-body">
				<div class="portlet">

					<div class="portlet-body form">
						<div class="form-body">
                            <div class="row">
                                <?php echo $this->formRow($form->get('name')); ?></div>
                                <?php echo $this->formRow($form->get('registration')); ?></div>
                            </div>
                        </div>
						<div class="form-actions">
							<div class="row">
								<div class="col-md-offset-3 col-md-9">
									<button type="submit" class="btn blue btn-lg action-save">Salvar</button>
									<a href="#" class="btn red btn-lg action cancel">Descartar</a>
								</div>
							</div>
						</div>

					</div>
				</div>
			</div>
		</div>
		<?php echo $this->form()->closeTag() ?>
	</div>
</div>