<?php $this->placeholder("home-class")->set("home"); ?>


<section class="banner">
    <div class="banner-items owl-carousel">
        <?php foreach ($this->bannerImages as $banner): ?>
            <div class="banner-item">
                <a target="_blank" href="<?php echo $banner->getMeta('_link') ?>">
                    <img src="<?php echo $this->thumbor()->url($banner->getMeta('_image'))->resize(1920, 648); ?>" alt="">
                    <p class="banner-caption"><?php echo $banner->getSubtitle(); ?></p>
                </a>
            </div>
        <?php endforeach; ?>
    </div>
</section>

<!-- Info -->
<!--<section class="notice">
    <div class="main-wrapper">
        <p class="notice-text"> Inscrições abertas para oficinas na 20ª Mostra de Cinema de Tiradentes
            de tiradentes</p>
        <a href="http://www.universoproducao.com.br/site/inscricoes.php?menu=ins" class="button-readmore">Inscreva-se</a>
    </div>
</section>-->

<!-- PRogramação -->
<?php
$programHighlight = $this->programHighlight;
$program = $this->program;
?>
<?php if($programHighlight && count($program)): ?>
<section class="prog">
    <div class="main-wrapper">
        <header class="main-header"><h1 class="section-title">Programação</h1></header>
    </div>
    <div class="prog-items">
        <article class="prog-item prog-item--high">
            <a href="<?php echo $programHighlight->getUrl(); ?>">
                <figure class="prog-figure">
                    <img class="grayscale" src="<?php echo  $this->thumbor()->url($programHighlight->getPhoto())->resize(960, 648); ?>" alt="">
                </figure>
                <div class="prog-content">
                    <p class="prog-day"><?php echo $programHighlight->getDate()->format('d'); ?>
                        <small><?php echo  str_replace('-feira', '', $this->dateFormat($programHighlight->getDate(), null, null, "pt_BR", "ccc")); ?></small>
                    </p>
                    <p class="prog-title"><?php echo $programHighlight->getTitle(); ?></p>
                    <p class="prog-cat"><?php echo $programHighlight->getSubTitle(); ?></p>
                    <p class="prog-place">
                        <?php echo $programHighlight->getPlace(); ?> - <?php echo $programHighlight->getHour(); ?>
                    </p>
                </div>
            </a>
        </article>
        <?php foreach ($program as $p): ?>
            <article class="prog-item">
                <a href="<?php echo $p->getUrl(); ?>">
                    <figure class="prog-figure">
                        <img class="grayscale" src="<?php echo  $this->thumbor()->url($p->getPhoto())->resize(960, 648); ?>" alt="">
                    </figure>
                    <div class="prog-content">
                        <p class="prog-day"><?php echo $p->getDate()->format('d'); ?>
                            <small><?php echo  str_replace('-feira', '', $this->dateFormat($p->getDate(), null, null, "pt_BR", "ccc")); ?></small>
                        </p>
                        <p class="prog-title"><?php echo $p->getTitle(); ?></p>
                        <p class="prog-cat"><?php echo $p->getSubTitle(); ?></p>
                        <p class="prog-place">
                            <?php echo $p->getPlace(); ?> - <?php echo $p->getHour(); ?>
                        </p>
                    </div>
                </a>
            </article>
        <?php endforeach; ?>
    </div>
    <div class="main-wrapper">
        <p class="prog-text">De 19 a 27 de janeiro, você estará em sintonia com o cinema em Tiradentes. São exposições, exibições de curtas e longas, debates, seminários e oficinas com grandes nomes da sétima arte
            <br /><a href="http://universoproducao.com.br/source/21Tiradentes/releases/Folder_21MCT_BX.pdf" class="button-readmore">Programação Completa</a></p>
    </div>
</section>
<?php endif; ?>

<section class="news">
    <div class="main-wrapper">
        <header class="main-header">
            <div class="main-wrapper">
                <h1 class="section-title">
                    <img src="<?php echo $this->basePath('assets/mostratiradentes2020/dist'); ?>/images/2020/news-icon.png" alt="">Notícias</h1>
            </div>
        </header>
        <div class="news-items">
            <?php foreach ($this->news as $news): ?>
            <article class="news-item">
                <a href="<?php echo $this->url("mostratiradentes2020/news", ['slug'=>$news->getSlug()]) ?>" class="news-link">
                    <figure class="news-figure"><img src="<?php echo  $this->thumbor()->url($news->getMeta('_thumb'))->resize(482, 360); ?>" alt=""></figure>
                    <p class="news-title"><?php echo $news->getTitle(); ?></p>
                    <p class="news-sub"><?php echo $this->truncate($news->getSubtitle()); ?></p>
                    <p class="news-readmore" style="color: #3eabc7">Leia mais +</p>
                </a>
            </article>
            <?php endforeach; ?>
        </div>
        <p class="news-all"><a class="button-readmore" href="<?php echo $this->url("mostratiradentes2020/default", ['slug'=>'noticias']); ?>">Todas as Notícias</a></p>
    </div>
</section>

<!-- TV -->
<?php if(count($this->videos)): ?>
<section class="tv">
    <div class="main-wrapper">
        <header class="main-header">
            <h1 class="section-title"><img src="<?php echo $this->basePath('assets/mostratiradentes2020/dist'); ?>/images/2020/prog-video.png" alt="">Videos</h1>
        </header>

        <div class="tv-items">
            <?php foreach ($this->videos as $v): ?>
            <article class="tv-item">
                <a  data-fancybox class="tv-link" href="<?php echo $v->getYoutube(); ?>">
                    <figure class="tv-figure">
                        <img src="<?php echo $this->thumbor()->url($v->getThumb())->resize(640, 396); ?>" alt="">
                    </figure>
                    <div class="tv-content">
                        <p class="tv-title"><?php echo $v->getCaption(); ?></p>
                    </div>
                </a>
            </article>
            <?php endforeach; ?>
        </div>
        <p class="tv-all"><a class="button-readmore" href="https://www.youtube.com/channel/UCaikc9czwiws39fvlHX-RpA">Ver todos os vídeos</a></p>
    </div>
</section>
<?php endif; ?>

<section class="gallery">

    <header class="main-header">
        <div class="main-wrapper">
            <h1 class="section-title">
                <img src="<?php echo $this->basePath('assets/mostratiradentes2020/dist'); ?>/images/2020/gal-icon.png  " alt="">Galeria de imagens</h1>
        </div>
    </header>

    <div class="gallery-wrapper">
        <div class="gallery-list owl-carousel">
            <?php foreach ($this->gallery as $img): ?>
                <div class="gallery-item">
                    <figure class="gallery-figure">
                        <img src="<?php echo $this->thumbor()->url($img->getMeta('_image'))->resize(382, 362); ?>" alt="">
                    </figure>
                    <!--<div class="gallery-desc">
                        <p class="gallery-title"><?php /*echo $img->getTitle(); */?>
                            <span><?php /*echo $img->getMeta('_credits'); */?></span></p>
                    </div>-->
                </div>
            <?php endforeach; ?>
        </div>
    </div>
    <p class="gallery-all"><a target="_blank" href="https://www.flickr.com/photos/universoproducao/" class="button-readmore">Galeria Completa</a></p>
</section>

<section class="guide">
    <div class="main-wrapper">
        <header class="guide-header">
            <h1>Descubra Tiradentes</h1>
        </header>
        <ul class="guide-items">
            <li class="guide-item">
                <a href="<?php echo $this->url("mostratiradentes2020/default", ['slug'=>'como-chegar']) ?>" class="guide-link">
                    <img src="<?php echo $this->basePath('assets/mostratiradentes2020/dist'); ?>/images/2020/como-chegar.png" alt="">
                    <p class="guide-title">Como Chegar</p>
                </a>
            </li>
            <li class="guide-item">
                <a href="<?php echo $this->url("mostratiradentes2020/default", ['slug'=>'turismo-e-informacoes']) ?>" class="guide-link">
                    <img src="<?php echo $this->basePath('assets/mostratiradentes2020/dist'); ?>/images/2020/turismo.png" alt="">
                    <p class="guide-title">Turismo e Informações</p>
                </a>
            </li>
            <li class="guide-item">
                <a href="<?php echo $this->url("mostratiradentes2020/default", ['slug'=>'restaurantes']) ?>" class="guide-link">
                    <img src="<?php echo $this->basePath('assets/mostratiradentes2020/dist'); ?>/images/2020/restaurantes.png" alt="">
                    <p class="guide-title">Restaurantes</p>
                </a>
            </li>
            <li class="guide-item">
                <a href="<?php echo $this->url("mostratiradentes2020/default", ['slug'=>'hoteis-e-acomodacoes']) ?>" class="guide-link">
                    <img src="<?php echo $this->basePath('assets/mostratiradentes2020/dist'); ?>/images/2020/hoteis.png" alt="">
                    <p class="guide-title">hotéis e acomodações</p>
                </a>
            </li>
        </ul>
    </div>
</section>

<section class="eufacoamostra">
    <div class="main-wrapper">
        <header class="eufacoamostra-header">
            <h1><span class="icon icon-eufacoamostra"></span></h1>
            <p class="eufacoamostra-subtitle">Compartilhe e publique suas imagens usando a #eufaçoaMostra</p>
        </header>
    </div>
    <div class="eufacoamostra-items">
        <?php foreach ($this->eufacoamostra as $eu): ?>
            <div class="eufacoamostra-item <?php echo !empty($eu->getVideo()) ? "eufacoamostra-item--video" : ""; ?>">
                <?php $href = $eu->getVideo() ? $this->youtubeEmbed($eu->getVideo()) : $this->thumbor()->url($eu->getThumb())->resize(700, 700); ?>
                <a title="<?php echo $eu->getDescription(); ?>" rel="eufacoamostra" href="<?php echo $href ?>" class="eufacoamostra-link fancybox <?php echo !empty($eu->getVideo) ? "fancybox.iframe" : ""; ?>">
                    <figure class="eufacoamostra-figure"><img class="grayscale grayscale-fade" src="<?php echo $this->thumbor()->url($eu->getThumb())->resize(700, 700); ?>" alt=""></figure></a></div>
        <?php endforeach; ?>
    </div>
    <p class="news-all"><a href="https://www.flickr.com/photos/universoproducao/" class="button-readmore">Veja Mais Galerias</a></p>
</section>

<section class="newsletter">
    <div class="main-wrapper">
        <header class="newsletter-header">
            <h1>Receba Nossos Informativos</h1>
        </header>
        <form action="<?php echo $this->url("mostratiradentes2020/newsletter") ?>" method="post" class="newsletter-form">
            <input required type="text" class="newsletter-input" placeholder="Nome">
            <input required type="text" class="newsletter-input" placeholder="Email">
            <button type="submit" class="newsletter-submit">Cadastrar</button>
        </form>
    </div>
</section>

<!--<section class="sponsorship">
    <div class="main-wrapper">
        <ul class="sponsorship-list">
            <li class="sponsorship-block sponsorship-block--full">
                <ul class="sponsorship-items">
                    <li class="sponsorship-item"><span class="sprite sprite-lei"></span></li>
                </ul>
            </li>
            <li class="sponsorship-block sponsorship-block--full">
                <p class="sponsorship-title">Patrocínio</p>
                <ul class="sponsorship-items">
                    <li class="sponsorship-item"><span class="sprite sprite-taesa"></span></li>
                    <li class="sponsorship-item"><span class="sprite sprite-kinea"></span></li>
                    <li class="sponsorship-item"><span class="sprite sprite-csn"></span></li>
                    <li class="sponsorship-item"><span class="sprite sprite-cbmm"></span></li>
                    <li class="sponsorship-item"><span class="sprite sprite-copasa"></span></li>
                    <li class="sponsorship-item"><span class="sprite sprite-cemig"></span></li>

                </ul>
            </li>

            <li class="sponsorship-block">
                <p class="sponsorship-title">PARCERIA CULTURAL</p>
                <ul class="sponsorship-items">
                    <li class="sponsorship-item"><span class="sprite sprite-sesc"></span></li>
                </ul>
            </li>
            <li class="sponsorship-block">
                <p class="sponsorship-title">Fomento</p>
                <ul class="sponsorship-items">
                    <li class="sponsorship-item"><span class="sprite sprite-codemge"></span></li>
                </ul>
            </li>

            <li class="sponsorship-block sponsorship-block--full">
                <p class="sponsorship-title">Apoio</p>
                <ul class="sponsorship-items">
                    <li class="sponsorship-item"><span class="sprite sprite-nova-era"></span></li>
                    <li class="sponsorship-item"><span class="sprite sprite-oi"></span></li>
                    <li class="sponsorship-item"><span class="sprite sprite-instituto-universo"></span></li>
                    <li class="sponsorship-item"><span class="sprite sprite-sesi"></span></li>
                    <li class="sponsorship-item"><span class="sprite sprite-tres"></span></li>
                    <li class="sponsorship-item"><span class="sprite sprite-wals"></span></li>
                    <li class="sponsorship-item"><span class="sprite sprite-ministerio-relacoes-exteriores"></span></li>
                    <li class="sponsorship-item"><span class="sprite sprite-senac"></span></li>
                    <li class="sponsorship-item"><span class="sprite sprite-cinema-brasil"></span></li>
                    <li class="sponsorship-item"><span class="sprite sprite-dot"></span></li>
                    <li class="sponsorship-item"><span class="sprite sprite-mistika"></span></li>
                    <li class="sponsorship-item"><span class="sprite sprite-ctaw"></span></li>
                    <li class="sponsorship-item"><span class="sprite sprite-naymar"></span></li>
                    <li class="sponsorship-item"><span class="sprite sprite-cinecolor"></span></li>
                    <li class="sponsorship-item"><span class="sprite sprite-globo"></span></li>
                    <li class="sponsorship-item"><span class="sprite sprite-canal-brasil"></span></li>
                    <li class="sponsorship-item"><span class="sprite sprite-institut-francais"></span></li>
                    <li class="sponsorship-item"><span class="sprite sprite-etc"></span></li>
                    <li class="sponsorship-item"><span class="sprite sprite-academia-internacional-cinema"></span></li>
                    <li class="sponsorship-item"><span class="sprite sprite-policia-militar"></span></li>
                    <li class="sponsorship-item"><span class="sprite sprite-prefeitura-tiradentes"></span></li>
                    <li class="sponsorship-item"><span class="sprite sprite-cultural"></span></li>
                </ul>
            </li>

            <li class="sponsorship-block sponsorship-block--20">
                <p class="sponsorship-title">Incentivo</p>
                <ul class="sponsorship-items">
                    <li class="sponsorship-item"><span class="sprite sprite-lei-estadual-mg"></span></li>
                </ul>
            </li>

            <li class="sponsorship-block sponsorship-block--80">
                <p class="sponsorship-title">Realização</p>
                <ul class="sponsorship-items">
                    <li class="sponsorship-item"><span class="sprite sprite-universo"></span></li>
                    <li class="sponsorship-item" style="float: right;"><span class="sprite sprite-governo-federal"></span></li>
                    <li class="sponsorship-item" style="float: right;"><span class="sprite sprite-ministerio-cidadania"></span></li>
                </ul>
            </li>

        </ul>
    </div>
</section>-->

<section class="sitemap">
    <div class="main-wrapper">
        <?php $this
            ->navigation('MostratiradentesNavigation2020')
            ->menu()->setPartial("mostratiradentes2020/partials/sitemap.phtml");

        echo $this
            ->navigation('MostratiradentesNavigation2020')
            ->menu()
            ->render(); ?>
    </div>
</section>