<!doctype html>
<html lang="">
    <head>
        <meta charset="utf-8">
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <title>Mostra Tiradentes 2020</title>
        <link rel="apple-touch-icon" href="apple-touch-icon.png">
        <link href="https://fonts.googleapis.com/css?family=Open+Sans&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="<?php echo $this->basePath('assets/mostratiradentes2020-tmp') ?>/main.css?v=20200305111600">

    </head>
    <body>
        <div class="wrapper">

            <div class="left">
                <a href="http://www.mostratiradentes.com.br/inicio">
                    <img src="<?php echo $this->basePath('assets/mostratiradentes2020-tmp') ?>/tiradentes.png" alt="">
                </a>
            </div>

            <div class="right">
                <a href="http://www.mostratiradentessp.com.br">
                    <img src="<?php echo $this->basePath('assets/mostratiradentes2020-tmp') ?>/sp.png" alt="">
                </a>
            </div>

        </div>
    </body>
</html>
