<div class="row">
	<div class="col-md-12">
		<div class="portlet light portlet-fit portlet-datatable bordered">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-th-list"></i>
					Lista de Perfis
				</div>
				<div class="actions">
					<a href="<?php echo $this->url('admin/default', ['controller'=>'profile', 'action'=>'create']); ?>"
					   class="btn blue btn-lg">
						<i class="fa fa-plus"></i>
						<span class="hidden-xs"> Inserir Perfil </span>
					</a>
					<div class="btn-group">
						<a class="btn btn-default dropdown-toggle" href="javascript:;" data-toggle="dropdown">
							<i class="fa fa-share"></i>
							<span class="hidden-xs"> Opções </span>
							<i class="fa fa-angle-down"></i>
						</a>
						<div class="dropdown-menu pull-right">
							<li><a href="javascript:;"> Exportar para Excel </a></li>
							<li><a href="javascript:;"> Exportar para PDF </a></li>
							<li class="divider"></li>
							<li><a href="javascript:;"> Imprimir </a></li>
						</div>
					</div>
				</div>
			</div>

			<div class="portlet-body">
				<div class="table-container post-list">
					<table class="table table-striped table-bordered table-hover">
						<thead>
						<tr role="row" class="heading">
							<th width="2%">#</th>
							<th width="78%">Nome</th>
							<th width="20%"></th>
						</tr>
						</thead>
						<tbody>
						<?php foreach ($this->profiles as $profile):
							$updateUrl = $this->url('admin/default', [
								'controller' => 'profile',
								'action'=>'update',
								'id'=>$profile->getId()
							]);

							$removeUrl = $this->url('admin/default', [
								'controller' => 'profile',
								'action'=>'delete',
								'id'=>$profile->getId(),
							]);
							?>
							<tr>
								<td></td>
								<td><a href="<?php echo $updateUrl; ?>"><?php echo $profile->getName(); ?></a></td>
								<td>
									<a href="<?php echo  $updateUrl; ?>" class="btn btn-sm btn-default">
										<i class="fa fa-edit"></i> Editar
									</a>
									<a href="<?php echo $removeUrl; ?>" class="btn btn-sm btn-default post-list-remove">
										<i class="fa fa-close"></i> Excluir
									</a>
								</td>
							</tr>
						<?php endforeach; ?>
						</tbody>
					</table>

					<div class="table-paginator">
						<?php echo $this->paginationcontrol($this->profiles, 'sliding', 'admin/partials/paginator.phtml'); ?>
					</div>

				</div>
			</div>
		</div>
	</div>
</div>