<?php $form = $this->form; ?>
<div class="row post page">
<div class="col-md-12">
	<?php $form->prepare(); echo $this->form(null, null)->openTag($form) ?>

	<div class="portlet light portlet-fit bordered">
		<div class="portlet-title">
			<div class="caption">
				<?php if($this->page->getId()): ?>
				<i class="fa fa-edit"></i>
				Editar Página
				<?php else: ?>
				<i class="fa fa-file-o"></i>
				Nova Página
				<?php endif; ?>
			</div>
			<div class="actions">
				<a href="<?php echo $this->url('admin/page', ['site'=>$this->site]); ?>"
				   class="btn btn-default">
					<i class="icon-action-undo"></i>
					<span class="hidden-xs"> Voltar </span>
				</a>
				<a href="<?php echo $this->url('admin/page', ['site'=>$this->site, 'action'=>'create']); ?>"
				   class="btn btn-default">
					<i class="fa fa-plus"></i>
					<span class="hidden-xs"> Nova Página </span>
				</a>
			</div>
		</div>
		<div class="portlet-body">
			<div class="row">
				<div class="col-md-9">
					<div class="portlet">
						<div class="portlet-body form">
							<div class="">
								<?php
								echo $this->formRow($form->get('title'));
								echo $this->formRow($form->get('subtitle'));
								echo $this->partial('admin/partials/_post-cover.phtml', ['form'=>$this->form]);
								echo $this->formRow($form->get('content'));
								?>
							</div>
						</div>
					</div>
				</div>
				<div class="col-md-3">

					<?php echo $this->partial('admin/partials/_post-sidebar.phtml', [
						'returnUrl' => $this->url('admin/page', array('site'=>$this->site)),
                        'createUrl' => $this->url('admin/page', array('action'=>'create', 'site'=>$this->site)),
                        'updateUrl' => $this->url('admin/page', array('action'=>'update', 'site'=>$this->site, 'id'=>$this->page->getId())),
                        'route'=>'admin/page',
                        'route_options' => array('site'=>$this->site),
						'site' => $this->site,
						'form' => $this->form,
						'post' => $this->page,
                        'site_route' => isset($this->site_route) ? $this->site_route : null,
                        'thumb' => true
					]) ?>


				</div>
			</div>
		</div>
	</div>
	<?php echo $this->form()->closeTag() ?>
</div>
</div>