<?php $form = $this->searchForm; ?>
<div class="row">
	<div class="col-md-12">
		<div class="portlet light portlet-fit portlet-datatable bordered">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-th-list"></i>
					Lista de Páginas - <?php echo $this->currentSite->getEvent()->getShortName(); ?>
				</div>
				<div class="actions">
					<a href="<?php echo $this->url('admin/page', ['site'=>$this->site, 'action'=>'create']); ?>"
					   class="btn blue btn-lg">
						<i class="fa fa-plus"></i>
						<span class="hidden-xs"> Nova Página </span>
					</a>
					<div class="btn-group">
						<a class="btn btn-default dropdown-toggle" href="javascript:;" data-toggle="dropdown">
							<i class="fa fa-share"></i>
							<span class="hidden-xs"> Opções </span>
							<i class="fa fa-angle-down"></i>
						</a>
						<div class="dropdown-menu pull-right">
							<li><a href="#change-event" data-toggle="modal"> Alterar Evento </a></li>
						</div>
					</div>
				</div>
			</div>

			<div class="portlet-body">


				<div class="table-container post-list">
					<table class="table table-striped table-bordered table-hover">
						<thead>
							<tr role="row" class="heading">
								<th width="2%">#</th>
								<th width="15%">Título</th>
								<th width="10%">Data de Publicação</th>
                                <th width="10%">Idioma</th>
								<th width="10%">Status</th>
								<th width="10%">Autor</th>
								<th width="10%">Ações</th>
							</tr>
							<tr role="row" class="filter">
								<?php $form->prepare(); echo $this->form()->openTag($form); ?>
								<td></td>
								<td><?php echo $this->formelement($form->get('title')); ?></td>
								<td>
									<div class="input-group date date-picker margin-bottom-5" data-date-format="dd/mm/yyyy">
										<?php echo $this->formelement($form->get('dateInit')); ?>
										<span class="input-group-btn">
												<button class="btn btn-sm default" type="button">
													<i class="fa fa-calendar"></i>
												</button>
											</span>
									</div>
									<div class="input-group date date-picker" data-date-format="dd/mm/yyyy">
										<?php echo $this->formelement($form->get('dateEnd')); ?>
										<span class="input-group-btn">
												<button class="btn btn-sm default" type="button">
													<i class="fa fa-calendar"></i>
												</button>
											</span>
									</div>
								</td>
                                <td><?php echo $this->formelement($form->get('language')); ?></td>
								<td><?php echo $this->formelement($form->get('status')); ?></td>
								<td><?php echo $this->formelement($form->get('author')); ?></td>
								<td>
									<div class="margin-bottom-5">
										<button class="btn btn-sm blue filter-submit margin-bottom"><i class="fa fa-search"></i> Pesquisar</button>
                                        <button class="btn btn-sm btn-default filter-cancel"><i class="fa fa-times"></i> Limpar</button>
									</div>
								</td>
								<?php echo $this->form()->closeTag(); ?>
							</tr>
						</thead>
						<tbody>
						<?php foreach ($this->pages as $page):
							$updateUrl = $this->url('admin/page', [
								'action'=>'update',
								'id'=>$page->getId(),
								'site'=>$this->site
							]);

							$removeUrl = $this->url('admin/page', [
								'action'=>'delete',
								'id'=>$page->getId(),
								'site'=>$this->site
							]);

							$restoreUrl = $this->url('admin/page', [
								'action'=>'restore',
								'id'=>$page->getId(),
								'site'=>$this->site
							]);

							?>
							<tr>
								<td></td>
								<td><a href="<?php echo $updateUrl; ?>"><?php echo $page->getTitle(); ?></a></td>
								<td><?php echo $page->getPostDate()->format('d/m/Y \á\s H:i'); ?></td>
                                <td><?php echo $page->getLanguage() ? $page->getLanguage()->getName() : ""; ?></td>
								<td><?php echo $this->statusLabel($page->getStatus()); ?></td>
								<td><?php echo $page->getAuthor()->getName(); ?></td>
								<td>
									<?php if($page->getStatus() != \Application\Entity\Post\PostStatus::TRASH): ?>
									<a href="<?php echo  $updateUrl; ?>" class="btn btn-sm btn-default">
										<i class="fa fa-edit"></i> Editar
									</a>
									<a href="<?php echo $removeUrl; ?>" class="btn btn-sm btn-default post-list-remove">
										<i class="fa fa-trash-o"></i> Lixeira
									</a>
									<?php else: ?>
									<div class="margin-bottom-5"><a href="<?php echo  $restoreUrl; ?>" class="btn btn-sm btn-default">
										<i class="fa fa-undo"></i> Restaurar
									</a></div>
									<a href="<?php echo $removeUrl; ?>" class="btn btn-sm btn-default post-list-remove">
										<i class="fa fa-times"></i> Excluir permanentemente
									</a>
									<?php endif; ?>

								</td>
							</tr>
						<?php endforeach; ?>
						</tbody>
					</table>

					<?php /*if(!count($this->pages) > 0) echo $this->messages([
						'type' => 'info',
						'title' => 'Atenção!',
						'message' => 'Nenhum dado foi encontrado!'
					]); */?>

					<div class="table-paginator">
						<?php echo $this->paginationcontrol(
							$this->pages,
							'sliding',
							'admin/partials/paginator.phtml',
							array(
								'route'=>'admin/page',
								'route_options' => array('site'=>$this->site)
							)
						); ?>
					</div>

				</div>
			</div>
		</div>
	</div>
</div>
<?php echo $this->partial('admin/page/_change_event.phtml', ['currentSite'=>$this->currentSite, 'sites'=>$this->sites]); ?>