<!doctype html>
<html class="no-js" lang="">
<head>
    <meta charset="utf-8">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>22ª Mostra de Cinema de Tiradentes</title>

    <link rel="apple-touch-icon" sizes="57x57" href="<?php echo $this->basePath('assets/tiradentes2019/dist/images/five') ?>/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="<?php echo $this->basePath('assets/tiradentes2019/dist/images/five') ?>/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="<?php echo $this->basePath('assets/tiradentes2019/dist/images/five') ?>/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="<?php echo $this->basePath('assets/tiradentes2019/dist/images/five') ?>/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="<?php echo $this->basePath('assets/tiradentes2019/dist/images/five') ?>/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="<?php echo $this->basePath('assets/tiradentes2019/dist/images/five') ?>/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="<?php echo $this->basePath('assets/tiradentes2019/dist/images/five') ?>/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="<?php echo $this->basePath('assets/tiradentes2019/dist/images/five') ?>/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="<?php echo $this->basePath('assets/tiradentes2019/dist/images/five') ?>/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192"  href="<?php echo $this->basePath('assets/tiradentes2019/dist/images/five') ?>/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="<?php echo $this->basePath('assets/tiradentes2019/dist/images/five') ?>/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="<?php echo $this->basePath('assets/tiradentes2019/dist/images/five') ?>/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="<?php echo $this->basePath('assets/tiradentes2019/dist/images/five') ?>/favicon-16x16.png">
    <link rel="manifest" href="<?php echo $this->basePath('assets/tiradentes2019/dist/images/five') ?>/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="<?php echo $this->basePath('assets/tiradentes2019/dist/images/five') ?>/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">

    <link rel="stylesheet" href="<?php echo $this->basePath('assets/tiradentes2019/dist') ?>/styles/vendor.css">
    <link rel="stylesheet" href="<?php echo $this->basePath('assets/tiradentes2019/dist') ?>/styles/main.css?time201801161559">

<!--    <script src="--><?php //echo $this->base    Path('assets/tiradentes2019/dist') ?><!--/scripts/modernizr/modernizr.js"></script>-->
</head>
<body>

<div class="site__wrapper">
    <header class="header">
        <!--<div class="header-bgc">
            <div class="header-wrapper">
                <h1 class="brand">
                    <a href="<?php /*echo $this->url("tiradentes2019/index"); */?>" class="brand-link">
                        <span class="icon icon-brand"></span>
                    </a>
                </h1>
                <div class="brand-right">
                    <p class="name">20-28 Janeiro 2017<span>Programação Gratuita</span></p>
                    <ul class="social">
                        <li class="social-item"><a target="_blank" class="social-link" href="https://www.facebook.com/tiradentes2019"><span class="icon icon-facebook"></span></a></li>
                        <li class="social-item"><a target="_blank" class="social-link" href="https://www.youtube.com/user/universoproducao"><span class="icon icon-youtube"></span></a></li>
                        <li class="social-item"><a target="_blank" class="social-link" href="https://www.instagram.com/universoproducao/"><span class="icon icon-instagram"></span></a></li>
                        <li class="social-item"><a target="_blank" class="social-link" href="https://www.flickr.com/photos/universoproducao/"><span class="icon icon-flickr"></span></a></li>
                    </ul>
                </div>
            </div>
        </div>-->
        <div class="header-bgc header-desk">
            <h1 class="brand">
                <img src="<?php echo $this->basePath('assets/tiradentes2019/dist'); ?>/images/2019/header.jpg" alt="">
            </h1>
        </div>
        <div class="header-mobile">
            <h1 class="brand">
                <img src="<?php echo $this->basePath('assets/tiradentes2019/dist'); ?>/images/2019/logo.png" alt="">
                <img src="<?php echo $this->basePath('assets/tiradentes2019/dist'); ?>/images/2019/date.png" alt="">
                <img src="<?php echo $this->basePath('assets/tiradentes2019/dist'); ?>/images/2019/letter.png" alt="">
            </h1>
        </div>

        <nav class="menu">
            <?php $this
                ->navigation('MostratiradentesNavigation')
                ->menu()->setPartial("mostratiradentes/partials/navigation.phtml");

            echo $this
                ->navigation('MostratiradentesNavigation')
                ->menu()
                ->render(); ?>
        </nav>
    </header>

    <main class="main <?php echo $this->placeholder("home-class") ?>">
        <?php echo $this->content; ?>
    </main>
    <footer class="footer">
        <div class="footer-wrapper">
            <div class="footer-contact">
<!--                <p class="footer-title">Contate-nos:</p>-->
                <span class="icon icon-universo-brand"></span>
                <span class="footer-add">+ 55 31 3282-2366<br />
                        mostratiradentes@universoproducao.com.br<br />
                        Rua Pirapetinga, 567 - Serra<br />
                        30220-150, Belo Horizonte | MG</span>

            </div>
            <div class="footer-social">
<!--                <p class="footer-title">Siga-nos:</p>-->
                <ul>
                    <li class="footer-socialitem"><a target="_blank" class="footer-socialink" href="https://www.facebook.com/universoproducao"><span class="icon icon-facebook"></span></a></li>
                    <li class="footer-socialitem"><a target="_blank" class="footer-socialink" href="https://twitter.com/universoprod"><span class="icon icon-twitter"></span></a></li>
                    <li class="footer-socialitem"><a target="_blank" class="footer-socialink" href="https://www.instagram.com/universoproducao/"><span class="icon icon-instagram"></span></a></li>
                    <li class="footer-socialitem"><a target="_blank" class="footer-socialink" href="https://www.flickr.com/photos/universoproducao/"><span class="icon icon-flickr"></span></a></li>
                    <li class="footer-socialitem"><a target="_blank" class="footer-socialink" href="https://www.youtube.com/user/universoproducao"><span class="icon icon-youtube"></span></a></li>
                </ul>
            </div>
            <p class="footer-title footer-copy">Copyright © 2015. Universo Produção - Todos os direitos reservados.</p>
        </div>
    </footer>
</div>

<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="/bower_components/jquery/dist/jquery.min.js"><\/script>')</script>

<script src="<?php echo $this->basePath('assets/tiradentes2019/dist') ?>/scripts/main.js"></script>
<script src="<?php echo $this->basePath('assets/tiradentes2019/dist') ?>/scripts/vendor.js"></script>


<!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-10028533-3', 'auto');
    ga('send', 'pageview');

</script>
<!-- endbuild -->
</body>
</html>
