<?php $form = $this->form; ?>
<div class="row post guide">
<div class="col-md-12">
	<?php $form->prepare(); echo $this->form(null, null)->openTag($form) ?>

	<div class="portlet light portlet-fit bordered">
		<div class="portlet-title">
			<div class="caption">
				<?php if($this->registration->getId()): ?>
				<i class="fa fa-edit"></i>
				Editar incrição
				<?php else: ?>
				<i class="fa fa-file-o"></i>
				Nova inscrição
				<?php endif; ?>
			</div>
			<div class="actions">
				<a href="<?php echo $this->url('admin/default', ['controller'=>'registration']); ?>"
				   class="btn btn-default">
					<i class="icon-action-undo"></i>
					<span class="hidden-xs"> Voltar </span>
				</a>
                <a href="<?php echo $this->url('admin/default', ['controller'=>'registration', 'action'=>'create']); ?>"
                   class="btn btn-default">
                    <i class="fa fa-plus"></i>
                    <span class="hidden-xs"> Nova Inscrição </span>
                </a>
			</div>
		</div>
		<div class="portlet-body">
			<div class="portlet">
                <div class="portlet-body form">
                    <div class="form-body">
                        <?php echo $this->formRow($form->get('name'));
                            echo $this->formRow($form->get('type')); ?>

                        <div class="form-group">
                            <label class="control-label col-md-4" for=""><?php echo $form->get('start_date')->getLabel(); ?><span class="required"> * </span></label>
                            <div class="col-md-2">
                                <div class="input-group date date-picker" data-date-format="dd/mm/yyyy">
                                    <?php echo $this->formelement($form->get('start_date')); ?>
                                    <span class="input-group-btn">
                                        <button class="btn default" type="button">
                                            <i class="fa fa-calendar"></i>
                                        </button>
                                    </span>
                                </div>
                            </div>
                            <div class="col-md-2">
                                <div class="input-group">
                                    <?php echo $this->formelement($form->get('hour_start')); ?>
                                    <span class="input-group-btn">
                                        <button class="btn default" type="button">
                                            <i class="fa fa-clock-o"></i>
                                        </button>
                                    </span>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-4" for=""><?php echo $form->get('end_date')->getLabel(); ?></label>
                            <div class="col-md-2">
                                <div class="input-group date date-picker" data-date-format="dd/mm/yyyy">
                                    <?php echo $this->formelement($form->get('end_date')); ?>
                                    <span class="input-group-btn">
                                        <button class="btn default" type="button">
                                            <i class="fa fa-calendar"></i>
                                        </button>
                                    </span>
                                </div>
                            </div>
                            <div class="col-md-2">
                                <div class="input-group">
                                    <?php echo $this->formelement($form->get('hour_end')); ?>
                                    <span class="input-group-btn">
                                        <button class="btn default" type="button">
                                            <i class="fa fa-clock-o"></i>
                                        </button>
                                    </span>
                                </div>
                            </div>
                        </div>

                        <?php echo $this->formRow($form->get('status'));
                        echo $this->formRow($form->get('events'));
                        echo $this->formRow($form->get('position')); ?>

                        <?php if($this->registration->getType() == \Application\Entity\Registration\Type::MOVIE): ?>

                            <div class="portlet light bordered">
                                <div class="portlet-title">
                                    <div class="caption">Configurações da inscrição de <?php echo \Application\Entity\Registration\Type::get($this->registration->getType()); ?></div>
                                </div>
                                <div class="portlet-body form">
                                    <div class="form-body">
                                        <?php echo $this->formRow($form->get('options['.\Application\Entity\Registration\Options::MOVIE_ALLOW_INTERNATIONAL_REGISTRATION.']')); ?>
                                        <div class="form-group">
                                            <label class="control-label col-md-4">Permitir filmes finalizados a partir de</label>
                                            <div class="col-md-8">
                                                <div class="input-group input-large date-picker input-daterange" data-date-format="dd/mm/yyyy">
                                                    <?php echo $this->formElement($form->get('options['.\Application\Entity\Registration\Options::MOVIE_ALLOW_FINISHED_FROM.']')); ?>
                                                    <span class="input-group-addon"> até </span>
                                                    <?php echo $this->formElement($form->get('options['.\Application\Entity\Registration\Options::MOVIE_ALLOW_FINISHED_TO.']')); ?> </div>
                                                <!-- /input-group -->
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label col-md-4" for=""><?php echo $form->get('options['.\Application\Entity\Registration\Options::MOVIE_ALLOW_EDIT_REGISTRATION_TO.']')->getLabel(); ?></label>
                                            <div class="col-md-2">
                                                <div class="input-group date date-picker" data-date-format="dd/mm/yyyy">
                                                    <?php echo $this->formelement($form->get('options['.\Application\Entity\Registration\Options::MOVIE_ALLOW_EDIT_REGISTRATION_TO.']')); ?>
                                                    <span class="input-group-btn">
                                                        <button class="btn default" type="button">
                                                            <i class="fa fa-calendar"></i>
                                                        </button>
                                                    </span>
                                                </div>
                                            </div>
                                        </div>
                                        <?php echo $this->formRow($form->get('options['.\Application\Entity\Registration\Options::MOVIE_DURATION_OBS.']')); ?>
                                    </div>
                                </div>
                            </div>
                        <?php endif; ?>

                        <?php
                            echo $this->formRow($form->get('regulation'));
                            echo $this->formRow($form->get('info')); ?>

                        <div class="form-group">
                            <label class="col-md-4 control-label">Imagem de capa</label>
                            <div class="col-md-6">
                                <div class="fileinput <?php echo $this->registration->getCover() ? "fileinput-exist" : ""; ?>">
                                    <div class="fileinput-new thumbnail" style="width: 200px; height: 150px;">
                                        <img src="http://www.placehold.it/200x150/EFEFEF/AAAAAA&amp;text=sem+imagem" alt="" /> </div>
                                    <div class="fileinput-preview thumbnail" style="max-width: 200px; max-height: 150px;">
                                        <?php if($this->registration->getCover()): ?>
                                            <img width="100%" src="<?php echo $this->registration->getCover() ?>" alt="" />
                                        <?php endif; ?>
                                    </div>
                                    <div>
                                        <a href="#"
                                           data-toggle="modal"
                                           data-target="#modal-responsivefilemanager"
                                           data-url="/filemanager/dialog.php?type=1&field_id=file"
                                           class="btn btn-success responsivefilemanager fileinput-add"><i class="fa fa-plus"></i> Selecionar uma Imagem</a>
                                        <a class="btn red fileinput-remove"> Remover </a>
                                        <?php echo $this->formElement($form->get('cover')); ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-actions">
                        <div class="row">
                            <div class="col-md-offset-3 col-md-9">
                                <button type="submit" class="btn blue btn-lg action-save">Salvar</button>
                                <a href="<?php echo $this->url('admin/default', ['controller'=>'registration']); ?>" class="btn red btn-lg action cancel">Descartar</a>
                            </div>
                        </div>
                    </div>
                </div>
			</div>
		</div>
	</div>
	<?php echo $this->form()->closeTag() ?>
</div>
</div>