<div class="row">
	<div class="col-md-12">
		<div class="portlet light portlet-fit portlet-datatable bordered">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-th-list"></i>
					Gerenciador de Arquivos
				</div>
				<div class="actions">
					<!--<a href=""
					   class="btn blue btn-lg">
						<i class="fa fa-plus"></i>
						<span class="hidden-xs"> Novo arquivo </span>
					</a>-->
				</div>
			</div>

			<div class="portlet-body">
				<iframe  width="100%" height="550" src="//filemanager.universoproducao.com.br/dialog.php?type=0" frameborder="0"></iframe>
			</div>
		</div>
	</div>
</div>