<?php $form = $this->form; ?>
<div class="row post news">
	<div class="col-md-12">
		<?php $form->prepare(); echo $this->form(null, null)->openTag($form) ?>
		<div class="portlet light portlet-fit bordered">
			<div class="portlet-title">
				<div class="caption">
					<?php if($this->place->getId()): ?>
					<i class="fa fa-edit"></i>
					Cadastrar Local
					<?php else: ?>
					<i class="fa fa-file-o"></i>
					Editar Local
					<?php endif; ?>
				</div>
				<div class="actions">
					<a href="<?php echo $this->url('admin/default', ['controller'=>'event-place']); ?>"
					   class="btn btn-default">
						<i class="icon-action-undo"></i>
						<span class="hidden-xs"> Voltar </span>
					</a>
                    <a href="<?php echo $this->url('admin/default', ['controller'=>'event-place', 'action'=>'create']); ?>"
                       class="btn blue btn-lg">
                        <i class="fa fa-plus"></i>
                        <span class="hidden-xs"> Novo local  </span>
                    </a>
				</div>
			</div>
			<div class="portlet-body">
				<div class="portlet state-cities"
                     data-url="<?php echo $this->url('util/cities'); ?>"
                     data-state-element="#state"
                     data-city-element="#city">

					<div class="portlet-body form">
						<div class="form-body">
                            <?php
                            echo $this->formRow($form->get('name'));
                            echo $this->formRow($form->get('event_type'));
                            echo $this->formRow($form->get('state'));
                            echo $this->formRow($form->get('city'));
                            echo $this->formRow($form->get('description'));
                            ?>
						</div>

						<div class="form-actions">
							<div class="row">
								<div class="col-md-offset-3 col-md-9">
									<button type="submit" class="btn blue btn-lg action-save">Salvar</button>
									<a href="#" class="btn red btn-lg action cancel">Descartar</a>
								</div>
							</div>
						</div>

					</div>
				</div>
			</div>
		</div>
		<?php echo $this->form()->closeTag() ?>
	</div>
</div>