<?php $form = $this->searchForm; ?>
<div class="row">
	<div class="col-md-12">
		<div class="portlet light portlet-fit portlet-datatable bordered">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-th-list"></i>
					Locais
				</div>
				<div class="actions">
					<a href="<?php echo $this->url('admin/default', ['controller' => 'event-place', 'action'=>'create']); ?>"
					   class="btn blue btn-lg">
						<i class="fa fa-plus"></i>
						<span class="hidden-xs"> Cadastrar Local </span>
					</a>
					<div class="btn-group">
						<a class="btn btn-default dropdown-toggle" href="javascript:;" data-toggle="dropdown">
							<i class="fa fa-share"></i>
							<span class="hidden-xs"> Opções </span>
							<i class="fa fa-angle-down"></i>
						</a>
						<div class="dropdown-menu pull-right">
							<li><a href="javascript:;"> Exportar para Excel </a></li>
							<li><a href="javascript:;"> Exportar para PDF </a></li>
							<li class="divider"></li>
							<li><a href="javascript:;"> Imprimir </a></li>
						</div>
					</div>
				</div>
			</div>

			<div class="portlet-body state-cities"
                 data-url="<?php echo $this->url('util/cities'); ?>"
                 data-state-element="#state"
                 data-city-element="#city">
				<div class="table-container post-list">
					<table class="table table-striped table-bordered table-hover">
						<thead>
							<tr role="row" class="heading">
								<th width="2%">#</th>
								<th width="40%">Nome</th>
								<th width="15%">Tipo</th>
                                <th width="15%">Estado</th>
                                <th width="15%">Cidade</th>
								<th width="15%">Ações</th>
							</tr>
                            <tr role="row" class="filter">
                                <?php $form->prepare(); echo $this->form()->openTag($form); ?>
                                <td></td>
                                <td><?php echo $this->formelement($form->get('name')); ?></td>
                                <td><?php echo $this->formelement($form->get('event_type')); ?></td>
                                <td><?php echo $this->formelement($form->get('state')); ?></td>
                                <td><?php echo $this->formelement($form->get('city')); ?></td>
                                <td>
                                    <button class="btn btn-sm blue filter-submit margin-bottom"><i class="fa fa-search"></i> Pesquisar</button>
                                    <button class="btn btn-sm btn-default filter-cancel"><i class="fa fa-times"></i> Limpar</button>
                                </td>
                                <?php echo $this->form()->closeTag(); ?>
                            </tr>
						</thead>
						<tbody>
						<?php foreach ($this->places as $place):
							$updateUrl = $this->url('admin/default', [
                                'controller' => 'event-place',
								'action' => 'update',
								'id' => $place->getId()
							]);

							$removeUrl = $this->url('admin/default', [
                                'controller' => 'event-place',
								'action'=>'delete',
								'id'=>$place->getId()
							]);
							?>
							<tr>
								<td></td>
								<td><a href="<?php echo $updateUrl; ?>"><?php echo $place->getName(); ?></a></td>
                                <td><?php echo \Application\Entity\Event\EventType::get($place->getEventType()); ?></td>
                                <td><?php echo $place->getCity() ? $place->getCity()->getState()->getName() : "" ?></td>
                                <td><?php echo $place->getCity() ? $place->getCity()->getName() : "" ?></td>
								<td>
									<a href="<?php echo  $updateUrl; ?>" class="btn btn-sm btn-default">
										<i class="fa fa-edit"></i> Editar
									</a>
									<a href="<?php echo $removeUrl; ?>" class="btn btn-sm btn-default post-list-remove">
										<i class="fa fa-trash-o"></i> Excluir
									</a>

								</td>
							</tr>
						<?php endforeach; ?>
						</tbody>
					</table>

					<div class="table-paginator">
						<?php echo $this->paginationcontrol(
							$this->places,
							'sliding',
							'admin/partials/paginator.phtml',
							array(
								'route'=>'admin/event',
								'route_options' => []
							)
						); ?>
					</div>

				</div>
			</div>
		</div>
	</div>
</div>