<?php $form = $this->form; ?>
<?php $programingForm = $this->programingForm; ?>
<div class="row post">
	<div class="col-md-12">

		<div class="portlet light portlet-fit bordered">
			<div class="portlet-title">
				<div class="caption">
					<?php if($this->art->getId()): ?>
					<i class="fa fa-edit"></i>
					Editar arte
					<?php else: ?>
					<i class="fa fa-file-o"></i>
					Cadastrar arte
					<?php endif; ?>
				</div>
				<div class="actions">
					<a href="<?php echo $this->url('admin/default', ['controller'=>'art']); ?>"
					   class="btn btn-default">
						<i class="icon-action-undo"></i>
						<span class="hidden-xs"> Voltar </span>
					</a>
                    <a href="<?php echo $this->url('admin/default', ['controller'=>'art', 'action'=>'create']); ?>"
                       class="btn blue btn-lg">
                        <i class="fa fa-plus"></i>
                        <span class="hidden-xs"> Nova arte  </span>
                    </a>
				</div>
			</div>
			<div class="portlet-body">
                <div class="portlet">
                    <div class="portlet-body form">
                        <?php $form->prepare(); echo $this->form(null, null)->openTag($form) ?>
                        <div class="form-body">
                            <div class="row">
                                <div class="col-md-4"><?php echo $this->formRow($form->get('title')) ?></div>
                                <div class="col-md-4"><?php echo $this->formRow($form->get('event')) ?></div>
                                <div class="col-md-4"><?php echo $this->formRow($form->get('category')) ?></div>
                            </div>
                            <div class="row">
                                <div class="col-md-12"><?php echo $this->formRow($form->get('description')) ?></div>
                            </div>

                            <div class="portlet image-collection">
                                <div class="portlet-title">
                                    <div class="caption">
                                        <i class="fa fa-gift"></i>Imagens </div>
                                    <div class="actions">
                                        <a href="javascript:;" class="btn default btn-sm image-collection-add"><i class="fa fa-plus"></i> Adicionar </a>
                                    </div>
                                </div>
                                <div class="portlet-body">
                                    <div class="row image-collection-items" data-origin="internal">
                                        <?php $mediaFieldsets = $form->get('medias')->getFieldsets(); ?>
                                        <?php foreach ($mediaFieldsets as $mFieldset): ?>
                                            <div class="col-md-4 image-collection-item">
                                                <div class="portlet light portlet-fit bordered">
                                                    <div class="portlet-title">
                                                        <div class="caption">Imagem</div>
                                                        <div class="actions">
                                                            <a href="#" class="btn blue btn-sm image-collection-delete">
                                                                <i class="fa fa-close"></i> Apagar </a>
                                                        </div>
                                                    </div>
                                                    <div class="portlet-body">
                                                        <div class="form-group <?php echo !empty($mFieldset->get("file")->getMessages()) ? "has-error" : ""; ?>">
                                                            <div class="margin-bottom-5">
                                                                <?php echo $this->formElement($mFieldset->get('caption')); ?>
                                                            </div>
                                                            <?php
                                                            $mediaSrc = null;
                                                            if($mFieldset->has("src")) {
                                                                $mediaSrc = $mFieldset->get("src")->getValue();
                                                            }
                                                            $fileEl = $mFieldset->get("file");
                                                            $fileEl->setAttribute('id', time(false).'_'.mt_rand());
                                                            ?>
                                                            <div class="fileinput fileinput2 <?php echo $mediaSrc ? "fileinput-exists" : "fileinput-new" ?>" data-provides="fileinput" data-file-id="<?php echo $fileEl->getAttribute('id') ?>" style="display: block">
                                                                <div class="fileinput-new thumbnail" style="width: 200px; height: 150px;">
                                                                    <?php if(!$mediaSrc):  ?>
                                                                        <img src="http://www.placehold.it/200x150/EFEFEF/AAAAAA&amp;text=no+image" alt="" />
                                                                    <?php endif; ?>
                                                                </div>
                                                                <div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 200px; max-height: 150px;">
                                                                    <?php if($mediaSrc): ?>
                                                                        <img src="<?php echo $this->fileManipulation()->url($mediaSrc); ?>" alt="">
                                                                    <?php endif; ?>
                                                                </div>
                                                                <div>
                                                                    <?php echo $this->formElement($fileEl); ?>
                                                                    <a href="#"
                                                                       data-toggle="modal"
                                                                       data-target="#modal-responsivefilemanager"
                                                                       data-url="/filemanager/dialog.php?type=1&field_id=<?php echo $fileEl->getAttribute('id') ?>"
                                                                       class="btn btn-success responsivefilemanager fileinput-add"><i class="fa fa-plus"></i> Selecionar uma Imagem</a>
                                                                    <a href="javascript:;" class="btn red fileinput-exists" data-dismiss="fileinput"> Remover </a>
                                                                </div>
                                                                <?php echo $this->formElement($mFieldset->get("id")); ?>
                                                                <?php echo $this->formElement($mFieldset->get("src")); ?>
                                                            </div>
                                                            <?php echo $this->formElementErrors($mFieldset->get('file')); ?>
                                                            <?php echo $this->formElementErrors($mFieldset->get('caption')); ?>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        <?php endforeach; ?>
                                    </div>
                                </div>
                            </div>

                            <h3 class="form-section">Programação</h3>
                            <div class="row">
                                <div class="col-md-9">
                                    <table class="table table-hover table-light table-programing">
                                        <thead>
                                        <tr>
                                            <th width="18%">Data</th>
                                            <th width="18%">Hora de início</th>
                                            <th width="18%">Hora de término</th>
                                            <th width="40%">Local</th>
                                            <th></th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>
                                                    <div class="input-group date date-picker" data-date-format="dd/mm/yyyy">
                                                        <?php echo $this->formElement($programingForm->get('date')); ?>
                                                        <span class="input-group-btn">
                                                            <button type="button" name="btn-date" class="btn default">
                                                                <span class="fa fa-fa fa-calendar"></span>
                                                            </button>
                                                        </span>
                                                    </div>
                                                </td>
                                                <td><?php echo $this->formElement($programingForm->get('start_time')); ?></td>
                                                <td><?php echo $this->formElement($programingForm->get('end_time')); ?></td>
                                                <td><?php echo $this->formElement($programingForm->get('place')); ?></td>
                                                <td><button class="btn btn-sm btn-success table-programing-add" type="button">
                                                        <i class="fa fa-plus"></i> Adicionar</button></td>
                                            </tr>
                                            <?php foreach ($this->art->getPrograming() as $pro): ?>
                                                <tr data-row="<?php echo $pro->getId() ?>">
                                                    <td><?php echo $pro->getDate()->format('d/m/Y') ?></td>
                                                    <td><?php echo $pro->getStartTime()->format('H:i:s') ?></td>
                                                    <td><?php echo $pro->getEndTime() ? $pro->getEndTime()->format('H:i:s') : "" ?></td>
                                                    <td><?php echo $pro->getPlace()->getName(); ?></td>
                                                    <td>
                                                        <a href="#" class="btn btn-sm btn-default table-programing-remove"
                                                           data-remove="<?php echo $pro->getId() ?>"><i class="fa fa-close"></i>
                                                        </a>
                                                        <input type="hidden" name="programing[<?php echo $pro->getId() ?>][date]" value="<?php echo $pro->getDate()->format('d/m/Y') ?>">
                                                        <input type="hidden" name="programing[<?php echo $pro->getId() ?>][start_time]" value="<?php echo $pro->getStartTime()->format('H:i:s') ?>">
                                                        <input type="hidden" name="programing[<?php echo $pro->getId() ?>][end_time]" value="<?php echo $pro->getEndTime() ? $pro->getEndTime()->format('H:i:s') : "" ?>">
                                                        <input type="hidden" name="programing[<?php echo $pro->getId() ?>][place]" value="<?php echo $pro->getPlace()->getId(); ?>"></td>
                                                </tr>
                                            <?php endforeach; ?>
                                        </tbody>
                                    </table>
                                </div>
                            </div>

                        </div>
                        <div class="form-actions">
                            <div class="row">
                                <div class="col-md-offset-3 col-md-9">
                                    <button type="submit" class="btn blue btn-lg action-save">Salvar</button>
                                    <a href="#" class="btn red btn-lg action cancel">Descartar</a>
                                </div>
                            </div>
                        </div>
                        <?php echo $this->form()->closeTag() ?>
                    </div>
                </div>
			</div>
		</div>

	</div>
</div>

<?php echo $this->partial('admin/partials/_media-fieldset-template.phtml'); ?>