<div class="main__figure">
    <?php if($post->getCover()): ?>
        <img src="<?php echo $post->getCover(); ?>" alt="">
    <?php else: ?>
        <img src="<?php echo $this->basePath("assets/cinebh/dist") ?>/images/internal.jpg" alt="">
    <?php endif; ?>
</div>

<?php if($this->breadcrumbs): ?>
    <?php echo $this->partial('cinebh/partials/_breadcrumbs.phtml', ['breadcrumbs'=>$this->breadcrumbs]); ?>
<?php endif; ?>

<section class="main__wrapper">
    <header class="main__header">
        <h1 class="main__title"><?php echo $this->post->getTitle(); ?></h1>
    </header>
    <?php echo $this->thumborize($post->getContent()); ?>
</section>