<!doctype html>
<html lang="">
    <head>
        <meta charset="utf-8">
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <title>Mostra Tiradentes 2019</title>
        <link rel="apple-touch-icon" href="apple-touch-icon.png">
        <link href="https://fonts.googleapis.com/css?family=Open+Sans&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="<?php echo $this->basePath('assets/mostratiradentes2019-tmp') ?>/css/main.css?v=201803031701">

    </head>
    <body>
        <div class="wrapper">
            <div class="left">
                <div class="left-content">
                    <img src="<?php echo $this->basePath('assets/mostratiradentes2019-tmp') ?>/img/left.svg" alt="">
                </div>
            </div>
            <div class="right">
                <div class="right-content">
                    <a target="_blank" href="http://universoproducao.com.br/inscricoes"><img src="<?php echo $this->basePath('assets/mostratiradentes2019-tmp') ?>/img/right.svg" alt=""></a>
                    <a class="ed" href="http://mostratiradentes.com.br/inicio">Edição anterior</a>
                </div>
            </div>
        </div>
    </body>
</html>
