<!-- BEGIN LOGIN FORM -->
<?php $form = $this->form;
	$form->prepare();
	echo $this->form(null, null)->openTag($form); ?>

	<h3 class="form-title">Autenticação</h3>

	<?php //echo $this->messages(); ?>

	<div class="form-group">
		<!--ie8, ie9 does not support html5 placeholder, so we just show field title for that-->
		<label class="control-label visible-ie8 visible-ie9"><?php echo $form->get('email')->getLabel() ?></label>
		<?php echo $this->formElement($form->get('email')); ?>
	</div>

	<div class="form-group">
		<label class="control-label visible-ie8 visible-ie9"><?php echo $form->get('password')->getLabel() ?></label>
		<?php echo $this->formElement($form->get('password')); ?>
	</div>

	<div class="form-actions">
		<label class="rememberme check">
			<input type="checkbox" name="remember" value="1" />Lembrar </label>

		<button type="submit" class="btn green pull-right">Login</button>
	</div>
	<div class="forget-password">
		<h4>Perdeu sua senha ?</h4>
		<p> clique <a href="javascript:;" id="forget-password"> here </a> para recuprar. </p>
	</div>
<?php $this->form()->closeTag(); ?>
<!-- END LOGIN FORM -->