<!-- BEGIN LOGIN FORM -->
<?php $form = $this->form;
	$form->prepare();
	echo $this->form(null, null)->openTag($form); ?>

	<h2 class="form-title font-green">Atualização obrigatória de Senha</h2>

	<?php
	    if(!empty($this->error)) {
	        echo $this->messages(null)->danger($this->error);
	    }

	    echo $this->formRow($form->get('email'));
	    echo $this->formRow($form->get('currentPassword'));
	    echo $this->formRow($form->get('newPassword'));
	    echo $this->formRow($form->get('reNewPassword'));
	?>

	<div class="form-actions pull-right">
		<button type="submit" class="btn green uppercase">Salvar</button>
		<a href="<?php echo $this->url('admin/auth', ['action'=>'get-out']); ?>" class="btn red uppercase">Cancelar</a>
	</div>
<!-- END LOGIN FORM -->