<?php $form = $this->form;
    $form->setAttribute('action', $this->url('admin/default', [
        'controller'=>'movie',
        'action'=>'movie-subscriptions',
        'id' => $this->movie->getId()
    ]));
    $form->prepare();
    echo $this->form(null, null)->openTag($form);
    $coll = $form->get('subscriptions');
    $fieldsets = $coll->getFieldsets(); ?>

<div class="form-body">
    
    <h3 class="form-section">Seleção</h3>

    <div class="row">
    <?php foreach ($fieldsets as $fieldset): ?>
        <div class="col-md-4">
            <div class="portlet box blue-hoki">
                <div class="portlet-title">
                    <div class="caption"><?php echo $fieldset->get('event_name')->getValue(); ?></div>
                </div>
                <div class="portlet-body">
                    <div class="row">
                        <div class="col-md-12"><?php echo $this->formRow($fieldset->get('status')); ?></div>
                        <?php echo $this->formRow($fieldset->get('id')); ?>
                    </div>
                </div>
            </div>
        </div>
    <?php endforeach; ?>
    </div>

    <div class="form-actions">
        <div class="btn-set pull-right">
            <button type="submit" name="save" class="btn blue btn-lg" id="save" value="Salvar">
                <span class="fa fa-fa fa-check"></span> Salvar
            </button>
        </div>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>