<?php $form = $this->searchForm; ?>

<div class="row">
	<div class="col-md-12">
		<div class="portlet light portlet-fit portlet-datatable bordered">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-th-list"></i>
					Filmes
				</div>
				<div class="actions">
					<a href="<?php echo $this->url('admin/default', ['controller'=>'movie', 'action'=>'create']); ?>"
					   class="btn blue btn-lg">
						<i class="fa fa-plus"></i>
						<span class="hidden-xs"> Novo filme  </span>
					</a>
                    <div class="btn-group">
                        <a class="btn btn-default dropdown-toggle" href="javascript:;" data-toggle="dropdown">
                            <i class="fa fa-share"></i>
                            <span class="hidden-xs"> Opções </span>
                            <i class="fa fa-angle-down"></i>
                        </a>
                        <div class="dropdown-menu pull-right">
                            <li><a href="javascript:;"> Exportar para Excel </a></li>
                        </div>
                    </div>
				</div>
			</div>

			<div class="portlet-body">

                <div class="portlet light bordered">
                    <div class="portlet-body">
                        <div class="row">
                            <?php foreach (\Application\Entity\Registration\Status::toArray() as $key=>$label): ?>
                                <div class="col-md-2"><?php echo $this->registrationStatus($key, $label) . " $label" ?></div>
                            <?php endforeach; ?>
                        </div>
                    </div>
                </div>

				<div class="table-container post-list">
					<table class="table table-striped table-bordered table-hover">
						<thead>
                        <?php $form->prepare(); echo $this->form()->openTag($form); ?>
							<tr role="row" class="heading">
								<th width="5%">ID</th>
								<th width="15%">Título</th>
								<th width="10%">Duração</th>
                                <th width="15%">Evento</th>
                                <th width="15%">Data de cadastro</th>
                                <th width="15%">Usuário</th>
								<th width="10%">Ações</th>
							</tr>
                            <tr role="row" class="filter">
                                <td><?php echo $this->formelement($form->get('id')); ?></td>
                                <td><?php echo $this->formelement($form->get('title')); ?></td>
                                <td>
                                    <div class="margin-bottom-5"><?php echo $this->formelement($form->get('durationInit')); ?></div>
                                    <?php echo $this->formelement($form->get('durationEnd')); ?>
                                </td>
                                <td>
                                    <div class="margin-bottom-5"><?php echo $this->formelement($form->get('events')); ?></div>
                                    <?php echo $this->formelement($form->get('status')); ?>
                                </td>
                                <td>
                                    <div class="input-group date date-picker margin-bottom-5" data-date-format="dd/mm/yyyy">
                                        <?php echo $this->formelement($form->get('dateInit')); ?>
                                        <span class="input-group-btn">
                                            <button class="btn btn-sm default" type="button">
                                                <i class="fa fa-calendar"></i>
                                            </button>
                                        </span>
                                    </div>
                                    <div class="input-group date date-picker" data-date-format="dd/mm/yyyy">
                                        <?php echo $this->formelement($form->get('dateEnd')); ?>
                                        <span class="input-group-btn">
                                            <button class="btn btn-sm default" type="button">
                                                <i class="fa fa-calendar"></i>
                                            </button>
                                        </span>
                                    </div>
                                </td>
                                <td><?php echo $this->formelement($form->get('author')); ?></td>
                                <td>
                                    <div class="margin-bottom-5">
                                        <button class="btn btn-sm blue filter-submit margin-bottom"><i class="fa fa-search"></i> Pesquisar</button>
                                    </div>
                                    <button type="reset" class="btn btn-sm btn-default filter-cancel"><i class="fa fa-times"></i> Limpar</button>
                                </td>
                            </tr>
                        <?php echo $this->form()->closeTag(); ?>
						</thead>
						<tbody>
						<?php foreach ($this->items as $item):
							$updateUrl = $this->url('admin/default', [
								'controller' => 'movie',
								'action'=>'update',
								'id'=>$item->getId()
							]);

							$removeUrl = $this->url('admin/default', [
								'controller' => 'movie',
								'action'=>'delete',
								'id'=>$item->getId()
							]);

							$restoreUrl = $this->url('admin/default', [
								'controller' => 'movie',
								'action'=>'restore',
								'id'=>$item->getId()
							]);

							?>
							<tr>
								<td><?php echo $item->getId() ?></td>
								<td><a href="<?php echo $updateUrl; ?>"><?php echo $item->getTitle(); ?></a></td>
                                <td>
                                    <?php echo $item->getDuration()->format('H:i:s'); ?><br>
                                    <?php echo \Application\Entity\Movie\Category::get($item->getCategory()); ?>
                                </td>
								<td>
                                    <?php if(count($item->getEvents())): ?>
                                    <table class="table table-in-td">
                                        <tbody>
                                        <?php foreach ($item->getEvents() as $e): ?>
                                            <tr>
                                                <td><?php echo $e->getEvent()->getShortName() ?></td>
                                                <td><?php echo $this->registrationStatus($e->getStatus(), \Application\Entity\Registration\Status::get($e->getStatus())); ?></td>
                                            </tr>
                                        <?php endforeach; ?>
                                        </tbody>
                                    </table>
                                    <?php endif; ?>
                                </td>
								<td><?php echo $item->getCreatedAt()->format('d/m/Y H:i') ?></td>
								<td>
                                    <a target="_blank" href="<?php echo $this->url('admin/default', ['controller' => 'user', 'action'=>'update', 'id'=>$item->getAuthor()->getId()]); ?>">
                                        <?php echo $item->getAuthor()->getName(); ?>
                                    </a>
                                </td>
								<td>
									<a href="<?php echo  $updateUrl; ?>" class="btn btn-sm btn-default">
										<i class="fa fa-edit"></i> Editar
									</a>
									<a href="<?php echo $removeUrl; ?>" class="btn btn-sm btn-default post-list-remove">
										<i class="fa fa-trash-o"></i> Excluir
									</a>
								</td>
							</tr>
						<?php endforeach; ?>
						</tbody>
					</table>

                    <div class="table-paginator">
                        <?php echo $this->paginationcontrol(
                            $this->items,
                            'sliding',
                            'admin/partials/paginator.phtml',
                            array(
                                'route'=>'admin/default',
                                'route_options' => array('controller'=>'movie'),
                                'route_query_options' => ['query'=>$this->searchData]
                            ));
                        ?>
                    </div>

				</div>
			</div>
		</div>
	</div>
</div>
