<?php $form = $this->searchForm; ?>

<div class="row">
	<div class="col-md-12">
		<div class="portlet light portlet-fit portlet-datatable bordered">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-th-list"></i>
					Filmes
				</div>
				<div class="actions">
					<a href="<?php echo $this->url('admin/default', ['controller'=>'movie', 'action'=>'create']); ?>"
					   class="btn blue btn-lg">
						<i class="fa fa-plus"></i>
						<span class="hidden-xs"> Novo filme  </span>
					</a>
				</div>
			</div>

			<div class="portlet-body">
				<div class="table-container post-list">
					<table class="table table-striped table-bordered table-hover">
						<thead>
							<tr role="row" class="heading">
								<th width="2%">ID</th>
								<th width="15%">Título</th>
                                <th width="15%">Eventos</th>
                                <th width="15%">Data de cadastro</th>
                                <th width="15%">Usuário</th>
								<th width="10%">Ações</th>
							</tr>
                            <tr role="row" class="filter">
                                <?php $form->prepare(); echo $this->form()->openTag($form); ?>
                                    <td><?php echo $this->formelement($form->get('id')); ?></td>
                                    <td><?php echo $this->formelement($form->get('title')); ?></td>
                                    <td><?php echo $this->formelement($form->get('events')); ?></td>
                                    <td>
                                        <div class="input-group date date-picker margin-bottom-5" data-date-format="dd/mm/yyyy">
                                            <?php echo $this->formelement($form->get('dateInit')); ?>
                                            <span class="input-group-btn">
												<button class="btn btn-sm default" type="button">
													<i class="fa fa-calendar"></i>
												</button>
											</span>
                                        </div>
                                        <div class="input-group date date-picker" data-date-format="dd/mm/yyyy">
                                            <?php echo $this->formelement($form->get('dateEnd')); ?>
                                            <span class="input-group-btn">
												<button class="btn btn-sm default" type="button">
													<i class="fa fa-calendar"></i>
												</button>
											</span>
                                        </div>
                                    </td>
                                    <td><?php echo $this->formelement($form->get('author')); ?></td>
                                    <td>
                                        <div class="margin-bottom-5">
                                            <button class="btn btn-sm blue filter-submit margin-bottom"><i class="fa fa-search"></i> Pesquisar</button>
                                        </div>
                                        <button class="btn btn-sm btn-default filter-cancel"><i class="fa fa-times"></i> Limpar</button>
                                    </td>
                                <?php echo $this->form()->closeTag(); ?>
                            </tr>
						</thead>
						<tbody>
						<?php foreach ($this->items as $item):
							$updateUrl = $this->url('admin/default', [
								'controller' => 'movie',
								'action'=>'update',
								'id'=>$item->getId()
							]);

							$removeUrl = $this->url('admin/default', [
								'controller' => 'movie',
								'action'=>'delete',
								'id'=>$item->getId()
							]);

							$restoreUrl = $this->url('admin/default', [
								'controller' => 'movie',
								'action'=>'restore',
								'id'=>$item->getId()
							]);

							?>
							<tr>
								<td><?php echo $item->getId() ?></td>
								<td><a href="<?php echo $updateUrl; ?>"><?php echo $item->getTitle(); ?></a></td>
								<td>
                                    <?php foreach ($item->getEvents() as $e): ?>
                                        <span style="margin-right: 10px" class="label label-sm label-info"> <?php echo $e->getEvent()->getShortName(); ?> </span>
                                    <?php endforeach; ?>
                                </td>
								<td><?php echo $item->getCreatedAt()->format('d/m/Y H:i') ?></td>
								<td><?php echo $item->getAuthor()->getName(); ?></td>
								<td>
									<a href="<?php echo  $updateUrl; ?>" class="btn btn-sm btn-default">
										<i class="fa fa-edit"></i> Editar
									</a>
									<a href="<?php echo $removeUrl; ?>" class="btn btn-sm btn-default post-list-remove">
										<i class="fa fa-trash-o"></i> Excluir
									</a>
								</td>
							</tr>
						<?php endforeach; ?>
						</tbody>
					</table>

                    <div class="table-paginator">
                        <?php echo $this->paginationcontrol(
                            $this->items,
                            'sliding',
                            'admin/partials/paginator.phtml',
                            array(
                                'route'=>'admin/default',
                                'route_options' => array('controller'=>'movie')
                            ));
                        ?>
                    </div>

				</div>
			</div>
		</div>
	</div>
</div>
