<?php $form = $this->searchForm; ?>

<div class="row">
	<div class="col-md-12">
		<div class="portlet light portlet-fit portlet-datatable bordered">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-th-list"></i>
					Filmes
				</div>
				<div class="actions">
					<a href="<?php echo $this->url('admin/default', ['controller'=>'movie', 'action'=>'create']); ?>"
					   class="btn blue btn-lg">
						<i class="fa fa-plus"></i>
						<span class="hidden-xs"> Novo filme  </span>
					</a>
                    <div class="btn-group">
                        <a class="btn btn-default dropdown-toggle" href="javascript:;" data-toggle="dropdown">
                            <i class="fa fa-share"></i>
                            <span class="hidden-xs"> Opções </span>
                            <i class="fa fa-angle-down"></i>
                        </a>
                        <div class="dropdown-menu pull-right">
                            <li>
                                <a class="report-link"
                                   data-form="#movie-form-search"
                                   data-url="<?php echo $this->url('admin/default', ['controller'=>'movie', 'action'=>'export-list']) ?>"
                                   href="#"> Exportar para Excel </a>
                            </li>
                        </div>
                    </div>
				</div>
			</div>

			<div class="portlet-body">
                <div class="portlet light bordered">
                    <div class="portlet-body">
                        <div class="row">
                            <?php foreach (\Application\Entity\Registration\Status::toArray() as $key=>$label): ?>
                                <div class="col-md-2"><?php echo $this->registrationStatus($key, $label) . " $label" ?></div>
                            <?php endforeach; ?>
                        </div>
                    </div>
                </div>

				<div class="table-container post-list list-actions"
                     data-total="<?php echo $this->items->getTotalItemCount(); ?>"
                     data-form="#movie-form-search">

                    <?php
                        $urlStatusAction = $this->url('admin/default', [
                            'controller' => 'movie',
                            'action' => 'modal-status'
                        ]);
                    ?>

                    <div class="row">
                        <div class="col-md-12 col-sm-12 margin-bottom-10">
                            <div class="table-group-actions pull-right">
                                <span class="list-actions-selected"></span>
                                <select class="table-group-action-input form-control input-inline input-sm list-actions-options">
                                    <option value="">Selecione uma ação...</option>
                                    <option data-modal="#modal-movie-status">Alterar status</option>
                                    <option>Enviar comunicados</option>
                                </select>
                                <button class="btn btn-sm btn-default table-group-action-submit list-actions-submit">
                                    <i class="fa fa-check"></i> Processar</button>
                            </div>
                        </div>
                    </div>

					<table class="table table-striped table-bordered table-hover">
						<thead>
                        <?php $form->prepare(); echo $this->form()->openTag($form); ?>
							<tr role="row" class="heading">
                                <th width="2%"> </th>
								<th width="5%">ID</th>
								<th width="15%">Título</th>
								<th width="10%">Duração</th>
                                <th width="15%">Evento</th>
                                <th width="15%">Tipo</th>
                                <th width="15%">Data de cadastro</th>
                                <th width="15%">Usuário</th>
								<th width="10%">Ações</th>
							</tr>
                            <tr role="row" class="filter">
                                <td>
                                    <input type="checkbox" class="icheck select-all" name="id_select_all" value="">
                                    <?php echo $this->formElement($form->get('selected')); ?>
                                </td>
                                <td>
                                    <div class="margin-bottom-5">
                                        <?php echo $this->formelement($form->get('id_from')); ?>
                                    </div>
                                    <?php echo $this->formelement($form->get('id_to')); ?>
                                </td>
                                <td><?php echo $this->formelement($form->get('title')); ?></td>
                                <td>
                                    <div class="margin-bottom-5"><?php echo $this->formelement($form->get('durationInit')); ?></div>
                                    <?php echo $this->formelement($form->get('durationEnd')); ?>
                                </td>
                                <td>
                                    <div class="margin-bottom-5"><?php echo $this->formElement($form->get('events')); ?></div>
                                    <?php echo $this->formelement($form->get('status')); ?>
                                </td>
                                <td><?php echo $this->formelement($form->get('type')); ?></td>
                                <td>
                                    <div class="input-group date date-picker margin-bottom-5" data-date-format="dd/mm/yyyy">
                                        <?php echo $this->formelement($form->get('dateInit')); ?>
                                        <span class="input-group-btn">
                                            <button class="btn btn-sm default" type="button">
                                                <i class="fa fa-calendar"></i>
                                            </button>
                                        </span>
                                    </div>
                                    <div class="input-group date date-picker" data-date-format="dd/mm/yyyy">
                                        <?php echo $this->formelement($form->get('dateEnd')); ?>
                                        <span class="input-group-btn">
                                            <button class="btn btn-sm default" type="button">
                                                <i class="fa fa-calendar"></i>
                                            </button>
                                        </span>
                                    </div>
                                </td>
                                <td><?php echo $this->formelement($form->get('author')); ?></td>
                                <td>
                                    <div class="margin-bottom-5">
                                        <button type="submit" class="btn btn-sm blue filter-submit margin-bottom"><i class="fa fa-search"></i> Pesquisar</button>
                                    </div>
                                    <button type="reset" class="btn btn-sm btn-default filter-cancel"><i class="fa fa-times"></i> Limpar</button>
                                </td>
                            </tr>
                        <?php echo $this->form()->closeTag(); ?>
						</thead>
						<tbody>
						<?php foreach ($this->items as $item):
							$updateUrl = $this->url('admin/default', [
								'controller' => 'movie',
								'action'=>'update',
								'id'=>$item->getId()
							]);

							$removeUrl = $this->url('admin/default', [
								'controller' => 'movie',
								'action'=>'delete',
								'id'=>$item->getId()
							]);
							?>
							<tr>
                                <td><input type="checkbox" class="icheck" name="id[]" value="<?php echo $item->getId() ?>"></td>
								<td><?php echo $item->getId() ?></td>
								<td><a href="<?php echo $updateUrl; ?>"><?php echo $item->getTitle(); ?></a></td>
                                <td>
                                    <?php echo $item->getDuration() ? $item->getDuration()->format('H:i:s') : ""; ?><br>
                                    <?php echo \Application\Entity\Movie\Category::get($item->getCategory()); ?>
                                </td>
								<td>
                                    <?php if(count($item->getSubscriptions())): ?>
                                    <table class="table table-in-td">
                                        <tbody>
                                        <?php foreach ($item->getSubscriptions() as $e): ?>
                                            <tr>
                                                <td><?php echo $e->getEvent()->getShortName() ?></td>
                                                <td><?php echo $this->registrationStatus($e->getStatus(), \Application\Entity\Registration\Status::get($e->getStatus())); ?></td>
                                            </tr>
                                        <?php endforeach; ?>
                                        </tbody>
                                    </table>
                                    <?php endif; ?>
                                </td>
                                <td><?php echo $item->getType()?\Application\Entity\Movie\Movie::getMovieTypes($item->getType()):"" ?></td>
								<td><?php echo $item->getCreatedAt()->format('d/m/Y H:i') ?></td>
								<td>
                                    <?php
                                        if($item->isInvited()) {
                                            echo "Filme convidado";
                                        } elseif($item->getAuthor()) {
                                            ?>
                                            <a href="#" class="user-modal" data-view-only data-user-id="<?php echo $item->getAuthor()->getId(); ?>">
                                                <?php echo $item->getAuthor()->getName(); ?>
                                            </a>
                                            <?php
                                        }
                                    ?>
                                </td>
								<td>
									<a href="<?php echo  $updateUrl; ?>" class="btn btn-sm btn-default">
										<i class="fa fa-edit"></i> Editar
									</a>
									<a href="<?php echo $removeUrl; ?>" class="btn btn-sm btn-default post-list-remove">
										<i class="fa fa-trash-o"></i> Excluir
									</a>
								</td>
							</tr>
						<?php endforeach; ?>
						</tbody>
					</table>

                    <div class="table-paginator">
                        <?php echo $this->paginationcontrol(
                            $this->items,
                            'sliding',
                            'admin/partials/paginator.phtml',
                            array(
                                'route'=>'admin/default',
                                'route_options' => array('controller'=>'movie'),
                                'route_query_options' => ['query'=>$this->searchData]
                            ));
                        ?>
                    </div>

				</div>
			</div>
		</div>
	</div>
</div>

<?php echo $this->partial('admin/movie/_modal-status.phtml', [
        'movieStatusModalForm' => $this->movieStatusModalForm
]); ?>
