<?php if($this->breadcrumbs): ?>
    <?php echo $this->partial('cinebh2017/partials/_breadcrumbs.phtml', ['breadcrumbs'=>$this->breadcrumbs]); ?>
<?php endif; ?>

<div class="main-wrapper">
    <section class="main-content">
        <header class="main-header">
            <h1 class="main-title"><?php echo $this->post->getTitle(); ?></h1>
        </header>

        <?php if($this->post->getSubtitle()): ?>
            <h2><?php echo $this->post->getSubtitle(); ?></h2>
        <?php endif; ?>

        <div class="news">
            <div class="news-items">
                <?php foreach ($this->newsList as $news): ?>
                    <div class="news-item">
                        <a href="<?php echo $this->url("cinebh2017/news", ['slug'=>$news->getSlug()]) ?>" class="news-link">
                            <div class="news-figure">
                                <img src="<?php echo  $this->thumbor()->url($news->getMeta('_thumb'))->resize(300, 214); ?>" alt="">
                            </div>
                            <p class="news-title"><?php echo $news->getTitle(); ?></p>
                            <p class="news-subtitle"><?php echo $news->getSubtitle(); ?></p>
                            <p class="news-readmore">Leia mais +</p>
                        </a>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    </section>
</div>