<div class="row">
	<div class="col-md-12">
		<div class="portlet light portlet-fit bordered">
			<div class="portlet-title">
				<div class="caption">
					<i class="icon-user"></i>
					<?php echo $this->user->getName(); ?>
				</div>
			</div>
			<div class="portlet-body">

				<div class="tab-pane" id="tab_1_3">
					<div class="row profile-account">
						<div class="col-md-3">
							<ul class="ver-inline-menu tabbable margin-bottom-10">
								<li class="<?php echo $this->tabActive == 'tab_info_form' ? 'active' : '' ?>">
									<a data-toggle="tab" href="#tab_info_form"><i class="fa fa-cog"></i> Informações Pessoais </a>
									<span class="after"> </span>
								</li>
								<li class="<?php echo $this->tabActive == 'tab_avatar' ? 'active' : '' ?>">
									<a data-toggle="tab" href="#tab_avatar"><i class="fa fa-picture-o"></i> Alterar Avatar</a>
								</li>
								<li class="<?php echo $this->tabActive == 'tab_change_pass' ? 'active' : '' ?>">
									<a data-toggle="tab" href="#tab_change_pass"><i class="fa fa-lock"></i> Alterar Senha </a>
								</li>
								<li>
									<a data-toggle="tab" href="#"><i class="fa fa-group"></i> Perfil de Acesso </a>
								</li>
								<li>
									<a data-toggle="tab" href="#"><i class="fa fa-list-alt"></i> Histórico de Login </a>
								</li>
							</ul>
						</div>

						<div class="col-md-9">
							<div class="tab-content">
								<div id="tab_info_form" class="tab-pane <?php echo $this->tabActive=='tab_info_form' ? 'active' : ''; ?>">
									<?php $infoForm = $this->infoForm;
									$infoForm->setAttribute('action', $this->url('admin/default', ['controller'=>'account', 'action'=>'info']));
									$infoForm->prepare();
									echo $this->form(null, null)->openTag($infoForm);

									echo $this->formRow($infoForm->get('name'));
									echo $this->formRow($infoForm->get('alias'));
									echo $this->formRow($infoForm->get('email'));
									echo $this->formRow($infoForm->get('occupation'));
									echo $this->formRow($infoForm->get('phone')); ?>

									<div class="margiv-top-10">
										<button type="submit" class="btn blue"><i class="fa fa-check"></i> Salvar Alterações</button>
										<a href="javascript:;" class="btn default"> Cancelar </a>
									</div>

									<?php echo $this->form()->closeTag() ?>
								</div>
								<div id="tab_avatar" class="tab-pane <?php echo $this->tabActive=='tab_avatar' ? 'active' : ''; ?>">
									<form action="#" role="form">
										<div class="form-group">
											<div class="fileinput fileinput-new" data-provides="fileinput">
												<div class="fileinput-new thumbnail" style="width: 200px; height: 150px;">
													<img src="http://www.placehold.it/200x150/EFEFEF/AAAAAA&amp;text=no+image" alt="" /> </div>
												<div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 200px; max-height: 150px;"> </div>
												<div>
													<span class="btn default btn-file">
														<span class="fileinput-new"> Select image </span>
														<span class="fileinput-exists"> Change </span>
														<input type="file" name="..."> </span>
													<a href="javascript:;" class="btn default fileinput-exists" data-dismiss="fileinput"> Remove </a>
												</div>
											</div>
										</div>
										<div class="margiv-top-10">
											<a href="javascript:;" class="btn blue"><i class="fa fa-check"></i> Salvar Alterações</a>
											<a href="javascript:;" class="btn default"> Cancelar </a>
										</div>
									</form>

								</div>
								<div id="tab_change_pass" class="tab-pane <?php echo $this->tabActive=='tab_change_pass' ? 'active' : ''; ?>">
									<div class="m-heading-1 border-green m-bordered">
										<h3>Complexidade da Senha:</h3>
										<p> Por questões de segurança, a senha deve conter no mínimo <strong>8 caracteres</strong>,
											pelo menos <strong>1 número</strong> e <strong>1 caractere especial</strong>.
										</p>
									</div>

									<?php $changePassForm = $this->changePassForm;
									$changePassForm->setAttribute('action', $this->url(
										'admin/default',
										['controller'=>'account', 'action'=>'change-password']
									));
									$changePassForm->prepare();
									echo $this->form(null, null)->openTag($changePassForm);

									echo $this->formRow($changePassForm->get('currentPassword'));
									echo $this->formRow($changePassForm->get('newPassword'));
									echo $this->formRow($changePassForm->get('reNewPassword')); ?>

									<div class="margiv-top-10">
										<button type="submit" class="btn blue"><i class="fa fa-check"></i> Alterar Senha</button>
									</div>

									<?php echo $this->form()->closeTag() ?>
								</div>
							</div>
						</div>

					</div>
				</div>
			</div>
		</div>
	</div>
</div>