<?php $form = $this->form; $form->prepare();?>
<div class="row post guide">
	<div class="col-md-12">
		<div class="portlet light portlet-fit bordered">
			<div class="portlet-title">
				<div class="caption">
					<?php if($item->getId()): ?>
					<i class="fa fa-edit"></i>
					Editar Item
					<?php else: ?>
					<i class="fa fa-file-o"></i>
					Novo Item
					<?php endif; ?>
				</div>
				<div class="actions">
					<a href="<?php echo $this->url('admin/eufacoamostra', ['controller'=>'eufaco', 'site'=>$this->site]); ?>"
					   class="btn btn-default">
						<i class="icon-action-undo"></i>
						<span class="hidden-xs"> Voltar </span>
					</a>
                    <a href="<?php echo $this->url('admin/eufacoamostra', ['action'=>'create', 'site'=>$this->site]); ?>"
                       class="btn blue btn-lg">
                        <i class="fa fa-plus"></i>
                        <span class="hidden-xs"> Cadastrar item </span>
                    </a>
				</div>
			</div>
			<div class="portlet-body">

				<div class="portlet">
					<div class="portlet-body form">
						<?php echo $this->form(null, null)->openTag($form); ?>
						<div class="row">
							<div class="col-md-4">
								<div class="form-group">
									<label class="control-label">Imagem</label>
									<div class="input-group ">
										<div class="fileinput <?php echo $this->item->getThumb() ? "fileinput-exist" : ""; ?>">
											<div class="fileinput-new thumbnail" style="width: 200px; height: 150px;">
												<img src="http://www.placehold.it/200x150/EFEFEF/AAAAAA&amp;text=no+image" alt="" /> </div>
											<div class="fileinput-preview thumbnail" style="max-width: 200px; max-height: 150px;">
												<?php if($this->item->getThumb()): ?>
													<img width="100%" src="<?php echo $this->item->getThumb() ?>" alt="" />
												<?php endif; ?>
											</div>
											<div>
												<a href="#"
												   data-toggle="modal"
												   data-target="#modal-responsivefilemanager"
												   data-url="/filemanager/dialog.php?type=1&field_id=file"
												   class="btn btn-success responsivefilemanager fileinput-add"><i class="fa fa-plus"></i> Selecionar uma Imagem</a>
												<a class="btn red fileinput-remove"> Remover </a>
												<?php echo $this->formElement($form->get('thumb')); ?>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>

						<div class="row">
							<div class="col-md-10"><?php echo $this->formRow($form->get('description')); ?></div>
						</div>


                        <div class="row">
                            <div class="col-md-10"><?php echo $this->formRow($form->get('video')); ?></div>
                        </div>

						<div class="form-actions">
							<div class="btn-set pull-right">
								<button type="submit" name="save" class="btn blue btn-lg" id="save" value="Salvar">
									<span class="fa fa-fa fa-check"></span> Salvar
								</button>
								<a href="<?php echo $this->url('admin/eufacoamostra', ['controller'=>'eufaco', 'site'=>$this->site]); ?>" class="btn red btn-lg action cancel">Descartar</a>
							</div>
						</div>
						<?php echo $this->form()->closeTag() ?>
					</div>
				</div>
			</div>
		</div>

	</div>
</div>