<div class="portlet light bordered page-gallery">
	<div class="portlet-title">
		<div class="caption">
			<i class="fa fa-edit"></i>
			Banner
		</div>

		<div class="actions">
			<a href="<?php echo $this->url('admin/eufacoamostra', ['action'=>'create', 'site'=>$this->site]); ?>"
			   class="btn blue btn-lg">
				<i class="fa fa-plus"></i>
				<span class="hidden-xs"> Cadastrar item </span>
			</a>
		</div>
	</div>
	<div class="portlet-body">
		<div class="table-container post-list">
			<table class="table table-striped table-bordered table-hover">
				<thead>
				<tr role="row" class="heading">
					<th width="2%">#</th>
					<th width="30%">Descrição</th>
                    <th width="30%">Video</th>
					<th width="10%">Ações</th>
				</tr>
				</thead>
				<tbody>
				<?php foreach ($this->items as $item):
					$updateUrl = $this->url('admin/eufacoamostra', [
						'action'=>'update',
						'id'=>$item->getId(),
                        'site' => $this->site
					]);
					$removeUrl = $this->url('admin/default', [
						'action'=>'delete',
						'id'=>$item->getId(),
                        'site' => $this->site
					]);
					?>
					<tr>
						<td></td>
						<td><?php echo $item->getDescription() ?></td>
						<td><?php echo $item->getVideo() ?></td>
						<td>
							<a href="<?php echo  $updateUrl; ?>" class="btn btn-sm btn-default">
								<i class="fa fa-edit"></i> Editar
							</a>
							<a href="<?php echo $removeUrl; ?>" class="btn btn-sm btn-default post-list-remove">
								<i class="fa fa-close"></i> Excluir
							</a>
						</td>
					</tr>
				<?php endforeach; ?>
				</tbody>
			</table>

			<div class="table-paginator">
				<?php echo $this->paginationcontrol($this->items, 'sliding', 'admin/partials/paginator.phtml'); ?>
			</div>
		</div>
	</div>
</div>


