<?php $form = $this->form; ?>
<div class="row post news">
	<div class="col-md-12">
		<?php $form->prepare(); echo $this->form(null, null)->openTag($form) ?>
		<div class="portlet light portlet-fit bordered">
			<div class="portlet-title">
				<div class="caption">
					<?php if($this->proposal->getId()): ?>
					<i class="fa fa-edit"></i>
					Cadastrar proposta
					<?php else: ?>
					<i class="fa fa-file-o"></i>
					Editar proposta
					<?php endif; ?>
				</div>
				<div class="actions">
					<a href="<?php echo $this->url('admin/default', ['controller'=>'workshop-proposal']); ?>"
					   class="btn btn-default">
						<i class="icon-action-undo"></i>
						<span class="hidden-xs"> Voltar </span>
					</a>
                    <?php if($this->proposal->getId()): ?>
                        <div class="btn-group">
                            <a class="btn btn-default dropdown-toggle" href="javascript:;" data-toggle="dropdown">
                                <i class="fa fa-share"></i>
                                <span class="hidden-xs"> Opções </span>
                                <i class="fa fa-angle-down"></i>
                            </a>
                            <div class="dropdown-menu pull-right">
                                <li>
                                    <a class="report-link"
                                       data-url="<?php echo $this->url('admin/default', ['controller'=>'workshop-proposal', 'action'=>'export', 'id'=>$this->proposal->getId()]) ?>"
                                       href="#"> Gerar ficha de cadastro </a>
                                </li>
                            </div>
                        </div>
                    <?php endif; ?>
				</div>
			</div>
			<div class="portlet-body">
				<div class="portlet">
					<div class="portlet-body form">
						<div class="form-body">
                            <div class="form-group ">
                                <?php
                                $userName = $this->proposal->getAuthor()?$this->proposal->getAuthor()->getName():"";
                                $userId = $this->proposal->getAuthor()?$this->proposal->getAuthor()->getId():"";
                                ?>
                                <label class="col-md-3 control-label">Usuário<span class="required"> * </span></label>
                                <div class=" col-md-4">
                                    <div class="input-group">
                                        <input readonly type="text" id="userName" class="form-control" value="<?php echo $userName ?>">
                                        <span class="input-group-btn">
                                                <button
                                                        class="btn user-modal"
                                                        type="button"
                                                        data-user-id="<?php echo $userId; ?>"
                                                        data-select-id-to="#user"
                                                        data-select-name-to="#userName">
                                                    <i class="fa fa-search"></i>
                                                </button>
                                            </span>
                                    </div>
                                </div>
                            </div>
                            <?php echo $this->formRow($form->get('name')) ?>
                            <?php echo $this->formRow($form->get('offer')) ?>
                            <?php echo $this->formRow($form->get('objectives')) ?>
                            <?php echo $this->formRow($form->get('program_content')) ?>
                            <?php echo $this->formRow($form->get('hours')) ?>
                            <?php echo $this->formRow($form->get('hour_class')) ?>
                            <?php echo $this->formRow($form->get('days_duration')) ?>
                            <?php echo $this->formRow($form->get('shift')) ?>
                            <?php echo $this->formRow($form->get('participant_prerequisites')) ?>
                            <?php echo $this->formRow($form->get('didactic_resources')) ?>
                            <?php echo $this->formRow($form->get('necessary_equipments')) ?>
                            <?php echo $this->formRow($form->get('final_product')) ?>
                            <?php echo $this->formRow($form->get('display_final_product')) ?>
                            <?php echo $this->formRow($form->get('value_hour_class')) ?>
                            <?php echo $this->formRow($form->get('total_value')) ?>
                            <?php echo $this->formRow($form->get('instructors_curriculum')) ?>
                            <?php echo $this->formRow($form->get('comments')) ?>
                        </div>

						<div class="form-actions">
							<div class="row">
								<div class="col-md-offset-3 col-md-9">
									<button type="submit" class="btn blue btn-lg action-save">Salvar</button>
									<a href="#" class="btn red btn-lg action cancel">Descartar</a>
								</div>
							</div>
						</div>

					</div>
				</div>
			</div>
		</div>
		<?php echo $this->form()->closeTag() ?>
	</div>
</div>