<?php $form = $this->form; ?>
<div class="row post news">
	<div class="col-md-12">
		<?php $form->prepare(); echo $this->form(null, null)->openTag($form) ?>
		<div class="portlet light portlet-fit bordered">
			<div class="portlet-title">
				<div class="caption">
					<?php if($this->proposal->getId()): ?>
					<i class="fa fa-edit"></i>
					Cadastrar proposta
					<?php else: ?>
					<i class="fa fa-file-o"></i>
					Editar proposta
					<?php endif; ?>
				</div>
				<div class="actions">
					<a href="<?php echo $this->url('admin/default', ['controller'=>'workshop-proposal']); ?>"
					   class="btn btn-default">
						<i class="icon-action-undo"></i>
						<span class="hidden-xs"> Voltar </span>
					</a>
				</div>
			</div>
			<div class="portlet-body">
				<div class="portlet">
					<div class="portlet-body form">
						<div class="form-body">
                            <div class="row">
                                <div class="col-md-6">
                                    <?php echo $this->formRow($form->get('name')); ?>
                                </div>
                                <div class="col-md-6">
                                    <?php echo $this->formRow($form->get('offer')); ?>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <?php echo $this->formRow($form->get('objectives')); ?>
                                </div>
                                <div class="col-md-6">
                                    <?php echo $this->formRow($form->get('program_content')); ?>
                                </div>

                            </div>
                            <div class="row">
                                <div class="col-md-3">
                                    <?php echo $this->formRow($form->get('hours')); ?>
                                </div>
                                <div class="col-md-3">
                                    <?php echo $this->formRow($form->get('hour_class')); ?>
                                </div>
                                <div class="col-md-3">
                                    <?php echo $this->formRow($form->get('days_duration')); ?>
                                </div>
                                <div class="col-md-3">
                                    <?php echo $this->formRow($form->get('shift')); ?>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-4">
                                    <?php echo $this->formRow($form->get('participant_prerequisites')); ?>
                                </div>
                                <div class="col-md-4">
                                    <?php echo $this->formRow($form->get('didactic_resources')); ?>
                                </div>
                                <div class="col-md-4">
                                    <?php echo $this->formRow($form->get('necessary_equipments')); ?>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-4">
                                    <?php echo $this->formRow($form->get('final_product')); ?>
                                </div>
                                <div class="col-md-4">
                                    <?php echo $this->formRow($form->get('display_final_product')); ?>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-4">
                                    <?php echo $this->formRow($form->get('value_hour_class')); ?>
                                </div>
                                <div class="col-md-4">
                                    <?php echo $this->formRow($form->get('total_value')); ?>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <?php echo $this->formRow($form->get('instructors_curriculum')); ?>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-4">
                                    <?php echo $this->formRow($form->get('contact_name')); ?>
                                </div>
                                <div class="col-md-4">
                                    <?php echo $this->formRow($form->get('email')); ?>
                                </div>
                                <div class="col-md-4">
                                    <?php echo $this->formRow($form->get('phones')); ?>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-4">
                                    <?php echo $this->formRow($form->get('address')); ?>
                                </div>
                                <div class="col-md-4">
                                    <?php echo $this->formRow($form->get('cep')); ?>
                                </div>
                                <div class="col-md-4">
                                    <?php echo $this->formRow($form->get('city')); ?>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <?php echo $this->formRow($form->get('comments')); ?>
                                </div>
                            </div>
                        </div>

						<div class="form-actions">
							<div class="row">
								<div class="col-md-offset-3 col-md-9">
									<button type="submit" class="btn blue btn-lg action-save">Salvar</button>
									<a href="#" class="btn red btn-lg action cancel">Descartar</a>
								</div>
							</div>
						</div>

					</div>
				</div>
			</div>
		</div>
		<?php echo $this->form()->closeTag() ?>
	</div>
</div>