<?php $form = $this->searchForm; ?>

<div class="row">
	<div class="col-md-12">
		<div class="portlet light portlet-fit portlet-datatable bordered">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-th-list"></i>
					Propostas artísticas
				</div>
				<div class="actions">
					<a href="<?php echo $this->url('admin/default', ['controller'=>'workshop-proposal', 'action'=>'create']); ?>"
					   class="btn blue btn-lg">
						<i class="fa fa-plus"></i>
						<span class="hidden-xs"> Inserir proposta </span>
					</a>
					<div class="btn-group">
						<a class="btn btn-default dropdown-toggle" href="javascript:;" data-toggle="dropdown">
							<i class="fa fa-share"></i>
							<span class="hidden-xs"> Opções </span>
							<i class="fa fa-angle-down"></i>
						</a>
						<div class="dropdown-menu pull-right">
							<li><a href="javascript:;"> Exportar para Excel </a></li>
						</div>
					</div>
				</div>
			</div>

			<div class="portlet-body">
				<div class="table-container post-list">
					<table class="table table-striped table-bordered table-hover">
						<thead>
						<tr role="row" class="heading">
							<th width="2%">#</th>
                            <th width="20%">Usuário</th>
                            <th width="30%">Nome da oficina</th>
							<th width="20%">Recebido em</th>
							<th width="10%">Ações</th>
						</tr>
						<tr role="row" class="filter">
							<?php $form->prepare(); echo $this->form()->openTag($form); ?>
							<td></td>
                            <td></td>
							<td><?php echo $this->formelement($form->get('name')); ?></td>
                            <td>
                                <div class="input-group date date-picker margin-bottom-5" data-date-format="dd/mm/yyyy">
                                    <?php echo $this->formelement($form->get('startDate')); ?>
                                    <span class="input-group-btn">
												<button class="btn btn-sm default" type="button">
													<i class="fa fa-calendar"></i>
												</button>
											</span>
                                </div>
                                <div class="input-group date date-picker" data-date-format="dd/mm/yyyy">
                                    <?php echo $this->formelement($form->get('endDate')); ?>
                                    <span class="input-group-btn">
												<button class="btn btn-sm default" type="button">
													<i class="fa fa-calendar"></i>
												</button>
											</span>
                                </div>
                            </td>
							<td>
								<div class="margin-bottom-5">
									<button class="btn btn-sm blue filter-submit margin-bottom"><i class="fa fa-search"></i> Pesquisar</button>
								</div>
								<button class="btn btn-sm btn-default filter-cancel"><i class="fa fa-times"></i> Limpar</button>
							</td>
							<?php echo $this->form()->closeTag(); ?>
						</tr>
						</thead>
						<tbody>
						<?php foreach ($this->items as $item):
							$updateUrl = $this->url('admin/default', [
								'controller' => 'workshop-proposal',
								'action'=>'update',
								'id'=>$item->getId()
							]);
							$removeUrl = $this->url('admin/default', [
								'controller' => 'workshop-proposal',
								'action'=>'delete',
								'id'=>$item->getId(),
							]);
							?>
							<tr>
								<td></td>
                                <td><?php echo $item->getAuthor() ? $item->getAuthor()->getName() : "" ?></td>
								<td><a href="<?php echo $updateUrl; ?>"><?php echo $item->getName(); ?></a></td>
								<td><?php echo $item->getCreatedAt()->format('d/m/Y H:i'); ?></td>
								<td>
									<a href="<?php echo  $updateUrl; ?>" class="btn btn-sm btn-default margin-bottom-5">
										<i class="fa fa-edit"></i> Editar
									</a>
									<a href="<?php echo $removeUrl; ?>" class="btn btn-sm btn-default post-list-remove">
										<i class="fa fa-close"></i> Excluir
									</a>
								</td>
							</tr>
						<?php endforeach; ?>
						</tbody>
					</table>
					<div class="table-paginator">
						<?php echo $this->paginationcontrol($this->items, 'sliding', 'admin/partials/paginator.phtml', array(
                            'route'=>'admin/default',
                            'route_options' => array('controller'=>'workshop-proposal'),
                            'route_query_options' => ['query'=>$this->searchData]
                        )); ?>
					</div>

				</div>
			</div>
		</div>
	</div>
</div>