<?php if($this->breadcrumbs): ?>
    <?php echo $this->partial('cinebh2017/partials/_breadcrumbs.phtml', ['breadcrumbs'=>$this->breadcrumbs]); ?>
<?php endif; ?>

<div class="main-wrapper">
    <section class="main-content">
        <header class="main-header">
            <h1 class="main-title"><?php echo $this->post->getTitle(); ?></h1>
        </header>

        <?php echo $this->thumborize($post->getContent()); ?>
    </section>
</div>