<div class="main__figure">
    <?php if($post->getMeta('_cover')): ?>
        <img src="<?php echo $this->thumbor()->url($post->getMeta('_cover'))->resize(1920, 492); ?>" alt="">
    <?php else: ?>
        <img src="<?php echo $this->basePath("assets/cinebh/dist") ?>/images/internal.jpg" alt="">
    <?php endif; ?>
</div>

<?php if($this->breadcrumbs): ?>
    <?php echo $this->partial('cinebh/partials/_breadcrumbs.phtml', ['breadcrumbs'=>$this->breadcrumbs]); ?>
<?php endif; ?>

<section class="main__wrapper">
    <header class="main__header">
        <h1 class="main__title"><?php echo $this->post->getTitle(); ?></h1>
    </header>
    <div class="news__list">
        <?php foreach ($this->events as $event): ?>
            <article class="news__item">
                <header class="news__header">
                    <h1 class="news__title"><?php echo $event->getFullName(); ?></h1>
                </header>
                <a href="<?php echo $this->url("cinebh/edition", ['id'=>$event->getId()]) ?>" class="news__link readmore-2">Leia mais</a>
            </article>
        <?php endforeach; ?>
    </div>
</section>