<?php if($this->breadcrumbs): ?>
    <?php echo $this->partial('cinebh2017/partials/_breadcrumbs.phtml', ['breadcrumbs'=>$this->breadcrumbs]); ?>
<?php endif; ?>

<div class="main-wrapper">
    <section class="main-content">
        <header class="main-header">
            <h1 class="main-title"><?php echo $this->post->getTitle(); ?></h1>
        </header>
        <div class="news-items">
            <?php foreach ($this->events as $event): ?>
                <div class="news-item" style="display: block; float: none;">
                    <p class="news-title"><?php echo $event->getFullName(); ?></p>
                    <p class="news-readmore"><a href="<?php echo $this->url("cinebh2017/edition", ['id'=>$event->getId()]) ?>" class="news__link readmore-2">Leia mais</a></p>
                </div>
            <?php endforeach; ?>
        </div>
    </section>
</div>