<?php $form = $this->form; ?>
<div class="row post news">
	<div class="col-md-12">
		<?php $form->prepare(); echo $this->form(null, null)->openTag($form) ?>
		<div class="portlet light portlet-fit bordered">
			<div class="portlet-title">
				<div class="caption">
					<?php if($this->proposal->getId()): ?>
					<i class="fa fa-edit"></i>
					Cadastrar proposta
					<?php else: ?>
					<i class="fa fa-file-o"></i>
					Editar proposta
					<?php endif; ?>
				</div>
				<div class="actions">
					<a href="<?php echo $this->url('admin/default', ['controller'=>'artistic-proposal']); ?>"
					   class="btn btn-default">
						<i class="icon-action-undo"></i>
						<span class="hidden-xs"> Voltar </span>
					</a>
                    <?php if($this->proposal->getId()): ?>
                        <div class="btn-group">
                            <a class="btn btn-default dropdown-toggle" href="javascript:;" data-toggle="dropdown">
                                <i class="fa fa-share"></i>
                                <span class="hidden-xs"> Opções </span>
                                <i class="fa fa-angle-down"></i>
                            </a>
                            <div class="dropdown-menu pull-right">
                                <li>
                                    <a class="report-link"
                                       data-url="<?php echo $this->url('admin/default', ['controller'=>'artistic-proposal', 'action'=>'export', 'id'=>$this->proposal->getId()]) ?>"
                                       href="#"> Gerar ficha de cadastro </a>
                                </li>
                            </div>
                        </div>
                    <?php endif; ?>
				</div>
			</div>
			<div class="portlet-body">
				<div class="portlet">
					<div class="portlet-body form">
						<div class="form-body">
                            <div class="row">
                                <?php echo $this->formRow($form->get('artist_name')) ?>
                                <?php echo $this->formRow($form->get('show_name')) ?>
                                <?php echo $this->formRow($form->get('category')) ?>
                                <?php echo $this->formRow($form->get('duration')) ?>
                                <?php echo $this->formRow($form->get('target_public')) ?>
                                <?php echo $this->formRow($form->get('suggested_cache')) ?>
                                <?php echo $this->formRow($form->get('staff_quantity')) ?>
                                <?php echo $this->formRow($form->get('incentive_law')) ?>
                                <?php echo $this->formRow($form->get('links')) ?>
                                <?php echo $this->formRow($form->get('short_presentation')) ?>
                                <?php echo $this->formRow($form->get('comments')) ?>
                            </div>
                        </div>

						<div class="form-actions">
							<div class="row">
								<div class="col-md-offset-3 col-md-9">
									<button type="submit" class="btn blue btn-lg action-save">Salvar</button>
									<a href="#" class="btn red btn-lg action cancel">Descartar</a>
								</div>
							</div>
						</div>

					</div>
				</div>
			</div>
		</div>
		<?php echo $this->form()->closeTag() ?>
	</div>
</div>