<div class="main-wrapper main-content">
    <header class="main-header">
        <h1 class="main-title"><?php echo $post->getTitle() ?></h1>
    </header>
    <div class="movie-list">
        <?php foreach ($this->movies as $movie): ?>
            <article class="movie-item">
                <a href="<?php echo $this->url('mostratiradentes/movie', ['id'=>$movie->getId()]) ?>" class="movie-link">
                    <div class="movie-cover">
                    <?php if($movie->getMedias()->first()): $media = $movie->getMedias()->first(); ?>
                        <figure class="movie-figure">
                            <img src="<?php echo $this->thumbor()->url($this->fileManipulation()->url($media->getSrc()))->resize(400, 400); ?>" alt="">
                        </figure>

                        <?php if(count($movie->getPrograming())): ?>
                        <div class="movie-highlight">
                            <div class="hightlight-wrapper">
                                <p class="hightlight-title">Exibições</p>
                                <?php foreach ($movie->getPrograming() as $pro): ?>
                                    <?php
                                    $progObj = null;
                                    if($pro->getParent()) {
                                        $progObj = $pro->getParent();
                                    } else {
                                        $progObj = $pro;
                                    }
                                    $date = $progObj->getDate()->format('d/m');
                                    $hour = $progObj->getStartTime()->format('H\hi');
                                    $place = $progObj->getPlace()?$progObj->getPlace()->getName():"";
                                    ?>
                                    <div class="highlight-item">
                                        <p class="hightlight-date"><?php echo "$date - $hour"; ?></p>
                                        <p class="hightlight-place"><?php echo $place ?></p>
                                    </div>
                                <?php endforeach; ?>
                            </div>
                        </div>
                        <?php endif; ?>
                    <?php endif; ?>
                    </div>
                    <h1 class="movie-title"><?php echo $movie->getTitle(); ?></h1>
                    <span class="movie-director">Direção: <?php echo $movie->getDirection(); ?></span>
                </a>
            </article>
        <?php endforeach; ?>
    </div>
</div>