<div class="main-wrapper main-content">
    <header class="main-header">
        <h1 class="main-title"><?php echo $post->getTitle() ?></h1>
    </header>
    <div class="movie-list">
        <?php foreach ($this->movies as $movie): ?>
            <article class="movie-item">
                <a href="<?php echo $this->url('mostratiradentes/movie', ['id'=>$movie->getId()]) ?>" class="movie-link">
                    <?php if($movie->getMedias()->first()): $media = $movie->getMedias()->first(); ?>
                        <figure class="movie-figure"><img src="<?php echo $this->thumbor()->url($media->getSrc())->resize(400, 400); ?>" alt=""></figure>
                    <?php endif; ?>
                    <h1 class="movie-title"><?php echo $movie->getTitle(); ?></h1>
                    <span class="movie-director">Direção: <?php echo $movie->getDirection(); ?></span>
                </a>
            </article>
        <?php endforeach; ?>
    </div>
</div>