<div class="main-wrapper main-content">

    <div class="movie">
        <header class="main-header">
            <h1 class="main-title"><?php echo $this->post->getTitle(); ?></h1>
            <?php if ($post->getTitleEnglish()): ?>
                <h2 class="movie-title--sub"><?php echo $this->post->getTitleEnglish(); ?></h2>
            <?php endif; ?>
        </header>


        <p class="movie-classification"><?php echo implode(', ', $movie_details) ?></p>

        <?php if(!empty($this->medias)): ?>
            <div class="movie-media">
                <div class="owl-carousel movie-carousel">
                    <?php foreach ($this->medias as $media): ?>
                        <div class="movie-media-item">
                            <div class="movie-media-wrapper">
                                <?php if($media['type'] == 'video'): ?>
                                    <a class="owl-video" href="<?php echo $media['src'] ?>"></a>
                                <?php else: ?>
                                    <img src="<?php echo $media['src'] ?>" alt="">
                                    <img src="<?php echo $this->thumbor()->url($this->fileManipulation()->url($media['src']))->resize(1140, 400); ?>" alt="">
                                <?php endif; ?>
                            </div>
                        </div>
                    <?php endforeach; ?>
                </div>
            </div>
        <?php endif; ?>


        <div class="movie-detail">
            <p><strong>Direção: </strong><?php echo $this->post->getDirection(); ?></p>
            <p class="movie-detail-title"><strong>Sinopse</strong></p>
            <p><?php echo $this->post->getSynopsis(); ?></p>

            <p><strong>Exibições</strong></p>
            <?php foreach ($this->post->getPrograming() as $pro): ?>
                <?php
                $progObj = null;
                if($pro->getParent()) {
                    $progObj = $pro->getParent();
                } else {
                    $progObj = $pro;
                }
                $date =  str_replace('-feira', '', $this->dateFormat($progObj->getDate(), null, null, "pt_BR", "dd/MM | cccc"));
                $hour = $progObj->getStartTime()->format('H\hi');
                $place = $progObj->getPlace()?$progObj->getPlace()->getName():"";
                ?>
                <div class="highlight-item">
                    <p class="hightlight-date"><?php echo "$date - $hour"; ?></p>
                    <p class="hightlight-place"><?php echo $place ?></p>
                </div>
            <?php endforeach; ?>
        </div>
    </div>

    <?php echo $this->partial("application/partials/share.phtml", ['title'=>$post->getTitle()]); ?>
</div>