<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>CineBH - 14ª Mostra de Cinema de Belo Horizonte</title>
    <link rel="apple-touch-icon" href="apple-touch-icon.png">
    <link rel="stylesheet" href="<?php echo $this->basePath('assets/cinebh_hotsite/dist') ?>/styles/main.css">
    <link href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:ital,wght@0,300;0,400;0,500;0,600;1,900&display=swap"
          rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@800&display=swap" rel="stylesheet">
</head>
<body>
<header>
    <div class="container">
        <div class="left">
            <h1><img src="<?php echo $this->basePath('assets/cinebh_hotsite/dist') ?>/images/logo-cinebh.png" alt=""></h1>
        </div>
        <div class="right"><img src="<?php echo $this->basePath('assets/cinebh_hotsite/dist') ?>/images/date.png" alt=""></div>
    </div>
</header>
<div class="content">
    <main>
        <div class="container">
            <div class="left">
                <div class="wrapper">
                    <p>Belo horizonte</p>
                    <p>mostra o cinema</p>
                    <p>para o mundo</p>
                </div>
            </div>
            <div class="right">
                <p><strong>A Mostra CineBH, o evento audiovisual da capital mineira, ganha versão online
                        em 2020.</strong>
                </p>
                <p>Vamos estar juntos nas redes sociais e em plataformas digitais mantendo o mesmo propósito conceitual
                    de fazer a conexão entre o cinema brasileiro e o mercado internacional stimulando a exibição,
                    reflexão e discussão de produções audiovisuais que tratem da vivência e experiência de estar e
                    ocupar a cidade de Belo Horizonte e sua região metropolitana.
                </p>
                <p><strong>Vamos encontrar pelo cinema.</strong><br>Programe-se!</p>
                <p><strong>Raquel Hallak</strong><br>Coordenadora Geral</p>
                <p><a href="http://www.cinebh.com.br/inicio" class="btn" target="_blank">Ir para edição anterior</a></p>
            </div>
            <div class="universo"><a href="http://www.universoproducao.com.br" target="_blank"><img
                            src="<?php echo $this->basePath('assets/cinebh_hotsite/dist') ?>/images/logo-up.png" alt=""></a></div>
        </div>
    </main>
    <footer>
        <div class="container">
            <p>Siga nossas redes sociais e fique por dentro dos basttidores, notícias e conteúdos
                exclusivos do evento
            </p>
            <ul>
                <li><a href="http://www.youtube.com/user/universoproducao/featured">
                        <img target="_blank"
                             src="<?php echo $this->basePath('assets/cinebh_hotsite/dist') ?>/images/youtube.png"
                             alt="">
                        <span>universoproducao</span></a>
                </li>
                <li><a href="http://instagram.com/universoproducao">
                        <img target="_blank" src="<?php echo $this->basePath('assets/cinebh_hotsite/dist') ?>/images/insta.png"
                                                                         alt=""> <span>universoproducao</span></a></li>
                <li><a href="http://www.facebook.com/universoproducao"><img target="_blank" src="<?php echo $this->basePath('assets/cinebh_hotsite/dist') ?>/images/facebook.png"
                                                                            alt=""> <span>universoproducao</span></a>
                </li>
                <li><a href="http://twitter.com/universoprod"><img target="_blank" src="<?php echo $this->basePath('assets/cinebh_hotsite/dist') ?>/images/twitter.png" alt="">
                        <span>universoprod</span></a>
                </li>
                <li><a href="https://www.linkedin.com/company/universo-produ%C3%A7%C3%A3o/"><img target="_blank"
                                                                                                 src="<?php echo $this->basePath('assets/cinebh_hotsite/dist') ?>/images/linkedin.png"
                                                                                                 alt=""> <span>universo producao</span></a>
                </li>
            </ul>
        </div>
    </footer>
</div>
</body>
</html>