<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Brasilcinemundi - 11º International Coproduction Meeting</title>
    <link rel="apple-touch-icon" href="apple-touch-icon.png">
    <link rel="stylesheet" href="<?php echo $this->basePath('assets/brasilcinemundi-hot/dist') ?>/styles/main.css">
    <link href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:ital,wght@0,300;0,400;0,500;0,600;1,900&display=swap" rel="stylesheet">
</head>
<body>
<div class="container">
    <header>
        <h1 class="brand">
            <a href=""><img src="<?php echo $this->basePath('assets/brasilcinemundi-hot/dist') ?>/images/logo-bcm.png" alt=""></a>
        </h1>
        <span class="date"><img src="<?php echo $this->basePath('assets/brasilcinemundi-hot/dist') ?>/images/data.png" alt=""></span>
    </header>
    <main>
        <div class="circle">
            <div class="circle-wrapper"><p>Inscrições</p>
                <p>Projetos de longa-metragem</p>
                <p>Até 5 de agosto</p><a class="btn" href="http://universoproducao.com.br/" target="_blank">inscrições abertas e gratuitas</a></div>
        </div>
        <div class="content"><p>Em 2020, está tudo diferente, mas continuamos juntos.</p>
            <p>O Brasil CineMundi – International Coproduction Meeting chega a sua 11ª edição de 29 de outubro a 02 de
                novembro de 2020 com novidades. Além de ser realizado no formato online, amplia as possibilidades de
                participação e inserção do projeto de longa brasileiro nas categorias - desenvolvimento, produção e
                finalização.</p>
            <p>O evento promove rede de contatos e negócios entre profissionais brasileiros e representantes da
                indústria nacional e estrangeira, além de atividades de capacitação, cooperação, intercâmbio, meetings e
                premiação, com foco nas tendências do cinema contemporâneo e na produção independente de perspectiva
                autoral e inovadora.</p>
            <p>Sejam bem-vindxs!</p>
            <p>Raquel Hallak<br><span>Coordenadora Geral</span></p>
            <a href="http://brasilcinemundi.com.br/inicio" class="btn" target="_blank">Ir para a edição anterior</a>
        </div>
        <div class="ed">
            <div class="left"><img src="<?php echo $this->basePath('assets/brasilcinemundi-hot/dist') ?>/images/logo-cinebh.png" alt=""></div>
            <div class="right"><img src="<?php echo $this->basePath('assets/brasilcinemundi-hot/dist') ?>/images/logo-up.png" alt=""></div>
        </div>
    </main>
    <footer>
        <div class="top"></div>
        <div class="bottom"><p>Siga nossas redes sociais e fique por dentro dos bastidores, notícias e conteúdos
                exclusivos do evento.</p>
            <ul>
                <li>
                    <a href="http://www.youtube.com/user/universoproducao/featured">
                        <img target="_blank" src="<?php echo $this->basePath('assets/brasilcinemundi-hot/dist') ?>/images/youtube.png" alt="">
                        <span>universoproducao</span>
                    </a>
                </li>
                <li>
                    <a href="http://instagram.com/universoproducao">
                        <img target="_blank" src="<?php echo $this->basePath('assets/brasilcinemundi-hot/dist') ?>/images/instagram.png" alt="">
                        <span>universoproducao</span>
                    </a>
                </li>
                <li>
                    <a href="http://www.facebook.com/universoproducao">
                        <img target="_blank" src="<?php echo $this->basePath('assets/brasilcinemundi-hot/dist') ?>/images/facebook.png" alt=""> <span>universoproducao</span>
                    </a>
                </li>
                <li>
                    <a href="http://twitter.com/universoprod">
                        <img target="_blank" src="<?php echo $this->basePath('assets/brasilcinemundi-hot/dist') ?>/images/twitter.png" alt="">
                        <span>universoprod</span>
                    </a>
                </li>
                <li>
                    <a href="https://www.linkedin.com/company/universo-produ%C3%A7%C3%A3o/">
                        <img target="_blank" src="<?php echo $this->basePath('assets/brasilcinemundi-hot/dist') ?>/images/linkedin.png" alt="">
                        <span>universo producao</span>
                    </a>
                </li>
            </ul>
        </div>
    </footer>
</div>
</body>
</html>