<?php $form = $this->form; ?>
<?php $programingForm = $this->programingForm; ?>
<div class="portlet">
    <div class="portlet-body form">
        <?php $form->prepare(); echo $this->form(null, null)->openTag($form) ?>
        <div class="form-body">

            <div class="row">
                <div class="col-md-4"><?php echo $this->formRow($form->get('registration')); ?></div>
            </div>

            <div class="row">
                <div class="col-md-4"><?php echo $this->formRow($form->get('name')); ?></div>
            </div>

            <div class="row">
                <div class="col-md-4"><?php echo $this->formRow($form->get('age_range')); ?></div>
            </div>

            <div class="row">
                <div class="col-md-4"><?php echo $this->formRow($form->get('movies')); ?></div>
            </div>

            <!--<div class="row">
                <div class="col-md-4 movie-session">
                    <div class="form-group">
                        <label for="">Filmes</label>
                        <div class="input-group">
                            <?php
/*                            $movieEl = $form->get('movie');
                            $movieEl->setAttribute('required', '');
                            echo $this->formElement($movieEl);
                            */?>
                            <span class="input-group-btn">
                                <button class="btn movie-session-add" type="button">
                                    <i class="fa fa-plus"></i>
                                </button>
                            </span>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <div class="dd" id="nestable_session_movie">
                            <ol class="dd-list">
                                <?php /*foreach ($this->session->getMovies() as $m): */?>
                                    <li class="dd-item" data-id="<?php /*echo $m->getId(); */?>">
                                        <div class="item-controls">
                                            <a class="movie-session-remove" role="button">excluir</a>
                                        </div>
                                        <div class="dd-handle">
                                            <span class="item-title">
                                                <?php /*echo $m->getTitle(); */?>
                                            </span>
                                        </div>
                                    </li>
                                <?php /*endforeach; */?>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>-->

            <h3 class="form-section">Programação</h3>
            <div class="row">
                <div class="col-md-9">
                    <table class="table table-hover table-light table-programing">
                        <thead>
                        <tr>
                            <th width="18%">Data</th>
                            <th width="18%">Hora de início</th>
                            <th width="18%">Hora de término</th>
                            <th width="18%">Vagas</th>
                            <th width="40%">Local</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td>
                                <div class="input-group date date-picker" data-date-format="dd/mm/yyyy">
                                    <?php echo $this->formElement($programingForm->get('date')); ?>
                                    <span class="input-group-btn">
                                        <button type="button" name="btn-date" class="btn default">
                                            <span class="fa fa-fa fa-calendar"></span>
                                        </button>
                                    </span>
                                </div>
                            </td>
                            <td><?php echo $this->formElement($programingForm->get('start_time')); ?></td>
                            <td><?php echo $this->formElement($programingForm->get('end_time')); ?></td>
                            <td><?php echo $this->formElement($programingForm->get('available_places')); ?></td>
                            <td><?php echo $this->formElement($programingForm->get('place')); ?></td>
                            <td><button class="btn btn-sm btn-success table-programing-add" type="button">
                                    <i class="fa fa-plus"></i> Adicionar</button></td>
                        </tr>
                        <?php foreach ($this->session->getPrograming() as $pro): ?>
                            <tr data-row="<?php echo $pro->getId() ?>">
                                <td><?php echo $pro->getDate()->format('d/m/Y') ?></td>
                                <td><?php echo $pro->getStartTime()->format('H:i:s') ?></td>
                                <td><?php echo $pro->getEndTime() ? $pro->getEndTime()->format('H:i:s') : "" ?></td>
                                <td><?php echo $pro->getAvailablePlaces() ? $pro->getAvailablePlaces() : "" ?></td>
                                <td><?php echo $pro->getPlace() ? $pro->getPlace()->getName() : ""; ?></td>
                                <td>
                                    <a href="#" class="btn btn-sm btn-default table-programing-remove"
                                       data-remove="<?php echo $pro->getId() ?>"><i class="fa fa-close"></i>
                                    </a>
                                    <input type="hidden" name="programing[<?php echo $pro->getId() ?>][id]" value="<?php echo $pro->getId() ?>">
                                    <input type="hidden" name="programing[<?php echo $pro->getId() ?>][date]" value="<?php echo $pro->getDate()->format('d/m/Y') ?>">
                                    <input type="hidden" name="programing[<?php echo $pro->getId() ?>][start_time]" value="<?php echo $pro->getStartTime()->format('H:i:s') ?>">
                                    <input type="hidden" name="programing[<?php echo $pro->getId() ?>][end_time]" value="<?php echo $pro->getEndTime() ? $pro->getEndTime()->format('H:i:s') : "" ?>">
                                    <input type="hidden" name="programing[<?php echo $pro->getId() ?>][available_places]" value="<?php echo $pro->getAvailablePlaces() ? $pro->getAvailablePlaces() : "" ?>">
                                    <input type="hidden" name="programing[<?php echo $pro->getId() ?>][place]" value="<?php echo $pro->getPlace() ? $pro->getPlace()->getName() : ""; ?>"></td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            </div>

        </div>

        <div class="form-actions">
            <div class="row">
                <div class="col-md-offset-3 col-md-9">
                    <button type="submit" class="btn blue btn-lg">Salvar</button>
                    <a href="#" class="btn red btn-lg action cancel">Descartar</a>
                </div>
            </div>
        </div>
        <?php echo $this->form()->closeTag() ?>
    </div>
</div>
