<?php $form = $this->searchForm; ?>
<div class="row">
	<div class="col-md-12">
		<div class="portlet light portlet-fit portlet-datatable bordered">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-th-list"></i>
					Sessões Cine Escola
				</div>
				<div class="actions">
					<a href="<?php echo $this->url('admin/default', ['controller' => 'session-school', 'action'=>'create']); ?>"
					   class="btn blue btn-lg">
						<i class="fa fa-plus"></i>
						<span class="hidden-xs"> Cadastrar sessão </span>
					</a>
				</div>
			</div>

			<div class="portlet-body">
				<div class="table-container post-list">
					<table class="table table-striped table-bordered table-hover">
						<thead>
							<tr role="row" class="heading">
								<th width="2%">#</th>
								<th width="25%">Nome</th>
								<th width="15%">Evento</th>
								<th width="15%">Ações</th>
							</tr>

						</thead>
						<tbody>
						<?php foreach ($this->items as $i):

                            //$events = $i->getRegistration()->getEvents();

							$updateUrl = "#";
							$removeUrl = "#"
							?>
							<tr>
								<td></td>
								<td></td>
								<td></td>
								<td></td>
							</tr>
						<?php endforeach; ?>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>