<?php $form = $this->searchForm; ?>
<div class="row">
	<div class="col-md-12">
		<div class="portlet light portlet-fit portlet-datatable bordered">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-th-list"></i>
					Sessões Cine Escola
				</div>
				<div class="actions">
					<a href="<?php echo $this->url('admin/default', ['controller' => 'session-school', 'action'=>'create']); ?>"
					   class="btn blue btn-lg">
						<i class="fa fa-plus"></i>
						<span class="hidden-xs"> Cadastrar sessão </span>
					</a>
				</div>
			</div>

			<div class="portlet-body">
				<div class="table-container post-list">
					<table class="table table-striped table-bordered table-hover">
						<thead>
							<tr role="row" class="heading">
								<th width="2%">#</th>
								<th width="25%">Nome</th>
								<th width="15%">Evento</th>
								<th width="15%">Ações</th>
							</tr>

						</thead>
						<tbody>
						<?php foreach ($this->items as $i):

                            //$events = $i->getRegistration()->getEvents();

                            $updateUrl = $this->url('admin/default', [
                                'controller' => 'session-school',
                                'action' => 'update',
                                'id' => $i->getId()
                            ]);

                            $removeUrl = $this->url('admin/default', [
                                'controller' => 'session-school',
                                'action'=>'delete',
                                'id'=>$i->getId()
                            ]);
							?>
							<tr>
                                <td></td>
                                <td>
                                    <div class="margin-bottom-20"><strong><?php echo $i->getName() ?></strong></div>
                                    <table class="table table-in-td">
                                        <tbody>
                                        <?php foreach ($i->getProgramming() as $p): ?>
                                            <tr>
                                                <td><?php echo $p->getDate()->format('d/m/Y').' | '.$p->getStartTime()->format('H:i') ?></td>
                                                <td>Vagas: <?php echo $p->getAvailablePlaces() ?></td>
                                                <td>Inscritos: <?php echo $this->repository->getTotalSubscriptionsSession($p->getId()) ?></td>
                                                <td><a class="btn btn-sm btn-default"><i class="fa fa-filter"></i> Inscrições</a></td>
                                            </tr>
                                        <?php endforeach; ?>
                                        </tbody>
                                    </table>
                                </td>
                                <td><?php echo $i->getEvent()->getShortName(); ?></td>
								<td>
                                    <a href="<?php echo  $updateUrl; ?>" class="btn btn-sm btn-default">
                                        <i class="fa fa-edit"></i> Editar
                                    </a>
                                    <a href="<?php echo $removeUrl; ?>" class="btn btn-sm btn-default post-list-remove">
                                        <i class="fa fa-trash-o"></i> Excluir
                                    </a></td>
							</tr>
						<?php endforeach; ?>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>