<!doctype html>
<html lang="">
<head>
    <meta charset="utf-8">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>CineOP - 12ª Mostra de Cinema de Ouro Preto</title>

    <link rel="apple-touch-icon" href="apple-touch-icon.png">
    <link rel="stylesheet" href="<?php echo $this->basePath('assets/cineop2017/dist') ?>/styles/main.css">
    <link rel="stylesheet" href="<?php echo $this->basePath('assets/cineop2017/dist') ?>/styles/vendor.css">

</head>
<body>
<!--[if lt IE 10]>
<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
<![endif]-->

<header class="header">
    <div class="header-top">
        <div class="header-wrapper">
            <div class="header-col">
                <p class="header-date">
                    21 - 27 Junho
                    <span>Programação Gratuita</span>
                </p>
            </div>
            <div class="header-col">
                <h1 class="header-brand">
                    <a href="<?php echo $this->url('cineop2017') ?>">
                        <span class="brand-icon icon-cineo2017-horizontal"></span>
                    </a>
                </h1>
            </div>
            <div class="header-col">
                <div class="social">
                    <ul class="social-list">
                        <li class="social-item"><a target="_blank" href="http://www.facebook.com/cineop/" class="social-link"><i class="icon-facebook"></i></a></li>
                        <li class="social-item"><a target="_blank" href="http://twitter.com/universoprod" class="social-link"><i class="icon-twitter"></i></a></li>
                        <li class="social-item"><a target="_blank" href="http://www.youtube.com/user/universoproducao/featured" class="social-link"><i class="icon-youtube"></i></a></li>
                        <li class="social-item"><a target="_blank" href="http://instagram.com/universoproducao" class="social-link"><i class="icon-instagram"></i></a></li>
                    </ul>
                </div>
            </div>
            <div class="header-wrapper-mobile">
                <a class="mainmenu-mobile-btn" href="#"><span class="icon-menu7"></span></a>
            </div>
        </div>
    </div>

    <nav class="header-navigation">
        <?php $this
            ->navigation('Cineop2017Navigation')
            ->menu()->setPartial("cineop2017/partials/navigation.phtml");

        echo $this
            ->navigation('Cineop2017Navigation')
            ->menu()
            ->render(); ?>
    </nav>

</header>

<?php echo $this->content; ?>

<footer class="footer">
    <div class="footer-wrapper">
        <div class="footer-clear">
            <div class="footer-contact">
                <p class="footer-title">Contate-nos:</p>
                <span class="icon icon-universo-producao"></span>
                <span class="footer-add">+ 55 31 3282-2366<br>
                            up@universoproducao.com.br<br>
                            Rua Pirapetinga, 567 - Serra<br>
                            30220-150, Belo Horizonte | MG</span>
            </div>
            <div class="footer-social">
                <p class="footer-title">Siga-nos:</p>
                <ul class="footer-socialitems">
                    <li class="footer-socialitem"><a target="_blank" class="footer-socialink" href="http://www.facebook.com/universoproducao"><span class="icon icon-facebook"></span></a></li>
                    <li class="footer-socialitem"><a target="_blank" class="footer-socialink" href="http://twitter.com/universoprod"><span class="icon icon-twitter"></span></a></li>
                    <li class="footer-socialitem"><a target="_blank" class="footer-socialink" href="http://instagram.com/universoproducao"><span class="icon icon-instagram"></span></a></li>
                    <li class="footer-socialitem"><a target="_blank" class="footer-socialink" href="http://www.flickr.com/photos/universoproducao"><span class="icon icon-flickr"></span></a></li>
                    <li class="footer-socialitem"><a target="_blank" class="footer-socialink" href="http://www.youtube.com/user/universoproducao/featured"><span class="icon icon-youtube"></span></a></li>
                </ul>
            </div>
        </div>
        <p class="footer-title footer-copy">Copyright © 2017. Universo Produção - Todos os direitos reservados.</p>
    </div>
</footer>


<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="/bower_components/jquery/dist/jquery.min.js"><\/script>')</script>

<script src="<?php echo $this->basePath('assets/cineop2017/dist') ?>/scripts/vendor.js"></script>
<script src="<?php echo $this->basePath('assets/cineop2017/dist') ?>/scripts/main.js"></script>
</body>
</html>
