<div class="main-no-bg">
    <header class="main-header">
    </header>
</div>

<section class="main-section">
    <div class="main-wrapper">
       <div class="page4004">
           <header class="page404-header">
               <h1 class="page404-title">404</h1>
           </header>
           <article class="page404-content">
               <p>A página não encontrada</p>
           </article>
       </div>
    </div>
</section>