<div class="breadcrumbs">
    <div class="breadcrumbs__wrapper">
        <ul class="breadcrumbs__list">
            <li class="breadcrumbs__item"><a href="<?php echo $this->url("cinebh/home") ?>" class="breadcrumbs__link">Início</a></li>
            <?php $relativeSlug=""; foreach($this->breadcrumbs as $slug): ?>
                <?php $relativeSlug.= "/" . key($slug); ?>
                <li class="breadcrumbs__item">
                    <a href="<?php echo $this->url("cinebh/default", ['slug' => trim($relativeSlug, "/")]); ?>" class="breadcrumbs__link"><?php echo current($slug); ?></a>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
</div>