<ul class="mainmenu__list">
    <li class="mainmenu__item">
        <a class="mainmenu__link" href="<?php echo $this->url("cinebh/home") ?>">
            <span>Início</span>
        </a>
    </li>
    <?php foreach ($this->container as $page):
        /** @var Zend\Navigation\Page\AbstractPage $page */ ?>
        <li class="mainmenu__item">
            <a class="mainmenu__link" href="<?php echo rawurldecode($page->getHref()) ?>" target="<?php echo $page->getTarget() ?>">
                <span><?php echo $page->getLabel() ?></span>
            </a>
            <?php if ($page->hasPages()): ?>
                <ul class="mainmenu__list mainmenu__list--sub">
                    <?php foreach ($page->getPages() as $child):
                        /** @var Zend\Navigation\Page\AbstractPage $child */ ?>
                        <li class="mainmenu__item">
                            <a class="mainmenu__link" href="<?php echo rawurldecode($child->getHref()); ?>">
                                <span><?php echo $child->getLabel() ?></span>
                            </a>
                        </li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>
        </li>
    <?php endforeach; ?>
</ul>
