<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="description" content="15 Mostra de Cinema de Ouro Preto">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>15ª CineOP</title>
    <link rel="apple-touch-icon" href="apple-touch-icon.png">
    <link rel="stylesheet" href="<?php echo $this->basePath('assets/cineop2020-hot/dist') ?>/styles/main.css">
    <link href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:ital,wght@0,300;0,400;0,500;0,600;1,900&display=swap"
          rel="stylesheet">
</head>
<body>
<div class="all">
    <div class="container">
        <header>
            <div class="left"><h1><a href=""><img src="<?php echo $this->basePath('assets/cineop2020-hot/dist') ?>/images/logo-cineop.png" alt=""></a></h1></div>
            <div class="right"><img class="desktop" src="<?php echo $this->basePath('assets/cineop2020-hot/dist') ?>/images/data.png" alt=""> <img class="mobile"
                                                                                       src="<?php echo $this->basePath('assets/cineop2020-hot/dist') ?>/images/data-m.png" alt="">
            </div>
        </header>
    </div>
    <div class="featured">
        <div class="main-content"><p>inscrição</p>
            <p class="yellow"><strong>Filmes Mostra Educação e Trabalhos Educativos</strong></p>
            <p class="white"><strong>até 20 de julho</strong></p><a class="btn" target="_blank"
                                                                    href="http://universoproducao.com.br/inscricoes">inscrições
                abertas e gratuitas</a></div>
    </div>
    <div class="main">
        <div class="main-content">
            <div class="text"><p>Em 2020, a CineOP celebra 15 anos de história.</p>
                <p>Uma trajetória rica e singular em propósitos, conhecimento, conexões e conquistas.</p>
                <p>Um trabalho coletivo a favor da construção da memória e preservação do cinema brasileiro.</p>
                <p><strong>Estaremos novamente juntos com uma programação online, abrangente e gratuita.</strong></p>
                <p>Vamos expandir nossa atuação, ampliar o alcance e levar nosso patrimônio audiovisual a uma público
                    ainda maior.</p>
                <p><strong>Agora, nosso Universo é também digital!</strong></p>
                <p>Sejam bem-vindxs!</p>
                <p>Raquel Hallak<br><span>Coordenação Geral</span></p></div>
            <div class="ed">
                <div class="left"><a class="btn" target="_blank" href="http://cineop.com.br/inicio">Ir para edição
                        anterior</a></div>
                <div class="right"><a href="http://universoproducao.com.br/"><img src="<?php echo $this->basePath('assets/cineop2020-hot/dist') ?>/images/logo-up.png" alt=""></a></div>
            </div>
        </div>
    </div>
    <footer>
        <div class="container"><p>Siga nossas redes sociais e fique por dentro dos bastidores, notícias e conteúdos
                exclusivos do evento:</p>
            <ul>
                <li><a href="http://www.youtube.com/user/universoproducao/featured"><img target="_blank"
                                                                                         src="<?php echo $this->basePath('assets/cineop2020-hot/dist') ?>/images/youtube.png"
                                                                                         alt="">
                        <span>universoproducao</span></a></li>
                <li><a href="http://instagram.com/universoproducao"><img target="_blank" src="<?php echo $this->basePath('assets/cineop2020-hot/dist') ?>/images/instagram.png"
                                                                         alt=""> <span>universoproducao</span></a></li>
                <li><a href="http://www.facebook.com/universoproducao"><img target="_blank" src="<?php echo $this->basePath('assets/cineop2020-hot/dist') ?>/images/facebook.png"
                                                                            alt=""> <span>universoproducao</span></a>
                </li>
                <li><a href="http://twitter.com/universoprod"><img target="_blank" src="<?php echo $this->basePath('assets/cineop2020-hot/dist') ?>/images/twitter.png" alt="">
                        <span>universoprod</span></a></li>
                <li><a href="https://www.linkedin.com/company/universo-produ%C3%A7%C3%A3o/"><img target="_blank"
                                                                                                 src="<?php echo $this->basePath('assets/cineop2020-hot/dist') ?>/images/linkedin.png"
                                                                                                 alt=""> <span>universo producao</span></a>
                </li>
            </ul>
        </div>
    </footer>
</div>
</body>
</html>