<?php $form = $this->form; ?>
<div class="row post news">
	<div class="col-md-12">
		<?php $form->prepare(); echo $this->form(null, null)->openTag($form) ?>
		<div class="portlet light portlet-fit bordered">
			<div class="portlet-title">
				<div class="caption">
					<?php if($this->project->getId()): ?>
					<i class="fa fa-edit"></i>
					Editar projeto
					<?php else: ?>
					<i class="fa fa-file-o"></i>
					Cadastrar projeto
					<?php endif; ?>
				</div>
				<div class="actions">
					<a href="<?php echo $this->url('admin/default', ['controller'=>'project']); ?>"
					   class="btn btn-default">
						<i class="icon-action-undo"></i>
						<span class="hidden-xs"> Voltar </span>
					</a>
                    <?php if($this->canEdit): ?>
                    <a href="<?php echo $this->url('admin/default', ['controller'=>'project', 'action'=>'create']); ?>"
                       class="btn blue btn-lg">
                        <i class="fa fa-plus"></i>
                        <span class="hidden-xs"> Novo projeto  </span>
                    </a>
                    <?php endif; ?>
				</div>
			</div>
			<div class="portlet-body">
				<div class="portlet">

                    <?php echo $this->partial('admin/project/_form.phtml', [
                        'form' => $this->form,
                        'project'=>$this->project,
                        'canEdit' => $this->canEdit
                    ]); ?>
				</div>
			</div>
		</div>
		<?php echo $this->form()->closeTag() ?>
	</div>
</div>

