<?php $form = $this->searchForm; ?>
<div class="row">
	<div class="col-md-12">
		<div class="portlet light portlet-fit portlet-datatable bordered">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-th-list"></i>
					Projetos BrasilCineMundi
				</div>
				<div class="actions">
					<a href="<?php echo $this->url('admin/default', ['controller' => 'project', 'action'=>'create']); ?>"
					   class="btn blue btn-lg">
						<i class="fa fa-plus"></i>
						<span class="hidden-xs"> Cadastrar projeto </span>
					</a>
				</div>
			</div>

			<div class="portlet-body">
				<div class="table-container post-list">
					<table class="table table-striped table-bordered table-hover">
						<thead>
							<tr role="row" class="heading">
								<th width="2%">#</th>
								<th width="20%">Título</th>
                                <th width="15%">Usuário</th>
                                <th width="20%">Evento</th>
                                <th width="20%">Status</th>
                                <th width="15%">Data de cadastro</th>

                                <th width="10%"></th>
							</tr>
                            <tr role="row" class="filter">
                                <?php $form->prepare(); echo $this->form()->openTag($form); ?>
                                <td></td>
                                <td><?php echo $this->formelement($form->get('title')); ?></td>
                                <td><?php echo $this->formelement($form->get('user')); ?></td>
                                <td><?php echo $this->formelement($form->get('event')); ?></td>
                                <td><?php echo $this->formelement($form->get('status')); ?></td>
                                <td></td>
                                <td>
                                    <button class="btn btn-sm blue filter-submit margin-bottom"><i class="fa fa-search"></i> Pesquisar</button>
                                    <button class="btn btn-sm btn-default filter-cancel"><i class="fa fa-times"></i> Limpar</button>
                                </td>
                                <?php echo $this->form()->closeTag(); ?>
                            </tr>
						</thead>
						<tbody>
						<?php foreach ($this->items as $i):
							$updateUrl = $this->url('admin/default', [
                                'controller' => 'project',
								'action' => 'update',
								'id' => $i->getId()
							]);

							$removeUrl = $this->url('admin/default', [
                                'controller' => 'project',
								'action'=>'delete',
								'id'=>$i->getId()
							]);
							?>
							<tr>
								<td></td>
								<td><a href="<?php echo $updateUrl; ?>"><?php echo $i->getTitle(); ?></a></td>
                                <td><?php echo $i->getUser() ? $i->getUser()->getName() : ""; ?></td>
                                <td><?php echo $i->getEvent() ? $i->getEvent()->getShortName() : ""; ?></td>
                                <td><?php $label = \Application\Entity\Registration\Status::get($i->getStatus());
                                    echo $this->registrationStatus($i->getStatus(), $label). " ". $label; ?></td>
                                <td><?php echo $i->getCreatedAt()->format('d/m/Y H:i') ?></td>
								<td>
									<a href="<?php echo  $updateUrl; ?>" class="btn btn-sm btn-default">
										<i class="fa fa-edit"></i> Editar
									</a>
									<a href="<?php echo $removeUrl; ?>" class="btn btn-sm btn-default post-list-remove">
										<i class="fa fa-trash-o"></i> Excluir
									</a>

								</td>
							</tr>
						<?php endforeach; ?>
						</tbody>
					</table>

					<div class="table-paginator">
						<?php echo $this->paginationcontrol(
							$this->items,
							'sliding',
							'admin/partials/paginator.phtml',
							array(
								'route'=>'admin/default',
								'route_options' => [
                                    'controller' => 'project'
                                ]
							)
						); ?>
					</div>

				</div>
			</div>
		</div>
	</div>
</div>