<?php $form = $this->searchForm; ?>
<div class="row">
	<div class="col-md-12">
		<div class="portlet light portlet-fit portlet-datatable bordered">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-th-list"></i>
					Projetos BrasilCineMundi
				</div>
				<div class="actions">
                    <?php if($this->canEdit): ?>
					<a href="<?php echo $this->url('admin/default', ['controller' => 'project', 'action'=>'create']); ?>"
					   class="btn blue btn-lg">
						<i class="fa fa-plus"></i>
						<span class="hidden-xs"> Cadastrar projeto </span>
					</a>
                    <?php endif; ?>
                    <div class="btn-group">
                        <a class="btn btn-default dropdown-toggle" href="javascript:;" data-toggle="dropdown">
                            <i class="fa fa-share"></i>
                            <span class="hidden-xs"> Opções </span>
                            <i class="fa fa-angle-down"></i>
                        </a>
                        <div class="dropdown-menu pull-right">
                            <li>
                                <a class="report-link"
                                   data-form="#project-search-form"
                                   data-url="<?php echo $this->url('admin/default', ['controller'=>'project', 'action'=>'export-list']) ?>"
                                   href="#"> Exportar para Excel </a>
                            </li>
                        </div>
                    </div>
				</div>
			</div>

			<div class="portlet-body">
                <div class="table-container post-list list-actions"
                     data-total="<?php echo $this->items->getTotalItemCount(); ?>"
                     data-form="#project-search-form">


                    <div class="row">
                        <div class="col-md-12 col-sm-12 margin-bottom-10">
                            <div class="table-group-actions pull-right">
                                <span class="list-actions-selected"></span>
                                <select class="table-group-action-input form-control input-inline input-sm list-actions-options">
                                    <option value="">Selecione uma ação...</option>
                                    <option data-modal="#modal-project-status">Alterar status</option>
                                    <!--<option>Enviar comunicados</option>-->
                                </select>
                                <button class="btn btn-sm btn-default table-group-action-submit list-actions-submit">
                                    <i class="fa fa-check"></i> Processar</button>
                            </div>
                        </div>
                    </div>

					<table class="table table-striped table-bordered table-hover">
						<thead>
							<tr role="row" class="heading">
                                <th width="2%"> </th>
								<th width="3%">ID</th>
								<th width="20%">Título</th>
                                <th width="15%">Usuário</th>
                                <th width="15%">Evento</th>
                                <th width="15%">Status</th>
                                <th width="10%">Data de cadastro</th>
                                <th width="10%"></th>
							</tr>
                            <tr role="row" class="filter">
                                <?php $form->prepare(); echo $this->form()->openTag($form); ?>
                                <td>
                                    <input type="checkbox" class="icheck select-all" name="id_select_all" value="">
                                    <?php echo $this->formElement($form->get('selected')); ?>
                                </td>
                                <td><?php echo $this->formelement($form->get('id')); ?></td>
                                <td><?php echo $this->formelement($form->get('title')); ?></td>
                                <td><?php echo $this->formelement($form->get('user')); ?></td>
                                <td><?php echo $this->formelement($form->get('event')); ?></td>
                                <td><?php echo $this->formelement($form->get('status')); ?></td>
                                <td>
                                    <div class="input-group date date-picker margin-bottom-5" data-date-format="dd/mm/yyyy">
                                        <?php echo $this->formelement($form->get('dateInit')); ?>
                                        <span class="input-group-btn">
                                            <button class="btn btn-sm default" type="button">
                                                <i class="fa fa-calendar"></i>
                                            </button>
                                        </span>
                                    </div>
                                    <div class="input-group date date-picker" data-date-format="dd/mm/yyyy">
                                        <?php echo $this->formelement($form->get('dateEnd')); ?>
                                        <span class="input-group-btn">
                                            <button class="btn btn-sm default" type="button">
                                                <i class="fa fa-calendar"></i>
                                            </button>
                                        </span>
                                    </div>
                                </td>
                                <td>
                                    <div class="margin-bottom-5"><button class="btn btn-sm blue filter-submit margin-bottom"><i class="fa fa-search"></i> Pesquisar</button></div>
                                    <button class="btn btn-sm btn-default filter-cancel"><i class="fa fa-times"></i> Limpar</button>
                                </td>
                                <?php echo $this->form()->closeTag(); ?>
                            </tr>
						</thead>
						<tbody>
						<?php foreach ($this->items as $i):
							$updateUrl = $this->url('admin/default', [
                                'controller' => 'project',
								'action' => 'update',
								'id' => $i->getId()
							]);

							$removeUrl = $this->url('admin/default', [
                                'controller' => 'project',
								'action'=>'delete',
								'id'=>$i->getId()
							]);

							?>
							<tr>
                                <td><input type="checkbox" class="icheck" name="id[]" value="<?php echo $i->getId() ?>"></td>
								<td><?php echo $i->getId(); ?></td>
								<td><a href="<?php echo $updateUrl; ?>"><?php echo $i->getTitle(); ?></a></td>
                                <td><?php echo $i->getUser() ? $i->getUser()->getName() : ""; ?></td>
                                <td><?php echo $i->getEvent() ? $i->getEvent()->getShortName() : ""; ?></td>
                                <td><?php $label = \Application\Entity\Registration\Status::get($i->getStatus());
                                    echo $this->registrationStatus($i->getStatus(), $label). " ". $label; ?></td>
                                <td><?php echo $i->getCreatedAt()->format('d/m/Y H:i') ?></td>
								<td>
                                    <?php if($this->canEdit): ?>
									<a href="<?php echo  $updateUrl; ?>" class="btn btn-sm btn-default">
										<i class="fa fa-edit"></i> Editar
									</a>
									<a href="<?php echo $removeUrl; ?>" class="btn btn-sm btn-default post-list-remove">
										<i class="fa fa-trash-o"></i> Excluir
									</a>
                                    <?php else: ?>
                                        <a href="<?php echo  $updateUrl; ?>" class="btn btn-sm btn-default">
                                            <i class="fa fa-edit"></i> Visualizar
                                        </a>
                                    <?php endif; ?>
								</td>
							</tr>
						<?php endforeach; ?>
						</tbody>
					</table>

					<div class="table-paginator">
						<?php echo $this->paginationcontrol(
							$this->items,
							'sliding',
							'admin/partials/paginator.phtml',
							array(
								'route'=>'admin/default',
								'route_options' => [
                                    'controller' => 'project'
                                ],
                                'route_query_options' => array('query'=>$this->searchData)
							)
						); ?>
					</div>

				</div>
			</div>
		</div>
	</div>
</div>

<?php echo $this->partial('admin/project/_modal-status.phtml', [
    'statusModalForm' => $this->statusModalForm
]); ?>