<div class="main-wrapper main-content">
    <header class="main-header">
        <h1 class="main-title"><?php echo $this->post->getName(); ?></h1>
    </header>
    <?php $workshop = $this->post; ?>
    <p>
        <strong>Instrutor(a):</strong>
        <?php echo $workshop->getManager()->getName(); ?>
    </p>
    <p>
        <strong>Faixa etária: </strong>
        <?php
        if($workshop->getMinimumAge()) {
            if($workshop->getMaximumAge()) {
                echo "De " . $workshop->getMinimumAge() . ' a ' . $workshop->getMaximumAge() . ' anos';
            } else {
                echo "A partir de " . $workshop->getMinimumAge() . 'anos';
            }
        } elseif($workshop->getMaximumAge()) {
            echo 'Até ' . $workshop->getMaximumAge();
        } else {
            echo "Livre";
        }
        ?>
    </p>
    <p>
        <strong>Carga horária:</strong>
        <?php echo $workshop->getDuration()->format('H\hi'); ?>
    </p>
    <p>
        <b>Número de vagas:</b>
        <?php echo $workshop->getAvailableSubscriptions(); ?>
    </p>
    <p>
        <strong>Conteúdo programático:</strong> <br />
        <div><?php echo $workshop->getDescription(); ?></div>
    </p>

    <p>
        <strong>Pré-requisitos:</strong> <br />
        <div><?php echo $workshop->getRequirements(); ?></div>
    </p>

    <?php echo $this->partial("application/partials/share.phtml", ['title'=>$post->getName()]); ?>
</div>