<div class="main-wrapper main-content">
    <header class="main-header">
        <h1 class="main-title"><?php echo $post->getTitle() ?></h1>
    </header>

    <div class="news-list">
        <?php foreach ($this->workshopList as $workshop): ?>
            <article class="news-item">
                <header class="news-header" style="display: inline-block">
                    <h1 class="news-title"><?php  echo $workshop->getName(); ?></h1>
                </header>
                <p><strong><?php echo $workshop->getManager(); ?></strong></p>
                <?php if($workshop->getFile()): ?>
                    <figure class="news-figure"><img src="<?php echo $this->thumbor()->url($workshop->getFile())->resize(220, 220); ?>" alt=""></figure>
                <?php endif; ?>
                <p class="news-desc"></p>
                <a href="<?php echo $this->url("mostratiradentes/workshop", ['id'=>$workshop->getId()]) ?>" class="button-readmore">Ver maiores informações</a>
            </article>
        <?php endforeach; ?>
    </div>
</div>