<?php $workshop = $this->workshop; $registration = $this->registration; ?>

<?php $urlSub = $this->url('meu-universo/workshop', [
    'controller'=>'workshop-registration',
    'action' => 'inscricao',
    'id' => $workshop->getId(),
    'id_reg' => $registration->getHash()
]); ?>

<div style="display: none;min-width:400px;min-height: 400px" id="manager_<?php echo $workshop->getManager()->getId(); ?>">
    <?php echo $workshop->getManager()->getDescription(); ?>
</div>

<div class="portlet workshop">
    <div class="portlet-title">
        <div class="caption font-dark">
            <h2 class="main-title"><?php echo $workshop->getName() ?> </h2>
            <strong>Instrutor(a): </strong><a style="color: #000;" data-fancybox data-src="#manager_<?php echo $workshop->getManager()->getId(); ?>" data-modal="true"  href="javascript:;"><?php echo $workshop->getManager()->getName(); ?>
                <i style="margin-left: 2px; font-size: 13px;" class="icon-plus-circle"></i></a>
            <?php if($this->show_register_link): ?>
                <a style="margin-left: 15px; color: #000;" href="<?php echo $urlSub; ?>">Fazer inscrição
                    <i style="font-size: 13px;" class="icon-arrow-right4"></i>
                </a>
            <?php endif; ?>
        </div>
        <div class="tools">
            <a href="javascript:;" class="expand" data-original-title="" title=""> </a>
        </div>
    </div>
    <div class="portlet-body form portlet-collapsed">
        <p>
            <strong>Faixa etária: </strong>
            <?php
            if($workshop->getMinimumAge()) {
                if($workshop->getMaximumAge()) {
                    echo "De " . $workshop->getMinimumAge() . ' a ' . $workshop->getMaximumAge() . ' anos';
                } else {
                    echo "A partir de " . $workshop->getMinimumAge() . 'anos';
                }
            } elseif($workshop->getMaximumAge()) {
                echo 'Até ' . $workshop->getMaximumAge();
            } else {
                echo "Livre";
            }
            ?>
        </p>
        <p>
            <strong>Carga horária:</strong> <?php echo $workshop->getDuration(); ?>
        </p>
        <p>
            <b>Número de vagas:</b> <?php echo $workshop->getAvailableSubscriptions(); ?>
        </p>
        <p>
            <strong>Conteúdo programático:</strong> <br />
            <?php echo $workshop->getDescription(); ?>
        </p>

        <p>
            <strong>Pré-requisitos:</strong> <br />
            <?php echo $workshop->getRequirements(); ?>
        </p>

        <?php if($this->show_register_link): ?>
        <div class="">
            <a href="<?php echo $urlSub; ?>" class="btn green button-submit">Fazer inscrição</a>
        </div>
        <?php endif; ?>
    </div>
</div>