<?php $form = $this->form;
    $form->prepare(); ?>

<div class="container">
    <div class="col-md-12">
        <p class="meuuniverso-brand meuuniverso-brand--center"><strong>Meu</strong>Universo | Oficinas</p>
    </div>

    <div class="portlet light" id="form_wizard_1">
        <div class="portlet-body-form">
            <?php echo $this->form(null, null)->openTag($form); ?>
            <?php if($form->getMessages()): ?>
                <div class="portlet box red">
                    <div class="portlet-title">
                        <div class="caption">Atenção, os seguintes erros foram encontrados </div>
                    </div>
                    <div class="portlet-body">
                        <?php foreach ($form->getMessages() as $field=>$message): ?>
                            <h4 class="h4">Campo <?php echo $form->get($field)->getLabel(); ?></h4>
                            <div style="padding-left: 20px">
                                <?php foreach ($message as $key=>$m): ?>
                                    <p class=""><?php echo $m ?></p>
                                <?php endforeach; ?>
                            </div>
                        <?php endforeach; ?>
                    </div>
                </div>
            <?php endif; ?>

            <div class="form-wizard">
                <div class="form-body">
                    <ul class="nav nav-pills nav-justified steps">
                        <li>
                            <a href="#tab_regulation" data-toggle="tab" class="step">
                                <span class="number"> 1 </span>
                                <span class="desc"><i class="glyphicon glyphicon-ok"></i> Regulamento </span>
                            </a>
                        </li>
                        <li>
                            <a href="#tab2" data-toggle="tab" class="step">
                                <span class="number"> 2 </span>
                                <span class="desc"><i class="glyphicon glyphicon-ok"></i> Cadastro </span>
                            </a>
                        </li>
                    </ul>
                    <div id="bar" class="progress progress-striped" role="progressbar">
                        <div class="progress-bar progress-bar-success"> </div>
                    </div>
                    <div class="tab-content">
                        <div class="tab-pane active" id="tab_regulation">
                            <h3 class="h3 block">Regulamento</h3>
                            <?php echo $this->regulation($this->reg); ?>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="movie-multi-check">
                                        <?php echo $this->formRow($form->get('accept_regulation')); ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="tab-pane" id="tab2">
                            <?php echo $this->partial('meu-universo/workshop-registration/_workshop.phtml', [
                                'workshop' => $this->workshop,
                                'show_register_link' => false
                            ]); ?>
                            <?php
                                if($form->has('user')) {
                                    echo $this->formRow($form->get('user'));
                                }

                                $workshopRegisterElements = $form->get('form_answer')->getElements();
                                foreach ($workshopRegisterElements as $workshopEl) {
                                    echo $this->formRow($workshopEl);
                                }
                            ?>
                        </div>
                    </div>
                </div>
                <div class="form-actions">
                    <div class="row">
                        <div class="col-md-offset-3 col-md-9">
                            <a href="javascript:;" class="btn default button-previous">
                                <i class="glyphicon glyphicon-chevron-left"></i> Voltar </a>
                            <a href="javascript:;" class="btn btn-outline green button-next"> Continuar
                                <i class="glyphicon glyphicon-chevron-right"></i>
                            </a>
                            <button type="submit" class="btn green button-submit"> Cadastrar
                                <i class="glyphicon glyphicon-ok"></i>
                            </button>
                        </div>
                    </div>
                </div>
            </div>

            <?php echo $this->form()->closeTag(); ?>
        </div>
    </div>

</div>