<div class="row post news">
	<div class="col-md-12">

		<div class="portlet light portlet-fit bordered">
			<div class="portlet-title">
				<div class="caption">
					<?php if($this->programing->getId()): ?>
					<i class="fa fa-edit"></i>
					Editar horário
					<?php else: ?>
					<i class="fa fa-file-o"></i>
					Cadastrar horário
					<?php endif; ?>
				</div>
				<div class="actions">
					<a href="<?php echo $this->url('admin/default', ['controller'=>'workshop-programing']); ?>"
					   class="btn btn-default">
						<i class="icon-action-undo"></i>
						<span class="hidden-xs"> Voltar </span>
					</a>
                    <a href="<?php echo $this->url('admin/default', ['controller'=>'workshop-programing', 'action'=>'create']); ?>"
                       class="btn blue btn-lg">
                        <i class="fa fa-plus"></i>
                        <span class="hidden-xs"> Novo horário  </span>
                    </a>
				</div>
			</div>
			<div class="portlet-body">
                <?php $form = $this->form; ?>
                <div class="portlet">
                    <div class="portlet-body form">
                        <?php $form->prepare(); echo $this->form(null, null)->openTag($form) ?>
                        <div class="form-body">
                            <?php
                                echo $this->formRow($form->get('event'));
                                echo $this->formRow($form->get('workshop'));
                                echo $this->formRow($form->get('place'));
                                echo $this->formRow($form->get('date'));
                                echo $this->formRow($form->get('start_time'));
                                echo $this->formRow($form->get('end_time'));
                            ?>
                        </div>

                        <div class="form-actions">
                            <div class="row">
                                <div class="col-md-offset-4 col-md-9">
                                    <button type="submit" class="btn blue btn-lg action-save">Salvar</button>
                                    <a href="#" class="btn red btn-lg action cancel">Descartar</a>
                                </div>
                            </div>
                        </div>
                        <?php echo $this->form()->closeTag() ?>
                    </div>
                </div>

            </div>
		</div>

	</div>
</div>