<?php $form = $this->searchForm; ?>
<?php $form->prepare(); echo $this->form(null, null)->openTag($form) ?>
<table class="table table-striped table-bordered table-hover programing-table">
    <thead>
    <tr role="row" class="heading">
        <th width="15%">Evento</th>
        <th width="15%">Filme|Sessão</th>
        <th width="13%">Data</th>
        <th width="13%">Hora de início</th>
        <th width="13%">Hora de término</th>
        <th width="13%">Local</th>
        <th width="15%">Ações</th>
    </tr>
    <tr role="row" class="filter">
        <td><?php echo $this->formelement($form->get('event')); ?></td>
        <td><?php echo $this->formelement($form->get('movie')); ?></td>
        <td><?php echo $this->formelement($form->get('date')); ?></td>
        <td><?php echo $this->formelement($form->get('start_time')); ?></td>
        <td><?php echo $this->formelement($form->get('end_time')); ?></td>
        <td><?php echo $this->formelement($form->get('place')); ?></td>
        <td>
            <button class="btn btn-sm blue margin-bottom programing-add"><i class="fa fa-plus"></i> Pesquisar</button>
            <button class="btn btn-sm btn-default programing-clean"><i class="fa fa-times"></i> Limpar</button>
        </td>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($this->items as $i):
        $updateUrl = $this->url('admin/default', [
            'controller' => 'movie-programing',
            'action'=>'update',
            'id'=>$i->getId()
        ]);

        $removeUrl = $this->url('admin/default', [
            'controller' => 'movie-programing',
            'action'=>'delete',
            'id'=>$i->getId(),
        ]); ?>
    <tr>
        <td><?php echo $i->getEvent()->getShortName() ?></td>
        <td>
            <?php if($i->getType() == 'movie') {
                echo $i->getObject()->getTitle();
            } elseif($i->getType() == 'session' && $i->hasMeta('session_title')) {
                echo 'Sessão de Filmes: ' . $i->hasMeta('session_title')->getValue();
            } ?>
        </td>
        <td><?php echo $i->getDate()->format('d/m/Y'); ?></td>
        <td><?php echo $i->getStartTime()->format('H:i:s'); ?></td>
        <td><?php echo $i->getEndTime() ? $i->getEndTime()->format('H:i:s') : ""; ?></td>
        <td><?php echo $i->getPlace()?$i->getPlace()->getName():""; ?></td>
        <td>
            <a href="<?php echo  $updateUrl; ?>" class="btn btn-sm btn-default">
                <i class="fa fa-edit"></i> Editar
            </a>
            <a href="<?php echo $removeUrl; ?>" class="btn btn-sm btn-default post-list-remove">
                <i class="fa fa-close"></i> Excluir
            </a>
        </td>
    </tr>
    <?php endforeach; ?>
    </tbody>
    </table>
<?php echo $this->form()->closeTag(); ?>