<?php if($post->getMeta('_cover')) $this->placeholder("is_header_dark")->set(true); ?>
<div class="<?php echo $post->getMeta('_cover') ? 'main-bg' : 'main-no-bg'; ?>"
               style="<?php echo $post->getMeta('_cover') ? 'background-image:url('.$post->getMeta('_cover').')' : ''; ?>">
    <header class="main-header">
        <div class="main-wrapper">
            <h1 class="main-title"><?php echo $post->getTitle(); ?></h1>
        </div>
    </header>
</div>

<section class="main-section">
    <div class="main-wrapper">
        <div class="main-content">

            <?php if($post->getSubtitle()): ?>
                <h2><?php echo $post->getSubtitle(); ?></h2>
            <?php endif; ?>

            <?php echo $this->shortcode($this->thumborize($post->getContent())); ?>

            <div class="share">
                <span class="share-title">Compartilhe:</span>
                <ul class="share-items">
                    <li class="share-item"><a href="http://www.facebook.com/share.php?u=<?php echo $this->serverUrl(true) ?>&display=popup&title=<?php echo $post->getTitle(); ?>" class="share-link"><span class="icon-facebook"></span></a></li>
                    <li class="share-item"><a href="https://twitter.com/intent/tweet?status=<?php echo $post->getTitle(); ?>+<?php echo $this->serverUrl(true) ?>" class="share-link"><span class="icon-twitter"></span></a></li>
                </ul>
            </div>

            <div class="main-separator"></div>
        </div>
    </div>
</section>