<?php if($post->getMeta('_cover')) $this->placeholder("is_header_dark")->set(true); ?>
<div class="<?php echo $post->getMeta('_cover') ? 'main-bg' : 'main-no-bg'; ?>"
     style="<?php echo $post->getMeta('_cover') ? 'background-image:url('.$post->getMeta('_cover').')' : ''; ?>">
    <header class="main-header">
        <div class="main-wrapper">
            <h1 class="main-title">Newsletter</h1>
        </div>
    </header>
</div>

<section class="main-section">
    <div class="main-wrapper">
        <div class="main-content">
            <p>Cadastro realizado com sucesso!</p>

            <div class="main-separator"></div>
        </div>
    </div>
</section>