<div class="main-no-bg">
    <header class="main-header">
        <div class="main-wrapper">
            <h1 class="main-title">Newsletter</h1>
        </div>
    </header>
</div>

<section class="main-section">
    <div class="main-wrapper">
        <div class="main-content">
            <p>Cadastro realizado com sucesso!</p>
            <div class="main-separator"></div>
        </div>
    </div>
</section>