<?php if($post->getCover()): ?>
    <div class="site__cover">
        <img src="<?php echo $post->getCover() ?>" alt="">
    </div>
<?php endif; ?>

<?php if($this->breadcrumbs): ?>
    <?php echo $this->partial('arquivoemcartaz/partials/_breadcrumbs.phtml', ['breadcrumbs'=>$this->breadcrumbs]); ?>
<?php endif; ?>

<main class="main">
    <div class="main__wrapper">
        <section class="main__section">
            <header class="main__header">
                <h1 class="main__title"><?php echo $post->getTitle(); ?></h1>
            </header>

            <div class="news__list">
                <?php foreach ($this->newsList as $news): ?>
                    <article class="news__item">
                        <a class="news__link" href="">
                            <header class="news__header"><h1 class="news__title"><?php echo $news->getTitle(); ?></h1></header>
                            <?php if($news->getThumb()): ?>
                                <figure class="news__figure"><img src="<?php echo $this->thumbor()->url($news->getThumb())->resize(240, 160); ?>" alt=""></figure>
                            <?php endif; ?>
                            <div class="news__content">
                                <p class="news__intro">
                                    <?php  echo $this->truncate($news->getContent(), 350); ?>
                                    <a href="<?php echo $this->url('arquivoemcartaz/news', ['slug'=>$news->getSlug()]) ?>" class="circle-link"><span class="icon icon-arrow-right8"></span></a></p>
                            </div>
                        </a>
                    </article>
                <?php endforeach; ?>
            </div>

            <?php echo $this->paginationcontrol(
                $this->newsList,
                'sliding',
                'application/partials/paginator.phtml',
                array(
                    'route'=>'arquivoemcartaz/default',
                    'route_options' => array('slug'=>'noticias'))); ?>
        </section>
    </div>
</main>