<?php
    $this->headMeta()->setProperty('og:title', $post->getTitle());
    if($post->getThumb()) {
        $this->headMeta()->setProperty('og:image', $post->getThumb());
    } ?>

<?php if($post->getCover()): ?>
    <div class="site__cover">
        <img src="<?php echo $post->getCover() ?>" alt="">
    </div>
<?php endif; ?>

<div class="site__breadcrumbs">
    <div class="site__breadcrumbs-wrapper">
        <ul class="breadcrumb">
            <li class="breadcrumb__item"><a class="breadcrumb__link" href="">Inicio</a></li>
            <li class="breadcrumb__item"><a class="breadcrumb__link" href="">Inicio</a></li>
        </ul>
    </div>
</div>

<main class="main">
    <div class="main__wrapper">
        <section class="main__section">
            <header class="main__header">
                <!--<time class="main__time"><?php /*echo strftime('%A, %d de %B de %Y, às %Hh%M', $post->getPostDate()->getTimestamp()); */?></time>-->
                <time class="main__time"><?php echo $this->dateFormat($post->getPostDate(), null, null, "pt_BR", "cccc, d 'de' MMMM Y', às' HH'h'mm"); ?></time>
                <h1 class="main__title"><?php echo $post->getTitle(); ?></h1>
            </header>
            <h2 class="main__subtitle"><?php echo $post->getSubtitle(); ?></h2>

            <?php echo $post->getContent(); ?>

            <?php echo $this->partial("application/partials/share.phtml", ['title'=>$post->getTitle()]); ?>

        </section>
    </div>
</main>