<?php
    $this->headMeta()->setProperty('og:title', $post->getTitle());
    if($post->getThumb()) {
        $this->headMeta()->setProperty('og:image', $post->getThumb());
    } ?>

<?php if($post->hasMeta('_cover')): ?>
    <div class="site__cover">
        <img src="<?php echo $post->getMeta('_cover') ?>" alt="">
    </div>
<?php endif; ?>

<?php if($this->breadcrumbs): ?>
    <?php echo $this->partial('arquivoemcartaz/partials/_breadcrumbs.phtml', ['breadcrumbs'=>$this->breadcrumbs]); ?>
<?php endif; ?>

<main class="main">
    <div class="main__wrapper">
        <section class="main__section">
            <header class="main__header">
                <time class="main__time"><?php echo $this->dateFormat($post->getPostDate(), null, null, "pt_BR", "cccc, d 'de' MMMM Y', às' HH'h'mm"); ?></time>
                <h1 class="main__title"><?php echo $post->getTitle(); ?></h1>
            </header>
            <h2 class="main__subtitle"><?php echo $post->getSubtitle(); ?></h2>

            <?php echo $this->thumborize($post->getContent()); ?>

            <?php echo $this->partial("application/partials/share.phtml", ['title'=>$post->getTitle()]); ?>

        </section>
    </div>
</main>