<?php if($post->getCover()): ?>
    <div class="site__cover">
        <img src="<?php echo $post->getCover() ?>" alt="">
    </div>
<?php endif; ?>

<div class="site__breadcrumbs">
    <div class="site__breadcrumbs-wrapper">
        <ul class="breadcrumb">
            <li class="breadcrumb__item"><a class="breadcrumb__link" href="">Inicio</a></li>
            <li class="breadcrumb__item"><a class="breadcrumb__link" href="">Inicio</a></li>
        </ul>
    </div>
</div>

<main class="main">
    <div class="main__wrapper">
        <section class="main__section">
            <header class="main__header">
                <time class="main__time">terça-feira, 9 de setembro de 2016, às 12h05</time>
                <h1 class="main__title"><?php echo $post->getTitle(); ?></h1>
            </header>
            <h2 class="main__subtitle"><?php echo $post->getSubtitle(); ?></h2>

            <?php echo $post->getContent(); ?>

            <div class="share">
                <ul class="share__list">
                    <li class="share__item share__item--title">
                        <span>Compartilhe</span>
                    </li>
                    <li class="share__item">
                        <a class="share__link" href=""><span class="icon icon-facebook"></span></a>
                    </li>
                    <li class="share__item">
                        <a class="share__link" href=""><span class="icon icon-twitter"></span></a>
                    </li>
                </ul>
            </div>

        </section>
    </div>
</main>