<div class="portlet light bordered page-gallery"
	 data-url="<?php echo $this->url('admin/banner', ['site'=>$site, 'action'=>'add-item' ]); ?>"
	 data-input="#returnResponsivefilemanager">
	<div class="portlet-title">
		<div class="caption">
			<i class="fa fa-edit"></i>
			Imagens Destaque
		</div>

		<div class="actions">
			<a href="#" class="btn btn-default">
				<i class="icon-action-undo"></i>
				<span class="hidden-xs"> Voltar </span>
			</a>
		</div>
	</div>
	<div class="portlet-body">
		<div class="table-container post-list">
			<table class="table table-striped table-bordered table-hover">
				<thead>
				<tr role="row" class="heading">
					<th width="2%">#</th>
					<th width="8%">Imagem</th>
					<th width="30%">Título</th>
					<th width="15%">Data de Exibição</th>
					<th width="10%">Ações</th>
				</tr>
				</thead>
				<tbody>
				<?php foreach ($this->items as $item):
					$updateUrl = $this->url('admin/banner', [
						'action'=>'update',
						'id'=>$item->getId(),
						'site' => $site
					]);
					$removeUrl = $this->url('admin/banner', [
						'action'=>'delete',
						'id'=>$item->getId(),
						'site' => $site
					]);
					?>
					<tr>
						<td></td>
						<td>
							<a href="<?php echo $item->getFile(); ?>" class="fancybox-button" data-rel="fancybox-button"><img width="150px" class="img-responsive" src="<?php echo str_replace('source', 'thumbs', $item->getFile()) ?>"</a>
						</td>
						<td><a href="<?php echo $updateUrl; ?>"><?php echo $item->getTitle(); ?></a></td>
						<td>
							<?php echo $item->getStartDate()
								? $item->getStartDate()->format('d/m/Y') : "(...)" ?> à
							<?php echo $item->getEndDate()
								? $item->getEndDate()->format('d/m/Y') : "(...)" ?>
						<td>
							<a href="<?php echo  $updateUrl; ?>" class="btn btn-sm btn-default">
								<i class="fa fa-edit"></i> Editar
							</a>
							<a href="<?php echo $removeUrl; ?>" class="btn btn-sm btn-default post-list-remove">
								<i class="fa fa-close"></i> Excluir
							</a>
						</td>
					</tr>
				<?php endforeach; ?>
				</tbody>
			</table>

			<div class="table-paginator">
				<?php echo $this->paginationcontrol($this->items, 'sliding', 'admin/partials/paginator.phtml'); ?>
			</div>
		</div>
	</div>
</div>


