<?php $form = $this->searchForm; ?>

<div class="row">
	<div class="col-md-12">
		<div class="portlet light portlet-fit portlet-datatable bordered">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-th-list"></i>
					Lista de Usuários
				</div>
				<div class="actions">
					<a href="<?php echo $this->url('admin/default', ['controller'=>'admin-user', 'action'=>'create']); ?>"
					   class="btn blue btn-lg">
						<i class="fa fa-plus"></i>
						<span class="hidden-xs"> Inserir Usuário </span>
					</a>
					<div class="btn-group">
						<a class="btn btn-default dropdown-toggle" href="javascript:;" data-toggle="dropdown">
							<i class="fa fa-share"></i>
							<span class="hidden-xs"> Opções </span>
							<i class="fa fa-angle-down"></i>
						</a>
						<div class="dropdown-menu pull-right">
							<li><a href="javascript:;"> Exportar para Excel </a></li>
							<li><a href="javascript:;"> Exportar para PDF </a></li>
							<li class="divider"></li>
							<li><a href="javascript:;"> Imprimir </a></li>
						</div>
					</div>
				</div>
			</div>

			<div class="portlet-body">
				<div class="table-container post-list">
					<table class="table table-striped table-bordered table-hover">
						<thead>
						<tr role="row" class="heading">
							<th width="2%">#</th>
							<th width="30%">Nome</th>
							<th width="30%">Email</th>
							<th width="15%">Administrador</th>
							<th width="10%">Ações</th>
						</tr>
						<tr role="row" class="filter">
							<?php $form->prepare(); echo $this->form()->openTag($form); ?>
							<td></td>
							<td><?php echo $this->formelement($form->get('name')); ?></td>
							<td><?php echo $this->formelement($form->get('email')); ?></td>
							<td><?php echo $this->formelement($form->get('is_administrator')); ?></td>
							<td>
								<div class="margin-bottom-5">
									<button class="btn btn-sm blue filter-submit margin-bottom"><i class="fa fa-search"></i> Pesquisar</button>
								</div>
								<button class="btn btn-sm btn-default filter-cancel"><i class="fa fa-times"></i> Limpar</button>
							</td>
							<?php echo $this->form()->closeTag(); ?>
						</tr>
						</thead>
						<tbody>
						<?php foreach ($this->users as $user):
							$updateUrl = $this->url('admin/default', [
								'controller' => 'admin-user',
								'action'=>'update',
								'id'=>$user->getId()
							]);

							$removeUrl = $this->url('admin/default', [
								'controller' => 'admin-user',
								'action'=>'delete',
								'id'=>$user->getId(),
							]);
							?>
							<tr>
								<td></td>
								<td><a href="<?php echo $updateUrl; ?>"><?php echo $user->getName(); ?></a></td>
								<td><?php echo $user->getEmail(); ?></td>
								<td>
									<?php if($user->isAdministrator()): ?>
										<span class="label label-info"><i class="fa fa-check" ></i> Administrador </span>
									<?php endif; ?>
								</td>
								<td>
									<a href="<?php echo  $updateUrl; ?>" class="btn btn-sm btn-default">
										<i class="fa fa-edit"></i> Editar
									</a>
									<a href="<?php echo $removeUrl; ?>" class="btn btn-sm btn-default post-list-remove">
										<i class="fa fa-close"></i> Excluir
									</a>
								</td>
							</tr>
						<?php endforeach; ?>
						</tbody>
					</table>
					<div class="table-paginator">
						<?php echo $this->paginationcontrol($this->users, 'sliding', 'admin/partials/paginator.phtml'); ?>
					</div>

				</div>
			</div>
		</div>
	</div>
</div>