<div class="row">
	<div class="col-md-12">
		<div class="portlet light portlet-fit portlet-datatable bordered">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-th-list"></i>
					Destaques da Programação
				</div>
				<div class="actions">
					<a href="<?php echo $this->url('admin/programation', ['site'=>$this->site, 'action'=>'create']); ?>"
					   class="btn blue btn-lg">
						<i class="fa fa-plus"></i>
						<span class="hidden-xs"> Novo Destaque </span>
					</a>
					<div class="btn-group">
						<a class="btn btn-default dropdown-toggle" href="javascript:;" data-toggle="dropdown">
							<i class="fa fa-share"></i>
							<span class="hidden-xs"> Opções </span>
							<i class="fa fa-angle-down"></i>
						</a>
						<div class="dropdown-menu pull-right">
							<li><a href="javascript:;"> Exportar para Excel </a></li>
							<li><a href="javascript:;"> Exportar para PDF </a></li>
							<li class="divider"></li>
							<li><a href="javascript:;"> Imprimir </a></li>
						</div>
					</div>
				</div>
			</div>

			<div class="portlet-body">
				<div class="table-container post-list">
					<table class="table table-striped table-bordered table-hover">
						<thead>
							<tr role="row" class="heading">
								<th width="2%">#</th>
								<th width="10%">Data</th>
								<th width="10%">Hora</th>
								<th width="25%">Título</th>
								<th width="25%">Subtítulo</th>
								<th width="7%">Posição</th>
								<th width="10%">Destaque Principal</th>
								<th></th>
							</tr>
						</thead>
						<tbody>
						<?php foreach ($this->items as $item):
							$updateUrl = $this->url('admin/programation', [
								'action' => 'update',
								'id' => $item->getId(),
								'site' => $this->site
							]);

							$removeUrl = $this->url('admin/programation', [
								'action' => 'delete',
								'id' => $item->getId(),
								'site' => $this->site
							]);
							?>
							<tr>
								<td></td>
								<td><a href="<?php echo $updateUrl; ?>"><?php echo $item->getDate()->format('d/m/Y'); ?></a></td>
								<td><?php echo $item->getHour(); ?></td>
								<td><?php echo $item->getTitle(); ?></td>
								<td><?php echo $item->getSubtitle(); ?></td>
								<td><?php echo $item->getPosition(); ?></td>
								<td><?php if($item->getIsHighlight()): ?><span class="label label-success">Destaque</span><?php endif; ?></td>
								<td>
									<a href="<?php echo  $updateUrl; ?>" class="btn btn-sm btn-default">
										<i class="fa fa-edit"></i> Editar
									</a>
									<a href="<?php echo $removeUrl; ?>" class="btn btn-sm btn-default post-list-remove">
										<i class="fa fa-trash-o"></i> Lixeira
									</a>
								</td>
							</tr>
						<?php endforeach; ?>
						</tbody>
					</table>
					<div class="table-paginator">
						<?php echo $this->paginationcontrol($this->items, 'sliding', 'admin/partials/paginator.phtml'); ?>
					</div>

				</div>
			</div>
		</div>
	</div>
</div>