<main class="main">
    <?php if($this->breadcrumbs): ?>
        <?php echo $this->partial('cineop2017/partials/_breadcrumbs.phtml', ['breadcrumbs'=>$this->breadcrumbs]); ?>
    <?php endif; ?>

    <div class="main-wrapper">
        <section class="main-content">
            <header class="main-header">
                <h1 class="main-title"><?php echo $this->post->getTitle(); ?></h1>
            </header>

            <?php if($this->post->getSubtitle()): ?>
                <h2><?php $this->post->getSubtitle(); ?></h2>
            <?php endif; ?>

            <div class="news">
                <div class="news-highlight">
                    <?php foreach ($this->newsList as $news): ?>
                        <article class="news-featured">
                            <div class="news-wrapper">
                                <a href="<?php echo $this->url("cineop2017/news", ['slug'=>$news->getSlug()]) ?>" class="news-link">
                                    <div class="news-bg">
                                        <figure class="news-figure">
                                            <img src="<?php echo  $this->thumbor()->url($news->getMeta('_thumb'))->resize(240, 240); ?>" alt="">
                                        </figure>
                                    </div>
                                    <p class="news-title"><?php echo $news->getTitle(); ?></p>
                                    <p class="news-subtitle"><?php echo $news->getSubtitle(); ?></p>
                                    <p class="news-seemore">Veja +</p>
                                </a>
                            </div>
                        </article>
                    <?php endforeach; ?>
                </div>
            </div>
        </section>
    </div>
</main>