<main class="main">
    <div class="breadcrumbs">
        <ul class="breadcrumbs-items">
            <li class="breadcrumbs-item"><a class="breadcrumbs-link" href="">Home</a></li>
            <li class="breadcrumbs-item"><a class="breadcrumbs-link" href="">12ª Cineop</a></li>
        </ul>
    </div>

    <div class="main-wrapper">
        <section class="main-content">
            <header class="main-header">
                <h1 class="main-title"><?php echo $this->post->getTitle(); ?></h1>
            </header>

            <?php if($this->post->getSubtitle()): ?>
                <h2><?php $this->post->getSubtitle(); ?></h2>
            <?php endif; ?>

            <?php echo $this->thumborize($post->getContent()); ?>
        </section>
    </div>
</main>