<?php $form = $this->form; ?>
<div class="row post news">
	<div class="col-md-12">
		<?php $form->prepare(); echo $this->form(null, null)->openTag($form) ?>
		<div class="portlet light portlet-fit bordered">
			<div class="portlet-title">
				<div class="caption">
					<?php if($this->event->getId()): ?>
					<i class="fa fa-edit"></i>
					Cadastrar Mostra
					<?php else: ?>
					<i class="fa fa-file-o"></i>
					Editar Mostra
					<?php endif; ?>
				</div>
				<div class="actions">
					<a href="<?php echo $this->url('admin/default', ['controller'=>'event']); ?>"
					   class="btn btn-default">
						<i class="icon-action-undo"></i>
						<span class="hidden-xs"> Voltar </span>
					</a>
				</div>
			</div>
			<div class="portlet-body">
				<div class="portlet">
					<div class="portlet-body form">
						<div class="form-body">
                            <?php echo $this->formRow($form->get('full_name')); ?>
                            <?php echo $this->formRow($form->get('short_name')); ?>
                            <?php echo $this->formRow($form->get('edition')); ?>
							<div class="form-group">
								<label class="control-label col-md-3" for=""><?php echo $form->get('start_date')->getLabel(); ?></label>
								<div class="col-md-4">
									<div class="input-group date date-picker" data-date-format="dd/mm/yyyy">
										<?php echo $this->formelement($form->get('start_date')); ?>
										<span class="input-group-btn">
											<button class="btn default" type="button">
												<i class="fa fa-calendar"></i>
											</button>
										</span>
									</div>
								</div>
							</div>
							<div class="form-group">
								<label class="control-label col-md-3" for=""><?php echo $form->get('end_date')->getLabel(); ?></label>
								<div class="col-md-4">
									<div class="input-group date date-picker" data-date-format="dd/mm/yyyy">
										<?php echo $this->formelement($form->get('end_date')); ?>
										<span class="input-group-btn">
											<button class="btn default" type="button">
												<i class="fa fa-calendar"></i>
											</button>
										</span>
									</div>
								</div>
							</div>

                            <?php echo $this->formRow($form->get('type')); ?>
                            <?php echo $this->formRow($form->get('default')); ?>
                            <?php echo $this->formRow($form->get('places')); ?>
                            <?php echo $this->formRow($form->get('sub_events')); ?>
                            <?php echo $this->formRow($form->get('description')); ?>
						</div>

						<div class="form-actions">
							<div class="row">
								<div class="col-md-offset-3 col-md-9">
									<button type="submit" class="btn blue btn-lg action-save">Salvar</button>
									<a href="#" class="btn red btn-lg action cancel">Descartar</a>
								</div>
							</div>
						</div>

					</div>
				</div>
			</div>
		</div>
		<?php echo $this->form()->closeTag() ?>
	</div>
</div>