<?php $form = $this->searchForm; ?>
<div class="row">
	<div class="col-md-12">
		<div class="portlet light portlet-fit portlet-datatable bordered">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-th-list"></i>
					Lista de Mostras
				</div>
				<div class="actions">
					<a href="<?php echo $this->url('admin/event', ['action'=>'create']); ?>"
					   class="btn blue btn-lg">
						<i class="fa fa-plus"></i>
						<span class="hidden-xs"> Cadastrar Mostra </span>
					</a>
					<div class="btn-group">
						<a class="btn btn-default dropdown-toggle" href="javascript:;" data-toggle="dropdown">
							<i class="fa fa-share"></i>
							<span class="hidden-xs"> Opções </span>
							<i class="fa fa-angle-down"></i>
						</a>
						<div class="dropdown-menu pull-right">
							<li><a href="javascript:;"> Exportar para Excel </a></li>
							<li><a href="javascript:;"> Exportar para PDF </a></li>
							<li class="divider"></li>
							<li><a href="javascript:;"> Imprimir </a></li>
						</div>
					</div>
				</div>
			</div>

			<div class="portlet-body">
				<div class="table-container post-list">
					<table class="table table-striped table-bordered table-hover">
						<thead>
							<tr role="row" class="heading">
								<th width="2%">#</th>
								<th width="15%">Nome</th>
                                <th width="10%">Tipo</th>
                                <th width="10%">Edição</th>
                                <th width="10%">Data</th>
								<th width="10%">Ações</th>
							</tr>
                            <tr role="row" class="filter">
                                <?php $form->prepare(); echo $this->form()->openTag($form); ?>
                                <td></td>
                                <td><?php echo $this->formelement($form->get('fullName')); ?></td>
                                <td><?php echo $this->formelement($form->get('type')); ?></td>
                                <td><?php echo $this->formelement($form->get('edition')); ?></td>
                                <td>
                                    <div class="input-group date date-picker margin-bottom-5" data-date-format="dd/mm/yyyy">
                                        <?php echo $this->formelement($form->get('startDate')); ?>
                                        <span class="input-group-btn">
												<button class="btn btn-sm default" type="button">
													<i class="fa fa-calendar"></i>
												</button>
											</span>
                                    </div>
                                    <div class="input-group date date-picker" data-date-format="dd/mm/yyyy">
                                        <?php echo $this->formelement($form->get('endDate')); ?>
                                        <span class="input-group-btn">
												<button class="btn btn-sm default" type="button">
													<i class="fa fa-calendar"></i>
												</button>
											</span>
                                    </div>
                                </td>
                                <td>
                                    <div class="margin-bottom-5">
                                        <button class="btn btn-sm blue filter-submit margin-bottom"><i class="fa fa-search"></i> Pesquisar</button>
                                    </div>
                                    <button class="btn btn-sm btn-default filter-cancel"><i class="fa fa-times"></i> Limpar</button>
                                </td>
                                <?php echo $this->form()->closeTag(); ?>
                            </tr>
						</thead>
						<tbody>
						<?php foreach ($this->events as $event):
							$updateUrl = $this->url('admin/event', [
								'action'=>'update',
								'id'=>$event->getId()
							]);

							$removeUrl = $this->url('admin/event', [
								'action'=>'delete',
								'id'=>$event->getId()
							]);
							?>
							<tr>
								<td></td>
								<td>
                                    <a href="<?php echo $updateUrl; ?>"><?php echo $event->getShortName(); ?></a>
                                    <?php if($event->getDefault()): ?>
                                        <span class="label label-success"> <i class="fa fa-check"></i> </span>
                                    <?php endif; ?>
                                </td>
                                <td><?php echo \Application\Entity\Event\EventType::get($event->getType()); ?></td>
                                <td><?php echo $event->getEdition(); ?></td>
                                <td>
                                    <?php echo $event->getStartDate() ? $event->getStartDate()->format('d/m/Y') : ""; ?> à
                                    <?php echo $event->getEndDate() ? $event->getEndDate()->format('d/m/Y') : ""; ?>
                                </td>
								<td>
									<a href="<?php echo  $updateUrl; ?>" class="btn btn-sm btn-default">
										<i class="fa fa-edit"></i> Editar
									</a>
									<a href="<?php echo $removeUrl; ?>" class="btn btn-sm btn-default post-list-remove">
										<i class="fa fa-trash-o"></i> Excluir
									</a>

								</td>
							</tr>
						<?php endforeach; ?>
						</tbody>
					</table>

					<div class="table-paginator">
						<?php echo $this->paginationcontrol(
							$this->events,
							'sliding',
							'admin/partials/paginator.phtml',
							array(
								'route'=>'admin/event',
								'route_options' => []
							)
						); ?>
					</div>

				</div>
			</div>
		</div>
	</div>
</div>