<?php //$form = $this->searchForm; ?>
<div class="row">
	<div class="col-md-12">
		<div class="portlet light portlet-fit portlet-datatable bordered">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-th-list"></i>
					Lista de Mostras
				</div>
				<div class="actions">
					<a href="<?php echo $this->url('admin/event', ['action'=>'create']); ?>"
					   class="btn blue btn-lg">
						<i class="fa fa-plus"></i>
						<span class="hidden-xs"> Cadastrar Mostra </span>
					</a>
					<div class="btn-group">
						<a class="btn btn-default dropdown-toggle" href="javascript:;" data-toggle="dropdown">
							<i class="fa fa-share"></i>
							<span class="hidden-xs"> Opções </span>
							<i class="fa fa-angle-down"></i>
						</a>
						<div class="dropdown-menu pull-right">
							<li><a href="javascript:;"> Exportar para Excel </a></li>
							<li><a href="javascript:;"> Exportar para PDF </a></li>
							<li class="divider"></li>
							<li><a href="javascript:;"> Imprimir </a></li>
						</div>
					</div>
				</div>
			</div>

			<div class="portlet-body">
				<div class="table-container post-list">
					<table class="table table-striped table-bordered table-hover">
						<thead>
							<tr role="row" class="heading">
								<th width="2%">#</th>
								<th width="15%">Nome</th>
								<th width="15%">Data de Início</th>
								<th width="15%">Data de Término</th>
								<th width="10%">Edição</th>
								<th width="10%">Ações</th>
							</tr>
						</thead>
						<tbody>
						<?php foreach ($this->events as $event):
							$updateUrl = $this->url('admin/event', [
								'action'=>'update',
								'id'=>$event->getId()
							]);

							$removeUrl = $this->url('admin/event', [
								'action'=>'delete',
								'id'=>$event->getId()
							]);
							?>
							<tr>
								<td></td>
								<td><a href="<?php echo $updateUrl; ?>"><?php echo $event->getShortName(); ?></a></td>
								<td><?php echo $event->getStartDate() ? $event->getStartDate()->format('d/m/Y') : ""; ?></td>
								<td><?php echo $event->getEndDate() ? $event->getEndDate()->format('d/m/Y') : ""; ?></td>
								<td><?php echo $event->getEdition(); ?></td>
								<td>
									<a href="<?php echo  $updateUrl; ?>" class="btn btn-sm btn-default">
										<i class="fa fa-edit"></i> Editar
									</a>
									<a href="<?php echo $removeUrl; ?>" class="btn btn-sm btn-default post-list-remove">
										<i class="fa fa-trash-o"></i> Excluir
									</a>

								</td>
							</tr>
						<?php endforeach; ?>
						</tbody>
					</table>

					<div class="table-paginator">
						<?php echo $this->paginationcontrol(
							$this->events,
							'sliding',
							'admin/partials/paginator.phtml',
							array(
								'route'=>'admin/event',
								'route_options' => []
							)
						); ?>
					</div>

				</div>
			</div>
		</div>
	</div>
</div>