<!--<div class="breadcrumbs">-->
<!--	<ul class="breadcrumbs__list">-->
<!--		<li class="breadcrumbs__list-item"><a class="breadcrumbs__link" href="--><?php //echo $this->url('cineop') ?><!--">Página Inicial</a></li>-->
<!--		<li class="breadcrumbs__list-item"><a class="breadcrumbs__link" href="">Notícias</a></li>-->
<!--	</ul>-->
<!--</div>-->


<?php
try {
    //$pdo = new \PDO('mysql:host=localhost;dbname=universoprod2', "root", "root", array(PDO::MYSQL_ATTR_INIT_COMMAND => "SET NAMES utf8"));
    $pdo = new \PDO('mysql:host=162.243.253.29;dbname=universoprod2', "universoprod2", "ag51www", array(PDO::MYSQL_ATTR_INIT_COMMAND => "SET NAMES utf8"));
    $pdo->setAttribute(\PDO::ATTR_ERRMODE, \PDO::ERRMODE_EXCEPTION);
} catch(\Exeception $e) {
    echo 'ERROR: ' . $e->getMessage();
    exit;
}
//$dbh=mysql_connect ("127.0.0.1", "root", "");
function databr($valor)
{
	$valor = substr($valor,8,2) . "/" . substr($valor,5,2) . "/" . substr($valor,0,4);
	return $valor;
}

function databr2($valor)
{
	$valor = substr($valor,8,2) . "." . substr($valor,5,2) . "." . substr($valor,0,4);
	return $valor;
}

function data_USA($valor1){
	$valor1 = substr($valor1,6,4) . "-" . substr($valor1,3,2) . "-" . substr($valor1,0,2);
	return $valor1;
}
function hora($valor)
{
	if ($valor == '00:00:00') {
		$texto = "";
	} else {
		$texto = date('H:i', strtotime($valor));
		$texto = str_replace(':','h',$texto);
		$texto = str_replace('h00','h',$texto);
	}
	return $texto;
}
function formata_data_extenso($strDate)
{
	// Array com os dia da semana em português;
	$arrDaysOfWeek = array('domingo', 'segunda', 'terça', 'quarta', 'quinta', 'sexta', 'sábado');
	// Array com os meses do ano em português;
	$arrMonthsOfYear = array(1 => '01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12');
	// Descobre o dia da semana
	$intDayOfWeek = date('w',strtotime($strDate));
	// Descobre o dia do mês
	$intDayOfMonth = date('d',strtotime($strDate));
	// Descobre o mês
	$intMonthOfYear = date('n',strtotime($strDate));
	// Descobre o ano
	$intYear = date('Y',strtotime($strDate));
	// Formato a ser retornado
	return $arrDaysOfWeek[$intDayOfWeek];
}
function is_utf8($str)
{
	$c=0; $b=0;
	$bits=0;
	$len=strlen($str);
	for($i=0; $i<$len; $i++)
	{
		$c=ord($str[$i]);
		if($c > 128)
		{
			if(($c >= 254)) return false;
			elseif($c >= 252) $bits=6;
			elseif($c >= 248) $bits=5;
			elseif($c >= 240) $bits=4;
			elseif($c >= 224) $bits=3;
			elseif($c >= 192) $bits=2;
			else return false;
			if(($i+$bits) > $len) return false;
			while($bits > 1)
			{
				$i++;
				$b=ord($str[$i]);
				if($b < 128 || $b > 191) return false;
				$bits--;
			}
		}
	}
	return true;
}

function utf8($string)
{
	if (is_utf8($string))
	{
		return $string;
	} else {
		return utf8_encode($string);
	}
}

$mostra = 1076;
$lg = '';
$url = '';
$fc = $fl = $sub = $subMostra = $fSub1 = $fSub2 = $fSub3 = '';
//$limitCurta = 0;
$Dir = "Direção";


$CodArte	= $this->arteId;
$result		= $pdo->query("SELECT * FROM tb_arte WHERE CodArte = '$CodArte'");

$resultArte = $result->fetchObject();

$TituloArte	= $resultArte->TitArte;
$Cat		= $resultArte->CodCatArte;
$DescArte	= $resultArte->DescArte;


$ImgArte		= $resultArte->ImgArte;
$caminhoFoto = "http://www.cinemasemfronteiras.com.br/admin/mostra_tiradentes/imagens/artes/".$ImgArte;


$titPagInt = "Arte > ".$TituloArte;

?>


<main class="main">
    <?php if($this->breadcrumbs): ?>
        <?php echo $this->partial('cineop2017/partials/_breadcrumbs.phtml', ['breadcrumbs'=>$this->breadcrumbs]); ?>
    <?php endif; ?>

    <div class="main-wrapper">
        <section class="main-content">
            <header class="main-header">
                <h1 class="main-title"><?php echo $TituloArte?></h1>
            </header>

            <?php if ($ImgArte != "") { ?>
                <div class="fotoRight">
                    <div class="imgFoto">
                        <img src="show_image_full.php?filename=<?php echo $caminhoFoto?>&width=200&height=200" alt="<?php echo utf8($NomeOp)?>" border="0" />

                    </div>
                </div>
            <?php } ?>


            <?php echo $DescArte?>
            <?php
            $resultProg  = $pdo->query("SELECT CodItemProg, CategoriaProg, Local, Data, HoraManhaInicial FROM tb_programacaoevento WHERE CodItemProg = $CodArte AND CategoriaProg = 'AR'");
            $resultProgFetch = $resultProg->fetchAll(PDO::FETCH_OBJ);
            $linhas = count($resultProgFetch);
            if ( $linhas > 0 ){
                if ( $linhas == 1 ){

                    $resultProgFetch = $resultProgFetch[0];

                    $horaArte = $resultProgFetch->HoraManhaInicial;
                    if ($horaArte == '24:30:00'){
                        $hora = "00h30";
                    } else {
                        if ($lg=='Ing'){
                            $hora = horaIng($horaArte);
                        } else {
                            $hora = hora($horaArte);
                        }
                    }

                    $dataOrig = $resultProgFetch->Data;
                    $data = databr($dataOrig);
                    $data2 = explode("/", $data);
                    if ($lg=='Ing'){
                        $dataFinal = $data2[1]."-".$data2[0];
                        $diaSemana = utf8(formata_data_extensoIng(".$dataOrig."));
                    } else {
                        $dataFinal = $data2[0]."/".$data2[1];
                        $diaSemana = utf8(formata_data_extenso(".$dataOrig."));
                    }


                    $local = $resultProgFetch->Local;
                    if ($local != "") {
                        $SqlLoc = "SELECT TitLocal, TitLocalIng FROM tb_local WHERE CodLocal = $local";
                        $resultLoc  = $pdo->query($SqlLoc);
                        $resultLoc = $resultLoc->fetchObject();
                        if ( $resultLoc ){
                            $local	= $resultLoc->TitLocal;
                        }
                    }
                    ?>
                    <p>&nbsp;</p>
                    <p><?php echo $lg=='Ing' ? "EXIBITION" : "PROGRAMAÇÃO"; ?>:<br />
                        <?php echo $dataFinal?> | <?php echo $diaSemana?><br />
                        <?php echo $hora?><br />
                        <?php echo $local?>
                    </p>
                    <?php
                } else {
                ?>
                <p>&nbsp;</p>
                <p><?php echo $lg=='Ing' ? "EXIBITIONS" : "PROGRAMAÇÃO"; ?><br />
                <ul class="listaPadrao">
                    <?php
                    $i=0;
                    foreach ($resultProgFetch as $row) {
                        $dataOrig = $row->Data;
                        $data = databr($dataOrig);
                        $data2 = explode("/", $data);
                        if ($lg=='Ing'){
                            $dataFinal = $data2[1]."-".$data2[0];
                            $hora = horaIng($row->HoraManhaInicial);
                            $diaSemana = utf8(formata_data_extensoIng(".$dataOrig."));
                        } else {
                            $dataFinal = $data2[0]."/".$data2[1];
                            $hora = hora($row->HoraManhaInicial);
                            $diaSemana = utf8(formata_data_extenso(".$dataOrig."));
                        }



                        $local = $row->Local;
                        if ($local != "") {
                            $SqlLoc = "SELECT TitLocal, TitLocalIng FROM tb_local WHERE CodLocal = $local";
                            $resultLoc  = $pdo->query($SqlLoc);
                            $resultLoc = $resultLoc->fetchObject();
                            if ( $resultLoc ){
                                $local	= $resultLoc->TitLocal;
                            }
                        }

                        ?>
                        <li><?php echo $dataFinal?> | <?php echo $diaSemana?> • <?php echo $hora?><br />
                            <?php echo $local?>
                        </li>

                        <?php
                    }
                    }
                }
                ?>
            </ul>
            <br class="clearfloat" />

        </section>
    </div>
</main>