<?php $form = $this->form; ?>
<div class="row post guide">
<div class="col-md-12">
	<?php $form->prepare(); echo $this->form(null, null)->openTag($form) ?>

	<div class="portlet light portlet-fit bordered">
		<div class="portlet-title">
			<div class="caption">
				<?php if($this->video->getId()): ?>
				<i class="fa fa-edit"></i>
				Editar Video
				<?php else: ?>
				<i class="fa fa-file-o"></i>
				Novo Video
				<?php endif; ?>
			</div>
			<div class="actions">
				<a href="<?php echo $this->url('admin/tv', ['site'=>$this->site]); ?>"
				   class="btn btn-default">
					<i class="icon-action-undo"></i>
					<span class="hidden-xs"> Voltar </span>
				</a>
			</div>
		</div>
		<div class="portlet-body">
			<div class="row">

				<div class="col-md-12">
					<div class="portlet-body form">
						<div class="">
							<?php echo $this->formRow($form->get('caption')); ?>

							<div class="row">
								<div class="form-group col-md-4">
									<?php echo $this->formLabel($form->get('date')); ?>
									<div class="input-group date date-picker" data-date-format="dd/mm/yyyy">
										<?php echo $this->formelement($form->get('date')); ?>
										<span class="input-group-btn">
											<button class="btn btn-sm default" type="button">
												<i class="fa fa-calendar"></i>
											</button>
										</span>
									</div>
								</div>
							</div>

							<?php echo $this->formRow($form->get('youtube')); ?>

                            <div class="row">
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label class="control-label">Imagem de Destaque</label>
                                        <div class="input-group ">
                                            <div class="fileinput <?php echo $video->getThumb() ? "fileinput-exist" : ""; ?>">
                                                <div class="fileinput-new thumbnail" style="width: 200px; height: 150px;">
                                                    <img src="http://www.placehold.it/200x150/EFEFEF/AAAAAA&amp;text=no+image" alt="" /> </div>
                                                <div class="fileinput-preview thumbnail" style="max-width: 200px; max-height: 150px;">
                                                    <?php if($video->getThumb()): ?>
                                                        <img width="100%" src="<?php echo $video->getThumb() ?>" alt="" />
                                                    <?php endif; ?>
                                                </div>
                                                <div>
                                                    <a href="#"
                                                       data-toggle="modal"
                                                       data-target="#modal-responsivefilemanager"
                                                       data-url="/filemanager/dialog.php?type=1&field_id=file"
                                                       class="btn btn-success responsivefilemanager fileinput-add"><i class="fa fa-plus"></i> Selecionar uma Imagem</a>
                                                    <a class="btn red fileinput-remove"> Remover </a>
                                                    <?php echo $this->formElement($form->get('thumb')); ?>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

						</div>
					</div>

					<div class="form">
						<div class="form-body"></div>
						<div class="form-actions">
							<button type="submit" class="btn blue btn-lg pull-right action-save">Salvar</button>
							<a href="<?php echo $this->url('admin/tv', ['site'=>$this->site]); ?>" class="btn red btn-lg pull-right action cancel">Descartar</a>
						</div>
					</div>
				</div>

			</div>
		</div>
	</div>
	<?php echo $this->form()->closeTag() ?>
</div>
</div>