<div class="row">
	<div class="col-md-12">
		<div class="portlet light portlet-fit portlet-datatable bordered">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-th-list"></i>
					Videos
				</div>
				<div class="actions">
					<a href="<?php echo $this->url('admin/tv', ['site'=>$this->site, 'action'=>'create']); ?>"
					   class="btn blue btn-lg">
						<i class="fa fa-plus"></i>
						<span class="hidden-xs"> Novo Video </span>
					</a>
					<div class="btn-group">
						<a class="btn btn-default dropdown-toggle" href="javascript:;" data-toggle="dropdown">
							<i class="fa fa-share"></i>
							<span class="hidden-xs"> Opções </span>
							<i class="fa fa-angle-down"></i>
						</a>
						<div class="dropdown-menu pull-right">
							<li><a href="javascript:;"> Exportar para Excel </a></li>
							<li><a href="javascript:;"> Exportar para PDF </a></li>
							<li class="divider"></li>
							<li><a href="javascript:;"> Imprimir </a></li>
						</div>
					</div>
				</div>
			</div>

			<div class="portlet-body">
				<div class="table-container post-list">
					<table class="table table-striped table-bordered table-hover">
						<thead>
							<tr role="row" class="heading">
								<th width="2%">#</th>
								<th width="15%">Legenda</th>
								<th width="15%">Data</th>
								<th width="10%">Autor</th>
								<th width="10%">Ações</th>
							</tr>
						</thead>
						<tbody>
						<?php foreach ($this->videos as $video):
							$updateUrl = $this->url('admin/tv', [
								'action' => 'update',
								'id' => $video->getId(),
								'site' => $this->site
							]);

							$removeUrl = $this->url('admin/tv', [
								'action' => 'delete',
								'id' => $video->getId(),
								'site' => $this->site
							]);

							?>
							<tr>
								<td></td>
								<td><a href="<?php echo $updateUrl; ?>"><?php echo $video->getCaption(); ?></a></td>
								<td><?php echo $video->getDate()->format('d/m/Y'); ?></td>
								<td><?php echo $video->getAuthor()->getName(); ?></td>
								<td>
									<a href="<?php echo  $updateUrl; ?>" class="btn btn-sm btn-default">
										<i class="fa fa-edit"></i> Editar
									</a>
									<a href="<?php echo $removeUrl; ?>" class="btn btn-sm btn-default post-list-remove">
										<i class="fa fa-trash-o"></i> Lixeira
									</a>
								</td>
							</tr>
						<?php endforeach; ?>
						</tbody>
					</table>
					<div class="table-paginator">
						
                        <?php echo $this->paginationcontrol(
                            $this->videos,
                            'sliding',
                            'admin/partials/paginator.phtml',
                            array(
                                'route'=>'admin/tv',
                                'route_options' => array('site'=>$this->site)
                            )
                        ); ?>
					</div>

				</div>
			</div>
		</div>
	</div>
</div>