<div class="userlogin-wrapper">
    <p class="meuuniverso-brand meuuniverso-brand--center"><strong>Meu</strong>Universo<br />Alterar senha</p>

    <?php if($this->error): ?>
        <div class="note note-danger">
            <h4 class="block">Ocorreu um erro!</h4>
            <p>Não conseguimos identificar o usuário. Por favor tente novamente ou entre em contato</p>
            <p><a class="btn blue" href="<?php echo $this->url('meu-universo/auth') ?>">Efetuar login</a></p>
        </div>
    <?php elseif(!$this->error && $this->reason == 'password_change'): ?>
        <div class="note note-info">
            <h4 class="block">Tudo certo!</h4>
            <p>Seu senha foi atualizada com sucesso.</p>
            <p><a class="btn blue" href="<?php echo $this->url('meu-universo/auth') ?>">Efetuar login</a></p>
        </div>
    <?php endif; ?>

    <?php if($this->requiredUpdate): ?>
        <div class="note note-info">
            <h4 class="block">Atualização de senha necessária</h4>
            <p> Sua senha precisa ser alterada. Por favor, informe os dados abaixo. </p>
        </div>
    <?php endif; ?>

    <?php
        if($this->form) {
            $form = $this->form;
            $form->prepare();
            echo $this->form(null, null)->openTag($form);

            if ($form->has('old_password')) {
                echo $this->formRow($form->get('old_password'));
            }
            echo $this->formRow($form->get('password'));
            echo $this->formRow($form->get('confirm_password'));
            echo '<button class="submit" class="userlogin-submit">Enviar</button>';
            echo $this->form()->closeTag();
        } ?>

</div>