<div class="userlogin-wrapper">
    <p class="meuuniverso-brand meuuniverso-brand--center"><strong>Meu</strong>Universo</p>

    <?php if($this->error): ?>
        <div class="alert alert-danger">Usuário ou senha inválidos</div>
    <?php endif; ?>

    <form action="" method="post" class="userlogin-form">
        <input class="input" name="login" placeholder="E-mail">
        <input type="password" class="input" name="password" placeholder="Senha">
        <button class="submit" class="userlogin-submit">Entrar</button>
    </form>
    <div class="userlogin-tricks">
        <p class="tricks-item"><a href="<?php echo $this->url('meu-universo/auth', ['action'=>'recuperar-senha']) ?>" class="tricks-link">Esqueci minha senha</a></p>
        <p class="tricks-item"><a href="<?php echo $this->url('meu-universo/register', ['action'=>'novo']) ?>" class="tricks-link">Quero me cadastrar</a></p>
        <!--<p class="tricks-item tricks-item--separator"><span>ou</span></p>
        <p class="tricks-item"><a href="#" class="submit tricks-link tricks-link--facebook">Entrar com o Facebook</a></p>-->
    </div>
</div>

<?php $this->inlineScript()->captureStart();
echo <<<JS
$(document).ready(function() {
    $.fancybox.open('<div class="" id="novo-sistema" style="width: 500px; height: 300px;">\
        <h2 style="font-size: 24px; font-weight: 900; margin-bottom: 24px;">Novo sistema</h2>\
        <p style="margin-bottom: 18px;">Olá! Nosso sistema está passando por mudanças.</p>\
        <p style="margin-bottom: 18px;">Se você já possuia um login e senha para acesso ao portal da Universo Produção, eles não valem mais. É necessário efetuar um novo cadastro.</p>\
        <p><a href="http://meu-universo.universoproducao.com.br/cadastro/novo" class="tricks-link">Quero me cadastrar</a></p>\
    </div>');
});
JS;
$this->inlineScript()->captureEnd();
?>