<div class="userlogin-wrapper">
    <p class="meuuniverso-brand meuuniverso-brand--center"><strong>Meu</strong>Universo</p>

    <?php if($this->error): ?>

        <?php if(isset($this->reason) && $this->reason == 'user_not_confirmed_register'): ?>
            <div class="alert alert-danger">
                <p>Confimação de conta necessária. Por favor, acesse seu e-mail e clique no link de validação.</p>
                <p>Você tambem pode <a href="<?php echo $this->url('meu-universo/register', ['action'=>'re-enviar-link']) ?>">Re-enviar link de ativação</a></p>
            </div>
        <?php else: ?>
            <div class="alert alert-danger">Usuário ou senha inválidos</div>
        <?php endif; ?>
    <?php endif; ?>

    <form action="" method="post" class="userlogin-form">
        <input class="input" name="login" placeholder="E-mail" value="<?php echo isset($this->login) ? $this->login : "" ?>">
        <input type="password" class="input" name="password" placeholder="Senha">
        <button class="submit" class="userlogin-submit">Entrar</button>
    </form>
    <div class="userlogin-tricks">
        <p class="tricks-item"><a href="<?php echo $this->url('meu-universo/auth', ['action'=>'recuperar-senha']) ?>" class="tricks-link">Esqueci minha senha</a></p>
        <p class="tricks-item"><a href="<?php echo $this->url('meu-universo/register', ['action'=>'novo']) ?>" class="tricks-link">Quero me cadastrar</a></p>
        <!--<p class="tricks-item tricks-item--separator"><span>ou</span></p>
        <p class="tricks-item"><a href="#" class="submit tricks-link tricks-link--facebook">Entrar com o Facebook</a></p>-->
    </div>
</div>
