<?php $this->headScript()->captureStart() ?>
(function() {
var cx = '004056108255715595582:l6tudq71ici';
var gcse = document.createElement('script');
gcse.type = 'text/javascript';
gcse.async = true;
gcse.src = 'https://cse.google.com/cse.js?cx=' + cx;
var s = document.getElementsByTagName('script')[0];
s.parentNode.insertBefore(gcse, s);
})();
<?php $this->headScript()->captureEnd() ?>

<div class="main__figure">
    <?php if($post->getMeta('_cover')): ?>
        <img src="<?php echo $this->thumbor()->url($post->getMeta('_cover'))->resize(1920, 492); ?>" alt="">
    <?php else: ?>
        <img src="<?php echo $this->basePath("assets/brasilcinemundi/dist") ?>/images/internal.jpg" alt="">
    <?php endif; ?>
</div>
<?php if($this->breadcrumbs): ?>
    <?php echo $this->partial('brasilcinemundi/partials/_breadcrumbs.phtml', ['breadcrumbs'=>$this->breadcrumbs]); ?>
<?php endif; ?>

<section class="main__wrapper">
    <header class="main__header">
        <h1 class="main__title"><?php echo $this->post->getTitle(); ?></h1>
    </header>
    <gcse:searchresults-only></gcse:searchresults-only>
</section>