<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Arquivo em Cartaz - 2017</title>
    <link rel="apple-touch-icon" href="apple-touch-icon.png">
    <link rel="stylesheet" href="<?php echo $this->basePath('assets/arquivoemcartaz_hotsite/dist') ?>/styles/main.css">
</head>
<body><!--[if IE]><p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a
        href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p><![endif]-->
<div class="wrapper">
    <div class="content">
        <div class="left"><h1 class="brand"><img src="<?php echo $this->basePath('assets/arquivoemcartaz_hotsite/dist/') ?>images/brand.png" alt=""></h1><span
                    class="su">Inscrições abertas<br>e gratuitas</span></div>
        <div class="right"><p><span>Oficina lanterna mágica</span> 25/5 a 5/7</p>
            <p><span>Filmes Mostra Competitiva</span> 1/6 a 31/7</p>
            <p><span>Filmes mostra arquivos do amanhã</span> 1/6 a 31/7</p>
            <p><span>Oficinas Técnicas</span> 4/10 a 20/10</p>
            <p><span>Arquivo Faz Escola</span> 21/10 a 23/10</p></div>
        <p class="center"><a href="http://arquivoemcartaz.com.br/inicio">Edição #2016</a></p></div>
</div>
<script>!function (e, t, a, n, c, o) {
        e.GoogleAnalyticsObject = n, e[n] || (e[n] = function () {
            (e[n].q = e[n].q || []).push(arguments)
        }), e[n].l = +new Date, c = t.createElement(a), o = t.getElementsByTagName(a)[0], c.src = "https://www.google-analytics.com/analytics.js", o.parentNode.insertBefore(c, o)
    }(window, document, "script", "ga"), ga("create", "UA-XXXXX-X"), ga("send", "pageview")</script>
<script src="scripts/main.js"></script>
</body>
</html>