<?php if(count($this->bannerImages)): ?>
    <section class="banner">
        <div class="owl-carousel" id="banner-home">
            <?php foreach ($this->bannerImages as $banner): ?>
                <div class="banner-item">
                    <img src="<?php echo $this->thumbor()->url($banner->getMeta('_image'))->resize(1920, 630); ?>" alt="">
                    <p class="banner-caption"><?php echo $banner->getSubtitle(); ?></p>
                </div>
            <?php endforeach; ?>
        </div>
    </section>
<?php endif; ?>

<main class="main home">
    <div class="main__wrapper">
        <?php if(count($this->news)): ?>
        <section class="main__section news">
            <header class="news__header">
                <h1 class="news__title main__title">Notícias</h1>
            </header>
            <div class="news__list">
                <?php $count=1; foreach ($this->news as $news): ?>
                <article class="news__item">
                    <div class="news__item-wrapper">
                        <figure class="news__item-figure">
                            <?php if($news->getMeta('_thumb')): ?>
                            <img src="<?php echo  $this->thumbor()->url($news->getMeta('_thumb'))->resize(450, 350); ?>" alt="" class="news__item-img">
                            <?php endif; ?>
                        </figure>
                        <div class="news__item-content">
                            <p class="news__item-title"><?php echo $news->getTitle(); ?></p>
                            <p class="news__item-text">
                                <?php
                                    $count == 1 ? $truncateLenght = 200 : $truncateLenght = 56;
                                    echo $this->truncate($news->getContent(), $truncateLenght);
                                ?>
                                <a href="<?php echo $this->url('arquivoemcartaz/news', ['slug' => $news->getSlug()]) ?>" class="news__item-link">
                                    <span class="icon icon-arrow-right8"></span>
                                </a>
                            </p>
                        </div>
                    </div>
                </article>
                <?php $count++; endforeach; ?>
            </div>
            <p class="readmore"><a class="readmore__link" href="<?php echo $this->url('arquivoemcartaz/default', ['slug'=>'noticias']) ?>">Mais Notícias<span class="icon icon-plus2"></span></a></p>
        </section>
        <?php endif; ?>

        <!--<section class="main__section programation">
            <header class="news__header">
                <h1 class="programation__title main__title">Programação</h1>
            </header>
            <div class="programation__wrapper">


                <div class="programation__parallax" style="background-image: url(<?php /*echo $this->basePath('assets/arquivoemcartaz/dist/images/programation.jpg') */?>)" data-stellar-background-ratio="0.5"></div>

                <div class="programation__items">
                    <article class="programation__item programation__item--highlight">
                        <div class="programation__item-wrapper">
                            <div class="programation__item-date">
                                <p class="programation__item-day">08 - 09</p>
                                <p class="programation__item-year">NOV / 2016</p>
                            </div>
                            <div class="programation__item-desc">
                                <p class="programation__item-title">Brazilian Film Program expansion</p>
                                <p class="programation__item-subtitle">18:15 | Auditório fernando nassau -  sala 4</p>
                            </div>
                        </div>
                    </article>
                    <article class="programation__item">
                        <div class="programation__item-wrapper">
                            <div class="programation__item-date">
                                <p class="programation__item-day">10 - 09</p>
                                <p class="programation__item-year">NOV / 2016</p>
                            </div>
                            <div class="programation__item-desc">
                                <p class="programation__item-title">South Korea's Polarizing Film Market</p>
                                <p class="programation__item-subtitle">18:15 | Auditório fernando nassau -  sala 4</p>
                            </div>
                        </div>
                    </article>
                    <article class="programation__item">
                        <div class="programation__item-wrapper">
                            <div class="programation__item-date">
                                <p class="programation__item-day">08 - 09</p>
                                <p class="programation__item-year">NOV / 2016</p>
                            </div>
                            <div class="programation__item-desc">
                                <p class="programation__item-title">South Korea's Polarizing Film Market</p>
                                <p class="programation__item-subtitle">18:15 | Auditório fernando nassau -  sala 4</p>
                            </div>
                        </div>
                    </article>
                    <article class="programation__item">
                        <div class="programation__item-wrapper">
                            <div class="programation__item-date">
                                <p class="programation__item-day">08 - 09</p>
                                <p class="programation__item-year">NOV / 2016</p>
                            </div>
                            <div class="programation__item-desc">
                                <p class="programation__item-title">South Korea's Polarizing Film Market</p>
                                <p class="programation__item-subtitle">18:15 | Auditório fernando nassau -  sala 4</p>
                            </div>
                        </div>
                    </article>
                </div>
            </div>
            <p class="readmore"><a class="readmore__link" href="">Programação Completa<span class="icon icon-plus2"></span></a></p>
        </section>-->

        <?php if(count($this->gallery)): ?>
        <section class="main__section gallery">
            <div class="gallery__wrapper">
                <header class="gallery__header">
                    <div class="gallery__header-wrapper">
                        <h1 class="gallery__title main__title">Galeria</h1>
                    </div>
                    <p class="readmore"><a class="readmore__link" target="_blank" href="https://www.flickr.com/photos/universoproducao">Galeria Completa<span class="icon icon-plus2"></span></a></p>
                </header>
                <div class="gallery__list owl-carousel">
                    <?php foreach ($this->gallery as $img): ?>
                    <div class="gallery__item">
                        <div class="gallery__figure">
                            <img src="<?php echo $this->thumbor()->url($img->getMeta('_image'))->resize(952, 624); ?>" alt="">
                            <?php if($img->getMeta('_credits')): ?>
                                <span class="gallery__caption"><?php echo $img->getMeta('_credits'); ?></span>
                            <?php endif; ?>
                        </div>
                        <div class="gallery__desc">
                            <div class="gallery__desc-wrapper">
                                <div class="gallery__desc-text">
                                    <p class="gallery__desc-title"><?php echo $img->getContent(); ?></p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <?php endforeach; ?>
                </div>
            </div>
            <p class="readmore"><a class="readmore__link" target="_blank" href="https://www.flickr.com/photos/universoproducao">Galeria Completa<span class="icon icon-plus2"></span></a></p>
        </section>
        <?php endif; ?>

        <?php if(count($this->guides)): ?>
            <section class="main__section place">
                <header class="place__header">
                    <h1 class="place__title main__title">Locais</h1>
                </header>
                <?php $firstGuide = current($this->guides);?>
                <div class="place__figure">
                    <img class="place__image" src="<?php echo $this->thumbor()->url($firstGuide->getMeta('_thumb'))->resize(472, 280); ?>" alt="">
                </div>
                <div class="place__desc">
                    <div class="place__desc-wrapper">
                        <p class="place__desc-title"><?php echo $firstGuide->getTitle(); ?></p>
                        <p class="place__desc-text">
                            <?php echo $this->truncate($firstGuide->getContent(), 300); ?>
                            <a href="<?php echo $this->url('arquivoemcartaz/default', ['slug'=>$firstGuide->getRelativeUrl()]); ?>" class="news__item-link">
                                <span class="icon icon-arrow-right8"></span>
                            </a>
                        </p>
                    </div>
                </div>
                <ul class="place__items">
                    <?php foreach ($this->guides as $guide): ?>
                    <li class="place__item <?php echo $firstGuide->getId()==$guide->getId() ? "place__item--active" : ""; ?>"
                        data-image="<?php echo $this->thumbor()->url($guide->getMeta('_thumb'))->resize(472, 280); ?>"
                        data-title="<?php echo $guide->getTitle(); ?>"
                        data-link="<?php echo $this->url('arquivoemcartaz/default', ['slug'=>$guide->getRelativeUrl()]); ?>"
                        data-desc=" <?php echo $this->truncate($guide->getContent(), 300); ?>"><a class="place__link" href=""><?php echo $guide->getTitle(); ?></a></li>
                    <?php endforeach; ?>
                </ul>
            </section>
        <?php endif; ?>

        <!--<section class="main__section sponsor">
            <div class="sponsor__block sponsor__block--1">
                <ul class="sponor__list">
                    <li class="sponsor__item"><span class="sprite sprite-lei"></span></li>
                </ul>
            </div>

            <div class="sponsor__block sponsor__block--3">
                <p class="sponsor__title">Patrocínio</p>
                <ul class="sponor__list">
                    <li class="sponsor__item"><span class="sprite sprite-bndes"></span></li>
                    <li class="sponsor__item"><span class="sprite sprite-light"></span></li>
                </ul>
            </div>

            <div class="sponsor__block sponsor__block--full">
                <p class="sponsor__title">Apoio</p>
                <ul class="sponor__list">
                    <li class="sponsor__item"><span class="sprite sprite-aaa"></span></li>
                    <li class="sponsor__item"><span class="sprite sprite-cinearte"></span></li>
                    <li class="sponsor__item"><span class="sprite sprite-cta"></span></li>
                    <li class="sponsor__item"><span class="sprite sprite-mis"></span></li>
                    <li class="sponsor__item"><span class="sprite sprite-cinemateca"></span></li>
                    <li class="sponsor__item"><span class="sprite sprite-afinal"></span></li>
                </ul>
            </div>

            <div class="sponsor__block sponsor__block--full">
                <p class="sponsor__title">Realização</p>
                <ul class="sponor__list">
                    <li class="sponsor__item"><span class="sprite sprite-instituto"></span></li>
                    <li class="sponsor__item"><span class="sprite sprite-universo"></span></li>
                    <li class="sponsor__item"><span class="sprite sprite-sponsor-arquivo-nacional"></span></li>
                    <li class="sponsor__item"><span class="sprite sprite-brasil"></span></li>
                </ul>
            </div>
        </section>-->
    </div>
</main>