<!doctype html>
<html lang="">
<head>
    <meta charset="utf-8">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Mostra Tiradentes 2019</title>
    <link rel="apple-touch-icon" href="apple-touch-icon.png">
    <link rel="stylesheet" href="<?php echo $this->basePath('assets/mostratiradentes2019') ?>/css/main.css?v=201803031701">

</head>
<body>
<div class="wrapper">

    <div class="all">

        <div class="slogan">
            <div class="brand-mobile-only">
                <img src="<?php echo $this->basePath('assets/mostratiradentes2019') ?>/images/brand.png" alt="">
            </div>
            <img class="slogan-img" src="<?php echo $this->basePath('assets/mostratiradentes2019') ?>/images/slogon.png" alt="">
            <div class="brand">
                <img src="<?php echo $this->basePath('assets/mostratiradentes2019') ?>/images/brand.png" alt="">
            </div>
            <div class="sub">
                <a href="http://universoproducao.com.br/inscricoes" target="_blank">
                    <img src="<?php echo $this->basePath('assets/mostratiradentes2019') ?>/images/subscription.png" alt="">
                </a>
            </div>
        </div>

        <div class="edition">
            <a href="http://mostratiradentes.com.br/inicio">
                <img src="<?php echo $this->basePath('assets/mostratiradentes2019') ?>/images/edicaoanterior.png" alt="">
            </a>
        </div>

    </div>

</div>
</body>
</html>
