<?php $form = $this->form; ?>

<h3 class="form-section">Inscrição</h3>
<div class="form-group ">
    <?php
        $userName = $this->subscription->getUser()?$this->subscription->getUser()->getName():"";
        $userId = $this->subscription->getUser()?$this->subscription->getUser()->getId():"";
    ?>
    <label class="col-md-4 control-label">Usuário<span class="required"> * </span></label>
    <div class=" col-md-4">
        <div class="input-group">
            <input readonly type="text" id="userName" class="form-control" value="<?php echo $userName ?>">
            <span class="input-group-btn">
                <button
                        class="btn user-modal"
                        type="button"
                        data-user-id="<?php echo $userId; ?>"
                        data-select-id-to="#user"
                        data-select-name-to="#userName">
                    <i class="fa fa-search"></i>
                </button>
            </span>
        </div>
    </div>
</div>

<?php echo $this->formElement($form->get("user")) ?>
<?php echo $this->formRow($form->get("registration")) ?>
<?php echo $this->formRow($form->get("workshop")) ?>
<?php
$workshopRegisterElements = $form->get('form_answer')->getElements();
foreach ($workshopRegisterElements as $workshopEl) {
    echo $this->formRow($workshopEl);
}
?>

