<?php
    $formStatusModal = $this->statusModalForm;
    $formStatusModal->setAttribute('action', $this->url('admin/default', ['controller'=>'workshop-registration', 'action'=>'status']));
    $formStatusModal->prepare(); ?>

<div class="modal fade" id="modal-workshop-status" tabindex="-1" role="basic" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <?php echo $this->form(null, null)->openTag($formStatusModal); ?>
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                    <h4 class="modal-title">Alterar status</h4>
                </div>
                <div class="modal-body">
                    <?php echo $this->formRow($formStatusModal->get('status')); ?>
                    <?php echo $this->formRow($formStatusModal->get('filter')); ?>
                </div>
                <div class="modal-footer">
                    <button type="reset" class="btn" data-dismiss="modal">Cancelar</button>
                    <button type="submit" class="btn blue">Salvar</button>
                </div>
            <?php echo $this->form()->closeTag();  ?>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>