<?php
    $form = $this->searchForm;
    $form->setAttribute('method', 'GET');
?>

<div class="row">
	<div class="col-md-12">
		<div class="portlet light portlet-fit portlet-datatable bordered">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-th-list"></i>
					Inscrição de oficinas
				</div>
				<div class="actions">
					<a href="<?php echo $this->url('admin/default', ['controller'=>'workshop-registration', 'action'=>'create']); ?>"
					   class="btn blue btn-lg">
						<i class="fa fa-plus"></i>
						<span class="hidden-xs"> Nova inscrição  </span>
					</a>
                    <div class="btn-group">
                        <a class="btn btn-default dropdown-toggle" href="javascript:;" data-toggle="dropdown">
                            <i class="fa fa-share"></i>
                            <span class="hidden-xs"> Opções </span>
                            <i class="fa fa-angle-down"></i>
                        </a>
                        <div class="dropdown-menu pull-right">
                            <li>
                                <a class="report-link"
                                   data-form="#workshop-registration-form"
                                   data-url="<?php echo $this->url('admin/default', ['controller'=>'workshop-registration', 'action'=>'export-list']) ?>"
                                   href="#"> Exportar para Excel </a>
                            </li>
                            <li>
                                <a class="report-link"
                                   data-form="#workshop-registration-form"
                                   data-url="<?php echo $this->url('admin/default', ['controller'=>'workshop-registration', 'action'=>'export-details-list']) ?>"
                                   href="#"> Exportar currículos </a>
                            </li>
                        </div>
                    </div>
				</div>
			</div>

			<div class="portlet-body">

				<div class="table-container post-list list-actions"
                     data-total="<?php echo $this->items->getTotalItemCount(); ?>"
                     data-form="#workshop-registration-form">

                    <div class="row">
                        <div class="col-md-12 col-sm-12 margin-bottom-10">
                            <div class="table-group-actions pull-right">
                                <span class="list-actions-selected"></span>
                                <select class="table-group-action-input form-control input-inline input-sm list-actions-options">
                                    <option value="">Selecione uma ação...</option>
                                    <option data-modal="#modal-workshop-status">Alterar status</option>
                                    <option>Enviar comunicados</option>
                                </select>
                                <button class="btn btn-sm btn-default table-group-action-submit list-actions-submit">
                                    <i class="fa fa-check"></i> Processar</button>
                            </div>
                        </div>
                    </div>

					<table class="table table-striped table-bordered table-hover">
						<thead>
                        <?php $form->prepare(); echo $this->form()->openTag($form); ?>
							<tr role="row" class="heading">
                                <th width="2%"> </th>
								<th width="3%">ID</th>
								<th width="15%">Evento</th>
								<th width="10%">Oficina</th>
                                <th width="15%">Usuário</th>
                                <th width="12%">Status</th>
                                <th width="8%">Pontuação</th>
                                <th width="10%">Data de cadastro</th>
								<th width="10%">Ações</th>
							</tr>
                            <tr role="row" class="filter">
                                <td>
                                    <input type="checkbox" class="icheck select-all" name="id_select_all" value="">
                                    <?php echo $this->formElement($form->get('selected')); ?>
                                </td>
                                <td><?php echo $this->formelement($form->get('id')); ?></td>
                                <td><?php echo $this->formelement($form->get('event')); ?></td>
                                <td><?php echo $this->formelement($form->get('workshop')); ?></td>
                                <td><?php echo $this->formelement($form->get('user_search')); ?></td>
                                <td><?php echo $this->formelement($form->get('status')); ?></td>
                                <td></td>
                                <td>
                                    <div class="input-group date date-picker margin-bottom-5" data-date-format="dd/mm/yyyy">
                                        <?php echo $this->formelement($form->get('dateInit')); ?>
                                        <span class="input-group-btn">
                                            <button class="btn btn-sm default" type="button">
                                                <i class="fa fa-calendar"></i>
                                            </button>
                                        </span>
                                    </div>
                                    <div class="input-group date date-picker" data-date-format="dd/mm/yyyy">
                                        <?php echo $this->formelement($form->get('dateEnd')); ?>
                                        <span class="input-group-btn">
                                            <button class="btn btn-sm default" type="button">
                                                <i class="fa fa-calendar"></i>
                                            </button>
                                        </span>
                                    </div>
                                </td>
                                <td>
                                    <div class="margin-bottom-5">
                                        <button type="submit" class="btn btn-sm blue filter-submit margin-bottom"><i class="fa fa-search"></i> Pesquisar</button>
                                    </div>
                                    <button type="reset" class="btn btn-sm btn-default filter-cancel"><i class="fa fa-times"></i> Limpar</button>
                                </td>
                            </tr>
                        <?php echo $this->form()->closeTag(); ?>
						</thead>
						<tbody>
						<?php foreach ($this->items as $item):
							$updateUrl = $this->url('admin/default', [
								'controller' => 'workshop-registration',
								'action'=>'update',
								'id'=>$item->getId()
							]);

							$removeUrl = $this->url('admin/default', [
								'controller' => 'workshop-registration',
								'action'=>'delete',
								'id'=>$item->getId()
							]);
							?>
							<tr>
                                <td><input type="checkbox" class="icheck" name="id[]" value="<?php echo $item->getId() ?>"></td>
								<td><?php echo $item->getId() ?></td>
								<td><?php echo $item->getEvent()?$item->getEvent()->getShortName():""; ?></td>
                                <td><?php echo $item->getWorkshop()->getName(); ?></td>
								<td>
                                    <?php echo $item->getUser()->getName(); ?> <br />
                                    <?php if($item->getUser()->getCity()) {
                                        echo $item->getUser()->getCity()->getName();
                                    } ?>
                                </td>
                                <td>
                                    <?php
                                        $label = \Application\Entity\Registration\Status::get($item->getStatus());
                                        echo $this->registrationStatus($item->getStatus(), $label). " ". $label; ?>
                                </td>
                                <td><?php echo $item->getTotalPontuation() ?></td>
								<td><?php echo $item->getCreatedAt()->format('d/m/Y H:i') ?></td>
								<td>
									<a href="<?php echo  $updateUrl; ?>" class="btn btn-sm btn-default">
										<i class="fa fa-edit"></i> Editar
									</a>
									<a href="<?php echo $removeUrl; ?>" class="btn btn-sm btn-default post-list-remove">
										<i class="fa fa-trash-o"></i> Excluir
									</a>
								</td>
							</tr>
						<?php endforeach; ?>
						</tbody>
					</table>

                    <div class="table-paginator">
                        <?php echo $this->paginationcontrol(
                            $this->items,
                            'sliding',
                            'admin/partials/paginator.phtml',
                            array(
                                'route'=>'admin/default',
                                'route_options' => array('controller'=>'workshop-registration'),
                                'route_query_options' => ['query'=>$this->searchData]
                            ));
                        ?>
                    </div>

				</div>
			</div>
		</div>
	</div>
</div>

<?php $this->inlineScript()->captureStart();
echo <<<JS
$( document ).ready(function() {
   $('#event').on('change', function(e) {
       App.blockUI({
           cenrerY: true,
           animate: true
       });
       var form = $('#submit_form');
       form.submit();
   });
});
JS;
$this->inlineScript()->captureEnd(); ?>

<?php echo $this->partial('admin/workshop-registration/_modal-status.phtml', [
    'statusModalForm' => $this->statusModalForm
]); ?>