<div class="row post news">
	<div class="col-md-12">

		<div class="portlet light portlet-fit bordered">
			<div class="portlet-title">
				<div class="caption">
					<?php if($this->workshopSubscription->getId()): ?>
					<i class="fa fa-edit"></i>
					Editar Inscrição
					<?php else: ?>
					<i class="fa fa-file-o"></i>
					Incluir Inscrição
					<?php endif; ?>
				</div>
				<div class="actions">
					<a href="<?php echo $this->url('admin/default', ['controller'=>'workshop-registration']); ?>"
					   class="btn btn-default">
						<i class="icon-action-undo"></i>
						<span class="hidden-xs"> Voltar </span>
					</a>
                    <a href="<?php echo $this->url('admin/default', ['controller'=>'workshop-registration', 'action'=>'create']); ?>"
                       class="btn blue btn-lg">
                        <i class="fa fa-plus"></i>
                        <span class="hidden-xs"> Incluir Inscrição  </span>
                    </a>
                    <div class="btn-group">
                        <a class="btn btn-default dropdown-toggle" href="javascript:;" data-toggle="dropdown">
                            <i class="fa fa-share"></i>
                            <span class="hidden-xs"> Opções </span>
                            <i class="fa fa-angle-down"></i>
                        </a>
                        <div class="dropdown-menu pull-right">
                            <li>
                                <a class="report-link"
                                   data-url="<?php echo $this->url('admin/default', ['controller'=>'workshop-registration', 'action'=>'export-confirmation', 'id'=>$this->workshopSubscription->getId()]) ?>"
                                   href="#"> Confirmação de participação </a>
                            </li>
                        </div>
                    </div>
				</div>
			</div>
			<div class="portlet-body">

			</div>
		</div>

	</div>
</div>