<div class="portlet light portlet-fit bordered post-sidebar-thumb">
	<div class="portlet-title">
		<div class="caption"><i class="fa fa-cogs"></i>Imagem de Destaque</div>
		<div class="actions">
			<a href="#"
			   data-toggle="modal"
			   data-target="#modal-responsivefilemanager"
			   data-url="/filemanager/dialog.php?type=1&field_id=returnResponsivefilemanager&akey=Un1v3rS0_Pr0dUcAo_Ag51_Sdni5fHgR2"
			   class="btn blue responsivefilemanager post-sidebar-thumb-action-add">
				<i class="fa fa-plus"></i> Selecionar
			</a>
		</div>
	</div>

	<div class="portlet-body">
		<div class="mt-card-item">
			<?php echo $this->formElement($form->get('meta[_thumb]'));  ?>
			<div class="mt-card-avatar post-sidebar-thumb-img" style="height: 200px; width: 200px;">
                <?php if($form->get('meta[_thumb]')->getValue()): ?>
                    <img src="<?php echo $this->thumbor()->url($form->get('meta[_thumb]')->getValue())->resize(200, 200); ?>" alt="">
                <?php endif; ?>
			</div>

			<a style="display: none" class="post-sidebar-thumb-action-remove" href="#">Remover</a>
		</div>
	</div>
</div>