<div class="portlet light bordered grey-cararra post-sidebar post-sidebar-translate">
    <div class="portlet-title">
        <div class="caption"><i class="fa fa-flag-checkered"></i>Tradução</div>
    </div>
    <div class="portlet-body">
        <div class="form-body">
            <!--<div class="item author">
                <div class="form-group">Idioma dessa página: <strong><?php /*echo $this->post->getLanguage() == 'en' ? 'Inglês' : 'Português' */?></strong></div>
                <hr />
                <?php /*if($this->post->getLanguage() == 'pt'): */?>
                    <div class="form-group"><h4>Incluir Tradução</h4></div>
                    <div class="form-group">
                        Inglês <a href="<?php /*echo $this->createUrl */?>?lang=en&translate_from=<?php /*echo $this->post->getId(); */?>" class="btn btn-default pull-right"><i class="fa fa-plus"></i></a>
                    </div>
                <?php /*endif; */?>
            </div>-->
        </div>
    </div>
</div>