<div class="portlet light portlet-fit bordered post-sites" data-url="<?php echo $this->url('admin/site_add_item'); ?>">
	<div class="portlet-title">
		<div class="caption">
			<i class="icon-star"></i>
			<span class="caption-subject"><?php echo $title; ?></span>
		</div>
	</div>

	<div class="portlet-body post-site-options">
		<div class="row">
			<div class="col-md-7 margin-bottom-10">
				<div class="form-inline post-site-form">
					<div class="form-group">
						<div class="input-group select2-bootstrap-prepend">
                            <span class="input-group-btn">
                                <button class="btn btn-default" type="button" data-select2-open="sites-enabled">
                                    <span class="fa fa-search"></span>
                                </button>
                            </span>
							<?php echo $this->formElement($form->get('sites-enabled')) ?>
						</div>
					</div>

					<div class="checkbox">
						<label for="site-highlight">
							<input type="checkbox" class="icheck" name="site-highlight" value="1"> Destaque
						</label>
					</div>

					<button type="submit" class="btn blue action add">Adicionar</button>
				</div>

			</div>

			<div class="col-md-5 ">
                <table class="table table-hover table-light post-sites-table">
                    <thead>
                        <tr>
                            <th width="80%%" class="uppercase"> Site </th>
                            <th><a class="action remove-all" href="#">remover todos</a></th>
                        </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($this->sites as $site): ?>
                        <tr class="post-sites-item" data-id="<?php echo $site['id'] ?>">
                            <td>
                                <?php echo $site['title'] ?>
                                <?php if($site['highlight'] == 'true'): ?>
                                    <span class="label label-sm label-success"> Destaque </span>
                                <?php endif; ?>
                            </td>
                            <td>
                                <button class="btn btn-sm btn-default action remove"><i class="fa fa-close"></i></button>
                                <input type="hidden" name="sites[<?php echo $site['id'] ?>][id]" value="<?php echo $site['id'] ?>" />
                                <input type="hidden" name="sites[<?php echo $site['id'] ?>][highlight]" value="<?php echo $site['highlight'] ?>" />
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
			</div>
		</div>
	</div>
</div>