<?php $this->route_options = $this->route_options ? $this->route_options : []; ?>
<?php $route_query_options = $this->route_query_options ? $this->route_query_options : []; ?>
<?php if ($this->pageCount): ?>
<div class="row">

	<div class="col-md-4">
		<p>Exibindo <?php echo $this->firstItemNumber; ?> a <?php echo $this->lastItemNumber; ?> de <?php echo $this->totalItemCount; ?> registros</p>
	</div>

	 <div class="col-md-6 pull-right">
		 <ul class="pagination pull-right">
			 <!-- Previous page link -->
			 <?php if (isset($this->previous)): ?>
                 <?php $route_query_options['query']['page'] =  $this->previous?>
				 <li>
					 <a href="<?php echo $this->url($this->route, $this->route_options, $route_query_options); ?>">
						 <<
					 </a>
				 </li>
			 <?php else: ?>
				 <li class="disabled">
					 <a href="#">
						 <<
					 </a>
				 </li>
			 <?php endif; ?>

			 <!-- Numbered page links -->
			 <?php foreach ($this->pagesInRange as $page): ?>
				 <?php if ($page != $this->current): ?>
                     <?php $route_query_options['query']['page'] =  $page?>
					 <li>
						 <a href="<?php echo $this->url($this->route, $this->route_options, $route_query_options);?>">
							 <?php echo $page; ?>
						 </a>
					 </li>
				 <?php else: ?>
					 <li class="active">
						 <a href="#"><?php echo $page; ?></a>
					 </li>
				 <?php endif; ?>
			 <?php endforeach; ?>

			 <!-- Next page link -->
			 <?php if (isset($this->next)): ?>
                 <?php $route_query_options['query']['page'] = $this->next; ?>
				 <li>
					 <a href="<?php echo $this->url($this->route, $this->route_options, $route_query_options); ?>">
						 >>
					 </a>
				 </li>
			 <?php else: ?>
				 <li class="disabled">
					 <a href="#">
						 >>
					 </a>
				 </li>
			 <?php endif; ?>
		 </ul>
	 </div>
</div>
<?php endif; ?>

