<?php $form = $this->form;
    $form->prepare(); ?>

<div class="container">
    <div class="col-md-12">
        <p class="meuuniverso-brand meuuniverso-brand--center"><strong>Meu</strong>Universo | Sessão</p>
    </div>

    <div class="portlet light">
        <div class="portlet-body form">
            <?php echo $this->form(null, null)->openTag($form); ?>
            <?php if($form->getMessages()): ?>
                <div class="portlet box red">
                    <div class="portlet-title">
                        <div class="caption">Atenção, os seguintes erros foram encontrados </div>
                    </div>
                    <div class="portlet-body">
                        <?php foreach ($form->getMessages() as $field=>$message): ?>
                            <h4 class="h4">Campo <?php echo $form->get($field)->getLabel(); ?></h4>
                            <div style="padding-left: 20px">
                                <?php foreach ($message as $key=>$m): ?>
                                    <p class="">
                                        <?php echo $m ?>
                                    </p>
                                <?php endforeach; ?>
                            </div>

                        <?php endforeach; ?>
                    </div>
                </div>
            <?php endif; ?>

            <h3 class="h3 block">Regulamento</h3>
            <?php echo $this->regulation($this->reg); ?>
            <div class="row">
                <div class="col-md-12">
                    <div class="movie-multi-check">
                        <div class="checkbox"><label><input type="checkbox" required name="accept_regulation" value="1"> Eu li e estou de acordo com as condições descritas no regulamento acima</label></div>
                    </div>
                </div>
            </div>

            <?php if($form->has('user')): ?>
                <hr>
                <div class="row">
                    <div class="col-md-5">
                        <?php echo $this->formRow($form->get('user')); ?>
                    </div>
                </div>
            <?php endif; ?>

            <div class="row">
                <div class="col-md-3">

                </div>
            </div>

            <?php if(count($this->debates) && $this->type == 'selected'): ?>
                <h3 class="h3 block">Debates, Painéis e Masterclass</h3>
                <table>
                    <?php foreach ($this->debates as $d):  ?>

                        <div style="display: none;width:600px;min-height: 400px" id="debate_<?php echo $d->getId(); ?>">
                            <?php echo $d->getDescription(); ?>
                        </div>

                    <tr>
                        <td>
                            <a style="color: #000;" data-fancybox data-src="#debate_<?php echo $d->getId(); ?>" data-modal="true"  href="javascript:;">
                                <?php echo $d->getTitle(); ?> <i class="fa fa-file"></i>
                            </a>
                        </td>
                        <td><input type="checkbox" name="debates[]" value="<?php echo $d->getId(); ?>"></td>
                    </tr>
                    <?php endforeach; ?>
                </table>
            <?php endif; ?>


            <div class="form-actions">
                <div class="row">
                    <div class="col-md-offset-3 col-md-9">
                        <button type="submit" class="btn btn-lg green button-submit"> Finalizar minha inscrição
                            <i class="glyphicon glyphicon-ok"></i>
                        </button>
                    </div>
                </div>
            </div>

            <?php echo $this->form()->closeTag(); ?>
        </div>
    </div>

</div>