<?php $form = $this->form;
    $form->prepare(); ?>

<div class="container">
    <div class="col-md-12">
        <p class="meuuniverso-brand meuuniverso-brand--center"><strong>Meu</strong>Universo | Sessão</p>
    </div>

    <div class="portlet light">
        <div class="portlet-body form">
            <?php echo $this->form(null, null)->openTag($form); ?>
            <?php if($form->getMessages()): ?>
                <div class="portlet box red">
                    <div class="portlet-title">
                        <div class="caption">Atenção, os seguintes erros foram encontrados </div>
                    </div>
                    <div class="portlet-body">
                        <?php foreach ($form->getMessages() as $field=>$message): ?>
                            <h4 class="h4">Campo <?php echo $form->get($field)->getLabel(); ?></h4>
                            <div style="padding-left: 20px">
                                <?php foreach ($message as $key=>$m): ?>
                                    <p class="">
                                        <?php echo $m ?>
                                    </p>
                                <?php endforeach; ?>
                            </div>

                        <?php endforeach; ?>
                    </div>
                </div>
            <?php endif; ?>

            <h3 class="h3 block">Regulamento</h3>
            <?php echo $this->regulation($this->reg); ?>
            <div class="row">
                <div class="col-md-12">
                    <div class="movie-multi-check">
                        <?php echo $this->formRow($form->get('accept_regulation')); ?>
                    </div>
                </div>
            </div>

            <?php if($form->has('user')): ?>
                <hr>
                <div class="row">
                    <div class="col-md-5">
                        <?php echo $this->formRow($form->get('user')); ?>
                    </div>
                </div>
            <?php endif; ?>

            <div class="row">
                <div class="col-md-3">

                </div>
            </div>

            <div class="form-actions">
                <div class="row">
                    <div class="col-md-offset-3 col-md-9">
                        <a href="<?php echo $this->url('meu-universo/seminar', ['id_reg'=>$this->reg->getHash()]) ?>" class="btn default button-previous">
                            <i class="glyphicon glyphicon-chevron-left"></i> Voltar </a>

                        <button type="submit" class="btn green button-submit"> Cadastrar
                            <i class="glyphicon glyphicon-ok"></i>
                        </button>
                    </div>
                </div>
            </div>

            <?php echo $this->form()->closeTag(); ?>
        </div>
    </div>

</div>