<div class="page-gallery"
     data-url="<?php echo $this->url('admin/gallery', ['site'=>$site, 'action'=>'add-item' ]); ?>"
     data-input="#returnResponsivefilemanager">

    <input type="hidden" id="returnResponsivefilemanager" name="returnResponsivefilemanager">
    <div class="gallery">
        <div id="tab_images_uploader_container" class="text-align-reverse margin-bottom-10">
            <a href="#"
               data-toggle="modal"
               data-target="#modal-responsivefilemanager"
               data-url="/filemanager/dialog.php?type=1&field_id=returnResponsivefilemanager"
               class="btn btn-success responsivefilemanager">
                <i class="fa fa-plus"></i> Selecionar uma Imagem
            </a>
        </div>

        <div class="table gallery-table">
            <?php echo $this->adminGallery($widget_value); ?>
        </div>
    </div>
</div>