<div class="row">
	<div class="col-md-12">
		<div class="portlet light portlet-fit portlet-datatable bordered">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-th-list"></i>
					Widgets
				</div>
				<div class="actions">
					<a href="<?php echo $this->url('admin/widget', ['action' => 'widgets', 'site'=>$this->site]); ?>"
					   class="btn blue btn-lg">
						<i class="fa fa-plus"></i>
						<span class="hidden-xs"> Novo Widget </span>
					</a>
					<div class="btn-group">
						<a class="btn btn-default dropdown-toggle" href="javascript:;" data-toggle="dropdown">
							<i class="fa fa-share"></i>
							<span class="hidden-xs"> Opções </span>
							<i class="fa fa-angle-down"></i>
						</a>
						<div class="dropdown-menu pull-right">
							<li><a href="javascript:;"> Exportar para Excel </a></li>
							<li><a href="javascript:;"> Exportar para PDF </a></li>
							<li class="divider"></li>
							<li><a href="javascript:;"> Imprimir </a></li>
						</div>
					</div>
				</div>
			</div>

			<div class="portlet-body">
				<div class="table-container post-list">
					<table class="table table-striped table-bordered table-hover">
						<thead>
							<tr role="row" class="heading">
								<th width="2%">#</th>
								<th width="15%">Título</th>
								<th width="15%">Tipo</th>
								<th width="15%">Código</th>
								<th width="10%">Ações</th>
							</tr>
						</thead>
						<tbody>
                        <?php foreach ($this->widgets as $w):
                            $widgetCode="[widget=".$w->getId()."]";

                            $updateUrl = $this->url('admin/widget', [
                                'action' => 'update',
                                'id' => $w->getId(),
                                'site' => $this->site
                            ], [
                                'query' => [
                                    'type' => $w->getType()
                                ]
                            ]);

                            $removeUrl = $this->url('admin/widget', [
                                'action' => 'delete',
                                'id' => $w->getId(),
                                'site' => $this->site
                            ]);
                        ?>
                            <tr>
                                <td></td>
                                <td><?php echo $w->getTitle(); ?></td>
                                <td><?php echo $w->getType(); ?></td>
                                <td><a class="data-copy" data-clipboard-text="<?php echo $widgetCode ?>" href="#"><?php echo $widgetCode?></a></td>
                                <td>
                                    <a href="<?php echo  $updateUrl; ?>" class="btn btn-sm btn-default">
                                        <i class="fa fa-edit"></i> Editar
                                    </a>
                                    <a href="<?php echo $removeUrl; ?>" class="btn btn-sm btn-default post-list-remove">
                                        <i class="fa fa-trash-o"></i> Lixeira
                                    </a>
                                </td>
                            </tr>
                        <?php endforeach; ?>
						</tbody>
					</table>
					<div class="table-paginator">
						<?php echo $this->paginationcontrol($this->widgets, 'sliding', 'admin/partials/paginator.phtml'); ?>
					</div>

				</div>
			</div>
		</div>
	</div>
</div>