<div class="row post guide">
<div class="col-md-12">
	<div class="portlet light portlet-fit bordered">
		<div class="portlet-title">
			<div class="caption"><i class="fa fa-file-o"></i>Novo Widget</div>
			<div class="actions">
				<a href="<?php echo $this->url('admin/widget', ['site'=>$this->site]); ?>"
				   class="btn btn-default">
					<i class="icon-action-undo"></i>
					<span class="hidden-xs"> Voltar </span>
				</a>
			</div>
		</div>
		<div class="portlet-body">
			<div class="row">

				<div class="col-md-12">
					<div class="portlet-body">
						<div class="col-md-4">
                            <div class="portlet light bordered">
                                <div class="portlet-title">
                                    <div class="caption font-green-sharp">
                                        <i class="icon-speech font-green-sharp"></i>
                                        <span class="caption-subject bold uppercase"> Galeria</span>
                                    </div>
                                    <div class="actions">
                                        <a href="<?php echo $this->url('admin/widget', ['action'=>'create', 'site'=>$this->site], ['query' => ['type' => 'gallery']] ) ?>" class="btn btn-circle btn-default btn-sm">
                                            <i class="fa fa-plus"></i> Adicionar </a>
                                    </div>
                                </div>
                                <div class="portlet-body">
                                    <p>Funcionalidade de galeria para páginas internas</p>
                                </div>
                            </div>
                        </div>
					</div>
				</div>

			</div>
		</div>
	</div>
	<?php echo $this->form()->closeTag() ?>
</div>
</div>