<?php $item = $this->post; ?>

<main class="main">
    <?php if($this->breadcrumbs): ?>
        <?php echo $this->partial('cineop2018/partials/_breadcrumbs.phtml', ['breadcrumbs'=>$this->breadcrumbs]); ?>
    <?php endif; ?>

    <div class="main-wrapper">
        <section class="main-content">
            <header class="main-header">
                <h1 class="main-title"><?php echo $item->getTitle(); ?></h1>
            </header>

            <?php echo $item->getDescription() ?>

            <p><strong>Programação</strong></p>
            <?php foreach ($this->post->getPrograming() as $pro): ?>
                <?php
                $progObj = null;
                if($pro->getParent()) {
                    $progObj = $pro->getParent();
                } else {
                    $progObj = $pro;
                }
                $date =  str_replace('-feira', '', $this->dateFormat($progObj->getDate(), null, null, "pt_BR", "dd/MM | cccc"));
                $hour = $progObj->getStartTime()->format('H\hi');
                $place = $progObj->getPlace()?$progObj->getPlace()->getName():"";
                ?>
                <div class="highlight-item">
                    <p class="hightlight-date"><?php echo "$date - $hour"; ?></p>
                    <p class="hightlight-place"><?php echo $place ?></p>
                </div>
            <?php endforeach; ?>
        </section>
    </div>
</main>