<main class="main">
    <?php if($this->breadcrumbs): ?>
        <?php echo $this->partial('cineop2018/partials/_breadcrumbs.phtml', ['breadcrumbs'=>$this->breadcrumbs]); ?>
    <?php endif; ?>

    <div class="main-wrapper">
        <section class="main-content">
            <header class="main-header">
                <h1 class="main-title"><?php echo $post->getTitle() ?></h1>
            </header>

            <div class="movie-filter filter">
                <form method="GET" name="programing-form" class="filter-form">
                    <select name="sub_event" class="filter-input form-control">
                        <option value="">Categoria</option>
                        <?php foreach ($this->categories as $cat): ?>
                            <option value="<?php echo $cat->getId(); ?>"><?php echo $cat->getName(); ?></option>
                        <?php endforeach; ?>
                    </select>
                    <button type="submit" class="filter-submit">Buscar</button>

                </form>
            </div>

            <div class="seminar">
                <div class="seminar-list">
                    <?php foreach ($this->list as $item): ?>
                        <article class="seminar-item">
                            <a class="seminar-link" href="<?php echo $this->url("cineop2018/seminar", ['id'=>$item->getId()]) ?>">
                                <?php if($item->getThematic()): ?>
                                    <span class="seminar-cat"><?php echo $item->getThematic()->getName(); ?></span>
                                <?php endif; ?>
                                <?php if($item->getCategory()): ?>
                                    <span class="seminar-cat"><?php echo $item->getCategory()->getName(); ?></span>
                                <?php endif; ?>
                                <header class="seminar-header">
                                    <h1 class="seminar-title"><?php  echo $item->getTitle(); ?></h1>
                                </header>
                            </a>
                        </article>
                    <?php endforeach; ?>
                </div>
            </div>
        </section>
    </div>
</main>