<main class="main">
    <?php if($this->breadcrumbs): ?>
        <?php echo $this->partial('cineop2018/partials/_breadcrumbs.phtml', ['breadcrumbs'=>$this->breadcrumbs]); ?>
    <?php endif; ?>

    <div class="main-wrapper">
        <section class="main-content">
            <header class="main-header">
                <h1 class="main-title"><?php echo $post->getTitle() ?></h1>
            </header>

            <div class="news-list">
                <?php foreach ($this->list as $item): ?>
                    <article class="news-item">
                        <header class="news-header">
                            <h1 class="news-title"><?php  echo $item->getTitle(); ?></h1>
                        </header>
                        <a href="<?php echo $this->url("cineop2018/seminar", ['id'=>$item->getId()]) ?>" class="btn">Maiores informações</a>
                    </article>
                <?php endforeach; ?>
            </div>
        </section>
    </div>
</main>