<footer class="footer">
    <div class="footer-contact">
        <div class="footer-wrapper">
            <div class="contact">
                <p class="footer-contact-title">Contato</p>
                <span class="contact-icon icon-universo-producao"></span>
                <span class="contact-add">+ 55 31 3282-2366<br>
              up@universoproducao.com.br<br>
              Rua Pirapetinga, 567 - Serra<br>
              30220-150, Belo Horizonte | MG</span>
            </div>

            <div class="social">
                <p class="footer-contact-title">Siga-nos</p>
                <ul class="social-items">
                    <li class="social-item"><a class="social-link" target="_blank" href="http://www.facebook.com/universoproducao"><span class="icon icon-facebook"></span></a></li>
                    <li class="social-item"><a class="social-link" target="_blank" href="http://twitter.com/universoprod"><span class="icon icon-twitter"></span></a></li>
                    <li class="social-item"><a class="social-link" target="_blank" href="http://instagram.com/universoproducao"><span class="icon icon-instagram"></span></a></li>
                    <li class="social-item"><a class="social-link" target="_blank" href="http://www.flickr.com/photos/universoproducao"><span class="icon icon-flickr"></span></a></li>
                    <li class="social-item"><a class="social-link" target="_blank" href="http://www.youtube.com/user/universoproducao/featured"><span class="icon icon-youtube"></span></a></li>
                </ul>
            </div>

            <div class="copy">
                <p>copyright © 2017. Universo produção - todos os direitos reservados</p>
            </div>

        </div>
    </div>
</footer>

<div class="static-social">
    <ul class="static-social-items">
        <li class="static-social-item"><a target="_blank" class="static-social-link" href="http://www.facebook.com/universoproducao"><span class="icon icon-facebook"></span></a></li>
        <li class="static-social-item"><a target="_blank" class="static-social-link" href="http://twitter.com/universoprod"><span class="icon icon-twitter"></span></a></li>
        <li class="static-social-item"><a target="_blank" class="static-social-link" href="http://instagram.com/universoproducao"><span class="icon icon-instagram"></span></a></li>
        <li class="static-social-item"><a target="_blank" class="static-social-link" href="http://www.flickr.com/photos/universoproducao"><span class="icon icon-flickr"></span></a></li>
        <li class="static-social-item"><a target="_blank" class="static-social-link" href="http://www.youtube.com/user/universoproducao/featured"><span class="icon icon-youtube"></span></a></li>
    </ul>
</div>

<nav class="mainmenu modal" id="mainmenu" data-open="#mainmenu-access">
    <div class="modal-header">
        <a href="#" class="modal-action modal-close">
            <span class="icon icon-cross2"></span>
        </a>
    </div>
</nav>

<div class="userlogin modal" id="userlogin" data-open="#userlogin-access">
    <div class="modal-header">
        <a href="#" class="modal-action modal-close">
            <span class="icon icon-cross2"></span>
        </a>
    </div>
    <div class="modal-content">
        <div class="userlogin-wrapper">
            <p class="userlogin-title"><strong>Meu</strong>Universo</p>
            <form action="" class="userlogin-form">
                <input class="input" name="login" placeholder="Login, e-mail ou CPF">
                <input class="input" name="password" placeholder="Senha">
                <button class="submit" class="userlogin-submit">Entrar</button>
            </form>
            <div class="userlogin-tricks">
                <p class="tricks-item"><a href="#" class="tricks-link">Esqueci minha senha</a></p>
                <p class="tricks-item"><a href="#" class="tricks-link">Quero me cadastrar</a></p>
                <p class="tricks-item tricks-item--separator"><span>ou</span></p>
                <p class="tricks-item"><a href="#" class="submit tricks-link tricks-link--facebook">Entrar com o Facebook</a></p>
            </div>
        </div>
    </div>
</div>

<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="/bower_components/jquery/dist/jquery.min.js"><\/script>')</script>

<script src="<?php echo $this->basePath('assets/universoproducao/dist'); ?>/scripts/vendor.js"></script>
<script src="<?php echo $this->basePath('assets/universoproducao/dist'); ?>/scripts/main.js"></script>
<script src="<?php echo $this->basePath('assets/universoproducao/dist'); ?>/scripts/vendor/imagesloaded.pkgd.min.js"></script>

<?php echo $this->inlineScript(); ?>

<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-10028533-1', 'auto');
    ga('send', 'pageview');

</script>
</body>
</html>