<!doctype html>
<html class="no-js" lang="pt">
<head>
    <meta charset="utf-8">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Universo Produção</title>

    <!--Facebook-->
    <meta property="og:url" content="<?php echo $this->serverUrl(true) ?>">
    <meta property="og:type" content="website" />

    <!-- Twitter -->
    <meta name="twitter:card" content="summary" />
    <meta name="twitter:site" content="@universoprod" />
    <meta name="twitter:creator" content="@universoprod" />

    <meta name="google-site-verification" content="K1liWW9R9uUH-6_Ggx7okBbrfDNCFd6cX34nO80hhVw" />

    <link rel="apple-touch-icon" href="apple-touch-icon.png">

    <link rel="stylesheet" href="<?php echo $this->basePath('assets/universoproducao/dist'); ?>/styles/main.css">

    <link rel="stylesheet" href="<?php echo $this->basePath('assets/universoproducao/dist'); ?>/styles/vendor.css">


    <script src="<?php echo $this->basePath('assets/universoproducao/dist')?>/scripts/vendor/modernizr.js"></script>


<!--    --><?php //echo $this->headScript() ?>
</head>
<body class="<?php echo !empty((string)$this->placeholder("is_home")) ? "home" : "" ?>
                <?php echo !empty((string)$this->placeholder("is_header_dark")) ? "header-dark" : "" ?>">
<!--[if lt IE 10]>
<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
<![endif]-->

<header class="header">
    <div class="header-wrapper">

        <h1 class="brand">
            <a class="brand-link" href="<?php echo $this->url('universoproducao') ?>"><span class="icon icon-universo-producao"></span></a>
            <span>Universo Produção</span>
        </h1>


        <!--<div class="header-right">
            <a class="headermenu-link" target="_blank" id="" href="http://universoproducao.com.br/site/inscricoes.php">
            <span class="icon">
              <i class="icon-user42"></i>
            </span>
            </a>
            <a class="headermenu-link mainmenu-access" id="mainmenu-access" href="#">
            <span class="icon">
              <i class="icon-menu7"></i>
            </span>
                <span class="title-menu">Menu</span>
            </a>
        </div>-->

        <ul class="links">
            <li class="links-item" id="manu-btn"><a class="links-action" href="#"><i class="icon-menu"></i></a></li>
            <li class="links-item" id="search-btn"><a class="links-action" href="#"><i class="icon-search"></i></a></li>
        </ul>

        <nav class="mainmenu">
            <?php $this
                ->navigation('UniversoproducaoNavigation')
                ->menu()->setPartial("application/partials/navigation.phtml");

            echo $this
                ->navigation('UniversoproducaoNavigation')
                ->menu()
                ->render(); ?>
        </nav>
    </div>
    <div class="search">
        <form class="search-form" action="<?php echo $this->url('universoproducao/search') ?>">
            <input type="text" class="search-input" placeholder="Buscar no site" name="q">
        </form>
    </div>
</header>

<main class="main">
    <?php echo $this->content; ?>
</main>

<footer class="footer">
    <div class="footer-wrapper">
        <section class="newsletter">
            <header class="newsletter-header">
                <h1 class="newsletter-title">Fique por dentro das nossas novidades</h1>
            </header>

            <form action="<?php echo $this->url('universoproducao/newsletter'); ?>" class="newsletter-form">
                <input required="required" class="input" placeholder="Nome">
                <input required="required" class="input" placeholder="Email">
                <button class="submit" type="submit">Cadastrar</button>
            </form>
        </section>
    </div>

    <div class="footer-contact">
        <div class="footer-wrapper">
            <div class="contact">
                <p class="footer-contact-title">Contato</p>
                <span class="contact-icon icon-universo-producao"></span>
                <span class="contact-add">+ 55 31 3282-2366<br>
              up@universoproducao.com.br<br>
              Rua Pirapetinga, 567 - Serra<br>
              30220-150, Belo Horizonte | MG</span>
            </div>

            <div class="social">
                <p class="footer-contact-title">Siga-nos</p>
                <ul class="social-items">
                    <li class="social-item"><a class="social-link" target="_blank" href="http://www.facebook.com/universoproducao"><span class="icon icon-facebook"></span></a></li>
                    <li class="social-item"><a class="social-link" target="_blank" href="http://twitter.com/universoprod"><span class="icon icon-twitter"></span></a></li>
                    <li class="social-item"><a class="social-link" target="_blank" href="http://instagram.com/universoproducao"><span class="icon icon-instagram"></span></a></li>
                    <li class="social-item"><a class="social-link" target="_blank" href="http://www.flickr.com/photos/universoproducao"><span class="icon icon-flickr"></span></a></li>
                    <li class="social-item"><a class="social-link" target="_blank" href="http://www.youtube.com/user/universoproducao/featured"><span class="icon icon-youtube"></span></a></li>
                </ul>
            </div>

            <div class="copy">
                <p>copyright © 2017. Universo produção - todos os direitos reservados</p>
            </div>

        </div>
    </div>
</footer>

<div class="static-social">
    <ul class="static-social-items">
        <li class="static-social-item"><a target="_blank" class="static-social-link" href="http://www.facebook.com/universoproducao"><span class="icon icon-facebook"></span></a></li>
        <li class="static-social-item"><a target="_blank" class="static-social-link" href="http://twitter.com/universoprod"><span class="icon icon-twitter"></span></a></li>
        <li class="static-social-item"><a target="_blank" class="static-social-link" href="http://instagram.com/universoproducao"><span class="icon icon-instagram"></span></a></li>
        <li class="static-social-item"><a target="_blank" class="static-social-link" href="http://www.flickr.com/photos/universoproducao"><span class="icon icon-flickr"></span></a></li>
        <li class="static-social-item"><a target="_blank" class="static-social-link" href="http://www.youtube.com/user/universoproducao/featured"><span class="icon icon-youtube"></span></a></li>
    </ul>
</div>

<nav class="mainmenu modal" id="mainmenu" data-open="#mainmenu-access">
    <div class="modal-header">
        <a href="#" class="modal-action modal-close">
            <span class="icon icon-cross2"></span>
        </a>
    </div>
</nav>

<div class="userlogin modal" id="userlogin" data-open="#userlogin-access">
    <div class="modal-header">
        <a href="#" class="modal-action modal-close">
            <span class="icon icon-cross2"></span>
        </a>
    </div>
    <div class="modal-content">
        <div class="userlogin-wrapper">
            <p class="userlogin-title"><strong>Meu</strong>Universo</p>
            <form action="" class="userlogin-form">
                <input class="input" name="login" placeholder="Login, e-mail ou CPF">
                <input class="input" name="password" placeholder="Senha">
                <button class="submit" class="userlogin-submit">Entrar</button>
            </form>
            <div class="userlogin-tricks">
                <p class="tricks-item"><a href="#" class="tricks-link">Esqueci minha senha</a></p>
                <p class="tricks-item"><a href="#" class="tricks-link">Quero me cadastrar</a></p>
                <p class="tricks-item tricks-item--separator"><span>ou</span></p>
                <p class="tricks-item"><a href="#" class="submit tricks-link tricks-link--facebook">Entrar com o Facebook</a></p>
            </div>
        </div>
    </div>
</div>

<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="/bower_components/jquery/dist/jquery.min.js"><\/script>')</script>

<script src="<?php echo $this->basePath('assets/universoproducao/dist'); ?>/scripts/vendor.js"></script>
<script src="<?php echo $this->basePath('assets/universoproducao/dist'); ?>/scripts/main.js"></script>
<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-10028533-1', 'auto');
    ga('send', 'pageview');

</script>
</body>
</html>