<div class="breadcrumbs">
	<ul class="breadcrumbs__list">
		<li class="breadcrumbs__list-item"><a class="breadcrumbs__link" href="">Página Inicial</a></li>
		<li class="breadcrumbs__list-item"><a class="breadcrumbs__link" href="">Notícias</a></li>
	</ul>
</div>

<header class="main__header">
	<h1 class="main__title">Cine-Concertos em Dois Programas Inéditos Comemoram os 10 Anos de CineOP em BH</h1>
	<time class="main__date">28 Jan 2015</time>
</header>

<div class="main__bg">
	<figure>
		<img class="main__bg-img" src="images/main-bg.jpg" alt="">
		<figcaption>Apresentação Sons & Imagens com a Associação Francesa Double Cadence</figcaption>
	</figure>
</div>

<div class="main__wrapper">
	<p>Em 2015, a CineOP celebra 10 anos e estende sua programação para a capital mineira em apresentações inéditas do Cine-Concerto Sons & Imagens com trilha executada ao vivo pelos músicos franceses da associação DoubleCadence. As pré-estreias nacionais dos espetáculos acontecem nos dias 24 e 25 de junho, às 20horas,  no Teatro Oi Futuro BH (Av. Afonso Pena, 4001), com entrada franca.</p>
	<p>No dia 24 de junho, quarta-feira, será apresentado o programa intitulado Soma de Todos os Tempos que exibe quatro curtas clássicos franceses emblemáticos, numa sessão que homenageia o cinema mudo, com trilha executada ao vivo, ao mesmo tempo em que oferece uma releitura original e contemporânea à experiência. Os filmes da sessão são "La petite marchande aux allumettes", de Jean Renoir (1928), " Der Scheintote Chinese", de Lotte Reiniger (1923), “Le piano Irrésistible”, de Alice Guy (1907) e “Sun Air de Charleston", de  Jean Renoir (1926).</p>
	<p>No dia 25 de junho, quinta-feira, é a estreia mundial do  programa Homenagens Históricas concebido exclusivamente para comemorar para os 10 anos da CineOP  e promover um triplo tributo: aos 120 anos da primeira projeção pública do cinematógrafo, com a exibição de curtas-metragens dos irmãos Lumiére realizados em 1895; aos 450 anos do Rio de Janeiro, com imagens amadoras inéditas, registradas entre os anos 1920 e 1980 por famílias cariocas e consideradas algumas das primeiras cenas filmadas na Cidade Maravilhosa; e ao cineasta português Manoel de Oliveira, falecido em 2015 aos 106 anos e cujo primeiro filme, o curta Douro, Faina Fluvial (1931), será exibido.</p>
	<p>Com sede em Paris e Toulouse, a Associação Double Cadence é composta por artistas com atuação interdisciplinar em diversos âmbitos culturais como música, cinema, artes visuais, circo e dança. Na apresentação, os integrantes vão acompanhar, musical e sonoramente, um conjunto de curtas-metragens históricos, de modo a promover um mergulho sensorial ao passado ao mesmo tempo em que celebram o contemporâneo com recursos modernos de criação de sons. Nestas apresentações, o grupo será representado pelos músicos Céline Benezeth (violino) e Marco Pereira (piano).</p>
</div>