<?php $form = $this->searchForm; ?>
<div class="row">
	<div class="col-md-12">
		<div class="portlet light portlet-fit portlet-datatable bordered table-order" data-item="tr.programing-item">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-th-list"></i>
					Grade da Programação
				</div>
				<div class="actions">
					<!--<a href="<?php /*echo $this->url('admin/default', ['controller' => 'programing-generic', 'action'=>'create']); */?>"
					   class="btn blue btn-lg">
						<i class="fa fa-plus"></i>
						<span class="hidden-xs"> Cadastrar item </span>
					</a>-->
                    <a href="#"
                       class="btn blue btn-lg table-order-save">
                        <i class="fa fa-check"></i>
                        <span class="hidden-xs"> Salvar ordem </span>
                    </a>
				</div>
			</div>

			<div class="portlet-body">
				<div class="table-container post-list">
					<table class="table table-striped table-bordered table-hover programing-table-sortable">
						<thead>
							<tr role="row" class="heading">
								<th width="2%">#</th>
								<th width="15%">Evento</th>
								<th width="15%">Tipo</th>
								<th width="15%">Data</th>
								<th width="10%">Início</th>
                                <th width="10%">Fim</th>
                                <th width="15%">Local</th>
								<th width="15%">Ações</th>
							</tr>
                            <tr role="row" class="filter">
                                <?php $form->prepare(); echo $this->form()->openTag($form); ?>
                                <td></td>
                                <td><?php echo $this->formelement($form->get('event')); ?></td>
                                <td><?php echo $this->formelement($form->get('type')); ?></td>
                                <td><?php echo $this->formelement($form->get('date')); ?></td>
                                <td><?php echo $this->formelement($form->get('start_time')); ?></td>
                                <td><?php echo $this->formelement($form->get('end_time')); ?></td>
                                <td><?php echo $this->formelement($form->get('place')); ?></td>
                                <td>
                                    <div class="margin-bottom-5">
                                        <button class="btn btn-sm blue filter-submit margin-bottom"><i class="fa fa-search"></i> Pesquisar</button>
                                        <button class="btn btn-sm btn-default filter-cancel"><i class="fa fa-times"></i> Limpar</button>
                                    </div>
                                </td>
                                <?php echo $this->form()->closeTag(); ?>
                            </tr>
						</thead>
						<tbody>
                        <form action="<?php echo $this->url('admin/default', ['controller'=>'programing-grid', 'action'=>'order']) ?>" method="POST" class="table-order-form">
                            <?php foreach ($this->items as $i):

                                $updateUrl = $this->url('admin/default', [
                                    'controller' => 'programing-generic',
                                    'action' => 'update',
                                    'id' => $i->getId()
                                ]);

                                $removeUrl = $this->url('admin/default', [
                                    'controller' => 'programing-generic',
                                    'action'=>'delete',
                                    'id'=>$i->getId()
                                ]);
                                ?>
                                <tr class="programing-item" data-id="<?php echo $i->getId() ?>">
                                    <td><input type="hidden" name="id[]" value="<?php echo $i->getId() ?>"></td>
                                    <td><?php echo $i->getEvent()->getShortName() ?></td>
                                    <td><?php echo \Application\Entity\Programing\Type::get($i->getType()); ?></td>
                                    <td><?php echo $i->getDate()->format('d/m/Y') ?></td>
                                    <td><?php echo $i->getStartTime()->format('H:i') ?></td>
                                    <td><?php echo $i->getEndTime()?$i->getEndTime()->format('H:i'):"" ?></td>
                                    <td><?php echo $i->getPlace()?$i->getPlace()->getName():"" ?></td>
                                    <td>
                                        <a href="<?php echo  $updateUrl; ?>" class="btn btn-sm btn-default">
                                            <i class="fa fa-edit"></i> Editar
                                        </a>
                                        <a href="<?php echo $removeUrl; ?>" class="btn btn-sm btn-default post-list-remove">
                                            <i class="fa fa-trash-o"></i> Excluir
                                        </a>
                                        <a class="btn btn-default programing-item-move"><i class="fa fa-arrows-v"></i> Mover</a>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                        </form>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>