<div class="container">
    <p class="meuuniverso-brand meuuniverso-brand--center"><strong>Meu</strong>Universo | Novo</p>

    <?php if(!empty($this->user->getId())): ?>
        <div class="note note-info">
            <h4 class="block">Tudo certo!</h4>
            <p>Seu cadastro foi realizadp com sucesso.<br /><br />
                <a class="btn blue" href="<?php echo $this->url('meu-universo/auth') ?>">Efetuar login</a></p>
        </div>
    <?php else: ?>
        <?php echo $this->partial("meu-universo/register/_user_form.phtml"); ?>
    <?php endif; ?>
</div>