<!doctype html>
<html class="no-js" lang="">
<head>
    <meta charset="utf-8">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Arquivo em Cartaz 2016</title>

    <link rel="apple-touch-icon" href="apple-touch-icon.png">
    <!-- Place favicon.ico in the root directory -->

    <!-- build:css styles/main.css -->
    <link rel="stylesheet" href="<?php echo $this->basePath('assets/arquivoemcartaz/dist/styles/main.css'); ?>">
    <link rel="stylesheet" href="<?php echo $this->basePath('assets/arquivoemcartaz/dist/styles/vendor.css'); ?>">
    <!-- endbuild -->

    <!-- build:js scripts/vendor/modernizr.js -->
    <script src="<?php echo $this->basePath('assets/arquivoemcartaz/dist/scripts/vendor/modernizr.js') ?>"></script>
    <!-- endbuild -->
</head>
<body>
<div class="site__wrapper">
    <header class="header">
        <div class="header-left">
            <h1 class="brand">
                <a href="<?php echo $this->url("arquivoemcartaz/home") ?>" class="brand-link">
                    <span class="brand-logo icon icon-brand2">Arquivo em Cartaz</span>
                </a>
            </h1>
        </div>

        <div class="header-right">
            <div class="menu">
                <div class="menu-button" id="mainmenu-access">
                    <div class="burger">
                        <span class="b"></span>
                        <span class="b"></span>
                        <span class="b"></span>
                        <span class="b"></span>
                    </div>
                </div>
            </div>
            <div class="search">
                <form action="" class="search-form form">
                    <input class="search-input form__input" type="text" placeholder="BUSCAR">
                </form>
                <a href="" class="search-link"><span class="search-icon icon icon-search"></span></a>
            </div>
        </div>
    </header>

    <?php echo $this->content; ?>

    <footer class="footer">
        <div class="footer__wrapper">
            <div class="footer__newsletter">
                <p class="footer__title">Receba nossos informativos</p>
                <form action="" class="form newsletter__form">
                    <input type="text" class="form__input newsletter__input" placeholder="Nome">
                    <input type="text" class="form__input newsletter__input" placeholder="Email">
                    <button href="" class="form__submit newsletter__button">Cadastrar</button>
                </form>
            </div>
            <div class="footer__contact">
                <p class="footer__title">Contato</p>
                <div class="contact">
                    <div class="contact__brand "><span class="icon icon-universo-brand"></span></div>
                    <div class="contact__add">
                        <p>+ 55 31 3282-2366</p>zf2 site
                        <p>up@universoproducao.com.br</p>
                        <p>Rua Pirapetinga, 567 - Serra</p>
                        <p>30220-150, Belo Horizonte | MG</p>
                    </div>
                </div>
            </div>

            <div class="sitemap">
                <?php $this
                    ->navigation('ArquivoemcartazNavigation')
                    ->menu()->setPartial("application/partials/sitemap.phtml");

                echo $this
                    ->navigation('ArquivoemcartazNavigation')
                    ->menu()
                    ->render(); ?>

                <!--<ul class="sitemap__items">
                    <li class="sitemap__item">
                        <a href="" class="sitemap__link">O Festival</a>
                        <ul class="sitemap__items--sub">
                            <li class="sitemap__item"><a href="" class="sitemap__link">Arquivo em Cartaz</a></li>
                            <li class="sitemap__item"><a href="" class="sitemap__link">Créditos</a></li>
                            <li class="sitemap__item"><a href="" class="sitemap__link">Parceiros</a></li>
                            <li class="sitemap__item"><a href="" class="sitemap__link">Locais</a></li>
                        </ul>
                    </li>
                    <li class="sitemap__item">
                        <a href="" class="sitemap__link">Programação</a>
                        <ul class="sitemap__items--sub">
                            <li class="sitemap__item"><a href="" class="sitemap__link">Homenagens</a></li>
                            <li class="sitemap__item"><a href="" class="sitemap__link">Filmes</a></li>
                            <li class="sitemap__item"><a href="" class="sitemap__link">Mostra</a></li>
                            <li class="sitemap__item"><a href="" class="sitemap__link">Debates</a></li>
                            <li class="sitemap__item"><a href="" class="sitemap__link">Exposição</a></li>
                            <li class="sitemap__item"><a href="" class="sitemap__link">Programação Completa</a></li>
                        </ul>
                    </li>
                    <li class="sitemap__item">
                        <a href="" class="sitemap__link">Comunicação</a>
                        <ul class="sitemap__items--sub">
                            <li class="sitemap__item"><a href="" class="sitemap__link">Notícias</a></li>
                            <li class="sitemap__item"><a href="" class="sitemap__link">Galeria</a></li>
                            <li class="sitemap__item"><a href="" class="sitemap__link">Redes Sociais</a></li>
                            <li class="sitemap__item"><a href="" class="sitemap__link">Fale Conosco</a></li>
                        </ul>
                    </li>
                    <li class="sitemap__item">
                        <a href="" class="sitemap__link">Imprensa</a>
                        <ul class="sitemap__items--sub">
                            <li class="sitemap__item"><a href="" class="sitemap__link">Credenciamento</a></li>
                            <li class="sitemap__item"><a href="" class="sitemap__link">Releases</a></li>
                            <li class="sitemap__item"><a href="" class="sitemap__link">Depoimentos</a></li>
                            <li class="sitemap__item"><a href="" class="sitemap__link">Saiu na Imprensa</a></li>
                        </ul>
                    </li>
                </ul>-->
            </div>
        </div>
        <div class="footer__end">
            <div class="footer__wrapper">
                <div class="social">
                    <ul class="">
                        <li class="social__item"><a target="_blank" href="https://www.instagram.com/universoproducao/" class="social__link"><span class="icon icon-instagram"></span></a></li>
                        <li class="social__item"><a target="_blank" href="href="href="https://www.facebook.com/universoproducao" class="social__link"><span class="icon icon-facebook"></span></a></li>
                        <li class="social__item"><a target="_blank" href="https://twitter.com/universoprod?lang=pt" class="social__link"><span class="icon icon-twitter"></span></a></li>
                        <li class="social__item"><a target="_blank" href="https://www.youtube.com/user/universoproducao" class="social__link"><span class="icon icon-youtube"></span></a></li>
                        <li class="social__item"><a target="_blank" href="https://www.flickr.com/photos/universoproducao/" class="social__link"><span class="icon icon-flickr"></span></a></li>
                    </ul>
                </div>
                <div class="site">
                    <p class="readmore">
                        <a class="readmore__link" target="_blank" href="http://www.universoproducao.com.br">Site Universo<span class="icon icon-arrow-right8"></span></a>
                    </p>
                </div>
                <p class="copy">Copyright © 2015. Universo Produção - Todos os direitos reservados.</p>
            </div>
        </div>
    </footer>
</div>

<div class="mainmenu mainmenu-modal" id="mainmenu-modal">
    <div class="mainmenu-bgc">
        <nav class="mainmenu__wrapper">
            <?php $this
                ->navigation('ArquivoemcartazNavigation')
                ->menu()->setPartial("application/partials/navigation.phtml");

            echo $this
                ->navigation('ArquivoemcartazNavigation')
                ->menu()
                ->render(); ?>
        </nav>
    </div>
</div>

<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="/bower_components/jquery/dist/jquery.min.js"><\/script>')</script>

<!-- build:js scripts/vendor.js -->
<script src="<?php echo $this->basePath('assets/arquivoemcartaz/dist/scripts/vendor.js') ?>"></script>
<!-- endbuild -->
<!-- build:js scripts/main.js -->
<script src="<?php echo $this->basePath('assets/arquivoemcartaz/dist/scripts/vendor.js') ?>"></script>
<script src="<?php echo $this->basePath('assets/arquivoemcartaz/dist/scripts/main.js') ?>"></script>
<!-- Place inline scripts here -->

<!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
<script>
    (function(c,u,s,t,o,m){c.GoogleAnalyticsObject=t;c[t]||(c[t]=
        function(){(c[t].q=c[t].q||[]).push(arguments)});c[t].l=+new Date;
        o=u.createElement(s);m=u.getElementsByTagName(s)[0];
        o.src='https://www.google-analytics.com/analytics.js';
        m.parentNode.insertBefore(o,m)}(window,document,'script','ga'));
    ga('create','UA-XXXXX-X');ga('send','pageview');
</script>
<!-- endbuild -->
</body>
</html>