<!doctype html>
<html class="no-js" lang="">
<head>
    <meta charset="utf-8">
    <meta name="description" content="">
    <meta name="keywords" content="arquivo em cartaz, festival, cinema, arquivo, universo produção">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <?php echo $this->headTitle("Arquivo em Cartaz 2017")->setSeparator(' - '); ?>

    <link rel="apple-touch-icon" href="apple-touch-icon.png">
    <!-- Place favicon.ico in the root directory -->

    <!-- build:css styles/main.css -->
    <link rel="stylesheet" href="<?php echo $this->basePath('assets/arquivoemcartaz/dist/styles/main.css'); ?>">
    <link rel="stylesheet" href="<?php echo $this->basePath('assets/arquivoemcartaz/dist/styles/vendor.css'); ?>">
    <!-- endbuild -->

    <!-- build:js scripts/vendor/modernizr.js -->
    <script src="<?php echo $this->basePath('assets/arquivoemcartaz/dist/scripts/vendor/modernizr.js') ?>"></script>
    <!-- endbuild -->

    <!--Facebook-->
    <meta property="og:url" content="<?php echo $this->serverUrl(true) ?>">
    <meta property="og:type" content="website" />

    <!-- Twitter -->
    <meta name="twitter:card" content="summary" />
    <meta name="twitter:site" content="@universoprod" />
    <meta name="twitter:creator" content="@universoprod" />

    <meta name="google-site-verification" content="LOLbpiW9x-KZp65j7ahp7D1nG09F6_kPNZwZEO7F0as" />

    <?php echo $this->headScript() ?>
</head>
<body>
<div class="site__wrapper">
    <header class="header">
        <div class="header-left">
            <h1 class="brand">
                <a href="<?php echo $this->url("arquivoemcartaz/home") ?>" class="brand-link">
                    <span class="brand-logo icon icon-brand2">Arquivo em Cartaz</span>
                </a>
            </h1>
        </div>

        <div class="header-right">
            <div class="menu">
                <div class="menu-button" id="mainmenu-access">
                    <div class="burger">
                        <span class="b"></span>
                        <span class="b"></span>
                        <span class="b"></span>
                        <span class="b"></span>
                    </div>
                </div>
            </div>
            <div class="search">
                <form action="<?php echo $this->url("arquivoemcartaz/search") ?>" method="get" class="search-form form">
                    <input name="q" class="search-input form__input" type="text" placeholder="BUSCAR">
                </form>
                <a href="" class="search-link"><span class="search-icon icon icon-search"></span></a>
            </div>
        </div>
    </header>

    <?php echo $this->content; ?>

    <footer class="footer">
        <div class="footer__wrapper">
            <div class="footer__newsletter">
                <p class="footer__title">Receba nossos informativos</p>
                <form action="<?php echo $this->url("arquivoemcartaz/newsletter"); ?>" class="form newsletter__form">
                    <input type="text" class="form__input newsletter__input" placeholder="Nome" required>
                    <input type="email" class="form__input newsletter__input" placeholder="Email" required>
                    <button type="submit" class="form__submit newsletter__button">Cadastrar</button>
                </form>
            </div>
            <div class="footer__contact">
                <p class="footer__title">Contato</p>
                <div class="contact">
                    <div class="contact__brand "><span class="icon icon-universo-brand"></span></div>
                    <div class="contact__add">
                        <p>+ 55 31 3282-2366</p>
                        <p>up@universoproducao.com.br</p>
                        <p>Rua Pirapetinga, 567 - Serra</p>
                        <p>30220-150, Belo Horizonte | MG</p>
                    </div>
                </div>
            </div>

            <div class="sitemap">
                <?php $this
                    ->navigation('ArquivoemcartazNavigation')
                    ->menu()->setPartial("arquivoemcartaz/partials/sitemap.phtml");

                echo $this
                    ->navigation('ArquivoemcartazNavigation')
                    ->menu()
                    ->render(); ?>
            </div>
        </div>
        <div class="footer__end">
            <div class="footer__wrapper">
                <div class="social">
                    <ul class="">
                        <li class="social__item"><a target="_blank" href="https://www.instagram.com/universoproducao/" class="social__link"><span class="icon icon-instagram"></span></a></li>
                        <li class="social__item"><a target="_blank" href="https://www.facebook.com/universoproducao" class="social__link"><span class="icon icon-facebook"></span></a></li>
                        <li class="social__item"><a target="_blank" href="https://twitter.com/universoprod?lang=pt" class="social__link"><span class="icon icon-twitter"></span></a></li>
                        <li class="social__item"><a target="_blank" href="https://www.youtube.com/user/universoproducao" class="social__link"><span class="icon icon-youtube"></span></a></li>
                        <li class="social__item"><a target="_blank" href="https://www.flickr.com/photos/universoproducao/" class="social__link"><span class="icon icon-flickr"></span></a></li>
                    </ul>
                </div>
                <div class="site">
                    <p class="readmore">
                        <a class="readmore__link" target="_blank" href="http://www.universoproducao.com.br">Site Universo<span class="icon icon-arrow-right8"></span></a>
                    </p>
                </div>
                <p class="copy">Copyright © 2015. Universo Produção - Todos os direitos reservados.</p>
            </div>
        </div>
    </footer>
</div>

<div class="mainmenu mainmenu-modal" id="mainmenu-modal">
    <div class="mainmenu-bgc">
        <header class="header">
            <div class="header-left">
                <h1 class="brand">
                    <a href="<?php echo $this->url("arquivoemcartaz/home") ?>" class="brand-link">
                        <span class="brand-logo icon icon-brand2">Arquivo em Cartaz</span>
                    </a>
                </h1>
            </div>

            <div class="header-right">
                <div class="menu">
                    <div class="menu-button" id="mainmenu-access">
                        <div class="burger">
                            <span class="b"></span>
                            <span class="b"></span>
                            <span class="b"></span>
                            <span class="b"></span>
                        </div>
                    </div>
                </div>
                <div class="search">
                    <form action="<?php echo $this->url("arquivoemcartaz/search") ?>" method="get" class="search-form form">
                        <input name="q" class="search-input form__input" type="text" placeholder="BUSCAR">
                    </form>
                    <a href="" class="search-link"><span class="search-icon icon icon-search"></span></a>
                </div>
            </div>
        </header>
        <nav class="mainmenu__wrapper">
            <?php $this
                ->navigation('ArquivoemcartazNavigation')
                ->menu()->setPartial("arquivoemcartaz/partials/navigation.phtml");

            echo $this
                ->navigation('ArquivoemcartazNavigation')
                ->menu()
                ->render(); ?>
        </nav>
    </div>
</div>

<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="/bower_components/jquery/dist/jquery.min.js"><\/script>')</script>

<!-- build:js scripts/vendor.js -->
<script src="<?php echo $this->basePath('assets/arquivoemcartaz/dist/scripts/vendor.js') ?>"></script>
<!-- endbuild -->
<!-- build:js scripts/main.js -->
<script src="<?php echo $this->basePath('assets/arquivoemcartaz/dist/scripts/vendor.js') ?>"></script>
<script src="<?php echo $this->basePath('assets/arquivoemcartaz/dist/scripts/main.js') ?>"></script>
<!-- Place inline scripts here -->

<!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-10028533-7', 'auto');
    ga('send', 'pageview');
</script>
<!-- endbuild -->
</body>
</html>