<!doctype html>
<html lang="">
<head>
    <meta charset="utf-8">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>hotsite_cinebh2017 2</title>

    <link rel="apple-touch-icon" href="apple-touch-icon.png">
    <!-- Place favicon.ico in the root directory -->

    <!-- build:css styles/vendor.css -->
    <!-- bower:css -->
    <!-- endbower -->
    <!-- endbuild -->

    <!-- build:css styles/main.css -->
    <link rel="stylesheet" href="<?php echo $this->basepath('assets/cinebh_hotsite/dist') ?>/styles/main.css">
    <!-- endbuild -->

</head>
<body>
<!--[if IE]>
<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
<![endif]-->

<div class="wrapper">
    <img class="bgc" src="<?php echo $this->basepath('assets/cinebh_hotsite/dist') ?>/images/bgc.jpg" alt="">

    <div class="content">
        <div class="brand">
            <img class="brand" id="Image-Maps-Com-image-maps-2017-06-05-115803" src="<?php echo $this->basepath('assets/cinebh_hotsite/dist') ?>/images/brand.jpg" border="0" width="1024" height="928" orgWidth="1024" orgHeight="928" usemap="#image-maps-2017-06-05-115803" alt="" />
            <map name="image-maps-2017-06-05-115803" id="ImageMapsCom-image-maps-2017-06-05-115803">
                <area  alt="" title="" href="www.cinemasemfronteiras.com.br/site/inscricoes.php" shape="rect" coords="40,814,120,848" style="outline:none;" target="_self"     />
                <area  alt="" title="" href="http://cinebh.com.br/inicio" shape="rect" coords="30,863,272,897" style="outline:none;" target="_self"     />
                <area shape="rect" coords="1022,926,1024,928" alt="Image Map" style="outline:none;" title="Image Map" href="http://www.image-maps.com/index.php?aff=mapped_users_0" />
            </map>


            <p class="date">22-27 AGOSTO 2017</p>
            <p class="subdate">Programação gratuita</p>

        </div>

        <div class="content-wrapper">
            <h2 class="title">Inscrições</h2>
            <p class="insc">Cine-Escola | <strong>04 de julho a 04 de Agosto</strong></p>
            <p class="insc">Oficinas e Workshops | <strong>20 de julho a 07 de Agosto</strong></p>
            <p class="insc">Mostra a Cidade em Movimento | <strong>Até 14 de Junho</strong></p>
            <p><small>(Até 21h, horário de brasília)</small></p>
            <p><a class="link" href="www.cinemasemfronteiras.com.br/site/inscricoes.php">| Clique aqui</a></p>
            <p class="insc last">| Edição Anterior | <a class="link" href="http://cinebh.com.br/inicio">Clique aqui</a></p>
        </div>

    </div>

</div>

<!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
<script>
    (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
        function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
        e=o.createElement(i);r=o.getElementsByTagName(i)[0];
        e.src='https://www.google-analytics.com/analytics.js';
        r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
    ga('create','UA-XXXXX-X');ga('send','pageview');
</script>

<!-- build:js scripts/vendor.js -->
<!-- bower:js -->
<!-- endbower -->
<!-- endbuild -->

<!-- build:js scripts/main.js -->
<script src="scripts/main.js"></script>
<!-- endbuild -->
</body>
</html>
