<?php $this->placeholder("home-class")->set("home"); ?>

<section class="banner">
    <div class="banner__items owl-carousel">
        <?php foreach ($this->bannerImages as $banner): ?>
            <a href="<?php echo $banner->getMeta('_link') ?>" <?php echo $banner->getMeta('_target_blank') ? "target='_blank'" : ""; ?> >
                <div class="banner__item item" style="background-image: url('<?php echo $this->thumbor()->url($banner->getMeta('_image'))->resize(1358, 912); ?>'); background-size: cover">
                    <p class="banner__caption"><?php echo $banner->getSubtitle(); ?></p>
                </div>
            </a>
        <?php endforeach; ?>
    </div>
</section>

<section class="programation">
    <header class="main__header main__header--bgc">
        <div class="header__wrapper">
            <h1 class="main__title">Programação</h1>
            <p class="readmore"><a class="readmore__link" href="<?php echo $this->url("cinebh/default", ['slug'=>'programacao']) ?>">Programação Completa<span class="icon icon-plus2"></span></a></p>
        </div>
    </header>

    <div class="programation__list">
        <?php if($this->programHighlight): ?>
            <div class="programation__item programation__item--highlight">
                <figure class="programation__figure">
<!--                    <img src="--><?php //echo $this->basePath("assets/cinebh/dist") ?><!--/images/prog1.jpg" alt="">-->
                    <img src="<?php echo  $this->thumbor()->url($this->programHighlight->getPhoto())->resize(1427, 833); ?>" alt="">
                </figure>
                <div class="programation__desc">
                    <p class="programation__date"><?php echo $this->programHighlight->getDate()->format('d/m') ?></p>
                    <p class="programation__day"><?php echo $this->dateFormat($this->programHighlight->getDate(), null, null, "pt_BR", "cccc"); ?></p>
                    <p class="programation__title"><strong><?php echo $this->programHighlight->getTitle(); ?></strong></p>
                    <p class="programation__title"><?php echo $this->programHighlight->getSubtitle(); ?></p>
    <!--                <p class="programation__title">Direção: Yun Jung-hee (Coréia)</p>-->
                    <p class="programation__subtitle"><?php echo $this->programHighlight->getPlace(); ?><br>
                        <?php echo $this->programHighlight->getHour(); ?></p>
                </div>
            </div>
        <?php endif; ?>
        <?php foreach ($this->program as $p): ?>
            <div class="programation__item">
                <figure class="programation__figure">
<!--                    <img src="--><?php //echo $this->basePath("assets/cinebh/dist") ?><!--/images/prog2.jpg" alt="">-->
                    <img src="<?php echo  $this->thumbor()->url($p->getPhoto())->resize(480, 480); ?>" alt="">
                </figure>
                <div class="programation__desc">
                    <p class="programation__date"><?php echo $p->getDate()->format('d/m') ?></p>
                    <p class="programation__day"><?php echo $this->dateFormat($p->getDate(), null, null, "pt_BR", "cccc"); ?></p>
                    <p class="programation__title"><?php echo $p->getTitle(); ?></p>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</section>

<?php if(count($this->news)): ?>
    <section class="news">
        <header class="main__header main__header--bgc">
            <div class="header__wrapper">
                <h1 class="main__title"><?php echo $this->translate("Notícias") ?></h1>
                <p class="readmore"><a class="readmore__link" href="<?php echo $this->url("cinebh/default", ['slug'=>'noticias']); ?>"><?php echo $this->translate("Todas as Notícias") ?><span class="icon icon-plus2"></span></a></p>
            </div>
        </header>
        <div class="news__list news__list--highlight">
            <?php foreach ($this->news as $news): ?>
                <div class="news__item">
                    <figure class="news__figure">
                        <?php if($news->getMeta('_thumb')): ?>
                            <img src="<?php echo  $this->thumbor()->url($news->getMeta('_thumb'))->resize(960, 468); ?>" alt="">
                        <?php endif; ?>
                    </figure>
                    <div class="news__desc">
                        <p class="news__title"><?php echo $news->getTitle(); ?></p>
                        <p class="news__text"><?php echo $this->truncate($news->getContent(), 150); ?></p>
                        <p class="news__button"><a class="news__link" href="<?php echo $this->url("cinebh/news", ['slug'=>$news->getSlug()]) ?>"><?php echo $this->translate("Leia Mais") ?></a></p>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    </section>
<?php endif; ?>

<?php if(count($this->gallery)): ?>
    <section class="gallery">
        <header class="main__header main__header--bgc">
            <div class="header__wrapper">
                <h1 class="main__title"><?php echo $this->translate("Galeria") ?></h1>
                <p class="readmore"><a class="readmore__link" target="_blank" href="https://www.flickr.com/photos/universoproducao/"><?php echo $this->translate("Galeria Completa") ?><span class="icon icon-plus2"></span></a></p>
            </div>
        </header>
        <div class="gallery__list owl-carousel">
            <?php foreach ($this->gallery as $img): ?>
                <div class="gallery__item">
                    <figure class="gallery__figure">
                        <img src="<?php echo $this->thumbor()->url($img->getMeta('_image'))->resize(960, 480); ?>" alt="">
                    </figure>
                    <div class="gallery__desc">
                        <p class="gallery__title"><?php echo $img->getTitle(); ?></p>
                        <p class="gallery__subtitle"><?php echo $img->getContent(); ?></p>
                        <p class="gallery__credits"><?php echo $img->getMeta('_credits'); ?></p>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    </section>
<?php endif; ?>

<section class="institutional">
    <div class="institutional__wrapper">
        <p class="institutional__title"><?php echo $this->translate("Belo Horizonte em Conexão com o mundo") ?></p>
        <div class="institutional__video">
            <iframe width="100%" height="540px" src="https://www.youtube.com/embed/YeMJyeOXtY0?rel=0&controls=0&showinfo=0" frameborder="0" allowfullscreen></iframe>
            <p class="institutional__desc"><?php echo $this->translate("VT CineBh e Brasil CineMundi"); ?></p>
        </div>
    </div>
</section>

<?php if(count($this->videos)): ?>
    <section class="tv">
        <?php
            $lastVideo = $this->videos[0];
        ?>

        <div class="tv__last">
            <figure class="tv__figure">
                <!--<img src="<?php /*echo $this->thumbor()->url($lastVideo->getThumb())->resize(959, 491); */?>" alt="">-->
                <img src="<?php echo $this->thumbor()->url($lastVideo->getThumb())->resize(959, 491); ?>" alt="">
            </figure>
            <div class="tv__last-desc">
                <p class="tv__last-title"><?php echo $lastVideo->getCaption(); ?></p>
                <a href="<?php echo $lastVideo->getYoutube(); ?>" class="tv__last-play" data-lity><span class="icon icon-play4"></span></a>
            </div>
        </div>
        <div class="tv__header">
            <p class="tv__title">Tv Mostra</p>
            <p class="tv__subtitle">Acesse o conteúdo exclusivo em vídeo dos principais momentos da 10ª CineBH</p>
            <p class="tv__subtitle"><strong>Uma década de história</strong></p>
            <p class="tv__day">Dias</p>
            <ul class="tv__items">
                <?php foreach ($this->videos as $v): ?>
                    <li class="tv__item"><a class="tv__link" href="<?php echo $v->getYoutube(); ?>" data-lity><?php echo $v->getDate()->format('d'); ?></a></li>
                <?php endforeach; ?>
            </ul>
            <!--<p class="readmore"><a class="readmore__link" href="">Veja Todos os Vídeos<span class="icon icon-plus2"></span></a></p>-->
        </div>
    </section>
<?php endif; ?>


<section class="guide">
    <div class="guide__wrapper">
        <header class="guide__header">
            <h1 class="main__title"><?php echo $this->translate("Guia") ?></h1>
        </header>
        <p class="guide__highlight"><?php echo $this->translate("A cidade em movimento") ?></p>
        <ul class="guide__list">
            <li class="guide__item"><a href="<?php echo $this->url("cinebh/default", ['slug'=>'locais']) ?>" class="guide__link"><img src="<?php echo $this->basePath("assets/cinebh/dist") ?>/images/guide-place.svg"><span><?php echo $this->translate("Locais"); ?></span></a></li>
            <li class="guide__item"><a href="<?php echo $this->url("cinebh/default", ['slug'=>'turismo-e-infomacoes']) ?>" class="guide__link"><img src="<?php echo $this->basePath("assets/cinebh/dist") ?>/images/guide-tur.svg"><span><?php echo $this->translate("Turismo e Informações"); ?></span></a></li>
            <li class="guide__item"><a href="<?php echo $this->url("cinebh/default", ['slug'=>'restaurantes']) ?>" class="guide__link"><img src="<?php echo $this->basePath("assets/cinebh/dist") ?>/images/guide-res.svg"><span><?php echo $this->translate("Restaurantes"); ?></span></a></li>
            <li class="guide__item"><a href="<?php echo $this->url("cinebh/default", ['slug'=>'hoteis-e-acomodacoes']) ?>" class="guide__link"><img src="<?php echo $this->basePath("assets/cinebh/dist") ?>/images/guide-hot.svg"><span><?php echo $this->translate("Hoteis e Acomodações"); ?></span></a></li>
        </ul>

    </div>
</section>


<section class="contact">
    <div class="contact__wrapper">
        <div class="newsletter">
            <p class="newsletter__title"><?php echo $this->translate("Receba nossos informativos") ?></p>
            <form action="#" class="newsletter__form">
                <input type="text" class="newsletter__input" placeholder="<?php echo $this->translate("Nome"); ?>">
                <input type="text" class="newsletter__input" placeholder="<?php echo $this->translate("Email"); ?>">
                <button onclick="javascript:alert('Erro. Não foi possível fazer o cadastro.')" class="newsletter__submit"><?php echo $this->translate("Cadastrar"); ?></button>
            </form>
        </div>
        <div class="social">
            <p class="social__title"><?php echo $this->translate("Siga-nos"); ?>:</p>
            <ul class="social__items">
                <li class="social__item">
                    <a href="https://www.instagram.com/universoproducao/" target="_blank" class="social__link"><span class="icon icon-instagram"></span></a>
                </li>
                <li class="social__item">
                    <a href="https://twitter.com/universoprod" target="_blank" class="social__link"><span class="icon icon-twitter"></span></a>
                </li>
                <li class="social__item">
                    <a href="https://www.facebook.com/cinebh/" target="_blank" class="social__link"><span class="icon icon-facebook"></span></a>
                </li>
                <li class="social__item">
                    <a href="https://www.youtube.com/user/universoproducao" target="_blank" class="social__link"><span class="icon icon-youtube"></span></a>
                </li>
                <li class="social__item">
                    <a href="https://www.flickr.com/photos/universoproducao/" target="_blank" class="social__link"><span class="icon icon-flickr"></span></a>
                </li>
            </ul>
        </div>
    </div>
</section>

<section class="sitemap">
    <div class="sitemap__wrapper">
        <?php $this
            ->navigation('CinebhNavigation')
            ->menu()->setPartial("cinebh/partials/sitemap.phtml");

        echo $this
            ->navigation('CinebhNavigation')
            ->menu()
            ->render(); ?>
        <p class="sitemap__high"><?php echo $this->translate("o futuro nasce da história,<br />da cultura nasce<br />a arte e dela<br />o cinema") ?></p>
        <p class="sitemap__contact"><?php echo $this->translate("Contate-nos") ?></p>
        <p class="sitemap__add">
            <span class="icon icon-universo-brand"></span>
            <span>+ 55 31 3282-2366<br />
                CINEBH@universoproducao.com.br<br />
                Rua Pirapetinga, 567 - Serra<br />
                30220-150, Belo Horizonte | MG</span>
        </p>
    </div>
</section>

<section class="sponsor">
    <div class="sponsor__wrapper">
        <ul class="sponsor__list">
            <li class="sponsor__block sponsor__block--1">
                <ul class="sponsor__items">
                    <li class="sponsor__item" style="margin-top: 20px"><span class="sponsor__img"><img height="110px" src="<?php echo $this->basepath() ?>/assets/cinebh/dist/images/sponsor/lei-cultura.svg" alt=""></span></li>
                </ul>
            </li>
            <li class="sponsor__block sponsor__block--5">
                <p class="sponsor__title"><?php echo $this->translate("Patrocínio") ?></p>
                <ul class="sponsor__items">
                    <li class="sponsor__item"><span class="sponsor__img sprite sprite-sesi"></span></li>
                    <li class="sponsor__item"><span class="sponsor__img sprite sprite-materdei"></span></li>
                    <li class="sponsor__item"><span class="sponsor__img sprite sprite-copasa"></span></li>
                </ul>
                <p class="sponsor__subtitle">Realizado com recursos da Lei Municipal de Incentivo à Cultura de Belo Horizonte - Projeto: 167/2015 | Valor: 100 mil reais</p>
            </li>
            <li class="sponsor__block sponsor__block--full">
                <p class="sponsor__title"><?php echo $this->translate("Apoio") ?></p>
                <ul class="sponsor__items">
                    <li class="sponsor__item"><span class="sponsor__img sprite sprite-universocultural"></span></li>
                    <li class="sponsor__item"><span class="sponsor__img sprite sprite-inhotim"></span></li>
                    <li class="sponsor__item"><span class="sponsor__img sprite sprite-globominas"></span></li>
                    <li class="sponsor__item"><span class="sponsor__img sprite sprite-hoteisothon"></span></li>
                    <li class="sponsor__item"><span class="sponsor__img sprite sprite-fundacaoclovissalgado"></span></li>
                    <li class="sponsor__item"><span class="sponsor__img sprite sprite-minasgerais"></span></li>
                    <li class="sponsor__item"><span class="sponsor__img sprite sprite-heineken"></span></li>
                </ul>
            </li>
            <li class="sponsor__block sponsor__block--2">
                <p class="sponsor__title"><?php echo $this->translate("Patrocínio Brasilcinemundi") ?></p>
                <ul class="sponsor__items">
                    <li class="sponsor__item"><span class="sponsor__img sprite sprite-codemig"></span></li>
                </ul>
            </li>
            <li class="sponsor__block sponsor__block--4">
                <p class="sponsor__title"><?php echo $this->translate("COOPERAÇÃO BRASIL CINEMUNDI") ?></p>
                <ul class="sponsor__items">
                    <li class="sponsor__item"><span class="sponsor__img sprite sprite-vs2016"></span></li>
                    <li class="sponsor__item"><span class="sponsor__img sprite sprite-cinelatino"></span></li>
                    <li class="sponsor__item"><span class="sponsor__img sprite sprite-torinofilmlab"></span></li>
                    <li class="sponsor__item"><span class="sponsor__img sprite sprite-doc"></span></li>
                </ul>
            </li>
            <li class="sponsor__block sponsor__block--full">
                <p class="sponsor__title"><?php echo $this->translate("APOIO BRASILCINEMUNDI") ?></p>
                <ul class="sponsor__items">
                    <li class="sponsor__item"><span class="sponsor__img sprite sprite-sebrae"></span></li>
                    <li class="sponsor__item"><span class="sponsor__img sprite sprite-vrasil"></span></li>
                    <li class="sponsor__item"><span class="sponsor__img sprite sprite-cinemadobrasil"></span></li>
                    <li class="sponsor__item"><span class="sponsor__img sprite sprite-cine"></span></li>
                    <li class="sponsor__item"><span class="sponsor__img sprite sprite-parati"></span></li>
                    <li class="sponsor__item"><span class="sponsor__img sprite sprite-cinecolor"></span></li>
                    <li class="sponsor__item"><span class="sponsor__img sprite sprite-dot"></span></li>
                    <li class="sponsor__item"><span class="sponsor__img sprite sprite-ciario"></span></li>
                    <li class="sponsor__item"><span class="sponsor__img sprite sprite-centrotecnicoaudiovisual"></span></li>
                    <li class="sponsor__item"><span class="sponsor__img sprite sprite-mistika"></span></li>
                </ul>
            </li>
            <li class="sponsor__block sponsor__block--full">
                <p class="sponsor__title"><?php echo $this->translate("Realização") ?></p>
                <ul class="sponsor__items">
                    <li class="sponsor__item"><span class="icon icon-universo-brand"></span></li>
                    <li class="sponsor__item" style="float: right"><span class="sponsor__img"><img height="70px" src="<?php echo $this->basepath() ?>/assets/cinebh/dist/images/sponsor/brasil.svg" alt=""></span></li>
                </ul>
            </li>
        </ul>
    </div>
</section>
