<?php $this->placeholder("home-class")->set("home"); ?>

<?php if(count($this->bannerImages )): ?>
<section class="banner">
    <div class="owl-carousel">
        <?php foreach ($this->bannerImages as $banner): ?>
            <div class="item">
                <a href="http://www.flickr.com/photos/universoproducao" target="_blank">
                    <img src="<?php echo $this->thumbor()->url($banner->getMeta('_image'))->resize(1920, 700); ?>" alt="">
                    <p class="banner-caption"><?php echo $banner->getSubtitle(); ?></p>
                </a>
            </div>
        <?php endforeach; ?>
    </div>
</section>
<?php endif; ?>