<!doctype html>
<html class="no-js" lang="">
<head>
	<meta charset="utf-8">
	<meta name="description" content="">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>11a CineOP</title>

	<link rel="apple-touch-icon" href="apple-touch-icon.png">
	<!-- Place favicon.ico in the root directory -->

	<!-- build:css styles/vendor.css -->
	<!-- bower:css -->
	<!-- endbower -->
	<!-- endbuild -->

	<!-- build:css styles/main.css -->
	<link rel="stylesheet" href="<?php echo $this->basePath('assets/cineop/dist/styles/main.css') ?>">
	<!-- endbuild -->

	<!-- build:js scripts/vendor/modernizr.js -->
	<script src="<?php echo $this->basePath('assets/cineop/bower_components/modernizr/modernizr.js') ?>"></script>
	<!-- endbuild -->
</head>
<body class="home">
<!--[if lt IE 10]>
<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
<![endif]-->

<div class="site-wrapper">

	<header class="header">
		<div class="header-left">
			<div class="menu-button" id="mainmenu-access">
				<div class="burger">
					<span class="b"></span>
					<span class="b"></span>
					<span class="b"></span>
					<span class="b"></span>
				</div>
			</div>
			<!--<div class="header__search">
				<span class="icon icon-search"></span>
				<form class="header__search-form" action="">
					<input class="header__search-input" type="text" name="q" placeholder="Buscar">
				</form>
				<script>
					(function() {
						var cx = '004056108255715595582:3lo3-essapk';
						var gcse = document.createElement('script');
						gcse.type = 'text/javascript';
						gcse.async = true;
						gcse.src = 'https://cse.google.com/cse.js?cx=' + cx;
						var s = document.getElementsByTagName('script')[0];
						s.parentNode.insertBefore(gcse, s);
					})();
				</script>
				<gcse:search></gcse:search>
			</div>-->
		</div>
		<div class="header-right">
			<h1 class="brand">
				<a href="<?php echo $this->url('cineop'); ?>" class="brand-link">
					<span class="brand-logo">
						11 Mostra de Cinema de Ouro Preto
					</span>
				</a>
			</h1>
		</div>
	</header>

	<main class="main">
		<?php echo $this->content; ?>
	</main>

	<footer class="footer">
		<div class="footer__wrapper">
			<div class="newsletter">
				<p class="newsletter__title">Receba nossos informativos</p>
				<form action="<?php echo $this->url('cineop') ?>newsletter" method="POST" class="newsletter__form">
					<input required type="text" class="form__input form__input--big" placeholder="Nome">
					<input required type="text" class="form__input form__input--big" placeholder="Email">
					<select required name="" id="" class="form__input">
						<option value="" selected>Estado</option>
						<option value="Acre">Acre</option>
						<option value="Alagoas">Alagoas</option>
						<option value="Amapá">Amapá</option>
						<option value="Amazonas">Amazonas</option>
						<option value="Bahia">Bahia</option>
						<option value="Ceará">Ceará</option>
						<option value="Distrito Federal">Distrito Federal</option>
						<option value="Espírito Santo">Espírito Santo</option>
						<option value="Goiás">Goiás</option>
						<option value="Maranhão">Maranhão</option>
						<option value="Mato Grosso">Mato Grosso</option>
						<option value="Mato Grosso do Sul">Mato Grosso do Sul</option>
						<option value="Minas Gerais">Minas Gerais</option>
						<option value="Pará">Pará</option>
						<option value="Paraíba">Paraíba</option>
						<option value="Paraná">Paraná</option>
						<option value="Pernambuco">Pernambuco</option>
						<option value="Piauí">Piauí</option>
						<option value="Rio de Janeiro">Rio de Janeiro</option>
						<option value="Rio Grande do Norte">Rio Grande do Norte</option>
						<option value="Rio Grande do Sul">Rio Grande do Sul</option>
						<option value="Rondônia">Rondônia</option>
						<option value="Roraima">Roraima</option>
						<option value="Santa Catarina">Santa Catarina</option>
						<option value="São Paulo">São Paulo</option>
						<option value="Sergipe">Sergipe</option>
						<option value="Tocantins">Tocantins</option>
					</select>
					<button type="submit" class="form__button">Cadastrar</button>
				</form>
			</div>

			<div class="sitemap">
				<?php echo $this->cineopMenu()->renderSiteMap(); ?>
			</div>

			<div class="contact">
				<div class="contact__wrapper">
					<div class="contact__col">
						<p class="contact__title">Contato</p>
						<div class="contact__brand sprite sprite-brand-universo">Universo Produção</div>
						<div class="contact__add">
							<p>+ 55 31 3282-2366</p>
							<p>cineop@universoproducao.com.br</p>
							<p>Rua Pirapetinga, 567 - Serra</p>
							<p>30220-150, Belo Horizonte | MG</p>
						</div>
					</div>

					<div class="contact__col">
						<p class="contact__title">Redes Sociais</p>
						<ul class="contact__social">
							<li class="social__item"><a target="_blank" href="https://www.instagram.com/universoproducao/" class="social__link"><span
										class="icon icon-instagram"></span></a></li>
							<li class="social__item"><a target="_blank" href="https://www.facebook.com/universoproducao" class="social__link"><span
										class="icon icon-facebook"></span></a></li>
							<li class="social__item"><a target="_blank" href="https://twitter.com/universoprod?lang=pt" class="social__link"><span
										class="icon icon-twitter"></span></a></li>
							<li class="social__item"><a target="_blank" href="https://www.youtube.com/user/universoproducao" class="social__link"><span
										class="icon icon-youtube"></span></a></li>
							<li class="social__item"><a target="_blank" href="https://www.flickr.com/photos/universoproducao/" class="social__link"><span
										class="icon icon-flicker"></span></a></li>
						</ul>
					</div>

					<div class="copy">
						<p>Copyright © 2015. Universo Produção - Todos os direitos reservados.</p>
					</div>
				</div>
			</div>
		</div>
	</footer>
</div>

<div class="invisibles">
	<?php echo $this->cineopMenu()->render(); ?>
</div>

<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="/bower_components/jquery/dist/jquery.min.js"><\/script>')</script>

<!-- build:js scripts/vendor.js -->
<!-- bower:js -->
<script src="<?php echo $this->basePath('assets/cineop/bower_components/perfect-scrollbar/js/perfect-scrollbar.jquery.js') ?>"></script>
<script src="<?php echo $this->basePath('assets/cineop/bower_components/jquery-easing-original/jquery.easing.min.js') ?>"></script>
<script src="<?php echo $this->basePath('assets/cineop/bower_components/jquery-mousewheel/jquery.mousewheel.js') ?>"></script>
<script src="<?php echo $this->basePath('assets/cineop/bower_components/jquery_nicescroll/nicescroll.js') ?>"></script>
<script src="<?php echo $this->basePath('assets/cineop/bower_components/jquery.advancedbreak/jquery.advancedBreak.js') ?>"></script>
<script src="<?php echo $this->basePath('assets/cineop/bower_components/jquery.advancedScroll/jquery.advancedScroll.js') ?>"></script>
<script src="<?php echo $this->basePath('assets/cineop/bower_components/slick-carousel/slick/slick.js') ?>"></script>
<!-- endbower -->
<!-- endbuild -->
<!-- build:js scripts/main.js
<script src="<?php echo $this->basePath('assets/cineop/dist/scripts/vendor/jquery.bez.min.js') ?>"></script>
<script src="<?php echo $this->basePath('assets/cineop/dist/scripts/plugins.js') ?>"></script> -->
<script src="<?php echo $this->basePath('assets/cineop/dist/scripts/main.js') ?>"></script>
<!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-10028533-4', 'auto');
    ga('send', 'pageview');
</script>
<!-- endbuild -->
</body>
</html>

