<?php $form = $this->form; ?>
<div class="row post news">
	<div class="col-md-12">
		<?php $form->prepare(); echo $this->form(null, null)->openTag($form) ?>
		<div class="portlet light portlet-fit bordered">
			<div class="portlet-title">
				<div class="caption">
					<?php if($this->message->getId()): ?>
					<i class="fa fa-edit"></i>
					Editar Mensagem
					<?php else: ?>
					<i class="fa fa-file-o"></i>
					Cadastrar Mensagem
					<?php endif; ?>
				</div>
				<div class="actions">
					<a href="<?php echo $this->url('admin/default', ['controller'=>'message']); ?>"
					   class="btn btn-default">
						<i class="icon-action-undo"></i>
						<span class="hidden-xs"> Voltar </span>
					</a>
                    <a href="<?php echo $this->url('admin/default', ['controller'=>'message', 'action'=>'create']); ?>"
                       class="btn blue btn-lg">
                        <i class="fa fa-plus"></i>
                        <span class="hidden-xs"> Nova Mensagem  </span>
                    </a>
				</div>
			</div>
			<div class="portlet-body">
				<div class="portlet">

					<div class="portlet-body form">
						<div class="form-body">
                            <div class="row">
                                <?php echo $this->formRow($form->get('type')); ?>
                                <?php echo $this->formRow($form->get('subject')); ?>

                                <?php
                                    $type = $form->get('type')->getValue();
                                    $vars = \Application\Entity\Message\MessageType::getVariablesByType($type);
                                    if($vars): ?>
                                    <div class="col-md-6 col-md-offset-4">
                                        <div class="portlet light portlet-fit bordered">
                                            <div class="portlet-title">Variáveis</div>
                                            <div class="portlet-body">
                                                <?php foreach ($vars as $key=>$varLabel): ?>
                                                    <button data-clipboard-text="<?php echo $key ?>" type="button" class="btn btn-default margin-bottom-5 data-copy">
                                                        <?php echo $key . " - " . $varLabel ?>
                                                    </button>
                                                <?php endforeach; ?>
                                            </div>
                                        </div>
                                    </div>
                                <?php endif; ?>
                                <?php echo $this->formRow($form->get('body')); ?>
                                <?php echo $this->formRow($form->get('status')); ?>
                            </div>
                        </div>
						<div class="form-actions">
							<div class="row">
								<div class="col-md-offset-3 col-md-9">
									<button type="submit" class="btn blue btn-lg action-save">Salvar</button>
									<a href="#" class="btn red btn-lg action cancel">Descartar</a>
								</div>
							</div>
						</div>

					</div>
				</div>
			</div>
		</div>
		<?php echo $this->form()->closeTag() ?>
	</div>
</div>
<?php
$this->inlineScript()->captureStart();
echo <<<JS
    $('[name="type"]').on('change', function() {
        var form = $('.message-form'),
            selected = $('option:selected', $(this)),
            validate = form.validate();
        
        validate.destroy();
        
        form.append($('<input type="hidden" name="no-validate" value="no-validate">'));
        form.submit();

        App.blockUI({
            cenrerY: true,
            animate: true
        });
    });
JS;
$this->inlineScript()->captureEnd();
?>

