<?php $form = $this->form; ?>
<div class="row post news">
	<div class="col-md-12">
		<?php $form->prepare(); echo $this->form(null, null)->openTag($form) ?>
		<div class="portlet light portlet-fit bordered">
			<div class="portlet-title">
				<div class="caption">
					<?php if($this->message->getId()): ?>
					<i class="fa fa-edit"></i>
					Editar Mensagem
					<?php else: ?>
					<i class="fa fa-file-o"></i>
					Cadastrar Mensagem
					<?php endif; ?>
				</div>
				<div class="actions">
					<a href="<?php echo $this->url('admin/default', ['controller'=>'message']); ?>"
					   class="btn btn-default">
						<i class="icon-action-undo"></i>
						<span class="hidden-xs"> Voltar </span>
					</a>
                    <a href="<?php echo $this->url('admin/default', ['controller'=>'message', 'action'=>'create']); ?>"
                       class="btn blue btn-lg">
                        <i class="fa fa-plus"></i>
                        <span class="hidden-xs"> Nova Mensagem  </span>
                    </a>
				</div>
			</div>
			<div class="portlet-body">
				<div class="portlet">

					<div class="portlet-body form">
						<div class="form-body">
                            <div class="row">
                                <?php echo $this->formRow($form->get('type')); ?>
                                <?php echo $this->formRow($form->get('subject')); ?>
                                <div class="col-md-6">
                                    <div class="portlet light">
                                        <div class="portlet-body">
                                            <?php $type = $form->get('type')->getValue();
                                            foreach (\Application\Entity\Message\MessageType::getVariablesByType($type) as $key=>$varLabel): ?>
                                                <button type="button" class="btn btn-default"><?php echo $varLabel ?></button>
                                            <?php endforeach; ?>
                                        </div>
                                    </div>
                                </div>
                                <?php echo $this->formRow($form->get('body')); ?>
                                <?php echo $this->formRow($form->get('status')); ?>
                            </div>
                        </div>
						<div class="form-actions">
							<div class="row">
								<div class="col-md-offset-3 col-md-9">
									<button type="submit" class="btn blue btn-lg action-save">Salvar</button>
									<a href="#" class="btn red btn-lg action cancel">Descartar</a>
								</div>
							</div>
						</div>

					</div>
				</div>
			</div>
		</div>
		<?php echo $this->form()->closeTag() ?>
	</div>
</div>