<div class="main__figure">
    <img src="<?php echo $this->basePath("assets/cinebh/dist") ?>/images/internal.jpg" alt="">
</div>

<div class="breadcrumbs">
    <div class="breadcrumbs__wrapper">
        <ul class="breadcrumbs__list">
            <li class="breadcrumbs__item"><a href="" class="breadcrumbs__link">Início</a></li>
            <li class="breadcrumbs__item"><a href="" class="breadcrumbs__link">Notícias</a></li>
            <li class="breadcrumbs__item"><a href="" class="breadcrumbs__link">No domingo, penultimo dia bla bla...</a></li>
        </ul>
    </div>
</div>

<section class="main__wrapper">
    <header class="main__header">
        <h1 class="main__title"><?php echo $post->getTitle() ?></h1>
    </header>

    <div class="news__list">
        <?php foreach ($this->newsList as $news): ?>
            <article class="news__item">
                <header class="news__header">
                    <h1 class="news__title"><?php  echo $news->getTitle(); ?></h1>
                </header>
                <?php if($news->getThumb()): ?>
                    <figure class="news__figure"><img src="<?php echo $this->thumbor()->url($news->getThumb())->resize(270, 180); ?>" alt=""></figure>
                <?php endif; ?>
                <p class="news__desc"><?php  echo $this->truncate($news->getContent(), 350); ?></p>
                <a href="<?php echo $this->url("cinebh/news", ['slug'=>$news->getSlug()]) ?>" class="news__link readmore-2">Leia a notícia completa</a>
            </article>
        <?php endforeach; ?>
    </div>
</section>