<div class="main__figure">
    <?php if($post->getCover()): ?>
        <img src="<?php echo $this->thumbor()->url($post->getCover())->resize(1920, 492); ?>" alt="">
    <?php else: ?>
        <img src="<?php echo $this->basePath("assets/cinebh/dist") ?>/images/internal.jpg" alt="">
    <?php endif; ?>
</div>

<?php if($this->breadcrumbs): ?>
    <?php echo $this->partial('cinebh/partials/_breadcrumbs.phtml', ['breadcrumbs'=>$this->breadcrumbs]); ?>
<?php endif; ?>

<section class="main__wrapper">
    <header class="main__header">
        <h1 class="main__title"><?php echo $post->getTitle() ?></h1>
    </header>

    <div class="news__list">
        <?php foreach ($this->newsList as $news): ?>
            <article class="news__item">
                <header class="news__header">
                    <h1 class="news__title"><?php  echo $news->getTitle(); ?></h1>
                </header>
                <?php if($news->getThumb()): ?>
                    <figure class="news__figure"><img src="<?php echo $this->thumbor()->url($news->getThumb())->resize(270, 180); ?>" alt=""></figure>
                <?php endif; ?>
                <p class="news__desc"><?php  echo $this->truncate($news->getContent(), 350); ?></p>
                <a href="<?php echo $this->url("cinebh/news", ['slug'=>$news->getSlug()]) ?>" class="news__link readmore-2">Leia a notícia completa</a>
            </article>
        <?php endforeach; ?>
    </div>
</section>