<div class="main__figure">
    <img src="<?php echo $this->basePath("assets/cinebh/dist") ?>/images/internal.jpg" alt="">
</div>

<div class="breadcrumbs">
    <div class="breadcrumbs__wrapper">
        <ul class="breadcrumbs__list">
            <li class="breadcrumbs__item"><a href="" class="breadcrumbs__link">Início</a></li>
            <li class="breadcrumbs__item"><a href="" class="breadcrumbs__link">Notícias</a></li>
            <li class="breadcrumbs__item"><a href="" class="breadcrumbs__link">No domingo, penultimo dia bla bla...</a></li>
        </ul>
    </div>
</div>

<section class="main__wrapper">
    <header class="main__header">
        <h1 class="main__title"><?php echo $this->post->getTitle(); ?></h1>
    </header>
    <?php echo $this->post->getContent(); ?>
</section>