<?php $form = $this->form; ?>
<div class="portlet">
    <div class="portlet-body form">
        <?php $form->prepare(); echo $this->form(null, null)->openTag($form) ?>
        <div class="form-body">

            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <?php
                            $userName = $this->sub->getUser()?$this->sub->getUser()->getName():"";
                            $userId = $this->sub->getUser()?$this->sub->getUser()->getId():""; ?>
                        <label>Usuário</label>
                        <div class="input-group">
                            <input readonly type="text" id="authorName" class="form-control" value="<?php echo $userName ?>">
                            <span class="input-group-btn">
                            <button
                                    class="btn user-modal"
                                    type="button"
                                    data-user-id="<?php echo $userId; ?>"
                                    data-select-id-to="#user"
                                    data-select-name-to="#authorName">
                                <i class="fa fa-search"></i>
                            </button>f
                        </span>
                        </div>
                    </div>
                    <?php echo $this->formElement($form->get("user")); ?>
                </div>
            </div>

            <div class="row">
                <div class="col-md-4"><?php echo $this->formRow($form->get('registration')); ?></div>
            </div>
        </div>

        <div class="form-actions">
            <div class="row">
                <div class="col-md-offset-3 col-md-9">
                    <button type="submit" class="btn blue btn-lg nestable-serialize-submit">Salvar</button>
                    <a href="#" class="btn red btn-lg action cancel">Descartar</a>
                </div>
            </div>
        </div>
        <?php echo $this->form()->closeTag() ?>
    </div>
</div>