<?php $form = $this->searchForm; ?>
<div class="row">
	<div class="col-md-12">
		<div class="portlet light portlet-fit portlet-datatable bordered">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-th-list"></i>
					Inscrição de debates
				</div>
				<div class="actions">
					<a href="<?php echo $this->url('admin/default', ['controller' => 'seminar-subscription', 'action'=>'create']); ?>"
					   class="btn blue btn-lg">
						<i class="fa fa-plus"></i>
						<span class="hidden-xs"> Incluir inscrição </span>
					</a>
                    <div class="btn-group">
                        <a class="btn btn-default dropdown-toggle" href="javascript:;" data-toggle="dropdown">
                            <i class="fa fa-share"></i>
                            <span class="hidden-xs"> Opções </span>
                            <i class="fa fa-angle-down"></i>
                        </a>
                        <div class="dropdown-menu pull-right">
                            <li>
                                <a class="report-link"
                                   data-form="#seminar-subscription-search"
                                   data-url="<?php echo $this->url('admin/default', ['controller'=>'seminar-subscription', 'action'=>'export-list']) ?>"
                                   href="#"> Exportar para Excel </a>
                            </li>
                        </div>
                    </div>
				</div>
			</div>

			<div class="portlet-body">
				<div class="table-container post-list">
					<table class="table table-striped table-bordered table-hover">
						<thead>
							<tr role="row" class="heading">
								<th width="2%">ID</th>
                                <th width="15%">Usuário</th>
								<th width="25%">Categoria</th>
                                <th width="15%">Evento</th>
								<th width="18%">Data</th>
								<th width="18%">Ações</th>
							</tr>
                            <tr role="row" class="filter">
                                <?php $form->prepare(); echo $this->form()->openTag($form); ?>
                                <td><?php echo $this->formElement($form->get('id')); ?></td>
                                <td><?php echo $this->formElement($form->get('user')); ?></td>
                                <td><?php echo $this->formElement($form->get('category')); ?></td>
                                <td><?php echo $this->formElement($form->get('event')); ?></td>
                                <td>
                                    <div class="input-group date date-picker margin-bottom-5" data-date-format="dd/mm/yyyy">
                                        <?php echo $this->formelement($form->get('dateInit')); ?>
                                        <span class="input-group-btn">
                                            <button class="btn btn-sm default" type="button">
                                                <i class="fa fa-calendar"></i>
                                            </button>
                                        </span>
                                    </div>
                                    <div class="input-group date date-picker" data-date-format="dd/mm/yyyy">
                                        <?php echo $this->formelement($form->get('dateEnd')); ?>
                                        <span class="input-group-btn">
                                            <button class="btn btn-sm default" type="button">
                                                <i class="fa fa-calendar"></i>
                                            </button>
                                        </span>
                                    </div>
                                </td>
                                <td>
                                    <button class="btn btn-sm blue filter-submit margin-bottom-5"><i class="fa fa-search"></i> Pesquisar</button>
                                    <button class="btn btn-sm btn-default filter-cancel margin-bottom-5"><i class="fa fa-times"></i> Limpar</button>
                                </td>
                                <?php echo $this->form()->closeTag(); ?>
                            </tr>
						</thead>
						<tbody>
						<?php foreach ($this->items as $i):
                            $updateUrl = $this->url('admin/default', [
                                'controller' => 'seminar-subscription',
                                'action' => 'update',
                                'id' => $i->getId()
                            ]);

                            $removeUrl = $this->url('admin/default', [
                                'controller' => 'seminar-subscription',
                                'action'=>'delete',
                                'id'=>$i->getId()
                            ]);
							?>
							<tr>
                                <td><?php echo $i->getId() ?></td>
                                <td><?php echo $i->getUser()->getName(); ?></td>
                                <td><?php echo $i->getSeminarCategory()->getName(); ?></td>
                                <td><?php echo $i->getEvent()->getShortName(); ?></td>
                                <td><?php echo $i->getCreatedAt()->format('d/m/Y H:i:s') ?></td>
								<td>
                                    <a href="<?php echo  $updateUrl; ?>" class="btn btn-sm btn-default margin-bottom-5">
                                        <i class="fa fa-edit"></i> Editar
                                    </a>
                                    <a href="<?php echo $removeUrl; ?>" class="btn btn-sm btn-default post-list-remove margin-bottom-5">
                                        <i class="fa fa-trash-o"></i> Excluir
                                    </a></td>
							</tr>
						<?php endforeach; ?>
						</tbody>
					</table>

                    <div class="table-paginator">
                        <?php echo $this->paginationcontrol(
                            $this->items,
                            'sliding',
                            'admin/partials/paginator.phtml',
                            array(
                                'route'=>'admin/default',
                                'route_options' => [
                                    'controller' => 'seminar-subscription'
                                ]
                            )
                        ); ?>
                    </div>
				</div>
			</div>
		</div>
	</div>
</div>

<?php $this->inlineScript()->captureStart();
echo <<<JS
$( document ).ready(function() {
   $('#event').on('change', function(e) {
       App.blockUI({
           cenrerY: true,
           animate: true
       });
       var form = $('#session-school-subscription-search');
       form.submit();
   });
});
JS;
$this->inlineScript()->captureEnd(); ?>