<!doctype html>
<html lang="">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="keywords" content="cinema,mostra,bh,cinebh,internacional,film,festival">

    <title><?php echo $this->translate("CineBH - 12ª Mostra de Cinema de Belo Horizonte"); ?></title>

    <!--Facebook-->
    <meta property="og:url" content="<?php echo $this->serverUrl(true) ?>">
    <meta property="og:type" content="website" />

    <!-- Twitter -->
    <meta name="twitter:card" content="summary" />
    <meta name="twitter:site" content="@universoprod" />
    <meta name="twitter:creator" content="@universoprod" />

    <meta name="google-site-verification" content="YvbTqZPnLwRE27su8GU0nAwqVEbW8PrdsxVbfDJ4488" />

    <link rel="stylesheet" href="<?php echo $this->basePath("assets/cinebh/dist") ?>/styles/vendor.css">
    <link rel="stylesheet" href="<?php echo $this->basePath("assets/cinebh/dist") ?>/styles/main.css">

    <link rel="icon" href="<?php echo $this->basePath('assets/cinebh/dist') ?>/images/icon32.png" sizes="16x16 32x32" type="image/png">

</head>
    <body class="<?php echo $this->placeholder("home-class") ?>">

    <header class="header">
        <div class="header-wrapper">
            <div class="header-actions">
                <?php if($this->locale == 'pt'): ?>
                    <a href="<?php echo $this->url("cinebh/home", ['locale'=>'en']) ?>" class="action langselector"><span>ENGLISH</span></a>
                <?php else: ?>
                    <a href="<?php echo $this->url("cinebh/home", ['locale'=>'pt']) ?>" class="action langselector"><span>Português</span></a>
                <?php endif; ?>
                <div class="action menu-button" id="menu-button" data-src="#navigation-modal">
                    <div class="circle">
                        <div class="burger">
                            <span class="b"></span>
                            <span class="b"></span>
                            <span class="b"></span>
                            <span class="b"></span>
                        </div>
                    </div>
                    <span>menu</span>
                </div>
            </div>
        </div>
    </header>

    <main class="main">
        <?php echo $this->content; ?>
    </main>

    <footer class="footer">
        <div class="footer-wrapper">
            <div class="footer-clear">
                <div class="footer-contact">
                    <p class="footer-title"><?php echo $this->translate("Contate-nos"); ?>:</p>
                    <span class="icon icon-universo-producao"></span>
                    <span class="footer-add">+ 55 31 3282-2366<br>
                            cinebh@universoproducao.com.br<br>
                            Rua Pirapetinga, 567 - Serra<br>
                            30220-150, Belo Horizonte | MG</span>
                </div>
                <div class="footer-social">
                    <p class="footer-title"><?php echo $this->translate("Siga-nos"); ?>:</p>
                    <ul class="footer-socialitems">
                        <li class="footer-socialitem"><a class="footer-socialink" target="_blank" href="https://www.facebook.com/cinebh/"><span class="icon icon-facebook"></span></a></li>
                        <li class="footer-socialitem"><a class="footer-socialink" target="_blank" href="http://twitter.com/universoprod"><span class="icon icon-twitter"></span></a></li>
                        <li class="footer-socialitem"><a class="footer-socialink" target="_blank" href="http://instagram.com/universoproducao"><span class="icon icon-instagram"></span></a></li>
                        <li class="footer-socialitem"><a class="footer-socialink" target="_blank" href="http://www.flickr.com/photos/universoproducao"><span class="icon icon-flickr"></span></a></li>
                        <li class="footer-socialitem"><a class="footer-socialink" target="_blank" href="http://www.youtube.com/user/universoproducao/featured"><span class="icon icon-youtube"></span></a></li>
                    </ul>
                </div>
            </div>
        </div>
        <p class="footer-copy">Copyright © 2018. Universo Produção - <?php echo $this->translate("Todos os direitos reservados") ?>.</p>
    </footer>

    <?php $this
        ->navigation('CinebhNavigation')
        ->menu()->setPartial("cinebh/partials/navigation.phtml");

        echo $this
            ->navigation('CinebhNavigation')
            ->menu()
            ->render(); ?>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>

    <script src="<?php echo $this->basePath("assets/cinebh/dist") ?>/scripts/vendor.js"></script>
    <script src="<?php echo $this->basePath("assets/cinebh/dist") ?>/scripts/main.js"></script>

    <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-10028533-2', 'auto');
        ga('send', 'pageview');

    </script>
    <!-- endbuild -->
    </body>
</html>
