<!doctype html>
<html class="no-js" lang="">
<head>
    <meta charset="utf-8">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>generator custom2</title>

    <link rel="apple-touch-icon" href="apple-touch-icon.png">
    <!-- Place favicon.ico in the root directory -->

    <!-- build:css styles/main.css -->
    <link rel="stylesheet" href="<?php echo $this->basePath("assets/cinebh/dist") ?>/styles/main.css">
    <!-- endbuild -->

    <!-- build:css styles/vendor.css -->
    <!-- bower:css -->
    <!-- endbower -->
    <!-- endbuild -->


    <!-- build:js scripts/vendor/modernizr.js -->
    <script src="<?php echo $this->basePath("assets/cinebh/dist") ?>/scripts/vendor/modernizr.js"></script>
    <!-- endbuild -->
</head>
<body class="<?php echo $this->placeholder("home-class") ?>">
<div class="site__wrapper">
    <header class="header">
        <div class="header__left">
            <h1 class="header__brand"><a class="header__link" href=""></a></h1>
            <!--<img class="header__letteringform" src="images/lettering-form.svg" alt="">-->
        </div>
        <div class="header__right">
            <div class="menu">
                <div class="menu-button" id="mainmenu-access">
                    <div class="burger">
                        <span class="b"></span>
                        <span class="b"></span>
                        <span class="b"></span>
                        <span class="b"></span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <main class="main">
        <?php echo $this->content; ?>
    </main>

    <footer class="footer">
        <div class="footer__brand">
            <span class="icon icon-universo-brand-min"></span>
        </div>
        <p class="footer__copy">Copyright © 2015. Universo Produção - Todos os direitos reservados.</p>
    </footer>
</div>

<div class="mainmenu mainmenu-modal" id="mainmenu-modal">
    <div class="mainmenu-bgc">
        <div class="mainmenu__header">
            <div class="mainmenu__header-left">
                <div class="brand">
                    <a class="brand__link" href=""><span class="icon icon-cinebh"></span></a>
                </div>
            </div>
            <div class="mainmenu__header-right">
                <ul class="usermenu__list">
                    <li class="usermenu__item">
                        <a href="" class="usermenu__link"><span class="icon icon-search"></span></a>
                    </li>
                    <li class="usermenu__item">
                        <a href="" class="usermenu__link mainmenu-close"><span class="icon icon-cross2"></span></a>
                    </li>
                </ul>
            </div>
        </div>
        <nav class="mainmenu__wrapper">
            <?php $this
                ->navigation('CinebhNavigation')
                ->menu()->setPartial("application/partials/navigation.phtml");

            echo $this
                ->navigation('CinebhNavigation')
                ->menu()
                ->render(); ?>
        </nav>
        <p class="back"><a class="mainmenu-close" href="">Voltar</a></p>
    </div>
</div>

<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="/bower_components/jquery/dist/jquery.min.js"><\/script>')</script>


<script src="<?php echo $this->basePath("assets/cinebh/dist") ?>/scripts/vendor.js"></script>
<script src="<?php echo $this->basePath("assets/cinebh/dist") ?>/scripts/main.js"></script>

<!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
<script>
    (function(c,u,s,t,o,m){c.GoogleAnalyticsObject=t;c[t]||(c[t]=
        function(){(c[t].q=c[t].q||[]).push(arguments)});c[t].l=+new Date;
        o=u.createElement(s);m=u.getElementsByTagName(s)[0];
        o.src='https://www.google-analytics.com/analytics.js';
        m.parentNode.insertBefore(o,m)}(window,document,'script','ga'));
    ga('create','UA-XXXXX-X');ga('send','pageview');
</script>
<!-- endbuild -->
</body>
</html>
