<div class="row post news">
    <div class="col-md-12">

        <div class="portlet light portlet-fit bordered">
            <div class="portlet-title">
                <div class="caption">
                    <?php if($this->sub->getId()): ?>
                        <i class="fa fa-edit"></i>
                        Editar inscrição
                    <?php else: ?>
                        <i class="fa fa-file-o"></i>
                        Nova inscrição
                    <?php endif; ?>
                </div>
                <div class="actions">
                    <a href="<?php echo $this->url('admin/default', ['controller'=>'session-school-subscriptions']); ?>"
                       class="btn btn-default">
                        <i class="icon-action-undo"></i>
                        <span class="hidden-xs"> Voltar </span>
                    </a>
                    <a href="<?php echo $this->url('admin/default', ['controller'=>'session-school-subscriptions', 'action'=>'create']); ?>"
                       class="btn blue btn-lg">
                        <i class="fa fa-plus"></i>
                        <span class="hidden-xs"> Incluir inscrição  </span>
                    </a>
                </div>
            </div>
            <div class="portlet-body">
                <?php echo $this->partial('admin/session-school-subscriptions/_form.phtml', [
                    'form' => $this->form,
                    'sub'=>$this->sub
                ]); ?>
            </div>
        </div>

    </div>
</div>