<?php $form = $this->searchForm; ?>
<div class="row">
	<div class="col-md-12">
		<div class="portlet light portlet-fit portlet-datatable bordered">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-th-list"></i>
					Sessões Cine Escola
				</div>
				<div class="actions">
					<a href="<?php echo $this->url('admin/default', ['controller' => 'session-school-subscriptions', 'action'=>'create']); ?>"
					   class="btn blue btn-lg">
						<i class="fa fa-plus"></i>
						<span class="hidden-xs"> Incluir inscrição </span>
					</a>
				</div>
			</div>

			<div class="portlet-body">
				<div class="table-container post-list">
					<table class="table table-striped table-bordered table-hover">
						<thead>
							<tr role="row" class="heading">
								<th width="2%">ID</th>
								<th width="25%">Escola</th>
                                <th width="15%">Evento</th>
                                <th width="20%">Sessão</th>
								<th width="10%">Nº Alunos</th>
								<th width="10%">Série</th>
								<th width="18%">Data</th>
								<th width="18%">Ações</th>
							</tr>
                            <tr role="row" class="filter">
                                <?php $form->prepare(); echo $this->form()->openTag($form); ?>
                                <td></td>
                                <td><?php echo $this->formElement($form->get('instituition_social_name')); ?></td>
                                <td><?php echo $this->formElement($form->get('event')); ?></td>
                                <td><?php echo $this->formElement($form->get('session')); ?></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td>
                                    <button class="btn btn-sm blue filter-submit margin-bottom-5"><i class="fa fa-search"></i> Pesquisar</button>
                                    <button class="btn btn-sm btn-default filter-cancel"><i class="fa fa-times"></i> Limpar</button>
                                </td>
                                <?php echo $this->form()->closeTag(); ?>
                            </tr>
						</thead>
						<tbody>
						<?php foreach ($this->items as $i):
                            $updateUrl = $this->url('admin/default', [
                                'controller' => 'session-school-subscriptions',
                                'action' => 'update',
                                'id' => $i->getId()
                            ]);

                            $removeUrl = $this->url('admin/default', [
                                'controller' => 'session-school-subscriptions',
                                'action'=>'delete',
                                'id'=>$i->getId()
                            ]);
							?>
							<tr>
                                <td><?php echo $i->getId() ?></td>
                                <td><?php echo $i->getInstituition()->getSocialName() ?></td>
                                <td><?php echo $i->getEvent()->getShortName(); ?></td>
                                <td>
                                    <?php echo $i->getSession()->getName() ?> <br />
                                    <?php echo $i->getSessionProgramming()->getDate()->format('d/m/Y')
                                        . ' | '
                                        . $i->getSessionProgramming()->getStartTime()->format('H:i'); ?>
                                </td>
                                <td><?php echo $i->getParticipants(); ?></td>
                                <td><?php echo $i->getSeriesAge(); ?></td>
                                <td><?php echo $i->getCreatedAt()->format('d/m/Y H:i:s') ?></td>
								<td>
                                    <a href="<?php echo  $updateUrl; ?>" class="btn btn-sm btn-default margin-bottom-5">
                                        <i class="fa fa-edit"></i> Editar
                                    </a>
                                    <a href="<?php echo $removeUrl; ?>" class="btn btn-sm btn-default post-list-remove">
                                        <i class="fa fa-trash-o"></i> Excluir
                                    </a></td>
							</tr>
						<?php endforeach; ?>
						</tbody>
					</table>

                    <div class="table-paginator">
                        <?php echo $this->paginationcontrol(
                            $this->items,
                            'sliding',
                            'admin/partials/paginator.phtml',
                            array(
                                'route'=>'admin/default',
                                'route_options' => [
                                    'controller' => 'session-school-subscriptions'
                                ]
                            )
                        ); ?>
                    </div>
				</div>
			</div>
		</div>
	</div>
</div>

<?php $this->inlineScript()->captureStart();
echo <<<JS
$( document ).ready(function() {
   $('#event').on('change', function(e) {
       App.blockUI({
           cenrerY: true,
           animate: true
       });
       var form = $('#session-school-subscription-search');
       form.submit();
   });
});
JS;
$this->inlineScript()->captureEnd(); ?>