<ul class="mainmenu-list">
    <li class="mainmenu-item"><a href="<?php echo $this->url('arquivoemcartaz')?>" class="mainmenu-link">Início</a></li>
    <?php foreach ($this->container as $page):
        /** @var Zend\Navigation\Page\AbstractPage $page */
        $url = $page->hasPages() ? '#' : rawurldecode($page->getHref()); ?>
        <li class="mainmenu-item">
            <a class="mainmenu-link" href="<?php echo $url; ?>" target="<?php echo $page->getTarget() ?>">
                <?php echo $page->getLabel() ?>
            </a>
            <?php if ($page->hasPages()): ?>
            <div class="mainmenu-list--sub">
                <ul class="mainmenu-list">
                    <?php foreach ($page->getPages() as $child):
                        /** @var Zend\Navigation\Page\AbstractPage $child */ ?>
                        <li class="mainmenu-item">
                            <a class="mainmenu-link" href="<?php echo rawurldecode($child->getHref()); ?>">
                                <?php echo $child->getLabel() ?>
                            </a>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </div>
            <?php endif; ?>
        </li>
    <?php endforeach; ?>
</ul>
