<?php if($this->breadcrumbs): ?>
    <?php echo $this->partial('cinebh/partials/_breadcrumbs.phtml', ['breadcrumbs'=>$this->breadcrumbs]); ?>
<?php endif; ?>

<div class="main-wrapper">
    <section class="main-content">
        <header class="main-header">
            <h1 class="main-title"><?php echo $this->post->getTitle(); ?></h1>
        </header>
        <div class="news">
            <div class="news-items">
                <?php foreach ($this->events as $event): ?>
                    <div class="news-item" style="display: block; float: none; margin: 0 !important; padding-right:0 !important; padding-left:0 !important; padding-bottom: 1em; display: block;">
                        <p class="news-title"><?php echo $event->getFullName(); ?></p>
                        <p class="news-readmore"><a href="<?php echo $this->url("cinebh/edition", ['id'=>$event->getId()]) ?>" class="news__link readmore-2">Leia mais</a></p>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    </section>
</div>