<?php $form = $this->form; ?>
<div class="portlet light bordered">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-edit"></i>
            Categoria de arte
        </div>
    </div>

    <div class="portlet-body form">
        <?php $form->prepare(); echo $this->form()->openTag($form); ?>
        <div class="form-body">
            <?php  echo $this->formRow($form->get('name')); ?>
            <div class="row">
                <div class="col-md-9">
                    <button type="submit" class="btn blue action-save pull-right">Salvar</button>
                </div>
            </div>
        </div>

        <?php echo $this->form(null, null)->closeTag(); ?>
    </div>

    <div class="portlet-body">
        <div class="table-container post-list">
            <table class="table table-striped table-bordered table-hover">
                <thead>
                <tr role="row" class="heading">
                    <th width="2%">#</th>
                    <th width="30%">Nome</th>
                    <th width="10%">Ações</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($this->items as $item):
                    $updateUrl = $this->url('admin/default', [
                        'controller' => 'user-category',
                        'action' => 'index',
                        'id' => $item->getId()
                    ]);;
                    $removeUrl = $this->url('admin/default', [
                        'controller' => 'user-category',
                        'action' => 'delete',
                        'id' => $item->getId()
                    ]);
                    ?>
                    <tr>
                        <td></td>
                        <td><?php echo $item->getName(); ?></td>
                        <td>
                            <a href="<?php echo  $updateUrl; ?>" class="btn btn-sm btn-default">
                                <i class="fa fa-edit"></i> Editar
                            </a>
                            <a href="<?php echo $removeUrl; ?>" class="btn btn-sm btn-default post-list-remove">
                                <i class="fa fa-close"></i> Excluir
                            </a>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>


