<main class="main">
    <div class="breadcrumbs">
        <ul class="breadcrumbs-items">
            <li class="breadcrumbs-item"><a class="breadcrumbs-link" href="">Home</a></li>
            <li class="breadcrumbs-item"><a class="breadcrumbs-link" href="">12ª Cineop</a></li>
        </ul>
    </div>

    <div class="main-wrapper">
        <section class="main-content">
            <header class="main-header">
                <h1 class="main-title">Newsletter</h1>
            </header>

            <p>Cadastro realizado com sucesso</p>
        </section>
    </div>
</main>