<?php
    $form = $this->form;
    $phoneForm = $this->phoneForm;
    $phoneForm->prepare();
?>
<div class="portlet">
	<div class="portlet-body form">
		<?php $form->prepare(); echo $this->form(null, null)->openTag($form) ?>

		<div class="form-body">

            <?php if($form->getMessages()):  ?>

                <div class="portlet box red">
                    <div class="portlet-title">
                        <div class="caption">Alguns erros foram encontrados. Por favor, efetue a correção. </div>
                    </div>
                    <div class="portlet-body">
                        <?php foreach ($form->getMessages() as $field=>$message): ?>
                            <h4 class="h4">Campo <?php echo $form->get($field)->getLabel(); ?></h4>
                            <div style="padding-left: 20px">
                                <?php foreach ($message as $key=>$m): ?>
                                    <p class=""><?php echo $m ?></p>
                                <?php endforeach; ?>
                            </div>
                        <?php endforeach; ?>
                    </div>
                </div>
            <?php endif; ?>

			<h4 class="form-section">Informações Pessoais</h4>
			<div class="row">
				<div class="col-md-8"><?php echo $this->formRow($form->get('name')); ?></div>
                <div class="col-md-3"><?php echo $this->formRow($form->get('identifier')); ?></div>
            </div>
            <div class="row">
				<div class="col-md-4"><?php echo $this->formRow($form->get('email')); ?></div>
				<div class="col-md-4">
					<div class="form-group ">
						<label class="control-label">
							<?php echo $form->get('birth_date')->getLabel();  ?>
						</label>
						<div class="input-group date date-picker" data-date-format="dd/mm/yyyy">
							<?php echo $this->formElement($form->get('birth_date'));?>
							<span class="input-group-btn">
								<button type="button" name="btn-date" class="btn default">
									<span class="fa fa-fa fa-calendar"></span>
								</button>
							</span>
						</div>
						<?php echo $this->formElementErrors($form->get('birth_date')); ?>
					</div>
				</div>
                <div class="col-md-4"><?php echo $this->formRow($form->get('gender')); ?></div>
			</div>

            <h4 class="form-section">SGC</h4>
            <div class="row user-category"
                 data-url="<?php echo $this->url('admin/default', ['controller'=>'contact', 'action'=>'subcategory']); ?>"
                 data-category-element="#category"
                 data-subcategory-element="#subcategory">
                <div class="col-md-4"><?php echo $this->formRow($form->get('origin')); ?></div>
                <div class="col-md-4"><?php echo $this->formRow($form->get('category')); ?></div>
                <div class="col-md-4"><?php echo $this->formRow($form->get('subcategory')); ?></div>
            </div>
            <div class="row">
                <div class="col-md-2"><?php echo $this->formRow($form->get('status')); ?></div>
                <div class="col-md-2"><?php echo $this->formRow($form->get('tag')); ?></div>
                <div class="col-md-3"><?php echo $this->formRow($form->get('occupation')); ?></div>
                <div class="col-md-5"><?php echo $this->formRow($form->get('variable_field')); ?></div>
            </div>

			<h4 class="form-section">Endereço</h4>
			<div class="row">
				<div class="col-md-4">
				<div class="form-group <?php echo $form->get('cep')->getMessages() ? "has-error" : ""; ?>">
						<label class="control-label" for=""><?php echo $form->get('cep')->getLabel();  ?><span class="required"> * </span></label>
						<div class="input-group cep"
							 data-url-cep="<?php echo $this->url('util/cep'); ?>"
							 data-form=".user-form">
							<?php echo $this->formElement($form->get('cep')); ?>
							<span class="input-group-btn">
								<button id="searchcep" class="btn btn-success " type="button">
									<i class="fa fa fa-search fa-fw"></i> Buscar</button>
							</span>
						</div>
						<?php echo $this->formElementErrors($form->get('cep')); ?>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-md-6"><?php echo $this->formRow($form->get('address')); ?></div>
				<div class="col-md-2"><?php echo $this->formRow($form->get('number')); ?></div>
				<div class="col-md-4"><?php echo $this->formRow($form->get('district')); ?></div>
			</div>
			<div class="row state-cities"
				 data-url="<?php echo $this->url('util/cities'); ?>"
				 data-state-element="#state"
				 data-city-element="#city">
				<div class="col-md-4"><?php echo $this->formRow($form->get('state')); ?></div>
				<div class="col-md-4"><?php echo $this->formRow($form->get('city')); ?></div>
				<div class="col-md-4"><?php echo $this->formRow($form->get('complement')); ?></div>
			</div>

            <h4 class="form-section">Contatos</h4>
            <div class="form-group <?php echo $form->get('phones')->getMessages() ? "has-error" : ""; ?>">
                <?php echo $this->formElementErrors($form->get('phones')); ?>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <table class="table table-hover table-light admin-phone">
                        <thead>
                            <tr>
                                <th width="8%">DDD</th>
                                <th>Número</th>
                                <th>Nome do Contato</th>
                                <th>Tipo</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php $phones = !empty($data['phones'])
                                ? $data['phones']
                                : $this->user->getPhones();

                            foreach ($phones as $phone): if(is_object($phone)) { $phone = $phone->_toArray(); }
                                $phoneid = isset($phone['id']) ? $phone['id'] : time().rand(); ?>
                                <tr data-row="<?php echo $phoneid; ?>">
                                    <td><?php echo $phone['ddd']; ?></td>
                                    <td><?php echo $phone['number']; ?></td>
                                    <td><?php echo $phone['contact_name']; ?></td>
                                    <td><?php echo \Application\Entity\Phone\PhoneType::get($phone['type']); ?></td>
                                    <td>
                                        <a href="#" class="btn btn-sm btn-default admin-phone-remove" data-remove="<?php echo $phoneid ?>">
                                            <i class="fa fa-close"></i>
                                        </a>
                                        <input type="hidden" name="phones[<?php echo $phoneid ?>][ddd]" value="<?php echo $phone['ddd']; ?>">
                                        <input type="hidden" name="phones[<?php echo $phoneid ?>][number]" value="<?php echo $phone['number']; ?>">
                                        <input type="hidden" name="phones[<?php echo $phoneid ?>][contact_name]" value="<?php echo $phone['contact_name']; ?>">
                                        <input type="hidden" name="phones[<?php echo $phoneid ?>][type]" value="<?php echo $phone['type']; ?>">

                                    </td>
                                </tr>
                            <?php endforeach; ?>
                            <tr id="admin-phone-form">
                                <td><?php echo $this->formElement($phoneForm->get('phone[ddd]')); ?></td>
                                <td><?php echo $this->formElement($phoneForm->get('phone[number]')); ?></td>
                                <td><?php echo $this->formElement($phoneForm->get('phone[contact_name]')); ?></td>
                                <td><?php echo $this->formElement($phoneForm->get('phone[type]')); ?></td>
                                <td><button class="btn btn-sm btn-success admin-phone-add" type="button">
                                        <i class="fa fa-plus"></i> Adicionar</button></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>

			<h4 class="form-section">Outros</h4>
			<div class="row">
				<div class="col-md-12"><?php echo $this->formRow($form->get('site')); ?></div>
			</div>
			<div class="row">
				<div class="col-md-4"><?php echo $this->formRow($form->get('facebook')); ?></div>
				<div class="col-md-4"><?php echo $this->formRow($form->get('twitter')); ?></div>
				<div class="col-md-4"><?php echo $this->formRow($form->get('instagram')); ?></div>
			</div>

		</div>
		<div class="form-actions">
			<div class="btn-set pull-right">
				<button type="submit" name="save" class="btn blue btn-lg" id="save" value="Salvar">
					<span class="fa fa-fa fa-check"></span> Salvar
				</button>
				<?php
				$urlCancel = empty($this->user->getId())
					? $this->url('admin/default', ['controller'=>'user', 'action'=>'create'])
					: $this->url('admin/default', ['controller'=>'user', 'action'=>'update', 'id'=>$this->user->getId()]) ?>
				<a href="<?php echo $urlCancel ?>" class="btn red btn-lg form-action-cancel">Cancelar</a>
			</div>
		</div>
		<?php echo $this->form()->closeTag() ?>
	</div>
</div>