<div class="row">
	<div class="col-md-12">
		<div class="portlet light portlet-fit portlet-datatable bordered">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-th-list"></i>
					Lista de Usuários
				</div>
				<div class="actions">
					<a href="<?php echo $this->url('admin/default', ['controller'=>'contact', 'action'=>'create']); ?>"
					   class="btn blue btn-lg">
						<i class="fa fa-plus"></i>
						<span class="hidden-xs"> Inserir Usuário </span>
					</a>
					<div class="btn-group">
						<a class="btn btn-default dropdown-toggle" href="javascript:;" data-toggle="dropdown">
							<i class="fa fa-share"></i>
							<span class="hidden-xs"> Opções </span>
							<i class="fa fa-angle-down"></i>
						</a>
						<div class="dropdown-menu pull-right">
							<li>
                                <a class="report-link"
                                   data-form="#user-contact-form"
                                   data-url="<?php echo $this->url('admin/default', ['controller'=>'contact', 'action'=>'export-list']) ?>"
                                   href="javascript:;"> Exportar para Excel </a>
                            </li>
						</div>
					</div>
				</div>
			</div>

			<div class="portlet-body">
				<div class="table-container post-list">
                    <?php echo $this->partial('admin/contact/_list.phtml', [
                        'form' => $this->searchForm,
                        'users'=>$this->users,
                        'searchData'=>$this->searchData
                    ]); ?>
				</div>
			</div>
		</div>
	</div>
</div>