<!doctype html>
<html lang="">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="keywords" content="cinema,mostra,bh,cinebh,internacional,film,festival">

    <title><?php echo $this->translate("Brasilcinemundi - 11ª International Coproduction Meeting"); ?></title>

    <!--Facebook-->
    <meta property="og:url" content="<?php echo $this->serverUrl(true) ?>">
    <meta property="og:type" content="website" />

    <!-- Twitter -->
    <meta name="twitter:card" content="summary" />
    <meta name="twitter:site" content="@universoprod" />
    <meta name="twitter:creator" content="@universoprod" />

    <meta name="google-site-verification" content="YvbTqZPnLwRE27su8GU0nAwqVEbW8PrdsxVbfDJ4488" />

    <link rel="stylesheet" href="<?php echo $this->basePath("assets/brasilcinemundi/dist") ?>/styles/vendor.css">
    <link rel="stylesheet" href="<?php echo $this->basePath("assets/brasilcinemundi/dist") ?>/styles/main.css?v=3">

    <link rel="icon" href="<?php echo $this->basePath('assets/brasilcinemundi/dist') ?>/images/icon32.png" sizes="16x16 32x32" type="image/png">

</head>
    <body class="<?php echo $this->placeholder("home-class") ?>">

    <header class="header">

            <div class="header-desktop">
                <img src="<?php echo $this->basePath("assets/brasilcinemundi/dist") ?>/images/2020/header_desk.jpg" alt="">
            </div>
            <div class="header-actions">
                <div class="action menu-button" id="menu-button" data-src="#navigation-modal">
                    <div class="circle">
                        <div class="burger">
                            <span class="b"></span>
                            <span class="b"></span>
                            <span class="b"></span>
                            <span class="b"></span>
                        </div>
                    </div>
                </div>
                <?php if($this->locale == 'pt'): ?>
                    <a href="<?php echo $this->url("brasilcinemundi/home", ['locale'=>'en']) ?>" class="action langselector"><span>ENGLISH</span></a>
                <?php else: ?>
                    <a href="<?php echo $this->url("brasilcinemundi/home", ['locale'=>'pt']) ?>" class="action langselector"><span>Português</span></a>
                <?php endif; ?>
            </div>
            <div class="header-mobile">
                <img src="<?php echo $this->basePath("assets/brasilcinemundi/dist") ?>/images/2020/header_mobile.jpg" alt="">
            </div>

    </header>

    <main class="main">
        <?php echo $this->content; ?>
    </main>

    <footer class="footer">
        <div class="footer-wrapper">
            <div class="footer-clear">
                <div class="footer-contact">
                    <p class="footer-title"><?php echo $this->translate("Contate-nos"); ?>:</p>
                    <span class="icon icon-universo-producao"></span>
                    <span class="footer-add">+ 55 31 3282-2366<br>
                            cinebh@universoproducao.com.br<br>
                            Rua Pirapetinga, 567 - Serra<br>
                            30220-150, Belo Horizonte | MG</span>
                </div>
                <div class="footer-social">
                    <p class="footer-title"><?php echo $this->translate("Siga-nos"); ?>:</p>
                    <ul class="footer-socialitems">
                        <li class="footer-socialitem"><a class="footer-socialink" target="_blank" href="https://www.facebook.com/cinebh/"><span class="icon icon-facebook"></span></a></li>
                        <li class="footer-socialitem"><a class="footer-socialink" target="_blank" href="http://twitter.com/universoprod"><span class="icon icon-twitter"></span></a></li>
                        <li class="footer-socialitem"><a class="footer-socialink" target="_blank" href="http://instagram.com/universoproducao"><span class="icon icon-instagram"></span></a></li>
                        <li class="footer-socialitem"><a class="footer-socialink" target="_blank" href="http://www.flickr.com/photos/universoproducao"><span class="icon icon-flickr"></span></a></li>
                        <li class="footer-socialitem"><a class="footer-socialink" target="_blank" href="http://www.youtube.com/user/universoproducao/featured"><span class="icon icon-youtube"></span></a></li>
                    </ul>
                </div>
            </div>
        </div>
        <p class="footer-copy">Copyright © 2020. Universo Produção - <?php echo $this->translate("Todos os direitos reservados") ?>.</p>
    </footer>

    <?php $this
        ->navigation('Brasilcinemundi')
        ->menu()->setPartial("brasilcinemundi/partials/navigation.phtml");

        echo $this
            ->navigation('Brasilcinemundi')
            ->menu()
            ->render(); ?>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>

    <script src="<?php echo $this->basePath("assets/brasilcinemundi/dist") ?>/scripts/vendor.js"></script>
    <script src="<?php echo $this->basePath("assets/brasilcinemundi/dist") ?>/scripts/main.js"></script>

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-10028533-8"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'UA-10028533-8');
    </script>
    <!-- endbuild -->
    </body>
</html>
