<div class="portlet light bordered page-gallery">
	<div class="portlet-title">
		<div class="caption">
			<i class="fa fa-edit"></i>Canal Universo</div>

		<div class="actions">
			<a href="<?php echo $this->url('admin/default', ['action'=>'create', 'controller'=>'channel']); ?>"
			   class="btn blue btn-lg">
				<i class="fa fa-plus"></i>
				<span class="hidden-xs"> Cadastrar item </span>
			</a>
		</div>
	</div>
	<div class="portlet-body">
		<div class="table-container post-list">
			<table class="table table-striped table-bordered table-hover">
				<thead>
				<tr role="row" class="heading">
					<th width="2%">#</th>
					<th width="30%">Título</th>
                    <th width="30%">Categorias</th>
                    <th width="30%">Data</th>
					<th width="10%">Ações</th>
				</tr>
				</thead>
				<tbody>
				<?php foreach ($this->items as $item):
					$updateUrl = $this->url('admin/default', [
						'action'=>'update',
                        'controller' => 'channel',
						'id'=>$item->getId(),
					]);
					$removeUrl = $this->url('admin/default', [
						'action'=>'delete',
						'controller'=>'channel',
						'id'=>$item->getId()
					]);
					?>
					<tr>
						<td></td>
						<td><?php echo $item->getTitle() ?></td>
						<td></td>
						<td>
							<a href="<?php echo  $updateUrl; ?>" class="btn btn-sm btn-default">
								<i class="fa fa-edit"></i> Editar
							</a>
							<a href="<?php echo $removeUrl; ?>" class="btn btn-sm btn-default post-list-remove">
								<i class="fa fa-close"></i> Excluir
							</a>
						</td>
					</tr>
				<?php endforeach; ?>
				</tbody>
			</table>
			<div class="table-paginator">
				<?php echo $this->paginationcontrol($this->items, 'sliding', 'admin/partials/paginator.phtml', array(
                    'route'=>'admin/eufacoamostra',
                    'route_options' => array('site'=>$this->site)
                )); ?>
			</div>
		</div>
	</div>
</div>


