<section class="channel channel--play">
    <div class="channel-video">
        <iframe width="100%" height="500px" src="<?php echo $this->youtubeEmbed($this->video->getStreamingUrl(), ['rel'=>0, 'controls'=>0, 'showinfo'=>0]); ?>" frameborder="0"></iframe>
    </div>
    <div class="main-wrapper">
        <div class="channel-content">
            <p class="title"><?php echo $this->video->getTitle() ?></p>
            <p class="date">Publicado em <?php echo ucfirst($this->dateFormat($this->video->getDate(), null, null, "pt_BR", "MMM Y")); ?></p>
            <div class="desc">
                <p><?php echo $this->video->getDescription(); ?></p>
            </div>
            <p class="cat">
                <strong>Categorias:</strong>
                <?php foreach ($this->video->getCategories() as $cat): ?>
                    <a href="<?php echo $this->url('universoproducao/channel', ['id'=>$cat->getId()]) ?>"><?php echo $cat->getName(); ?></a>
                <?php endforeach; ?>
            </p>
        </div>

        <div class="share">
            <span class="share-title">Compartilhe:</span>
            <ul class="share-items">
                <li class="share-item"><a target="_blank" href="http://www.facebook.com/share.php?u=<?php echo $this->serverUrl(true) ?>&display=popup&title=<?php echo $this->video->getTitle(); ?>" class="share-link"><span class="icon-facebook"></span></a></li>
                <li class="share-item"><a target="_blank" href="https://twitter.com/intent/tweet?status=<?php echo $this->video->getTitle(); ?>+<?php echo $this->serverUrl(true) ?>" class="share-link"><span class="icon-twitter"></span></a></li>
            </ul>
        </div>

        <div class="main-separator"></div>

    </div>
</section>