<?php $form = $this->searchForm; ?>
<div class="row">
	<div class="col-md-12">
		<div class="portlet light portlet-fit portlet-datatable bordered">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-th-list"></i>
					Oficinas
				</div>
				<div class="actions">
					<a href="<?php echo $this->url('admin/default', ['controller' => 'workshop', 'action'=>'create']); ?>"
					   class="btn blue btn-lg">
						<i class="fa fa-plus"></i>
						<span class="hidden-xs"> Cadastrar oficina </span>
					</a>
					<div class="btn-group">
						<a class="btn btn-default dropdown-toggle" href="javascript:;" data-toggle="dropdown">
							<i class="fa fa-share"></i>
							<span class="hidden-xs"> Opções </span>
							<i class="fa fa-angle-down"></i>
						</a>
						<div class="dropdown-menu pull-right">
							<li><a href="javascript:;"> Exportar para Excel </a></li>
							<li><a href="javascript:;"> Exportar para PDF </a></li>
							<li class="divider"></li>
							<li><a href="javascript:;"> Imprimir </a></li>
						</div>
					</div>
				</div>
			</div>

			<div class="portlet-body">
				<div class="table-container post-list">
					<table class="table table-striped table-bordered table-hover">
						<thead>
							<tr role="row" class="heading">
								<th width="2%">#</th>
								<th width="25%">Nome</th>
								<th width="15%">Evento</th>
                                <th width="10%">N. vagas</th>
                                <th width="10%">N. inscrições</th>
								<th width="15%">Ações</th>
							</tr>
                            <tr role="row" class="filter">
                                <?php $form->prepare(); echo $this->form()->openTag($form); ?>
                                <td></td>
                                <td><?php echo $this->formelement($form->get('name')); ?></td>
                                <td><?php echo $this->formelement($form->get('event')); ?></td>
                                <td></td>
                                <td></td>
                                <td>
                                    <button class="btn btn-sm blue filter-submit margin-bottom"><i class="fa fa-search"></i> Pesquisar</button>
                                    <button class="btn btn-sm btn-default filter-cancel"><i class="fa fa-times"></i> Limpar</button>
                                </td>
                                <?php echo $this->form()->closeTag(); ?>
                            </tr>
						</thead>
						<tbody>
						<?php foreach ($this->items as $i):

                            $events = $i->getRegistration()->getEvents();

							$updateUrl = $this->url('admin/default', [
                                'controller' => 'workshop',
								'action' => 'update',
								'id' => $i->getId()
							]);

							$removeUrl = $this->url('admin/default', [
                                'controller' => 'workshop',
								'action'=>'delete',
								'id'=>$i->getId()
							]);

							$subscriptionUrl = $this->url('admin/default', [
							    'controller' => 'workshop-registration',
                            ], ['query'=>[
                                'event' => $i->getEvent()?$i->getEvent()->getId():'',
                                'workshop' => $i->getId()
                            ]]);

							?>
							<tr>
								<td></td>
								<td><a href="<?php echo $updateUrl; ?>"><?php echo $i->getName(); ?></a></td>
								<td><?php echo $i->getEvent()?$i->getEvent()->getShortName():""; ?></td>
                                <td>
                                    <table class="table table-in-td">
                                        <tbody>
                                            <tr>
                                                <td>Vagas:</td>
                                                <td><?php echo $i->getAvailableSubscriptions() ?></td>
                                            </tr>
                                            <tr>
                                                <td>Máx. inscrições</td>
                                                <td><?php echo $i->getMaximumSubscriptions() ?></td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </td>
                                <td><?php echo $i->getSubscriptions()->count(); ?>
                                    <a href="<?php echo $subscriptionUrl; ?>" class="btn btn-sm btn-default">
                                        <i class="fa fa-filter"></i> Inscrições
                                    </a>
                                </td>
								<td>
									<a href="<?php echo  $updateUrl; ?>" class="btn btn-sm btn-default">
										<i class="fa fa-edit"></i> Editar
									</a>
									<a href="<?php echo $removeUrl; ?>" class="btn btn-sm btn-default post-list-remove">
										<i class="fa fa-trash-o"></i> Excluir
									</a>

								</td>
							</tr>
						<?php endforeach; ?>
						</tbody>
					</table>

					<div class="table-paginator">
						<?php echo $this->paginationcontrol(
							$this->items,
							'sliding',
							'admin/partials/paginator.phtml',
							array(
								'route'=>'admin/default',
								'route_options' => [
                                    'controller' => 'workshop'
                                ]
							)
						); ?>
					</div>

				</div>
			</div>
		</div>
	</div>
</div>