<div class="container">
    <div class="col-md-12">
        <p class="meuuniverso-brand meuuniverso-brand--center"><strong>Meu</strong>Universo | Sessões</p>
    </div>
    <div class="portlet light">
        <div class="portlet-body">
            <div class="panel-group accordion" id="workshop_list">
                <?php foreach ($this->sessions as $session): ?>
                    <div class="portlet workshop">
                        <div class="portlet-title">
                            <div class="caption font-dark">
                                <h2 class="main-title"><?php echo $session->getName(); ?></h2>
                            </div>
                        </div>
                        <div class="portlet-body">
                            <?php if(count($session->getMovies()) > 1): ?>
                                <span style="display: block; text-transform: uppercase; font-style: italic; margin-bottom: 8px">Sessão de curtas:</span>
                            <?php endif; ?>

                                <?php foreach ($session->getMovies() as $m): ?>
                                    <a data-fancybox class="fancybox" style="color: #000; text-decoration: none" href="#moviemodal<?php echo $m->getMovie()->getId() ?>">
                                        <strong><?php echo mb_strtoupper($m->getMovie()->getTitle()); ?></strong>
                                        <i style="margin-left: 2px; font-size: 13px;" class="icon-plus-circle"></i>
                                    </a>
                                    <br />
                                    <div style="display: none;width:800px;min-height: 800px" id="moviemodal<?php echo $m->getMovie()->getId(); ?>">
                                        <h3 class="main-title"><?php echo $m->getMovie()->getTitle() ?></h3>
                                        <p><?php echo mb_strtoupper(implode(', ', $m->getMovie()->getHighlights())); ?></p>

                                        <?php if(count($m->getMovie()->getMedias())): ?>
                                            <p>
                                                <img src="<?php echo $this->thumbor()->url($this->fileManipulation()->url($m->getMovie()->getMedias()->first()->getSrc()))->resize(1140, 400); ?>" alt="">
                                            </p>
                                        <?php endif; ?>

                                        <br>

                                        <p>
                                            <b>Direção: </b>
                                            <?php echo $m->getMovie()->getDirection(); ?>
                                        </p>
                                        <br>
                                        <p>
                                            <b>Sinopse: </b>
                                            <?php echo $m->getMovie()->getSynopsis(); ?>
                                        </p>

                                    </div>
                                <?php endforeach; ?>
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>Data/Hora</th>
                                        <th>Local</th>
                                        <th>Vagas</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                <?php foreach ($session->getProgramming() as $prog): ?>
                                    <?php $urlSub = $this->url('meu-universo/session_school', [
                                            'action'=>'inscricao',
                                            'id_reg' => $this->registration->getHash(),
                                            'id' => $prog->getId()
                                    ]); ?>
                                    <tr>
                                        <td><?php echo $prog->getDate()->format('d/m/Y').' | '.$prog->getStartTime()->format('H\hi'); ?></td>
                                        <td><?php echo $prog->getPlace()?$prog->getPlace()->getName():""; ?></td>
                                        <td><?php echo ($prog->getAvailablePlaces() - $this->sessionSchoolRepository->getTotalSubscriptionsSession($prog->getId())); ?></td>
                                        <td>
                                            <?php if($this->sessionSchoolRepository->hasAvailableSubscriptions($prog->getId())): ?>
                                            <a style="margin-left: 15px; color: #000;" href="<?php echo $urlSub; ?>">Fazer inscrição
                                                <i style="font-size: 13px;" class="icon-arrow-right4"></i>
                                            </a>
                                            <?php else: ?>
                                            Inscrições esgotadas
                                            <?php endif; ?>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <hr>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
</div>
