<?php $this->placeholder("home-class")->set("home"); ?>


<section class="banner">
    <div class="banner-items owl-carousel">
        <?php foreach ($this->bannerImages as $banner): ?>
            <div class="banner-item"><img src="<?php echo $this->thumbor()->url($banner->getMeta('_image'))->resize(1920, 648); ?>" alt=""></div>
        <?php endforeach; ?>
    </div>
</section>

<!-- Info -->
<!--<section class="notice">
    <div class="main-wrapper">
        <p class="notice-text"> Inscrições abertas para oficinas na 20ª Mostra de Cinema de Tiradentes
            de tiradentes</p>
        <a href="http://www.universoproducao.com.br/site/inscricoes.php?menu=ins" class="button-readmore">Inscreva-se</a>
    </div>
</section>-->

<!-- PRogramação -->
<!--<section class="prog">
    <div class="main-wrapper">
        <header class="main-header"><h1 class="section-title">Programação</h1></header>
    </div>
    <div class="prog-items">
        <article class="prog-item prog-item--high">
            <figure class="prog-figure">
                <img src="images/prog1.jpg" alt="">
            </figure>
            <div class="prog-content">
                <p class="prog-day">20 <small>sex</small></p>
                <p class="prog-title">Tantinho -memória em verde e rosa</p>
                <p class="prog-cat">Mostra Pré-estreia</p>
                <p class="prog-place">Centro Histórico - 15h</p>
            </div>
        </article>
        <article class="prog-item">
            <figure class="prog-figure">
                <img src="images/prog5.jpg" alt="">
            </figure>
            <div class="prog-content">
                <p class="prog-day">20 <small>sex</small></p>
                <p class="prog-title">Tantinho -memória em verde e rosa</p>
                <p class="prog-cat">Mostra Pré-estreia</p>
                <p class="prog-place">Centro Histórico - 15h</p>
            </div>
        </article>
        <article class="prog-item">
            <figure class="prog-figure">
                <img src="images/prog2.jpg" alt="">
            </figure>
            <div class="prog-content">
                <p class="prog-day">20 <small>sex</small></p>
                <p class="prog-title">Tantinho -memória em verde e rosa</p>
                <p class="prog-cat">Mostra Pré-estreia</p>
                <p class="prog-place">Centro Histórico - 15h</p>
            </div>
        </article>
        <article class="prog-item">
            <figure class="prog-figure">
                <img src="images/prog3.jpg" alt="">
            </figure>
            <div class="prog-content">
                <p class="prog-day">20 <small>sex</small></p>
                <p class="prog-title">Tantinho -memória em verde e rosa</p>
                <p class="prog-cat">Mostra Pré-estreia</p>
                <p class="prog-place">Centro Histórico - 15h</p>
            </div>
        </article>
        <article class="prog-item">
            <figure class="prog-figure">
                <img src="images/prog4.jpg" alt="">
            </figure>
            <div class="prog-content">
                <p class="prog-day">20 <small>sex</small></p>
                <p class="prog-title">Tantinho -memória em verde e rosa</p>
                <p class="prog-title">Mostra Pré-estreia</p>
                <p class="prog-place">Centro Histórico - 15h</p>
            </div>
        </article>
    </div>
    <div class="main-wrapper">
        <p class="prog-text">De 20 a 28 de janeiro, você estará em sintonia com o cinema em Tiradentes. São exposições, exibições de curtas e longas, debates, seminários e oficinas com grandes nomes da sétima arte
            <br /><a href="" class="button-readmore">Programação Completa</a></p>
    </div>
</section>-->

<section class="news">
    <div class="main-wrapper">
        <header class="news-header">
            <h1>acompanhe tudo o que acontece na 20ª mostra de Tiradentes</h1>
        </header>
        <div class="news-items">
            <?php foreach ($this->news as $news): ?>
            <article class="news-item">
                <a href="<?php echo $this->url("mostratiradentes/news", ['slug'=>$news->getSlug()]) ?>" class="news-link">
                    <figure class="news-figure"><img src="<?php echo  $this->thumbor()->url($news->getMeta('_thumb'))->resize(532, 331); ?>" alt=""></figure>
                    <p class="news-title"><?php echo $news->getTitle(); ?></p>
                </a>
            </article>
            <?php endforeach; ?>
        </div>
        <p class="news-all"><a class="button-readmore" href="<?php echo $this->url("mostratiradentes/default", ['slug'=>'noticias']); ?>">Todas as Notícias</a></p>
    </div>
</section>

<!-- TV -->
<!--<section class="tv">
    <div class="main-wrapper">
        <header class="main-header"><h1 class="section-title">TV Mostra</h1></header>

        <div class="tv-items">

            <article class="tv-item">
                <figure class="tv-figure">
                    <img src="images/tv1.jpg" alt="">
                </figure>
                <div class="tv-content">
                    <p class="tv-title">Estréia do longa comboio de sal e açúcar</p>
                </div>
            </article>

            <article class="tv-item">
                <figure class="tv-figure">
                    <img src="images/tv2.jpg" alt="">
                </figure>
                <div class="tv-content">
                    <p class="tv-title">stréia de longas nacionais é destaque na 20ª mostra de cinema de tiradentes</p>
                    <p class="tv-subtitle">Filmes nacionais estreiam em grande estilo na Mostra Tiradentes. Confira como foi o primeiro dia</p>
                </div>
            </article>

            <article class="tv-item">
                <figure class="tv-figure">
                    <img src="images/tv2.jpg" alt="">
                </figure>
                <div class="tv-content">
                    <p class="tv-title">stréia de longas nacionais é destaque na 20ª mostra de cinema de tiradentes</p>
                    <p class="tv-subtitle">Filmes nacionais estreiam em grande estilo na Mostra Tiradentes. Confira como foi o primeiro dia</p>
                </div>
            </article>
            <p class="tv-all"><a href="">Assista todos os vídeos <span class="icon icon-plus-circle"></span></a></p>
        </div>

    </div>
</section>-->

<section class="gallery">
    <div class="gallery-list owl-carousel">
        <?php foreach ($this->gallery as $img): ?>
            <div class="gallery-item">
                <figure class="gallery-figure">
                    <img src="<?php echo $this->thumbor()->url($img->getMeta('_image'))->resize(780, 505); ?>" alt="">
                </figure>
                <div class="gallery-desc">
                    <p class="gallery-title"><?php echo $img->getTitle(); ?>
                        <span><?php echo $img->getMeta('_credits'); ?></span></p>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
    <p class="gallery-all"><a href="https://www.flickr.com/photos/universoproducao/" class="button-readmore">Galeria Completa</a></p>
</section>

<section class="guide">
    <div class="main-wrapper">
        <header class="guide-header">
            <h1>se renda aos encantos de uma das cidades históricas mais importantes do brasil e
                aprecie a sétima arte em uma mostra singular</h1>
        </header>
        <ul class="guide-items">
            <li class="guide-item">
                <a href="<?php echo $this->url("mostratiradentes/default", ['slug'=>'como-chegar']) ?>" class="guide-link">
                    <span class="sprite sprite-como-chegar"></span>
                    <p class="guide-title">Como Chegar</p>
                </a>
            </li>
            <li class="guide-item">
                <a href="<?php echo $this->url("mostratiradentes/default", ['slug'=>'turismo-e-informacoes']) ?>" class="guide-link">
                    <span class="sprite sprite-turismo"></span>
                    <p class="guide-title">Turismo e Informações</p>
                </a>
            </li>
            <li class="guide-item">
                <a href="<?php echo $this->url("mostratiradentes/default", ['slug'=>'restaurantes']) ?>" class="guide-link">
                    <span class="sprite sprite-restaurantes"></span>
                    <p class="guide-title">Restaurantes</p>
                </a>
            </li>
            <li class="guide-item">
                <a href="<?php echo $this->url("mostratiradentes/default", ['slug'=>'hoteis-e-acomodacoes']) ?>" class="guide-link">
                    <span class="sprite sprite-hospedagem"></span>
                    <p class="guide-title">hotéis e acomodações</p>
                </a>
            </li>
        </ul>
    </div>
</section>

<section class="timeline">
    <div class="timeline-header">
        <h1>Mostra Tiradentes, 20 anos de cinema, arte e cultura</h1>
        <p>Há 20 anos, temos o prazer de celebrar o maior festival de cinema de Minas Gerais e um dos mais relevantes do Brasil,
            20 anos de orgulho, história e emoção! <strong>Clique e conheça a nossa trajetória</strong></p>
        <div class="timeline-button">
            <a id="timeline-active" class="circle-button" href="">
                <i class="icon icon-arrow-right4"></i></a>
        </div>
    </div>

    <div class="timeline-navigation">
    </div>

    <div class="timeline-container">
        <div class="timeline-body">
            <div class="timeline-wrapper">
                <div class="timeline-events">
                    <div class="events">
                        <div class="event">
                            <p class="event-year squere-font">1998</p>
                            <p class="event-title">O começo</p>
                            <div class="event-content">
                                <p class="event-subtitle">Homenagens</p>
                                <div class="event-text">
                                    <p>À cineasta Carla Camurati e ao ator Paulo José</p>
                                    <ul class="event-actions">
                                        <li><a class="circle-button plus" href=""><i class="icon icon-plus3"></i></a></li>
                                    </ul>
                                </div>
                                <ul>
                                    <li><span class="squere-font">82</span> filmes</li>
                                    <li><span class="squere-font">40</span> sessões</li>
                                    <li><span class="squere-font">22</span> longas</li>
                                    <li><span class="squere-font">27</span> curtas</li>
                                    <li><span class="squere-font">33</span> vídeos</li>
                                    <li><span class="squere-font">04</span> oficinas</li>
                                    <li><span class="squere-font">148</span> alunos certificados</li>
                                </ul>
                                <p class="event-audience">Público estimado: <span class="squere-font">7.500</span> <i class="icon icon-people"></i></p>
                            </div>
                        </div>
                        <div class="event">
                            <p class="event-year squere-font">1999</p>
                            <div class="event-figure">
                                <img src="<?php echo $this->basePath("assets/mostratiradentes/dist") ?>/images/1998.jpg" alt="">
                                <ul class="event-actions">
                                    <li><a class="circle-button plus" href=""><i class="icon icon-plus3"></i></a></li>
                                </ul>
                            </div>
                            <div class="event-content">
                                <p class="event-title">aprendendo a caminhar</p>
                                <p class="event-subtitle">Homenagens</p>
                                <p>Ao cineasta Denoy de Oliveira (in memorian),
                                    ao cineasta Helvécio Ratton
                                    e à atriz Patrícia Pillar</p>
                                <ul>
                                    <li><span class="squere-font">82</span> filmes</li>
                                    <li><span class="squere-font">40</span> sessões</li>
                                    <li><span class="squere-font">22</span> longas</li>
                                    <li><span class="squere-font">27</span> curtas</li>
                                    <li><span class="squere-font">33</span> vídeos</li>
                                    <li><span class="squere-font">04</span> oficinas</li>
                                    <li><span class="squere-font">148</span> alunos certificados</li>
                                </ul>
                            </div>
                            <p class="event-audience">Público estimado: <span class="squere-font">25.000</span> <i class="icon icon-people"></i></p>
                        </div>
                        <div class="event">
                            <p class="event-year squere-font">2000</p>
                            <div class="event-figure">
                                <img src="<?php echo $this->basePath("assets/mostratiradentes/dist") ?>/images/2000.jpg" alt="">
                                <ul class="event-actions">
                                    <li><a class="circle-button plus" href=""><i class="icon icon-plus3"></i></a></li>
                                    <li><a class="circle-button" href=""><i class="icon icon-trophy"></i></a></li>
                                </ul>
                            </div>
                            <div class="event-content">
                                <p class="event-title">o cinema na praça</p>
                                <p class="event-subtitle">Homenagens</p>
                                <p>À cineasta Carlos Reichenbach</p>
                                <ul>
                                    <li><span class="squere-font">110</span> filmes</li>
                                    <li><span class="squere-font">49</span> sessões</li>
                                    <li><span class="squere-font">29</span> longas</li>
                                    <li><span class="squere-font">42</span> curtas</li>
                                    <li><span class="squere-font">39</span> vídeos</li>
                                    <li><span class="squere-font">05</span> oficinas</li>
                                    <li><span class="squere-font">180</span> alunos certificados</li>
                                </ul>
                            </div>
                            <p class="event-audience">Público estimado: <span class="squere-font">30.000</span> <i class="icon icon-people"></i></p>
                        </div>
                        <div class="event">
                            <p class="event-year squere-font">2001</p>
                            <div class="event-figure">
                                <img src="<?php echo $this->basePath("assets/mostratiradentes/dist") ?>/images/2001.jpg" alt="">
                                <ul class="event-actions">
                                    <li><a class="circle-button plus" href=""><i class="icon icon-plus3"></i></a></li>
                                    <li><a class="circle-button" href=""><i class="icon icon-trophy"></i></a></li>
                                </ul>
                            </div>
                            <div class="event-content">
                                <p class="event-title">Mulheres em cena</p>
                                <p class="event-subtitle">Homenagens</p>
                                <p>À cineasta Ana Carolina, à atriz Odete Lara
                                    e ao videoartista Carlos Nader</p>
                                <ul>
                                    <li><span class="squere-font">123</span> filmes</li>
                                    <li><span class="squere-font">38</span> sessões</li>
                                    <li><span class="squere-font">30</span> longas</li>
                                    <li><span class="squere-font">4</span> curtas</li>
                                    <li><span class="squere-font">52</span> vídeos</li>
                                    <li><span class="squere-font">11</span> oficinas</li>
                                    <li><span class="squere-font">330</span> alunos certificados</li>
                                </ul>
                            </div>
                            <p class="event-audience">Público estimado: <span class="squere-font">32.270</span> <i class="icon icon-people"></i></p>
                        </div>
                        <div class="event">
                            <p class="event-year squere-font">2002</p>
                            <div class="event-figure">
                                <img src="<?php echo $this->basePath("assets/mostratiradentes/dist") ?>/images/2002.jpg" alt="">
                                <ul class="event-actions">
                                    <li><a class="circle-button plus" href=""><i class="icon icon-plus3"></i></a></li>
                                    <li><a class="circle-button" href=""><i class="icon icon-trophy"></i></a></li>
                                </ul>
                            </div>
                            <div class="event-content">
                                <p class="event-title">Cinema de ator e de autor</p>
                                <p class="event-subtitle">Homenagens</p>
                                <p>Ao cineasta Júlio Bressane,
                                    ao ator José Lewgoy
                                    e ao videoartista Kiko Goifman</p>
                                <ul>
                                    <li><span class="squere-font">110</span> filmes</li>
                                    <li><span class="squere-font">49</span> sessões</li>
                                    <li><span class="squere-font">29</span> longas</li>
                                    <li><span class="squere-font">42</span> curtas</li>
                                    <li><span class="squere-font">39</span> vídeos</li>
                                    <li><span class="squere-font">05</span> oficinas</li>
                                    <li><span class="squere-font">180</span> alunos certificados</li>
                                </ul>
                            </div>
                            <p class="event-audience">Público estimado: <span class="squere-font">33.780</span> <i class="icon icon-people"></i></p>
                        </div>
                        <div class="event">
                            <p class="event-year squere-font">2003</p>
                            <div class="event-figure">
                                <img src="<?php echo $this->basePath("assets/mostratiradentes/dist") ?>/images/2003.jpg" alt="">
                                <ul class="event-actions">
                                    <li><a class="circle-button plus" href=""><i class="icon icon-plus3"></i></a></li>
                                    <li><a class="circle-button" href=""><i class="icon icon-trophy"></i></a></li>
                                </ul>
                            </div>
                            <div class="event-content">
                                <p class="event-title">Heróis do cotidiano
                                    no cinema brasileiro</p>
                                <p class="event-subtitle">Homenagens</p>
                                <p>Ao cineasta Eduardo Coutinho,
                                    ao ator Gianfrancesco Guarnieri
                                    e à videoartista Inês Cardoso</p>
                                <ul>
                                    <li><span class="squere-font">118</span> filmes</li>
                                    <li><span class="squere-font">35</span> sessões</li>
                                    <li><span class="squere-font">25</span> longas</li>
                                    <li><span class="squere-font">42</span> curtas</li>
                                    <li><span class="squere-font">51</span> vídeos</li>
                                    <li><span class="squere-font">13</span> oficinas</li>
                                    <li><span class="squere-font">330</span> alunos certificados</li>
                                </ul>
                            </div>
                            <p class="event-audience">Público estimado: <span class="squere-font">35.000</span> <i class="icon icon-people"></i></p>
                        </div>
                        <div class="event">
                            <p class="event-year squere-font">2004</p>
                            <div class="event-figure">
                                <img src="<?php echo $this->basePath("assets/mostratiradentes/dist") ?>/images/2004.jpg" alt="">
                                <ul class="event-actions">
                                    <li><a class="circle-button plus" href=""><i class="icon icon-plus3"></i></a></li>
                                    <li><a class="circle-button" href=""><i class="icon icon-trophy"></i></a></li>
                                </ul>
                            </div>
                            <div class="event-content">
                                <p class="event-title">Modos narrativos do
                                    cinema brasileiro</p>
                                <p class="event-subtitle">Homenagens</p>
                                <p>ÀAo cineasta Nelson Pereira dos Santos,
                                    ao ator Paulo César Pereio
                                    e ap videoartista Marcelo Tas</p>
                                <ul>
                                    <li><span class="squere-font">119</span> filmes</li>
                                    <li><span class="squere-font">34</span> sessões</li>
                                    <li><span class="squere-font">24</span> longas</li>
                                    <li><span class="squere-font">4</span> curtas</li>
                                    <li><span class="squere-font">54</span> vídeos</li>
                                    <li><span class="squere-font">13</span> oficinas</li>
                                    <li><span class="squere-font">450</span> alunos certificados</li>
                                </ul>
                            </div>
                            <p class="event-audience">Público estimado: <span class="squere-font">35.000</span> <i class="icon icon-people"></i></p>
                        </div>
                        <div class="event">
                            <p class="event-year squere-font">2005</p>
                            <div class="event-figure">
                                <img src="<?php echo $this->basePath("assets/mostratiradentes/dist") ?>/images/2005.jpg" alt="">
                                <ul class="event-actions">
                                    <li><a class="circle-button plus" href=""><i class="icon icon-plus3"></i></a></li>
                                    <li><a class="circle-button" href=""><i class="icon icon-trophy"></i></a></li>
                                </ul>
                            </div>
                            <div class="event-content">
                                <p class="event-title">O primeiro cinema</p>
                                <p class="event-subtitle">Homenagens</p>
                                <p>Ao cineasta Walter Lima Jr.
                                    e ao videoartista Cao Guimarães</p>
                                <ul>
                                    <li><span class="squere-font">149</span> filmes</li>
                                    <li><span class="squere-font">40</span> sessões</li>
                                    <li><span class="squere-font">22</span> longas</li>
                                    <li><span class="squere-font">58</span> curtas</li>
                                    <li><span class="squere-font">69</span> vídeos</li>
                                    <li><span class="squere-font">13</span> oficinas</li>
                                    <li><span class="squere-font">400</span> alunos certificados</li>
                                </ul>
                            </div>
                            <p class="event-audience">Público estimado: <span class="squere-font">35.000</span> <i class="icon icon-people"></i></p>
                        </div>
                        <div class="event">
                            <p class="event-year squere-font">2006</p>
                            <div class="event-figure">
                                <img src="<?php echo $this->basePath("assets/mostratiradentes/dist") ?>/images/2006.jpg" alt="">
                                <ul class="event-actions">
                                    <li><a class="circle-button plus" href=""><i class="icon icon-plus3"></i></a></li>
                                    <li><a class="circle-button" href=""><i class="icon icon-trophy"></i></a></li>
                                </ul>
                            </div>
                            <div class="event-content">
                                <p class="event-title">Livre para pensar</p>
                                <p class="event-subtitle">Homenagens</p>
                                <p>Ao cineasta Ruy Guerra
                                    e ao videoartista Eder Santos</p>
                                <ul>
                                    <li><span class="squere-font">173</span> filmes</li>
                                    <li><span class="squere-font">47</span> sessões</li>
                                    <li><span class="squere-font">24</span> longas</li>
                                    <li><span class="squere-font">60</span> curtas</li>
                                    <li><span class="squere-font">69</span> vídeos</li>
                                    <li><span class="squere-font">13</span> oficinas</li>
                                    <li><span class="squere-font">430</span> alunos certificados</li>
                                </ul>
                            </div>
                            <p class="event-audience">Público estimado: <span class="squere-font">37.400</span> <i class="icon icon-people"></i></p>
                        </div>
                        <div class="event">
                            <p class="event-year squere-font">2007</p>
                            <div class="event-figure">
                                <img src="<?php echo $this->basePath("assets/mostratiradentes/dist") ?>/images/2007.jpg" alt="">
                                <ul class="event-actions">
                                    <li><a class="circle-button plus" href=""><i class="icon icon-plus3"></i></a></li>
                                    <li><a class="circle-button" href=""><i class="icon icon-trophy"></i></a></li>
                                </ul>
                            </div>
                            <div class="event-content">
                                <p class="event-title">Vitalidade do cinema
                                    brasileiro</p>
                                <p class="event-subtitle">Homenagens</p>
                                <p>o cineasta Beto Brant,
                                    ao videoartista Fábio Carvalho e aos atores
                                    Lazaro Ramos e Matheus Nachtergaele</p>
                                <ul>
                                    <li><span class="squere-font">219</span> filmes</li>
                                    <li><span class="squere-font">55</span> sessões</li>
                                    <li><span class="squere-font">26</span> longas</li>
                                    <li><span class="squere-font">59</span> curtas</li>
                                    <li><span class="squere-font">134</span> vídeos</li>
                                    <li><span class="squere-font">13</span> oficinas</li>
                                    <li><span class="squere-font">444</span> alunos certificados</li>
                                </ul>
                            </div>
                            <p class="event-audience">Público estimado: <span class="squere-font">40.000</span> <i class="icon icon-people"></i></p>
                        </div>
                        <div class="event">
                            <p class="event-year squere-font">2008</p>
                            <div class="event-figure">
                                <img src="<?php echo $this->basePath("assets/mostratiradentes/dist") ?>/images/2008.jpg" alt="">
                                <ul class="event-actions">
                                    <li><a class="circle-button plus" href=""><i class="icon icon-plus3"></i></a></li>
                                    <li><a class="circle-button" href=""><i class="icon icon-trophy"></i></a></li>
                                </ul>
                            </div>
                            <div class="event-content">
                                <p class="event-title">Juventude em
                                    trânsito</p>
                                <p class="event-subtitle">Homenagens</p>
                                <p>À atriz Rosane Mulholand
                                    e ao ator João Miguel</p>
                                <ul>
                                    <li><span class="squere-font">126</span> filmes</li>
                                    <li><span class="squere-font">48</span> sessões</li>
                                    <li><span class="squere-font">27</span> longas</li>
                                    <li><span class="squere-font">35</span> curtas</li>
                                    <li><span class="squere-font">64</span> vídeos</li>
                                    <li><span class="squere-font">13</span> oficinas</li>
                                    <li><span class="squere-font">390</span> alunos certificados</li>
                                </ul>
                            </div>
                            <p class="event-audience">Público estimado: <span class="squere-font">40.000</span> <i class="icon icon-people"></i></p>
                        </div>
                        <div class="event">
                            <p class="event-year squere-font">2009</p>
                            <div class="event-figure">
                                <img src="<?php echo $this->basePath("assets/mostratiradentes/dist") ?>/images/2009.jpg" alt="">
                                <ul class="event-actions">
                                    <li><a class="circle-button plus" href=""><i class="icon icon-plus3"></i></a></li>
                                    <li><a class="circle-button" href=""><i class="icon icon-trophy"></i></a></li>
                                </ul>
                            </div>
                            <div class="event-content">
                                <p class="event-title">o personagem
                                    e seu lugar</p>
                                <p class="event-subtitle">Homenagens</p>
                                <p>Ao cineasta José Eduardo Belmonte </p>
                                <ul>
                                    <li><span class="squere-font">121</span> filmes</li>
                                    <li><span class="squere-font">50</span> sessões</li>
                                    <li><span class="squere-font">28</span> longas</li>
                                    <li><span class="squere-font">32</span> curtas película</li>
                                    <li><span class="squere-font">61</span> curtas digitais</li>
                                    <li><span class="squere-font">10</span> oficinas</li>
                                    <li><span class="squere-font">300</span> alunos certificados</li>
                                </ul>
                            </div>
                            <p class="event-audience">Público estimado: <span class="squere-font">40.000</span> <i class="icon icon-people"></i></p>
                        </div>
                        <div class="event">
                            <p class="event-year squere-font">2010</p>
                            <div class="event-figure">
                                <img src="<?php echo $this->basePath("assets/mostratiradentes/dist") ?>/images/2010.jpg" alt="">
                                <ul class="event-actions">
                                    <li><a class="circle-button plus" href=""><i class="icon icon-plus3"></i></a></li>
                                    <li><a class="circle-button" href=""><i class="icon icon-trophy"></i></a></li>
                                </ul>
                            </div>
                            <div class="event-content">
                                <p class="event-title">paradoxos do
                                    contemporâneo</p>
                                <p class="event-subtitle">Homenagens</p>
                                <p>Ao cineasta Karim Ainouz</p>
                                <ul>
                                    <li><span class="squere-font">128</span> filmes</li>
                                    <li><span class="squere-font">48</span> sessões</li>
                                    <li><span class="squere-font">29</span> longas</li>
                                    <li><span class="squere-font">99</span> curtas</li>
                                    <li><span class="squere-font">12</span> oficinas</li>
                                    <li><span class="squere-font">310</span> alunos certificados</li>
                                </ul>
                            </div>
                            <p class="event-audience">Público estimado: <span class="squere-font">40.000</span> <i class="icon icon-people"></i></p>
                        </div>
                        <div class="event">
                            <p class="event-year squere-font">2011</p>
                            <div class="event-figure">
                                <img src="<?php echo $this->basePath("assets/mostratiradentes/dist") ?>/images/2011.jpg" alt="">
                                <ul class="event-actions">
                                    <li><a class="circle-button plus" href=""><i class="icon icon-plus3"></i></a></li>
                                    <li><a class="circle-button" href=""><i class="icon icon-trophy"></i></a></li>
                                </ul>
                            </div>
                            <div class="event-content">
                                <p class="event-title">inquietações políticas</p>
                                <p class="event-subtitle">Homenagens</p>
                                <p>Ao cineasta Paulo Cezar Saraceni
                                    e ao ator Irandhir Santos</p>
                                <ul>
                                    <li><span class="squere-font">134</span> filmes</li>
                                    <li><span class="squere-font">49</span> sessões</li>
                                    <li><span class="squere-font">30</span> longas</li>
                                    <li><span class="squere-font">104</span> curtas</li>
                                    <li><span class="squere-font">12</span> oficinas</li>
                                    <li><span class="squere-font">310</span> alunos certificados</li>
                                </ul>
                            </div>
                            <p class="event-audience">Público estimado: <span class="squere-font">40.000</span> <i class="icon icon-people"></i></p>
                        </div>
                        <div class="event">
                            <p class="event-year squere-font">2012</p>
                            <div class="event-figure">
                                <img src="<?php echo $this->basePath("assets/mostratiradentes/dist") ?>/images/2012.jpg" alt="">
                                <ul class="event-actions">
                                    <li><a class="circle-button plus" href=""><i class="icon icon-plus3"></i></a></li>
                                    <li><a class="circle-button" href=""><i class="icon icon-trophy"></i></a></li>
                                </ul>
                            </div>
                            <div class="event-content">
                                <p class="event-title">ao ator em expansão</p>
                                <p class="event-subtitle">Homenagens</p>
                                <p>Ao ator, produtor, roteirista e diretor
                                    Selton Mello</p>
                                <ul>
                                    <li><span class="squere-font">116</span> filmes</li>
                                    <li><span class="squere-font">50</span> sessões</li>
                                    <li><span class="squere-font">31</span> longas</li>
                                    <li><span class="squere-font">84</span> curtas</li>
                                    <li><span class="squere-font">1</span> média</li>
                                    <li><span class="squere-font">12</span> oficinas</li>
                                    <li><span class="squere-font">310</span> alunos certificados</li>
                                </ul>
                            </div>
                            <p class="event-audience">Público estimado: <span class="squere-font">40.000</span> <i class="icon icon-people"></i></p>
                        </div>
                        <div class="event">
                            <p class="event-year squere-font">2013</p>
                            <div class="event-figure">
                                <img src="<?php echo $this->basePath("assets/mostratiradentes/dist") ?>/images/2013.jpg" alt="">
                                <ul class="event-actions">
                                    <li><a class="circle-button plus" href=""><i class="icon icon-plus3"></i></a></li>
                                    <li><a class="circle-button" href=""><i class="icon icon-trophy"></i></a></li>
                                </ul>
                            </div>
                            <div class="event-content">
                                <p class="event-title">cinema expandido</p>
                                <p class="event-subtitle">Homenagens</p>
                                <p>À atriz cinematográfica Simone Spoladore</p>
                                <ul>
                                    <li><span class="squere-font">131</span> filmes</li>
                                    <li><span class="squere-font">54</span> sessões</li>
                                    <li><span class="squere-font">34</span> longas</li>
                                    <li><span class="squere-font">97</span> curtas</li>
                                    <li><span class="squere-font">1</span> média</li>
                                    <li><span class="squere-font">12</span> oficinas</li>
                                    <li><span class="squere-font">335</span> alunos certificados</li>
                                </ul>
                            </div>
                            <p class="event-audience">Público estimado: <span class="squere-font">35.000</span> <i class="icon icon-people"></i></p>
                        </div>
                        <div class="event">
                            <p class="event-year squere-font">2014</p>
                            <div class="event-figure">
                                <img src="<?php echo $this->basePath("assets/mostratiradentes/dist") ?>/images/2014.jpg" alt="">
                                <ul class="event-actions">
                                    <li><a class="circle-button plus" href=""><i class="icon icon-plus3"></i></a></li>
                                    <li><a class="circle-button" href=""><i class="icon icon-trophy"></i></a></li>
                                </ul>
                            </div>
                            <div class="event-content">
                                <p class="event-title">janelas para o mundo</p>
                                <p class="event-subtitle">Homenagens</p>
                                <p>Ao ator Marat Descartes</p>
                                <ul>
                                    <li><span class="squere-font">134</span> filmes</li>
                                    <li><span class="squere-font">54</span> sessões</li>
                                    <li><span class="squere-font">29</span> longas</li>
                                    <li><span class="squere-font">101</span> curtas</li>
                                    <li><span class="squere-font">4</span> médias</li>
                                    <li><span class="squere-font">11</span> oficinas</li>
                                    <li><span class="squere-font">330</span> alunos certificados</li>
                                </ul>
                            </div>
                            <p class="event-audience">Público estimado: <span class="squere-font">35.000</span> <i class="icon icon-people"></i></p>
                        </div>
                        <div class="event">
                            <p class="event-year squere-font">2015</p>
                            <div class="event-figure">
                                <img src="<?php echo $this->basePath("assets/mostratiradentes/dist") ?>/images/2015.jpg" alt="">
                                <ul class="event-actions">
                                    <li><a class="circle-button plus" href=""><i class="icon icon-plus3"></i></a></li>
                                    <li><a class="circle-button" href=""><i class="icon icon-trophy"></i></a></li>
                                </ul>
                            </div>
                            <div class="event-content">
                                <p class="event-title">Janelas para o mundo</p>
                                <p class="event-subtitle">Homenagens</p>
                                <p>À atriz Dira Paes</p>
                                <ul>
                                    <li><span class="squere-font">128</span> filmes</li>
                                    <li><span class="squere-font">59</span> sessões</li>
                                    <li><span class="squere-font">37</span> longas</li>
                                    <li><span class="squere-font">91</span> curtas</li>
                                    <li><span class="squere-font">10</span> oficinas</li>
                                    <li><span class="squere-font">270</span> alunos certificados</li>
                                </ul>
                            </div>
                            <p class="event-audience">Público estimado: <span class="squere-font">35.000</span> <i class="icon icon-people"></i></p>
                        </div>
                        <div class="event">
                            <p class="event-year squere-font">2016</p>
                            <div class="event-figure">
                                <img src="<?php echo $this->basePath("assets/mostratiradentes/dist") ?>/images/2016.jpg" alt="">
                                <ul class="event-actions">
                                    <li><a class="circle-button plus" href=""><i class="icon icon-plus3"></i></a></li>
                                    <li><a class="circle-button" href=""><i class="icon icon-trophy"></i></a></li>
                                </ul>
                            </div>
                            <div class="event-content">
                                <p class="event-title">cinema é brasileiro</p>
                                <p class="event-subtitle">Homenagens</p>
                                <p>Ao cineasta Andrea Tonaccie</p>
                                <ul>
                                    <li><span class="squere-font">117</span> filmes</li>
                                    <li><span class="squere-font">57</span> sessões</li>
                                    <li><span class="squere-font">35</span> longas</li>
                                    <li><span class="squere-font">82</span> curtas</li>
                                    <li><span class="squere-font">10</span> oficinas</li>
                                    <li><span class="squere-font">280</span> alunos certificados</li>
                                </ul>
                            </div>
                            <p class="event-audience">Público estimado: <span class="squere-font">35.000</span> <i class="icon icon-people"></i></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</section>

<section class="eufacoamostra">
    <div class="main-wrapper">
        <header class="eufacoamostra-header">
            <h1><span class="icon icon-eufacoamostra"></span></h1>
            <p class="eufacoamostra-subtitle">Comemoramos o melhor do cenário cinematográfico de Minas e do Brasil. E é claro que não poderíamos fazer história sem a sua essencial participação</p>
        </header>
    </div>
    <div class="eufacoamostra-items">
        <?php foreach ($this->eufacoamostra as $eu): ?>
            <div class="eufacoamostra-item <?php echo !empty($eu->getVideo) ? "eufacoamostra-item--video" : ""; ?>">
                <?php $href = $eu->getVideo() ? $this->youtubeEmbed($eu->getVideo()) : $this->thumbor()->url($eu->getThumb())->resize(700, 700); ?>
                <a title="<?php echo $eu->getDescription(); ?>" rel="eufacoamostra" href="<?php echo $href ?>" class="eufacoamostra-link fancybox <?php echo !empty($eu->getVideo) ? "fancybox.iframe" : ""; ?>">
                    <figure class="eufacoamostra-figure"><img class="grayscale grayscale-fade" src="<?php echo $this->thumbor()->url($eu->getThumb())->resize(700, 700); ?>" alt=""></figure></a></div>
        <?php endforeach; ?>
    </div>
    <p class="news-all"><a href="" class="button-readmore">Veja Mais Galerias</a></p>
</section>

<section class="newsletter">
    <div class="main-wrapper">
        <header class="newsletter-header">
            <h1>Receba Nossos Informativos</h1>
        </header>
        <form action="" class="newsletter-form">
            <input required type="text" class="newsletter-input" placeholder="Nome">
            <input required type="text" class="newsletter-input" placeholder="Email">
            <button onclick="alert('Cadastro efetuado com sucesso!')" type="submit" class="newsletter-submit">Cadastrar</button>
        </form>
    </div>
</section>

<!--<section class="sponsorship">
    <div class="main-wrapper">
        <ul class="sponsorship-list">
            <li class="sponsorship-block sponsorship-block--full sponsorship-block--center">
                <ul class="sponsorship-items">
                    <li class="sponsorship-item"><span class="sprite sprite-lei"></span></li>
                </ul>
            </li>
            <li class="sponsorship-block">
                <p class="sponsorship-title">Patrocínio</p>
                <ul class="sponsorship-items">
                    <li class="sponsorship-item"><span class="sprite sprite-mercantil"></span></li>
                    <li class="sponsorship-item"><span class="sprite sprite-contax"></span></li>
                </ul>
            </li>
            <li class="sponsorship-block">
                <p class="sponsorship-title">Incentivo</p>
                <ul class="sponsorship-items">
                    <li class="sponsorship-item"><span class="sprite sprite-incentivo"></span></li>
                    <li class="sponsorship-item"><span class="sprite sprite-fundacao-cultura"></span></li>
                    <li class="sponsorship-item"><span class="sprite sprite-prefeitura-bh"></span></li>
                </ul>
            </li>
            <li class="sponsorship-block">
                <p class="sponsorship-title">APOIO Brasil CineMundi</p>
                <ul class="sponsorship-items">
                    <li class="sponsorship-item"><span class="sprite sprite-sebrae"></span></li>
                </ul>
            </li>
            <li class="sponsorship-block">
                <p class="sponsorship-title">Correalização</p>
                <ul class="sponsorship-items">
                    <li class="sponsorship-item"><span class="sprite sprite-fundacao-clovis-salgado"></span></li>
                    <li class="sponsorship-item"><span class="sprite sprite-governo-minas"></span></li>
                </ul>
            </li>
            <li class="sponsorship-block sponsorship-block--full">
                <p class="sponsorship-title">realização</p>
                <ul class="sponsorship-items">
                    <li class="sponsorship-item"><span class="sprite sprite-universo-producao"></span></li>
                </ul>
            </li>
        </ul>
    </div>
</section>-->

<section class="sitemap">
    <div class="main-wrapper">
        <?php $this
            ->navigation('MostratiradentesNavigation')
            ->menu()->setPartial("mostratiradentes/partials/sitemap.phtml");

        echo $this
            ->navigation('MostratiradentesNavigation')
            ->menu()
            ->render(); ?>
    </div>
</section>