<!doctype html>
<html lang="">
<head>
    <meta charset="utf-8">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Mostra Tiradentes 2018</title>
    <style>
        html,body {
            background-color: black;
            width: 100%;
            height: 100%;
        }
        body {
            overflow-x: hidden;
            overflow-y: hidden;
            min-height: 100vh;
        }
        .home img{
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            -webkit-transform: translate(-50%, -50%);
            -moz-transform: translate(-50%, -50%);
            -o-transform: translate(-50%, -50%);
            -ms-transform: translate(-50%, -50%);


        }
    </style>
</head>
<body>
<div class="home">
    <img id="Image-Maps-Com-image-maps-2018-02-19-063756" src="<?php echo $this->basePath('assets/mostratiradentes/dist/images/tiradentes-home.jpg') ?>" border="0" width="1000" height="707" orgWidth="1000" orgHeight="707" usemap="#image-maps-2018-02-19-063756" alt="" />
    <map name="image-maps-2018-02-19-063756" id="ImageMapsCom-image-maps-2018-02-19-063756">
        <area  alt="" title="" href="http://www.mostratiradentes.com.br/inicio" shape="rect" coords="15,16,473,679" style="outline:none;" target="_self"     />
        <area  alt="" title="" href="http://www.mostratiradentessp.com.br" shape="rect" coords="512,29,979,684" style="outline:none;" target="_self"     />
    </map>
</div>
</body>
</html>
