<!doctype html>
<html lang="">
<head>
    <meta charset="utf-8">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Mostra Tiradentes 2019</title>
    <link rel="apple-touch-icon" href="apple-touch-icon.png">
    <link rel="stylesheet" href="<?php echo $this->basePath('assets/tiradentes2018') ?>/dist/styles/main.css?v=201803031701">

</head>
<body style="position: relative">
<div class="all" style="text-align: center; margin-top: 50px">
    <img id="Image-Maps-Com-image-maps-2018-09-25-072539" src="http://www.image-maps.com/m/private/0/csdhu6otip9drmc49rnnsmn2q5_home.jpg" border="0" width="1000" height="800" orgWidth="1000" orgHeight="800" usemap="#image-maps-2018-09-25-072539" alt="" />
    <map name="image-maps-2018-09-25-072539" id="ImageMapsCom-image-maps-2018-09-25-072539">
        <area  alt="" title="" href="http://universoproducao.com.br/inscricoes" shape="rect" coords="478,560,970,687" style="outline:none;" target="_self"     />
        <area  alt="" title="" href="http://mostratiradentes.com.br/inicio" shape="rect" coords="762,706,963,745" style="outline:none;" target="_self"     />
        <area shape="rect" coords="998,798,1000,800" alt="Image Map" style="outline:none;" title="Image Map" href="http://www.image-maps.com/index.php?aff=mapped_users_0" />
    </map>

</div>
</body>
</html>
