<!doctype html>
<html lang="pt">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Mostra Tiradente</title>

    <style>
        html,body {
            background-color: black;
            width: 100%;
            height: 100%;
        }
        body {
            overflow-x: hidden;
            overflow-y: hidden;
            min-height: 100vh;
        }
        .wrapper img{
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            -webkit-transform: translate(-50%, -50%);
            -moz-transform: translate(-50%, -50%);
            -o-transform: translate(-50%, -50%);
            -ms-transform: translate(-50%, -50%);


        }
    </style>

</head>
<body>

<div class="wrapper">
    <img id="Image-Maps-Com-image-maps-2017-02-13-064117" src="<?php echo $this->basePath('assets/mostratiradentes/dist/images/tiradentes-home.jpg') ?>" border="0" width="1000" height="625" orgWidth="1000" orgHeight="625" usemap="#image-maps-2017-02-13-064117" alt="" />
    <map name="image-maps-2017-02-13-064117" id="ImageMapsCom-image-maps-2017-02-13-064117">
        <area  alt="" title="" href="www.mostratiradentes.com.br/inicio" shape="rect" coords="404,24,978,307" style="outline:none;" target="_blank"     />
        <area  alt="" title="" href="www.mostratiradentessp.com.br/" shape="rect" coords="398,322,982,599" style="outline:none;" target="_blank"     />
    </map>
</div>

</body>
</html>