<?php $this->placeholder("home-class")->set("home"); ?>


<section class="banner">
    <div class="banner-items owl-carousel">
        <?php foreach ($this->bannerImages as $banner): ?>
            <div class="banner-item"><img src="<?php echo $this->thumbor()->url($banner->getMeta('_image'))->resize(1920, 648); ?>" alt=""></div>
        <?php endforeach; ?>
    </div>
</section>

<!-- Info -->
<section class="notice">
    <div class="main-wrapper">
        <p class="notice-text">Inscrições abertas para Filmes, seminários, oficinas, workshops e exibições na 20ª Mostra
            de tiradentes</p>
        <a href="" class="button-readmore">Inscreva-se</a>
    </div>
</section>

<!-- PRogramação -->
<!--<section class="prog">
    <div class="main-wrapper">
        <header class="main-header"><h1 class="section-title">Programação</h1></header>
    </div>
    <div class="prog-items">
        <article class="prog-item prog-item--high">
            <figure class="prog-figure">
                <img src="images/prog1.jpg" alt="">
            </figure>
            <div class="prog-content">
                <p class="prog-day">20 <small>sex</small></p>
                <p class="prog-title">Tantinho -memória em verde e rosa</p>
                <p class="prog-cat">Mostra Pré-estreia</p>
                <p class="prog-place">Centro Histórico - 15h</p>
            </div>
        </article>
        <article class="prog-item">
            <figure class="prog-figure">
                <img src="images/prog5.jpg" alt="">
            </figure>
            <div class="prog-content">
                <p class="prog-day">20 <small>sex</small></p>
                <p class="prog-title">Tantinho -memória em verde e rosa</p>
                <p class="prog-cat">Mostra Pré-estreia</p>
                <p class="prog-place">Centro Histórico - 15h</p>
            </div>
        </article>
        <article class="prog-item">
            <figure class="prog-figure">
                <img src="images/prog2.jpg" alt="">
            </figure>
            <div class="prog-content">
                <p class="prog-day">20 <small>sex</small></p>
                <p class="prog-title">Tantinho -memória em verde e rosa</p>
                <p class="prog-cat">Mostra Pré-estreia</p>
                <p class="prog-place">Centro Histórico - 15h</p>
            </div>
        </article>
        <article class="prog-item">
            <figure class="prog-figure">
                <img src="images/prog3.jpg" alt="">
            </figure>
            <div class="prog-content">
                <p class="prog-day">20 <small>sex</small></p>
                <p class="prog-title">Tantinho -memória em verde e rosa</p>
                <p class="prog-cat">Mostra Pré-estreia</p>
                <p class="prog-place">Centro Histórico - 15h</p>
            </div>
        </article>
        <article class="prog-item">
            <figure class="prog-figure">
                <img src="images/prog4.jpg" alt="">
            </figure>
            <div class="prog-content">
                <p class="prog-day">20 <small>sex</small></p>
                <p class="prog-title">Tantinho -memória em verde e rosa</p>
                <p class="prog-title">Mostra Pré-estreia</p>
                <p class="prog-place">Centro Histórico - 15h</p>
            </div>
        </article>
    </div>
    <div class="main-wrapper">
        <p class="prog-text">De 20 a 28 de janeiro, você estará em sintonia com o cinema em Tiradentes. São exposições, exibições de curtas e longas, debates, seminários e oficinas com grandes nomes da sétima arte
            <br /><a href="" class="button-readmore">Programação Completa</a></p>
    </div>
</section>-->

<section class="news">
    <div class="main-wrapper">
        <header class="news-header">
            <h1>acompanhe tudo o que acontece na 20ª mostra de Tiradentes</h1>
        </header>
        <div class="news-items">
            <?php foreach ($this->news as $news): ?>
            <article class="news-item">
                <a href="<?php echo $this->url("mostratiradentes/news", ['slug'=>$news->getSlug()]) ?>" class="news-link">
                    <figure class="news-figure"><img src="<?php echo  $this->thumbor()->url($news->getMeta('_thumb'))->resize(532, 331); ?>" alt=""></figure>
                    <p class="news-title"><?php echo $news->getTitle(); ?></p>
                </a>
            </article>
            <?php endforeach; ?>
        </div>
        <p class="news-all"><a class="button-readmore" href="<?php echo $this->url("mostratiradentes/default", ['slug'=>'noticias']); ?>">Todas as Notícias</a></p>
    </div>
</section>

<!-- TV -->
<!--<section class="tv">
    <div class="main-wrapper">
        <header class="main-header"><h1 class="section-title">TV Mostra</h1></header>

        <div class="tv-items">

            <article class="tv-item">
                <figure class="tv-figure">
                    <img src="images/tv1.jpg" alt="">
                </figure>
                <div class="tv-content">
                    <p class="tv-title">Estréia do longa comboio de sal e açúcar</p>
                </div>
            </article>

            <article class="tv-item">
                <figure class="tv-figure">
                    <img src="images/tv2.jpg" alt="">
                </figure>
                <div class="tv-content">
                    <p class="tv-title">stréia de longas nacionais é destaque na 20ª mostra de cinema de tiradentes</p>
                    <p class="tv-subtitle">Filmes nacionais estreiam em grande estilo na Mostra Tiradentes. Confira como foi o primeiro dia</p>
                </div>
            </article>

            <article class="tv-item">
                <figure class="tv-figure">
                    <img src="images/tv2.jpg" alt="">
                </figure>
                <div class="tv-content">
                    <p class="tv-title">stréia de longas nacionais é destaque na 20ª mostra de cinema de tiradentes</p>
                    <p class="tv-subtitle">Filmes nacionais estreiam em grande estilo na Mostra Tiradentes. Confira como foi o primeiro dia</p>
                </div>
            </article>
            <p class="tv-all"><a href="">Assista todos os vídeos <span class="icon icon-plus-circle"></span></a></p>
        </div>

    </div>
</section>-->

<section class="gallery">
    <div class="gallery-list owl-carousel">
        <?php foreach ($this->gallery as $img): ?>
            <div class="gallery-item">
                <figure class="gallery-figure">
                    <img src="<?php echo $this->thumbor()->url($img->getMeta('_image'))->resize(780, 505); ?>" alt="">
                </figure>
                <div class="gallery-desc">
                    <p class="gallery-title"><?php echo $img->getTitle(); ?>
                        <span><?php echo $img->getMeta('_credits'); ?></span></p>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</section>

<section class="guide">
    <div class="main-wrapper">
        <header class="guide-header">
            <h1>se renda aos encantos de uma das cidades históricas mais importantes do brasil e
                aprecie a sétima arte em uma mostra singular</h1>
        </header>
        <ul class="guide-items">
            <li class="guide-item">
                <a href="<?php echo $this->url("mostratiradentes/default", ['slug'=>'como-chegar']) ?>" class="guide-link">
                    <span class="sprite sprite-como-chegar"></span>
                    <p class="guide-title">Como Chegar</p>
                </a>
            </li>
            <li class="guide-item">
                <a href="<?php echo $this->url("mostratiradentes/default", ['slug'=>'turismo-e-informacoes']) ?>" class="guide-link">
                    <span class="sprite sprite-turismo"></span>
                    <p class="guide-title">Turismo e Informações</p>
                </a>
            </li>
            <li class="guide-item">
                <a href="<?php echo $this->url("mostratiradentes/default", ['slug'=>'restaurantes']) ?>" class="guide-link">
                    <span class="sprite sprite-restaurantes"></span>
                    <p class="guide-title">Restaurantes</p>
                </a>
            </li>
            <li class="guide-item">
                <a href="<?php echo $this->url("mostratiradentes/default", ['slug'=>'hoteis-e-acomodacoes']) ?>" class="guide-link">
                    <span class="sprite sprite-hospedagem"></span>
                    <p class="guide-title">hotéis e acomodações</p>
                </a>
            </li>
        </ul>
    </div>
</section>

<section class="eufacoamostra">
    <div class="main-wrapper">
        <header class="eufacoamostra-header">
            <h1><span class="icon icon-eufacoamostra"></span></h1>
            <p class="eufacoamostra-subtitle">Comemoramos o melhor do cenário cinematográfico de Minas e do Brasil. E é claro que não poderíamos fazer história sem a sua essencial participação</p>
        </header>
    </div>
    <div class="eufacoamostra-items">
        <?php foreach ($this->eufacoamostra as $eu): ?>
            <div class="eufacoamostra-item <?php echo !empty($eu->getVideo) ? "eufacoamostra-item--video" : ""; ?>">
                <a href="#" class="eufacoamostra-link">
                    <figure class="eufacoamostra-figure"><img src="<?php echo $this->thumbor()->url($eu->getThumb())->resize(600, 600); ?>" alt=""></figure></a></div>
        <?php endforeach; ?>
    </div>
    <p class="news-all"><a href="" class="button-readmore">Veja Mais Galerias</a></p>
</section>

<section class="newsletter">
    <div class="main-wrapper">
        <header class="newsletter-header">
            <h1>Receba Nossos Informativos</h1>
        </header>
        <form action="" class="newsletter-form">
            <input type="text" class="newsletter-input" placeholder="Nome">
            <input type="text" class="newsletter-input" placeholder="Email">
            <button type="submit" class="newsletter-submit">Cadastrar</button>
        </form>
    </div>
</section>

<section class="sponsorship">
    <div class="main-wrapper">
        <ul class="sponsorship-list">
            <li class="sponsorship-block sponsorship-block--full sponsorship-block--center">
                <ul class="sponsorship-items">
                    <li class="sponsorship-item"><span class="sprite sprite-lei"></span></li>
                </ul>
            </li>
            <li class="sponsorship-block">
                <p class="sponsorship-title">Patrocínio</p>
                <ul class="sponsorship-items">
                    <li class="sponsorship-item"><span class="sprite sprite-mercantil"></span></li>
                    <li class="sponsorship-item"><span class="sprite sprite-contax"></span></li>
                </ul>
            </li>
            <li class="sponsorship-block">
                <p class="sponsorship-title">Incentivo</p>
                <ul class="sponsorship-items">
                    <li class="sponsorship-item"><span class="sprite sprite-incentivo"></span></li>
                    <li class="sponsorship-item"><span class="sprite sprite-fundacao-cultura"></span></li>
                    <li class="sponsorship-item"><span class="sprite sprite-prefeitura-bh"></span></li>
                </ul>
            </li>
            <li class="sponsorship-block">
                <p class="sponsorship-title">APOIO Brasil CineMundi</p>
                <ul class="sponsorship-items">
                    <li class="sponsorship-item"><span class="sprite sprite-sebrae"></span></li>
                </ul>
            </li>
            <li class="sponsorship-block">
                <p class="sponsorship-title">Correalização</p>
                <ul class="sponsorship-items">
                    <li class="sponsorship-item"><span class="sprite sprite-fundacao-clovis-salgado"></span></li>
                    <li class="sponsorship-item"><span class="sprite sprite-governo-minas"></span></li>
                </ul>
            </li>
            <li class="sponsorship-block sponsorship-block--full">
                <p class="sponsorship-title">realização</p>
                <ul class="sponsorship-items">
                    <li class="sponsorship-item"><span class="sprite sprite-universo-producao"></span></li>
                </ul>
            </li>
        </ul>
    </div>
</section>

<section class="sitemap">
    <div class="main-wrapper">
        <?php $this
            ->navigation('MostratiradentesNavigation')
            ->menu()->setPartial("mostratiradentes/partials/sitemap.phtml");

        echo $this
            ->navigation('MostratiradentesNavigation')
            ->menu()
            ->render(); ?>
    </div>
</section>