<?php
/**
 * Created by PhpStorm.
 * User: ricardo
 * Date: 03/05/2018
 * Time: 09:37
 */

namespace Admin\Form\SessionSchool;


use Application\Entity\Movie\Movie;
use Application\Entity\Movie\MovieEventStatus;
use Application\Entity\Programing\Type;
use Application\Entity\Registration\Registration;
use Zend\Form\Form;

class SessionSchoolForm extends Form
{
    private $entityManager;
    private $registration;

    public function __construct($em, $registration=null)
    {
        if ($em) {
            $this->entityManager = $em;
        }

        if ($registration) {
            $this->registration = $registration;
        }

        parent::__construct('session-school-form');
        $this->setAttributes([
            'method' => 'POST',
            'class' => ' form-reload default-form-actions enable-validators'
        ]);

        $this->add([
            'type' => 'Select',
            'name' => 'registration',
            'options' => [
                'label' => 'Regulamento',
                'value_options' => $this->populateRegulations(),
                'empty_option' => 'Selecione'
            ],
            'attributes' => [
                'required' => 'required',
                'class' => 'trigger-form-reload'
            ]
        ]);

        $this->add([
            'name' => 'name',
            'options' => [
                'label' => 'Nome',
            ],
            'attributes' => [
                'placeholder' => 'Nome da sessão',
                'required' => 'required'
            ]
        ]);

        $this->add([
            'name' => 'age_range',
            'options' => [
                'label' => 'Faixa etária',
            ],
        ]);

        $this->add([
            'name' => 'movies',
            'type' => 'select',
            'options' => [
                'label' => 'Filme(s)',
                'empty_option' => 'Selecione',
                'value_options' => $this->populateMovies(),
            ],
            'attributes' => [
                'class' => 'select2',
                'multiple' => 'multiple'
            ]
        ]);
    }

    public function populateRegulations()
    {
        $regulations = [];
        if($this->getEntityManager()) {
            $coll = $this
                ->getEntityManager()
                ->getRepository(Registration::class)
                ->findBy([
                    'type' => Type::SESSION_SCHOOL
                ], ['startDate'=>'DESC']);

            foreach ($coll as $c) {
                $regulations[$c->getId()] = $c->getName();
            }
        }
        return $regulations;
    }

    public function setData($data)
    {
        return parent::setData($data); // TODO: Change the autogenerated stub
    }

    public function populateMovies()
    {
        $movies = [];
        if($this->getEntityManager() && $this->getRegistration()) {
            $itens = $this
                ->getEntityManager()
                ->getRepository(Movie::class)
                ->createQueryBuilder('m')
                ->innerJoin('m.subscriptions', 's')
                ->andWhere('s.event = :idEvent')
                ->andWhere('s.status = :status')
                ->setParameters([
                    'idEvent' => $this->getRegistration()->getEvent()->getId(),
                    'status' => MovieEventStatus::SELECTED
                ])
                ->orderBy('m.title', 'ASC')
                ->getQuery()
                ->getResult();

            foreach ($itens as $m) {
                $movies[$m->getId()] = $m->getTitle();
            }
        }
        return $movies;
    }

    /**
     * @return null
     */
    public function getEntityManager()
    {
        return $this->entityManager;
    }

    /**
     * @param null $entityManager
     */
    public function setEntityManager($entityManager)
    {
        $this->entityManager = $entityManager;
    }

    /**
     * @return Registration
     */
    public function getRegistration()
    {
        return $this->registration;
    }

    /**
     * @param null $registration
     */
    public function setRegistration($registration)
    {
        $this->registration = $registration;
    }

}