<?php $form = $this->form; ?>

<div class="container">
    <p class="meuuniverso-brand meuuniverso-brand--center"><strong>Meu</strong>Universo | Proposta artística</p>
        <div class="row">
            <?php $form->prepare(); echo $this->form(null, null)->openTag($form); ?>

            <?php echo $this->formRow($form->get('artist_name')) ?>
            <?php echo $this->formRow($form->get('show_name')) ?>
            <?php echo $this->formRow($form->get('category')) ?>
            <?php echo $this->formRow($form->get('duration')) ?>
            <?php echo $this->formRow($form->get('target_public')) ?>
            <?php echo $this->formRow($form->get('suggested_cache')) ?>
            <?php echo $this->formRow($form->get('staff_quantity')) ?>
            <?php echo $this->formRow($form->get('incentive_law')) ?>
            <?php echo $this->formRow($form->get('links')) ?>
            <?php echo $this->formRow($form->get('short_presentation')) ?>
            <?php echo $this->formRow($form->get('comments')) ?>


            <div class="form-group">
                <div class="col-md-offset-3 col-md-5"><button class="btn btn-success" type="submit">Cadastrar</button></div>
            </div>
            <?php echo $this->form()->closeTag() ?>
        </div>
</div>