<div class="portlet light" id="form_wizard_1">
    <div class="portlet-body form">
        <?php $form = $this->form;
        $form->prepare();
        echo $this->form(null, null)->openTag($form); ?>

        <?php if($form->getMessages()): ?>
            <div class="portlet box red">
                <div class="portlet-title">
                    <div class="caption">Atenção, os seguintes erros foram encontrados </div>
                </div>
                <div class="portlet-body">
                    <?php foreach ($form->getMessages() as $field=>$message): ?>
                        <h4 class="h4">Campo <strong class="bold"><?php echo $form->get($field)->getLabel(); ?></strong></h4>
                        <div style="padding-left: 20px">
                        <?php foreach ($message as $key=>$m): ?>
                            <?php if(is_array($m)): ?>
                                <?php foreach ($m as $subK => $subN): ?>
                                    <p class=""><?php echo is_array($subN)?implode(';', $subN):$subN ?></p>
                                <?php endforeach; ?>
                            <?php else: ?>
                                <p class=""><?php echo $m ?></p>
                            <?php endif; ?>
                        <?php endforeach; ?>
                        </div>
                    <?php endforeach; ?>
                </div>
            </div>
        <?php endif; ?>

        <div class="form-wizard">
            <div class="form-body">
                <ul class="nav nav-pills nav-justified steps">
                    <li>
                        <a href="#tab_regulation" data-toggle="tab" class="step">
                            <span class="number"> 1 </span>
                            <span class="desc"><i class="glyphicon glyphicon-ok"></i> Regulamento </span>
                        </a>
                    </li>
                    <li>
                        <a href="#tab2" data-toggle="tab" class="step">
                            <span class="number"> 2 </span>
                            <span class="desc"><i class="glyphicon glyphicon-ok"></i> Cadastro </span>
                        </a>
                    </li>

                </ul>
                <div id="bar" cla ss="progress progress-striped" role="progressbar">
                    <div class="progress-bar progress-bar-success"> </div>
                </div>

                <div class="tab-content">
                    <div class="tab-pane active" id="tab_regulation">
                        <h3 class="h3 block">Regulamento</h3>
                        <?php echo $this->regulation($this->reg); ?>

                        <div class="row">
                            <div class="col-md-12">
                                <div class="movie-multi-check">
                                    <?php echo $this->formRow($form->get('accept_regulation')); ?>
                                </div>
                            </div>
                        </div>

                    </div>
                    <div class="tab-pane" id="tab2">
                        <?php echo $this->formRow($form->get('proposers_name')) ?>
                        <?php echo $this->formRow($form->get('responsible')) ?>
                        <?php echo $this->formRow($form->get('institution')) ?>
                        <?php echo $this->formRow($form->get('institution_address')) ?>
                        <?php echo $this->formRow($form->get('institution_uf')) ?>
                        <?php echo $this->formRow($form->get('institution_phone')) ?>
                        <?php echo $this->formRow($form->get('institution_mobile_phone')) ?>
                        <?php echo $this->formRow($form->get('institution_email')) ?>
                        <?php echo $this->formRow($form->get('title')) ?>
                        <?php echo $this->formRow($form->get('category')) ?>
                        <?php echo $this->formRow($form->get('presentation')) ?>
                        <?php echo $this->formRow($form->get('curriculum')) ?>
                        <?php echo $this->formRow($form->get('complete_text')) ?>
                        <?php echo $this->formRow($form->get('references')) ?>
                        <?php echo $this->formRow($form->get('links')) ?>

                        <?php $files = $form->get('files')->getFieldsets(); ?>
                        <div class="form-group">
                            <label class="control-label col-md-4">Imagem<span class="required" aria-required="true"> * </span></label>
                            <div class="col-md-6">
                            <?php foreach ($files as $fieldset):  ?>
                                <div class="fileinput fileinput-new" data-provides="fileinput">
                                    <div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 200px; height: 150px;">
                                    </div>
                                    <div>
                                        <span class="btn red btn-outline btn-file">
                                            <span class="fileinput-new"> Selecionar imagem </span>
                                            <span class="fileinput-exists"> Alterar </span>
                                            <?php echo $this->formElement($fieldset->get('file')); ?>
                                        </span>
                                        <a href="javascript:;" class="input-group-addon btn red fileinput-exists" data-dismiss="fileinput"> Remove </a>
                                    </div>
                                    <?php echo $this->formElement($fieldset->get("credits")) ?>
                                    <?php echo $this->formElementErrors($fieldset->get('file')); ?>
                                </div><br>
                            <?php endforeach; ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-actions">
                <div class="row">
                    <div class="col-md-offset-3 col-md-9">
                        <a href="javascript:;" class="btn default button-previous">
                            <i class="glyphicon glyphicon-chevron-left"></i> Voltar </a>
                        <a href="javascript:;" class="btn btn-outline green button-next"> Continuar
                            <i class="glyphicon glyphicon-chevron-right"></i>
                        </a>
                        <button type="submit" class="btn green button-submit"> Cadastrar
                            <i class="glyphicon glyphicon-ok"></i>
                        </button>
                    </div>
                </div>
            </div>
        </div>
        <?php echo $this->form()->closeTag() ?>
    </div>
</div>
