<?php

/**
 * Created by PhpStorm.
 * User: Ricardo Viana
 * Date: 08/02/2016
 * Time: 10:59
 */
namespace TwbBundle\Form\View\Helpe;

use Zend\Form\ElementInterface;
use Zend\Form\View\Helper\FormTextarea;

class TwbBundleFormCKEditor extends FormTextarea
{
	public function render(ElementInterface $element)
	{
		return parent::render($element); // TODO: Change the autogenerated stub
	}
}