<?php
namespace TwbBundle\Form\View\Helper;

use Zend\Form\Element\Button;
use Zend\Form\ElementInterface;
use Zend\Form\View\Helper\FormText;

class TwbBundleFormDatePicker extends FormText
{
	public function render(ElementInterface $element)
	{
		$phpFormat = $element->getOption('php-date-format')
			? $element->getOption('php-date-format')
			: 'd/m/Y';

		if($value = $element->getValue()) {
			if($value instanceof \DateTime) {
				$element->setValue($value->format($phpFormat));
			}
		}

		return parent::render($element); // TODO: Change the autogenerated stub
	}
}