<?php
/**
 * Created by PhpStorm.
 * User: Ricardo Viana
 * Date: 08/02/2016
 * Time: 11:00
 */

namespace TwbBundle\Form\View\Helper;


use Zend\Form\ElementInterface;
use Zend\Form\View\Helper\FormText;

class TwbBundleFormTagsInput extends FormText
{
	public function render(ElementInterface $element)
	{
		return parent::render($element); // TODO: Change the autogenerated stub
	}
}