<?php $this->placeholder("is_home")->set(true); ?>
<?php $this->placeholder("is_header_dark")->set(true); ?>
<section class="banner">
    <div class="owl-carousel" id="banner-home">
        <?php if(count($this->bannerImages) > 0):
            foreach ($this->bannerImages as $banner): ?>
                <div class="banner-slide owl-slide" style="background-image: url('<?php echo $this->thumbor()->url($banner->getMeta('_image'))->resize(1920, 746); ?>')">
                    <?php if($banner->getSubtitle()): ?>
                        <span class="banner-copy"><?php echo $banner->getSubtitle(); ?></span>
                    <?php endif; ?>
                </div>
            <?php endforeach; ?>
        <?php else: ?>
            <div class="banner-slide owl-slide" style="background-image: url('<?php echo $this->basePath('assets/universoproducao/dist') ?>/images/banner-1.jpg')">
                <div class="banner-content">
                    <div class="banner-wrapper">
                        <p class="banner-title">&nbsp;</p>
                    </div>
                </div>
            </div>
        <?php endif; ?>
    </div>
    <a class="mouse-bottom" id="mouse-bottom" href="#"><span class="icon-arrow-down4"></span></a>
</section>

<section class="news" id="news">
    <div class="news-wrapper">
        <header class="news-header--home">
            <h1 class="news-title">Nosso Universo está em constante produção</h1>
        </header>

        <ul class="news-list news-list--highlight">
            <?php foreach ($this->news as $news): ?>
                <li class="news-item">
                    <a href="<?php echo $this->url('universoproducao/news', ['slug'=>$news->getSlug()])?>" class="news-link">
                        <?php if($news->hasMeta('_thumb')): ?>
                            <figure class="news-figure">
                                <img src="<?php echo  $this->thumbor()->url($news->getMeta('_thumb'))->resize(384, 288); ?>" alt="">
                            </figure>
                        <?php endif; ?>
                        <article class="news-article">
                            <header class="news-header">
                                <h1><?php echo $news->getTitle(); ?></h1>
                            </header>
                        </article>
                    </a>
                </li>
            <?php endforeach; ?>
        </ul>
        <p class="news-readmore">
            <a href="<?php echo $this->url("universoproducao/default", ['slug'=>'noticias']); ?>" class="link-readmore">Veja mais notícias <span class="icon-plus3"></span></a>
        </p>
    </div>
</section>

<?php if(!empty($this->videos)): ?>
    <section class="channel channel--home">
        <header class="channel-header">
          <h1 class="channel-title">Canal Universo</h1>
        </header>
        <div class="channel-row">
            <div class="channel-slider--home owl-carousel">
                <?php foreach ($this->videos as $v): ?>
                    <div class="channel-item">
                        <a class="channel-link" href="<?php echo $this->url('universoproducao/channel', ['id'=>$v->getId()]) ?>">
                            <div class="channel-image">
                                <img src="<?php echo  $this->thumbor()->url($v->getCover())->resize(612, 390); ?>" alt="">
                            </div>
                            <span class="channel-play"><span class="play-icon icon-play4"></span></span>
                            <div class="channel-content">
                                <p class="title"><?php echo $v->getTitle(); ?></p>
                                <p class="date"><?php echo ucfirst($this->dateFormat($v->getDate(), null, null, "pt_BR", "MMM Y")); ?></p>
                            </div>
                        </a>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>

        <div class="main-wrapper">
            <p class="channel-readmore">
                <a href="<?php echo $this->url("universoproducao/default", ['slug'=>'canal-universo']) ?>" class="link-readmore">Veja mais videos <span class="icon-plus3"></span></a>
            </p>
        </div>

    </section>
<?php endif; ?>

<?php if(!empty($this->gallery)): ?>
    <section class="gallery">
        <div class="gallery-header gallery-header--mobile">
            <h1 class="gallery-title">O universo da produção</h1>
        </div>
        <div class="gallery-items">
            <div class="gallery-row">
                <div class="col">
                    <?php foreach (array_slice($this->gallery, 0, 4) as $img): ?>
                        <div class="gallery-item">
                            <a data-fancybox data-caption="<?php echo $img->getTitle() . $img->getMeta('_credits'); ?>" href="<?php echo $this->thumbor()->url($img->getMeta('_image'))->resize(958, 620); ?>" class="gallery-link">
                                <img src="<?php echo $this->thumbor()->url($img->getMeta('_image'))->resize(479, 310); ?>" alt="" class="gallery-img">
                            </a>
                        </div>
                    <?php endforeach; ?>
                </div>
                <div class="col col--header">
                    <header class="gallery-header">
                        <div class="wrapper">
                            <h1 class="gallery-title">O universo da<br>produção</h1>
                            <a class="gallery-subtitle" target="_blank" href="http://www.flickr.com/photos/universoproducao">Veja mais fotos no <span><i class="icon icon-flickr"></i><span class="name">flickr</span></span></a>
                        </div>
                    </header>
                </div>
            </div>
            <div class="gallery-row">
                <?php foreach (array_slice($this->gallery, 4, 4) as $img): ?>
                    <div class="gallery-item">
                        <a data-fancybox data-caption="<?php echo $img->getTitle() . $img->getMeta('_credits'); ?>" href="<?php echo $this->thumbor()->url($img->getMeta('_image'))->resize(958, 620); ?>" class="gallery-link">
                            <img src="<?php echo $this->thumbor()->url($img->getMeta('_image'))->resize(479, 310); ?>" alt="" class="gallery-img">
                        </a>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
        <div class="gallery-header gallery-header--mobile">
            <a class="gallery-subtitle" target="_blank" href="http://www.flickr.com/photos/universoproducao">Veja mais fotos no <span><i class="icon icon-flickr"></i><span class="name">flickr</span></span></a>
        </div>
    </section>
<?php endif; ?>

<div class="main-wrapper">
    <section class="newsletter">
        <header class="newsletter-header">
            <h1 class="newsletter-title">Fique por dentro das nossas novidades</h1>
        </header>
        <form action="<?php echo $this->url('universoproducao/newsletter'); ?>" class="newsletter-form">
            <input required="required" class="input" placeholder="Nome">
            <input required="required" class="input" placeholder="Email">
            <button class="submit" type="submit">Cadastrar</button>
        </form>
    </section>
</div>