<?php $this->placeholder("is_home")->set(true); ?>
<div class="fullslider">
    <div class="home-slider">
        <?php foreach ($this->bannerImages as $banner): ?>
            <div class="home-slider__slide home-slider__slide--img" style="background-image: url('<?php echo $banner->getFile()?>')">
                <?php if($banner->getTitle()): ?>
                    <div class="home-slider__text center-bottom">
                        <a href="">
                            <h2 class="home-slider__title"><?php echo $banner->getTitle(); ?></h2>
                            <p class="home-slider__subtitle"><?php echo $banner->getDescription(); ?></p>
                        </a>
                    </div>
                <?php endif; ?>
            </div>
        <?php endforeach; ?>
    </div>
    <div class="home-slider-dots">
    </div>
</div>