<section class="main-wrapper main-content">
    <header class="main-header">
        <h1 class="main-title"><?php echo $this->post->getTitle(); ?></h1>
    </header>
    <?php echo $this->thumborize($post->getContent()); ?>

    <?php if($this->credenciamento): ?>
        <h2 class="main-subtitle">Cadastro realizado com sucesso!</h2>
    <?php else: ?>

    <form action="" class="form" method="POST">
        <table width="100%" border="0" cellspacing="0" class="tabelaForm">
            <tr>
                <td align="right" bgcolor="#FFF9F0"><strong>Nome do Ve&iacute;culo<span class="obrigatorio">*</span>:</strong></td>
                <td bgcolor="#FFF9F0"><input name="NomeVeiculo" type="text" class="w350" id="NomeVeiculo" value=""/></td>
            </tr>
            <tr>
                <td align="right"><strong>Endere&ccedil;o<span class="obrigatorio">*</span>:</strong></td>
                <td><input name="Endereco" type="text" class="w350" id="Endereco" /></td>
            </tr>
            <tr>
                <td align="right" bgcolor="#FFF9F0"><strong>Cidade<span class="obrigatorio">*</span>:</strong></td>
                <td bgcolor="#FFF9F0"><input name="Cidade" type="text" class="w256" id="Cidade" />
                    &nbsp;&nbsp;UF<span class="obrigatorio">*</span>:
                    <input name="UF" type="text" class="w50" id="UF" /></td>
            </tr>
            <tr>
                <td align="right"><strong>Cep<span class="obrigatorio">*</span>:</strong></td>
                <td><input name="CEP" type="text" class="w100" id="CEP" /></td>
            </tr>
            <tr>
                <td align="right"><strong>Website<span class="obrigatorio">*</span>:</strong></td>
                <td><input name="Website" type="text" class="w350" id="Endereco" /></td>
            </tr>
            <tr>
                <td height="50" align="right" bgcolor="#FFF9F0"><strong>Tipo<span class="obrigatorio">*</span>: </strong></td>
                <td bgcolor="#FFF9F0"><table width="100%" border="0" cellspacing="0" cellpadding="0" class="tabelaFormInterna">
                        <tr>
                            <td width="23%">
                                <input name="Tipo" type="radio" class="semBorda" id="Tipo" value="Jornal Impresso" />
                                Jornal Impresso</td>
                            <td width="23%"><input name="Tipo" type="radio" class="semBorda" id="Tipo" value="Revista Impressa" />
                                Revista Impressa</td>
                            <td width="15%"><input name="Tipo" type="radio" class="semBorda" id="Tipo" value="Site_Internet" />
                                Online</td>
                            <td width="39%"><input name="Tipo" type="radio" class="semBorda" id="Tipo" value="TV Aberta" />
                                TV Aberta</td>
                        </tr>
                        <tr>
                            <td><input name="Tipo" type="radio" class="semBorda" id="Tipo" value="TV Fechada" />
                                TV Fechada</td>
                            <td><input name="Tipo" type="radio" class="semBorda" id="Tipo" value="Radio" />
                                R&aacute;dio</td>
                            <td colspan="2"><input name="Tipo" type="radio" class="semBorda" id="Tipo" value="Outros" />
                                Outros (Detalhar)
                                <input name="TipoOutros" type="text" class="w100" id="TipoOutros" /></td>
                        </tr>
                    </table></td>
            </tr>
            <tr>
                <td height="30" align="right"><strong> Circulação do veículo<span class="obrigatorio">*</span>:</strong></td>
                <td><table width="100%" border="0" cellspacing="0" cellpadding="0">
                        <tr>
                            <td width="29%"><input name="Cobertura" type="radio" class="semBorda" id="Cobertura" value="Nacional" />
                                Nacional </td>
                            <td width="30%"><input name="Cobertura" type="radio" class="semBorda" id="Cobertura" value="Regional" />
                                Regional</td>
                        </tr>
                    </table></td>
            </tr>
            <tr>
                <td height="50" align="right" bgcolor="#FFF9F0"><strong>Periodicidade<span class="obrigatorio">*</span>:</strong></td>
                <td bgcolor="#FFF9F0"><table width="100%" border="0" cellspacing="0" cellpadding="0">
                        <tr>
                            <td width="29%"><input name="Periodicidade" type="radio" class="semBorda" id="Periodicidade" value="Diaria" />
                                Di&aacute;ria </td>
                            <td width="30%"><input name="Periodicidade" type="radio" class="semBorda" id="Periodicidade" value="Semanal" />
                                Semanal</td>
                            <td width="41%"><input name="Periodicidade" type="radio" class="semBorda" id="Periodicidade" value="Quinzenal" />
                                Quinzenal</td>
                        </tr>
                        <tr>
                            <td><input name="Periodicidade" type="radio" class="semBorda" id="Periodicidade" value="Mensal" />
                                Mensal </td>
                            <td colspan="2"><input name="Periodicidade" type="radio" class="semBorda" id="Periodicidade" value="Outros" />
                                Outros (Detalhar)
                                <input name="PeriodicidadeOutros" type="text" class="w100" id="PeriodicidadeOutros" /></td>
                        </tr>
                    </table></td>
            </tr>
            <tr>
                <td align="right"><strong>Alcance/Tiragem*:</strong></td>
                <td><input name="alcance" type="text" class="w350" id="alcance" /></td>
            </tr>
            <tr bgcolor="#FFF9F0">
                <td align="right"><strong>Ano de Fundação*:</strong></td>
                <td><input name="anoFundacao" type="text" class="w350" id="anoFundacao" /></td>
            </tr>
            <tr>
                <td align="right"><strong>Editoria*:</strong></td>
                <td><input name="editoria" type="text" class="w350" id="editoria" /></td>
            </tr>
            <tr bgcolor="#FFF9F0">
                <td width="23%" align="right"><strong>Nome do redator chefe:</strong></td>
                <td width="77%"><input name="NomeRedatorChefe" type="text" class="w350" id="NomeRedatorChefe" /></td>
            </tr>
            <tr>
                <td align="right"><strong>Nome do respons&aacute;vel pelo credenciamento<span class="obrigatorio">*</span>:</strong></td>
                <td><input name="NomeResponsavelCredenciamento" type="text" class="w350" id="NomeResponsavelCredenciamento" /></td>
            </tr>
            <tr bgcolor="#FFF9F0">
                <td align="right"><strong>Cargo<span class="obrigatorio">*</span>:</strong></td>
                <td><input name="Cargo" type="text" class="w350" id="Cargo" /></td>
            </tr>
            <tr>
                <td align="right"><strong>Telefone fixo do ve&iacute;culo:</strong></td>
                <td><input name="TelefoneFixo" type="text" class="w100" id="TelefoneFixo" /></td>
            </tr>
            <tr bgcolor="#FFF9F0">
                <td align="right"><strong>Telefone celular<span class="obrigatorio">*</span>:</strong></td>
                <td><input name="TelefoneCelular" type="text" class="w100" id="TelefoneCelular" /></td>
            </tr>
            <tr>

                <td align="right"><strong>Email<span class="obrigatorio">*</span>:</strong></td>
                <td><input name="email" type="email" class="w350" id="email" value="" required /></td>

            </tr>
            <tr>
                <td height="30" align="right" bgcolor="#FFF9F0"><strong>Per&iacute;odo de Cobertura:</strong></td>
                <td bgcolor="#FFF9F0"><table width="100%" border="0" cellspacing="0" cellpadding="0">
                        <tr>
                            <td width="29%"><input name="perCobertura" type="radio" class="semBorda" id="perCobertura" value="TodoEvento" />
                                Todo o Evento</td>
                            <td width="71%"><input name="perCobertura" type="radio" class="semBorda" id="perCobertura" value="ParteDoEvento" />
                                Parte do Evento (Detalhar)
                                <input name="coberturaParte" type="text" class="w100" id="coberturaParte" /></td>
                        </tr>
                    </table></td>
            </tr>
            <tr>
                <td colspan="2" align="left" valign="middle"><strong>PROPOSTA DE COBERTURA (Descreva o tipo de cobertura pretendida)</strong></td>
            </tr>
            <tr>
                <td align="right" valign="top"><strong>Justificativa<span class="obrigatorio">*</span>:</strong></td>
                <td><textarea name="TipoCorbeturaJustificativa" rows="5" class="w350" id="TipoCorbeturaJustificativa"></textarea></td>
            </tr>
            <tr>
                <td height="50" align="right" bgcolor="#FFF9F0"><strong>Foco Principal<span class="obrigatorio">*</span>:</strong></td>
                <td bgcolor="#FFF9F0"><table width="100%" border="0" cellspacing="0" cellpadding="0">
                        <tr>
                            <td width="29%" height="28"><input name="Foco" type="radio" class="semBorda" id="Foco" value="Filmes" />
                                Filmes </td>
                            <td width="30%"><input name="Foco" type="radio" class="semBorda" id="Foco" value="Seminarios" />
                                Seminários</td>
                            <td width="20%"><input name="Foco" type="radio" class="semBorda" id="Foco" value="Tematica" />
                                Temática</td>
                            <td width="21%"><input name="Foco" type="radio" class="semBorda" id="Foco" value="Homenagem" />
                                Homenagem
                            </td>
                        </tr>
                        <tr>
                            <td colspan="4"><input name="Foco" type="radio" class="semBorda" id="Foco" value="Outros" />
                                Outros (Detalhar)
                                <input name="FocoOutros" type="text" class="w100" id="FocoOutros" /></td>
                        </tr>
                    </table></td>
            </tr>
            <tr>
                <td align="right" valign="top"><strong>Número de Publicações/Inserções previstas (especificar por editoria/programa):</strong></td>
                <td><textarea name="publicacoes" rows="5" class="w350" id="publicacoes"></textarea></td>
            </tr>
            <tr>
                <td height="70" align="right" bgcolor="#FFF9F0"><strong>Período de publicações/inserções<span class="obrigatorio">*</span>:</strong></td>
                <td bgcolor="#FFF9F0"><table width="100%" border="0" cellspacing="0" cellpadding="0">
                        <tr>
                            <td width="29%"><input name="PeriodoPublicacao" type="radio" class="semBorda" id="PeriodoPublicacao" value="Filmes" />
                                Apenas durante o evento</td>
                        </tr>
                        <tr>
                            <td><input name="PeriodoPublicacao" type="radio" class="semBorda" id="PeriodoPublicacao" value="Outros" />
                                Durante e após o evento (Detalhar data limite prevista)
                                <input name="dataLimiteDuranteApos" type="text" class="w100" id="dataLimiteDuranteApos" /></td>
                        </tr>
                        <tr>
                            <td><input name="PeriodoPublicacao" type="radio" class="semBorda" id="PeriodoPublicacao" value="Outros" />
                                Apenas após o evento (Detalhar data limite prevista)
                                <input name="dataLimiteApos" type="text" class="w100" id="dataLimiteApos" /></td>
                        </tr>
                    </table></td>
            </tr>
            <tr>
                <td align="right" valign="top"><strong>Equipe de cobertura<br />nomes e fun&ccedil;&otilde;es:</strong></td>
                <td><textarea name="EquipeCorbetura" rows="5" class="w350" id="EquipeCorbetura"></textarea></td>
            </tr>
            <tr>
                <td align="right" valign="top"><strong>Informações Adicionais</strong></td>
                <td><textarea name="logistica" rows="5" class="w350" id="logistica"></textarea></td>
            </tr>
            <tr>
                <td height="80" align="left"></td>
                <td align="left"><input name="" type="submit" value="ENVIAR" class="btForm" onclick="return validarCamposObrigatorios();"/></td>
            </tr>
        </table>
    </form>
    <?php endif; ?>

</section>