<?php
error_reporting(E_ALL);
ini_set("display_errors", 1);

?>
<main class="main">
    <?php if($this->breadcrumbs): ?>
        <?php echo $this->partial('cineop2017/partials/_breadcrumbs.phtml', ['breadcrumbs'=>$this->breadcrumbs]); ?>
    <?php endif; ?>


    <div class="main-wrapper">
        <section class="main-content">
            <header class="main-header">
                <h1 class="main-title"><?php echo $this->post->getTitle(); ?></h1>
            </header>

            <?php
//            $dbh=mysql_connect ("162.243.253.29", "universoprod2", "ag51www");
            try {
                $pdo = new \PDO('mysql:host=162.243.253.29;dbname=universoprod2', "universoprod2", "ag51www", array(PDO::MYSQL_ATTR_INIT_COMMAND => "SET NAMES utf8"));
                $pdo->setAttribute(\PDO::ATTR_ERRMODE, \PDO::ERRMODE_EXCEPTION);
            } catch(\Exeception $e) {
                echo 'ERROR: ' . $e->getMessage();
                exit;
            }
            //$dbh=mysql_connect ("127.0.0.1", "root", "");
           /* if (!$dbh) {
                echo "Não foi possível conectar ao banco de dados: " . mysql_error();
                exit;
            }
            if (!mysql_select_db("universoprod2")) {
                echo "Não foi possível selecionar universoproducao: " . mysql_error();
                exit;
            }*/
            function databr($valor)
            {
                $valor = substr($valor,8,2) . "/" . substr($valor,5,2) . "/" . substr($valor,0,4);
                return $valor;
            }

            function databr2($valor)
            {
                $valor = substr($valor,8,2) . "." . substr($valor,5,2) . "." . substr($valor,0,4);
                return $valor;
            }

            function data_USA($valor1){
                $valor1 = substr($valor1,6,4) . "-" . substr($valor1,3,2) . "-" . substr($valor1,0,2);
                return $valor1;
            }
            function hora($valor)
            {
                if ($valor == '00:00:00') {
                    $texto = "";
                } else {
                    $texto = date('H:i', strtotime($valor));
                    $texto = str_replace(':','h',$texto);
                    $texto = str_replace('h00','h',$texto);
                }
                return $texto;
            }
            function formata_data_extenso($strDate)
            {
                // Array com os dia da semana em português;
                $arrDaysOfWeek = array('domingo', 'segunda', 'terça', 'quarta', 'quinta', 'sexta', 'sábado');
                // Array com os meses do ano em português;
                $arrMonthsOfYear = array(1 => '01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12');
                // Descobre o dia da semana
                $intDayOfWeek = date('w',strtotime($strDate));
                // Descobre o dia do mês
                $intDayOfMonth = date('d',strtotime($strDate));
                // Descobre o mês
                $intMonthOfYear = date('n',strtotime($strDate));
                // Descobre o ano
                $intYear = date('Y',strtotime($strDate));
                // Formato a ser retornado
                return $arrDaysOfWeek[$intDayOfWeek];
            }
            function is_utf8($str)
            {
                if(!is_string($str))
                    return true;

                $c=0; $b=0;
                $bits=0;
                $len=strlen($str);
                for($i=0; $i<$len; $i++)
                {
                    $c=ord($str[$i]);
                    if($c > 128)
                    {
                        if(($c >= 254)) return false;
                        elseif($c >= 252) $bits=6;
                        elseif($c >= 248) $bits=5;
                        elseif($c >= 240) $bits=4;
                        elseif($c >= 224) $bits=3;
                        elseif($c >= 192) $bits=2;
                        else return false;
                        if(($i+$bits) > $len) return false;
                        while($bits > 1)
                        {
                            $i++;
                            $b=ord($str[$i]);
                            if($b < 128 || $b > 191) return false;
                            $bits--;
                        }
                    }
                }
                return true;
            }

            function utf8($string)
            {
                if (is_utf8($string))
                {
                    return $string;
                } else {
                    return utf8_encode($string);
                }
            }

            $mostra = 1076;
            $lg = '';
            $url = '';
            $fc = $fl = $sub = $subMostra = $fSub1 = $fSub2 = $fSub3 = '';
            //$limitCurta = 0;
            $Dir = "Direção";
            $subMostra = isset($_GET['subMostra']) ? $_GET['subMostra'] : null;
            ?>


            <h2 class="subTitProgramacao">Programação por data</h2>

            <div id="menuProgramacao">
                <?php
                $filtroDia = "";
                $filtroCat = "";
                $filtroLoc = "";
                $filtroSem = "";

                $filtroSub = "";

                if (isset($_GET['fd'])) {
                    $fd = $_GET['fd'];
                    $filtroDia = "AND PR.Data = '".$fd."'";
                }
                if (isset($_GET['fc'])) {
                    $fc = $_GET['fc'];
                    switch($fc){
                        case 'AB': $filtroCat = "AND PR.CategoriaProg = 'AB'";  break;
                        case 'FI': $filtroCat = "AND PR.CategoriaProg = 'FI'";  break;
                        case 'SCE': $filtroCat = "AND PR.CategoriaProg = 'SCE'";  break;
                        case 'MO': $filtroCat = "AND PR.CategoriaProg = 'MO'";  break;
                        case 'SE': $filtroCat = "AND PR.CategoriaProg = 'SE'";  break;
                        case 'AR': $filtroCat = "AND PR.CategoriaProg = 'AR'";  break;
                        case 'EN': $filtroCat = "AND PR.CategoriaProg = 'EN'";  break;
                        case 'EX': $filtroCat = "AND PR.CategoriaProg = 'EX'";  break;
                    }

                }
                if (isset($_GET['fl'])) {
                    $fl = $_GET['fl'];
                    if ($fl == "") {
                        $filtroLoc = "";
                    } else {
                        $filtroLoc = "AND PR.Local = ".$fl;
                    }
                }

                if(isset($_GET['subMostra'])) {
                    $sub = $_GET['subMostra'];
                    if ($sub == "") {
                        $fSub1 = "";
                        $fSub2 = "";
                        $fSub3 = "";
                    } else {
                        $fSub1 = ", FM.SubMostra, O.SubMostra";
                        $fSub2 = " inner join tb_obras O ON O.codObra = PR.CodItemProg left join tb_filmemostra FM ON FM.CodFilme = PR.CodItemProg ";
                        $fSub3 = "AND PR.CategoriaProg = 'FI' AND (O.SubMostra = $sub OR FM.SubMostra = $sub)";
                    }
                }

                //echo "<p>FD: ".$fd."</p>";
                //$SqlMenuProg = mysql_query("Select distinct Data, CodMostra from tb_programacaoevento where CodMostra = $mostra and CategoriaProg <> 'FI' order by Data");
                $SqlMenuProg = $pdo->query("Select distinct Data, CodMostra from tb_programacaoevento where CodMostra = $mostra and CategoriaProg <> 'FI' order by Data");
//                $SqlMenuProg = $SqlMenuProg->fetchAll();
                ?>

                <?php
                while($Dado = $SqlMenuProg->fetch()) {
                    $data = databr($Dado["Data"]);
                    $data2 = explode("/", $data);
                    $dia = $data2[0];
                    ?>
                    <a class="form__button" href="<?php echo $this->url('cineop2017')?>programacao/programacao-completa?fd=<?php echo $Dado["Data"]?>"><?php echo $lg=='Ing' ? "" : "DIA"; ?> <?php echo $dia ?><?php echo $lg=='Ing' ? "TH" : ""; ?></a>
                <?php } ?>
            </div>
            <br />
            <form class="form-filtro" action="" method="get" name="form">

                <select class="form__input" name="fc" id="fc">

                    <?php if ($lg=='Ing'){ ?>
                        <option value="">-- CATEGORY --</option>
                        <option value="AB">OPENING</option>
                        <option value="FI">FILMS</option>
                        <option value="MO">CINEMA LITTLE EXHIBIT</option>
                        <option value="SE">BRASIL CINEMUNDI</option>
                        <option value="AR">ART</option>
                        <option value="EX">EXPOSITION</option>
                        <option value="EN">CLOSING</option>

                    <?php } else { ?>
                        <option value="">CATEGORIA</option>
                        <option value="AB" <?php echo $fc == "AB" ? "selected='selected'" : "";?>>ABERTURA</option>
                        <option value="FI" <?php echo $fc == "FI" ? "selected='selected'" : "";?>>FILMES</option>
                        <option value="MO" <?php echo $fc == "MO" ? "selected='selected'" : "";?>>MOSTRINHA</option>
                        <option value="SCE" <?php echo $fc == "SCE" ? "selected='selected'" : "";?>>CINE-ESCOLA</option>
                        <option value="SE" <?php echo $fc == "SE" ? "selected='selected'" : "";?>>SEMINÁRIO</option>
                        <option value="AR" <?php echo $fc == "AR" ? "selected='selected'" : "";?>>ARTE</option>
                        <option value="EX" <?php echo $fc == "EX" ? "selected='selected'" : "";?>>EXPOSIÇÃO</option>
                        <option value="EN" <?php echo $fc == "EN" ? "selected='selected'" : "";?>>ENCERRAMENTO</option>
                    <?php } ?>

                </select>
                <select class="form__input" name="subMostra" id="subMostra">
                    <option value=""><?php echo $lg=='Ing' ? "SUB-MOSTRA" : "SUB-MOSTRA"; ?></option>
                    <?php
                    $resultCatMostra = $pdo->query("SELECT * FROM tb_cat_filme WHERE CodMostra='$mostra' ORDER BY posicao");

                    if ($lg == 'Ing') {
                        while($rowCat = $resultCatMostra->fetch(\PDO::FETCH_OBJ)) {
                            if($rowCat->NomeHomIng != "") {
                                ?>
                                <option value="<?php echo $rowCat->CodCat?>"> <?php echo utf8($rowCat->NomeHomIng)?> </option>
                                <?php
                            }
                        }
                    } else {
                        while($rowCat = $resultCatMostra->fetch(\PDO::FETCH_OBJ)) {
                            ?>
                            <option value="<?php echo $rowCat->CodCat?>" <?php echo $subMostra == $rowCat->CodCat ? "selected='selected'" : "";?>> <?php echo utf8($rowCat->NomeHom) ?> </option>
                            <?php
                        }
                    }
                    ?>
                </select>
                <select class="form__input" name="fl" id="fl" >
                    <option value=""><?php echo $lg=='Ing' ? "SPOTS" : "LOCAL"; ?></option>
                    <?php
                    $result = $pdo->query("SELECT CodLocal, TitLocal, TitLocalIng FROM tb_local where CodMostra = $mostra order by TitLocal");
                    while ($row = $result->fetch(\PDO::FETCH_OBJ)) {
                        $TitLoc = $lg=='Ing' ? "TitLocalIng" : "TitLocal";?>
                        <option value="<?php echo $row->CodLocal?>" <?php echo $fl == $row->CodLocal ? "selected='selected'" : "";?>><?php echo utf8($row->$TitLoc)?></option>
                        <?php
                    }
//                    mysql_free_result($result);

                    ?>
                </select>
                <button type="submit" class="form__button" class="form__button">Filtrar</button>

                <input name="lg" type="hidden" value="<?php echo $lg?>" />
                <input name="menu" type="hidden" value="prog" />
                <input name="sub" type="hidden" value="pc" />

            </form>
            <!--<p><a href="<?php /*echo $this->basePath("assets/cinebh/programacao-completa.pdf") */?>" target="_blank">Faça o download da programação</a></p>-->

            <?php
            if (isset($_GET['fd']) || isset($_GET['fc']) || isset($_GET['fl'])  ) {
                ?>
                <h4 style="font-size: 12px; margin: 7px 0;"><a href="<?php echo $this->url('cineop2017')?>programacao/programacao-completa">&gt; <?php echo $lg=='Ing' ? "SHOW ENTIRE PROGRAM" : "EXIBIR TODA A PROGRAMAÇÃO"; ?></a></h4>
            <?php } ?>


            <!-- LISTA DE FILMES -->

            <?php
            $sqlProg = "select PR.CodProgEvento, PR.CodItemProg, PR.CategoriaProg, PR.Local, PR.order, PR.Data, PR.HoraManhaInicial, PR.HoraManhaFinal,
                PR.HoraTardeInicial, PR.HoraTardeFinal, PR.HoraNoiteInicial, PR.HoraNoiteFinal, PR.status, PR.mostraClassificacao, PR.preNacional, PR.preMundial, PR.infoAdicional $fSub1
                from tb_programacaoevento PR $fSub2
                where PR.CodMostra = $mostra AND (PR.CategoriaProg <> 'OF' && PR.CategoriaProg <> 'CE') $filtroDia $filtroCat $filtroLoc $fSub3
                order by Data, HoraManhaInicial, HoraManhaFinal, HoraTardeInicial, HoraTardeFinal, PR.order asc, HoraNoiteInicial, HoraNoiteFinal, status";




            /*if(isset($_GET["fc"]) && $_GET["fc"] == "SE" && empty($_GET['subMostra']))
            {
                $sqlProg = "(select PR.CodItemProg, PR.CodProgEvento, PR.CategoriaProg, PR.Local, PR.Data, PR.HoraManhaInicial, PR.HoraManhaFinal,
                PR.HoraTardeInicial, PR.HoraTardeFinal, PR.HoraNoiteInicial, PR.HoraNoiteFinal, PR.status, PR.mostraClassificacao, PR.preNacional, PR.preMundial, PR.infoAdicional
                from tb_programacaoevento PR
                where PR.CodMostra = $mostra AND PR.CategoriaProg <> 'OF' AND PR.CategoriaProg <> 'CE' AND PR.SessCurtas <> 999 $filtroDia $filtroCat $filtroLoc
                order by Data, HoraManhaInicial, HoraManhaFinal, HoraTardeInicial, HoraTardeFinal, HoraNoiteInicial, HoraNoiteFinal, status)
                UNION
                (select PR.CodItemProg, PR.CodProgEvento, PR.CategoriaProg, PR.Local, PR.Data, PR.HoraManhaInicial, PR.HoraManhaFinal,
                PR.HoraTardeInicial, PR.HoraTardeFinal, PR.HoraNoiteInicial, PR.HoraNoiteFinal, PR.status, PR.mostraClassificacao, PR.preNacional, PR.preMundial, PR.infoAdicional
                from tb_programacaoevento PR
                INNER JOIN tb_obras OB ON OB.codObra = PR.CodItemProg AND OB.SubMostra=92
                where PR.CodMostra = $mostra AND PR.CategoriaProg <> 'OF' AND PR.CategoriaProg <> 'CE' AND PR.SessCurtas <> 999 $filtroDia $filtroLoc
                order by Data, HoraManhaInicial, HoraManhaFinal, HoraTardeInicial, HoraTardeFinal, HoraNoiteInicial, HoraNoiteFinal, status)";
            }
            else
            {
                $sqlProg = "select PR.CodItemProg, PR.CodProgEvento, PR.CategoriaProg, PR.Local, PR.Data, PR.HoraManhaInicial, PR.HoraManhaFinal,
                PR.HoraTardeInicial, PR.HoraTardeFinal, PR.HoraNoiteInicial, PR.HoraNoiteFinal, PR.status, PR.mostraClassificacao, PR.preNacional, PR.preMundial, PR.infoAdicional
                from tb_programacaoevento PR
                $filtroSub
                where PR.CodMostra = $mostra AND PR.CategoriaProg <> 'OF' AND PR.CategoriaProg <> 'CE' AND PR.SessCurtas <> 999 $filtroDia $filtroCat $filtroLoc
                order by Data, HoraManhaInicial, HoraManhaFinal, HoraTardeInicial, HoraTardeFinal, HoraNoiteInicial, HoraNoiteFinal, status";
            }*/


            //echo "<p>SQL: ".$sqlProg."</p>";

            $resultProg = $pdo->query($sqlProg);
            $dataAnterior = "";
            $horaAnterior = "";
            $localAnterior = "";
            $categoriaAnterior = "";
            $countCurta = 0;
            $countAbertura = 0;
            $limitCurta = 0;
            $url = "#";
            $horarioFim = "";
            $horarioFimImp = "";
            $dia23 = false;
            ?>
            <table cellpadding="0" cellspacing="0" class="programacao diferent" width="100%">

                <tr>



                    <?php while ($rowProg = $resultProg->fetch(\PDO::FETCH_OBJ)) {


                    if($rowProg->CodItemProg == 209) {
                    ?>
                </tr>
                <tr style="">
                    <th valign="top">
                        <h5> 20h30 </h5>
                        <span style="font-size: 9px;">CINE VILA RICA</span>
                    </th>
                    <td valign="top">
                        <h5 >ABERTURA OFICIAL</h5>
                        <h6><a href="arte-detalhe.php?menu=programacao&amp;item=arte&amp;CodArte=209"><strong>PERFORMANCE AUDIOVISUAL</strong></a></h6><br />

                        <p style="font-size: 14px">
                            Tema Central da 11a CineOP: <strong>CINEMA, TV E EDUCAÇÃO</strong><br />
                            Direção: Chico de Paula <br />
                            Participações especiais: Leri Faria e atrizes  <br />
                            Trilha ao vivo: Rafael no som
                        </p>

                        <h5 >Homenagens</h5>
                        <p style="font-size: 14px">
                            <br />AO RESTAURADOR <strong>CHICO MOREIRA</strong> (in memoriam)	<br />
                            AO CINEASTA <strong>EDUARDO COUTINHO</strong> (in memoriam)
                        </p>

                        <br />

                    </td>
                </tr>


                <?php
                continue;
                }



                $dataOrig = $rowProg->Data;
                $data	 = databr($dataOrig);



                $horarioFim = $rowProg->HoraManhaFinal;

                if ($rowProg->HoraManhaInicial == '24:30:00'){
                    $horarioImp = "00h30";
                } else if ($rowProg->HoraManhaInicial == '20:29:00' OR $rowProg->HoraManhaInicial == '20:30:00'){
                    $horarioImp = "20h30";
                } else if ($rowProg->HoraManhaInicial == '20:59:00'){
                    $horarioImp = "21h";
                } else {


                    if ($lg=='Ing'){
                        $horarioImp = horaIng($rowProg->HoraManhaInicial);
                    } else {
                        $horarioImp = hora($rowProg->HoraManhaInicial);
                        //$horario = $rowProg->HoraManhaInicial;
                    }

                    $horario = hora($rowProg->HoraManhaInicial);


                    if ($horarioFim != ""){

                        if ($horarioFim != "00:00:00"){



                            if ($lg=='Ing'){
                                $horarioFimImp = " - ".horaIng($horarioFim);
                            } else {
                                $horarioFimImp = " às ".hora($horarioFim);
                            }

                            $horarioFim = " às ".hora($horarioFim);
                        }
                    }
                }

                $ccc = $rowProg->CategoriaProg;
                switch($rowProg->CategoriaProg){
                    case 'FI': $SqlTit = "select TituloObra, TituloObraIng, classeObra, FilmeConvidado, 
                                CategoriaConvidado, DirecaoObra, SubMostra, preEstreia, FaixaEtaria1, FaixaEtaria2 from tb_obras where codObra = $rowProg->CodItemProg";

                        $nomeSub = "";

                        $resultTit  = $pdo->query($SqlTit);
                        $resultTit = $resultTit->fetchObject();

                        @$titulo	= $resultTit->TituloObra;
                        @$direcao	= $resultTit->DirecaoObra;
                        @$preEstreia = $resultTit->preEstreia;
                        @$con	= $resultTit->FilmeConvidado;
                        @$subM	= $resultTit->SubMostra;

                        @$faixaEtaria1	= $resultTit->FaixaEtaria1;
                        @$faixaEtaria2	= $resultTit->FaixaEtaria2;
                        if ($con == 1) {
                            @$cat	= $resultTit->CategoriaConvidado;

                            if ($subM <> 0) {
                                @$SqlSub = "select CodCat, NomeHom, NomeHomIng from tb_cat_filme where CodCat = $subM";
                                @$resultSub  = $pdo->query($SqlSub);
                                @$resultSub = $resultSub->fetchObject();
                                @$nomeSub	= utf8($resultSub->NomeHom);

                                if ($nomeSub == "PRINCIPAL" || $nomeSub == "MOSTRA PRINCIPAL") {
                                    $subMostra = "";
                                } else {
                                    $subMostra = $nomeSub." • ";
                                }

                            } else {
                                $subMostra = "";
                            }

                        } else {

                            @$SqlSub = "select tb_filmemostra.SubMostra from tb_obras, tb_filmemostra where tb_obras.codObra = $rowProg->CodItemProg and tb_obras.codObra = tb_filmemostra.CodFilme and tb_filmemostra.CodMostra = $mostra";
                            @$resultSub  = $pdo->query($SqlSub);
                            @$resultSub = $resultSub->fetchObject();
                            @$subM	= $resultSub->SubMostra;

                            @$cat	= $resultSub->classeObra;

                            if ($subM <> 0) {
                                $SqlSub = "select CodCat, NomeHom, NomeHomIng from tb_cat_filme where CodCat = $subM";
                                $resultSub  = $pdo->query($SqlSub);
                                $resultSub = $resultSub->fetchObject();
                                $nomeSub	= utf8($resultSub->NomeHom);

                                if ($nomeSub == "PRINCIPAL" || $nomeSub == "MOSTRA PRINCIPAL") {
                                    $subMostra = "";
                                } else {
                                    $subMostra = $nomeSub." • ";
                                }

                            } else {
                                $subMostra = "";
                            }


                            switch($cat){
                                case 1: $cat = "Longa";  break;
                                case 2: $cat = "Media";  break;
                                case 3: $cat = "Curta";  break;
                            }


                        }

                        if ($cat == "Curta") {
                            $cat = "Sessão de Curtas";
                            $catIng = "Short Film Session";
                        }

                        $url = $this->url('cineop2017/movie', ['id'=>$rowProg->CodItemProg]);

                        if ($lg=='Ing'){
                            switch($cat){
                                case "Longa" : $catIng = 'FEATURES'; break;
                                case "Media" : $catIng = 'MEDIUN-FORMAT'; break;
                                case "Curta" : $catIng = 'SHORT FILMS'; break;
                            }
                            $categoria = "FILM • ".$subMostra.$catIng;
                        } else {
                            $categoria = "FILME • ".$subMostra.$cat;
                        }



                        break;


                    case 'SCE': $categoria = "SESSÃO CINE-ESCOLA";
                        $categoria = $lg=='Ing' ? "CINE-SCHOOL SESSION" : "SESSÃO CINE-ESCOLA";

                        $resultSess = $pdo->query("select idFilme from tb_sessoes_ce WHERE idSessao = '".$rowProg->CodItemProg."' ORDER BY Ordem ASC");

                        $titulo = array();
                        $direcao = array();
                        $preEstreia = array();
                        //$faixaEtaria1 = array();
                        //$faixaEtaria2 = array();
                        $url = array();
                        while($linhaSess = $resultSess->fetch(\PDO::FETCH_OBJ))
                        {
                            $SqlTit = "select TituloObra, TituloObraIng, DirecaoObra, preEstreia, FaixaEtaria1, FaixaEtaria2 from tb_obras where codObra = $linhaSess->idFilme";

                            $resultTit  = $pdo->query($SqlTit);
                            $r=$resultTit->fetch();

                            if($r)
                            {
                                $titulo[]	= $r["TituloObra".$lg];
                                $direcao[]	= $r["DirecaoObra"];
                                $preEstreia[] = $r["preEstreia"];
                                //$faixaEtaria1[]	= $r["FaixaEtaria1"];
                                //$faixaEtaria2[]	= $r["FaixaEtaria2"];
                                $faixaEtaria1	= $r["FaixaEtaria1"];
                                $faixaEtaria2	= $r["FaixaEtaria2"];
                                //$url = "cine-escola-detalhe.php?menu=prog&sub=cinescol&cat=$categoria&CodFilme=$linhaSess->idFilme";
                                $url = $this->url('cineop2017/movie', ['id'=>$linhaSess->idFilme]);
                            }
                        }


                        break;

                    case 'MO': $SqlTit = "select TituloObra, TituloObraIng, classeObra, FilmeConvidado, CategoriaConvidado, DirecaoObra, preEstreia, FaixaEtaria1, FaixaEtaria2 
                                from tb_obras where codObra = $rowProg->CodItemProg";
                        $resultTit  = $pdo->query($SqlTit);
                        $resultTit = $resultTit->fetchObject();
                        $titulo	= $resultTit->TituloObra;
                        $direcao	= $resultTit->DirecaoObra;
                        $preEstreia = $resultTit->preEstreia;
                        $faixaEtaria1	= $resultTit->FaixaEtaria1;
                        $faixaEtaria2	= $resultTit->FaixaEtaria2;
                        $con	= $resultTit->FilmeConvidado;
                        if ($con == 1) {
                            $cat	= $resultTit->CategoriaConvidado;
                        } else {
                            $cat	= $resultTit->classeObra;
                            switch($cat){
                                case 1: $cat = "Longa";  break;
                                case 2: $cat = "Media";  break;
                                case 3: $cat = "Curta";  break;
                            }

                        }
                        if ($cat == "Curta") {
                            $cat = "Sessão de Curtas";
                            $catIng = "Short Film Session";
                        }
                        //$url = "filme-detalhe.php?menu=programacao&item=filmes&cat=$cat&mostrinha=1&CodFilme=$rowProg->CodItemProg";
                        $url = $this->url('cineop2017/movie', ['id'=>$rowProg->CodItemProg]);

                        if ($lg=='Ing'){
                            switch($cat){
                                case "Longa" : $catIng = 'FEATURES'; break;
                                case "Media" : $catIng = 'MEDIUN-FORMAT'; break;
                                case "Curta" : $catIng = 'SHORT FILMS'; break;
                            }
                            $categoria = "CINEMA LITTLE EXHIBIT • ".$catIng;
                        } else {
                            $categoria = "MOSTRINHA • ".$cat;
                        }

                        break;

                    case 'SE': $categoria = "SEMINÁRIO";
                        $categoria = $lg=='Ing' ? "SEMINARS" : "SEMINÁRIO";

                        /*if ($rowProg->CodItemProg == 60) {
                            $categoria = $categoria." - ABERTURA OFICIAL";
                        }*/

                        $SqlTit = "select tituloSeminario, tituloSeminarioIng, tematica from tb_seminarios 
                                            where codSeminario = $rowProg->CodItemProg";
                        @$resultTit  = $pdo->query($SqlTit);
                        @$resultTit = $resultTit->fetchObject();
                        @$titulo	= $resultTit->tituloSeminario;
                        @$tematica	= $resultTit->tematica;

                        if($tematica)
                        {
                            $SqlTem = "select titTematica from tb_tematica where codTematica = $tematica";
                            $resultTem  = $pdo->query($SqlTem);
                            $r = $resultTem->fetchObject();
                            $TitTematica	= $r->titTematica;
                            $categoria .= " • ".$TitTematica;
                        }

                        //$url = "seminario-detalhe.php?menu=programacao&item=seminario&CodSem=$rowProg->CodItemProg";
                        $url = $this->url('cineop2017/seminar', ['id'=>$rowProg->CodItemProg]);
                        break;
                    case 'AR': $SqlTit = "select TitArte, TitArteIng, CodCatArte from tb_arte where CodArte = $rowProg->CodItemProg";
                        $resultTit  = $pdo->query($SqlTit);
                        $resultTit = $resultTit->fetchObject();
                        $titulo	= $resultTit->TitArte;
                        $CodCatArte	= $resultTit->CodCatArte;
                        //@$resultCat  = mysql_query($SqlCat);
                        //@$cat = utf8(mysql_result($resultCat,0,"TitCatArte"));
                        $categoria = $lg=='Ing' ? "ART" : "ARTE • ".$cat;
                        //$url = "arte-detalhe.php?menu=programacao&item=arte&CodArte=$rowProg->CodItemProg";
                        $url = $this->url('cineop2017/arte', ['id'=>$rowProg->CodItemProg]) . '/?CodArte='.$rowProg->CodItemProg;
                        $preEstreia = "";
                        break;
                    case 'AB': $categoria = "ABERTURA";
                        $categoria = $lg=='Ing' ? "OPENING" : "ABERTURA";
                        $SqlTit = "select TitAbertura, TitAberturaIng, DescAbertura, DescAberturaIng from tb_abertura 
                                            where CodAbertura = $rowProg->CodItemProg";
                        $resultTit  = $pdo->query($SqlTit);
                        $resultTit = $resultTit->fetch();
                        $titulo	= $resultTit->TitAbertura;
                        $descricao	= $resultTit->DescAbertura;
                        $url = $this->url('cineop2017') . 'abertura/';
                        break;
                    case 'EX': $categoria = "EXPOSIÇÃO";
                        $categoria = $lg=='Ing' ? "EXPOSITION" : "EXPOSIÇÃO";
                        $SqlTit = "select TitExpo, TitExpoIng from tb_exposicao where CodExpo = $rowProg->CodItemProg";
                        $resultTit  = $pdo->query($SqlTit);
                        $r = $resultTit->fetchObject();
                        $titulo	= $r->TitExpo;
                        $url = $this->url('cineop2017') . 'exposicao/';
                        $preEstreia = "";
                        break;
                    case 'EN': $categoria = "ENCERRAMENTO";
                        $categoria = $lg=='Ing' ? "CLOSING" : "ENCERRAMENTO";
                        $SqlTit = "select TitEnc, TitEncIng, DescEnc, DescEncIng from tb_encerramento 
                                            where CodEnc = $rowProg->CodItemProg";

                        $resultTit  = $pdo->query($SqlTit);
                        $r = $resultTit->fetchObject();
                        $titulo	= $r->TitEnc;

                        $descricao	= $r->DescEnc;
                        $url = $this->url('cineop2017') . 'encerramento/';
                        $preEstreia = "";
                        break;
                }

                $titulo = isset($titulo) ? utf8($titulo) : '';
                $direcao = isset($direcao) ? utf8($direcao) : '';

                /*if(isset($preEstreia)) {
                    if($preEstreia) {
                        $titulo .= " - PRÉ-ESTREIA NACIONAL";
                    }
                }*/

                $local = $rowProg->Local;
                if ($local != "") {
                    $SqlLoc = "SELECT TitLocal, TitLocalIng FROM tb_local WHERE CodLocal = $local";
                    $resultLoc  = $pdo->query($SqlLoc);

                    $linhas = $resultLoc->fetchObject();
                    if ( $linhas){
                        $localImp	= utf8($linhas->TitLocal);
                        $local	= utf8($linhas->TitLocal);
                    }
                }
                ?>

                <?php
                $data2 = explode("/", $data);
                if ($lg=='Ing'){
                    $dataFinalImp = $data2[1]."-".$data2[0];
                    $diaSemanaImp = utf8(formata_data_extensoIng(".$dataOrig."));
                } else {
                    $dataFinalImp = $data2[0]."/".$data2[1];
                    $diaSemanaImp = utf8(formata_data_extenso(".$dataOrig."));
                }

                $dataFinal = $data2[0]."/".$data2[1];
                $diaSemana = utf8(formata_data_extenso(".$dataOrig."));
                ?>

                <?php if ($dataFinal != $dataAnterior) { ?>
                    <tr>
                        <td colspan="2" class="titListaProg" style="padding-top: 15px; border-left: none;">
                            <?php echo $dataFinalImp?> | <?php echo $diaSemanaImp?>
                        </td>
                    </tr>
                    <?php
                    $dataAnterior = $dataFinal;
                }
                ?>




                <?php
                $cat = isset($cat) ? $cat : "";

                if ($cat == "Sessão de Curtas" || $cat == "Media") {
                    $countCurta = $countCurta+1;
                } else {
                    $countCurta = 0;
                }


                if ($dataFinal == '23/06' && $horario == '16h30'){
                    //$countCurta = 1;
                    $limitCurta = 13;
                } elseif ($dataFinal == '23/06' && $horario == '17h30'){
                    //$countCurta = 1;
                    $limitCurta = 17;
                } elseif ($dataFinal == '23/06' && $horario == '19h'){
                    //$countCurta = 1;
                    $limitCurta = 21;
                } elseif ($dataFinal == '23/06' && $horario == '22h45'){
                    //$countCurta = 1;
                    $limitCurta = 21;
                } elseif ($dataFinal == '24/06' && $horario == '18h45'){
                    //$countCurta = 1;
                    $limitCurta = 3;
                } elseif ($dataFinal == '24/06' && $horario == '19h30'){
                    //$countCurta = 1;
                    $limitCurta = 14;
                } elseif ($dataFinal == '24/06' && $horario == '20h'){
                    //$countCurta = 1;
                    $limitCurta = 18;
                } elseif ($dataFinal == '25/06' && $rowProg->CodProgEvento == 5571){
                    $countCurta = 1;
                    $limitCurta = 2;
                } elseif ($dataFinal == '25/06' && $rowProg->CodProgEvento == 5572){
                    $countCurta = 1;
                    $limitCurta = 2;
                } elseif ($dataFinal == '25/06' && $horario == '22h' && $rowProg->CodProgEvento == 5575){
                    $countCurta = 1;
                    $limitCurta = 2;
                } elseif ($dataFinal == '25/06' && $horario == '22h' && $rowProg->CodProgEvento == 5574){
                    $countCurta = 1;
                    $limitCurta = 2;
                } elseif ($dataFinal == '25/06' && $horario == '22h' && $rowProg->CodProgEvento == 5576){
                    $countCurta = 1;
                    $limitCurta = 2;
                }

                ?>
                <tr
                    <?php
                    if( ($countCurta > 0 && $countCurta < $limitCurta && $rowProg->CodProgEvento != 5408)
//                        ||($rowProg->CategoriaProg == "AB")
//                        ||($rowProg->CodProgEvento == 5341)
                        ||($rowProg->CodProgEvento == 5482)
                        ||($rowProg->CodProgEvento == 5538)
                        ||($rowProg->CodProgEvento == 5537)
                        //||($rowProg->CodProgEvento == 3132)

                        /*||($rowProg->CodItemProg == 13028)
                        ||($rowProg->CodItemProg == 12638)
                        ||($rowProg->CodItemProg == 13136 && $local=="CINE SANTA TEREZA") */
                        //||($rowProg->CategoriaProg == "EN")
                        //||($rowProg->CategoriaProg == "EX" && $rowProg->CodItemProg == 13 && $dataFinal == '01/10' && $horario == '10h')
                    )
                    {
                        echo "style='border: none;'";
                    }

                    ?> >


                    <th valign="top">
                        <h5>
                            <?php //if($rowProg->CodProgEvento == 18177){$horarioImp = ""; $horarioFimImp="";}?>
                            <?php
                                if (($horaAnterior != $horario || $localAnterior != $local) || $rowProg->CategoriaProg == "EN" || $rowProg->CodProgEvento == 5360 || $rowProg->CodProgEvento == 5367 || $rowProg->CodProgEvento == 5375 || $rowProg->CodProgEvento == 5351 || $rowProg->CodProgEvento == 5346 || $rowProg->CodProgEvento == 5368 || $rowProg->CodProgEvento == 5408) {
                                    if($rowProg->CodProgEvento == 5358) {
                                        echo "01h50";
                                    } elseif($rowProg->CodProgEvento == 5335) {
                                        echo "01h30";
                                    } elseif ($rowProg->CodProgEvento == 5408) {
                                        echo "01H45 ÀS 02H45";
                                    } else {
                                        echo $horarioImp;echo $horarioFimImp;
                                    }
                                }
                            ?>
                        </h5>
                        <span style="font-size: 12px;">

                        <?php if (($horaAnterior != $horario || $localAnterior != $local) || $rowProg->CategoriaProg == "EN" || $rowProg->CodProgEvento == 5360 || $rowProg->CodProgEvento == 5367 || $rowProg->CodProgEvento == 5375 || $rowProg->CodProgEvento == 5351 || $rowProg->CodProgEvento == 5346 || $rowProg->CodProgEvento == 5368 || $rowProg->CodProgEvento == 5408) { ?>
                            <?php if ($rowProg->CodItemProg != 18177) { ?>
                                <?php echo $localImp?>
                            <?php } ?>
                        <?php } ?>
                        </span>
                    </th>

                    <td valign="top">

                        <?php //echo "contCurta: " . $countCurta . " | limiteCurta: " . $limitCurta . " | horaAnterior: $horaAnterior | horario: $horario | LocalAnterior: $localAnterior | Local: $local | CodProg: $rowProg->CodItemProg | CodProdEvento: $rowProg->CodProgEvento"; ?>
                        <?php if($cat == "Sessão de Curtas")
                        { echo "<a name='curta'></a>";
                        }?>

                        <?php if (($horaAnterior != $horario
                                || $localAnterior != $local
                                || $cat != "Sessão de Curtas"
                                || $rowProg->CodItemProg == 12030
                            ) and $rowProg->CodItemProg != 17970 && $rowProg->CodItemProg != 18179 && $rowProg->CodItemProg != 17634 && $rowProg->CodItemProg != 18039)
                        {?>



                            <h5 <?php if($cat == "Sessão de Curtas")

                            { echo "style='margin-bottom:10px;'"; }?>>



                                <?php

                                //if($rowProg->CategoriaProg == "SE" && $rowProg->CodItemProg == 199)
                                //	{
                                //		echo "<p>DEBATE INAUGURAL</p>";
                                //	}

                                if ($rowProg->CategoriaProg == 'AB' || $rowProg->CategoriaProg == 'EN' || $rowProg->CodProgEvento == 3138)
                                {
                                    echo "<span style='color:#000;'>".$categoria."</span>";
                                }
                                /*elseif ($titulo == 'ENCERRAMENTO')
                                    {
                                        echo "ENCERRAMENTO";
                                    }*/
                                else
                                {
                                    if($rowProg->CodProgEvento != 17970)
                                    {


                                        ?>

                                        <?php

                                        if ($rowProg->preMundial == 1) {

                                            $pe = " • PRÉ-ESTREIA MUNDIAL";
                                        } else if ($rowProg->preNacional == 1) {
                                            $pe = " • PRÉ-ESTREIA NACIONAL";
                                        } else {
                                            $pe = "";
                                        }

                                        if($rowProg->CodItemProg == 213 && $horario == "23h" ){$pe="SHOW MUSICAL";}
                                        elseif($rowProg->CodItemProg == 17970 && $horario != "20h30" ){$categoria = "";}
                                        elseif($rowProg->CodItemProg == 18178 && $horario != "20h30" ){$categoria = "HISTÓRICA • CURTA E LONGA";}
                                        elseif($rowProg->CodItemProg == 17986){$categoria = "CONTEMPORÂNEA • MEDIAS";}
                                        elseif($rowProg->CodItemProg == 18179 && $horario != "20h30" ){$categoria = "";}
                                        elseif($rowProg->CategoriaProg == "SE"){$pe = "";}
                                        elseif($rowProg->CategoriaProg == "EN"){$categoria = "ENCERRAMENTO";}
                                        elseif($rowProg->CategoriaProg == "FI" && $rowProg->CodItemProg == 14053){$pe = "";}
                                        if($rowProg->CodProgEvento == 3090 || $rowProg->CodProgEvento == 3102 || $rowProg->CodProgEvento == 3108 || $rowProg->CodProgEvento == 3109){$categoria = str_replace("Sessão de Curtas", "Curta", $categoria);}
                                        ?>

                                        <a href="<?php echo !empty($url)&&is_string($url) ? $url : "" ?>"><?php echo $categoria; ?> <?php echo $pe;?>
                                            <?php if($cat == "Sessão de Curtas" && $dataFinal == '22/10' && $horario == '19h30') {?>
                                                - Recomendado para maiores de 16 anos
                                            <?php } ?>
                                            <?php if($cat == "Sessão de Curtas" && $dataFinal == '23/10' && $horario == '20h') {?>
                                                - Série Especial
                                            <?php } ?>
                                            <?php if($rowProg->CategoriaProg == 'FI' && $dataFinal == '24/10' && $horario == '17h') {?>
                                                - Sessão Família
                                            <?php } ?>
                                        </a>
                                    <?php } }				?>
                            </h5>
                        <?php } ?>
                        <h6>
                            <?php if ($rowProg->CategoriaProg == 'AB' || $rowProg->CategoriaProg == 'EN') {
                                echo $descricao;
                            } else if(is_array($titulo))
                            {
                                $a = count($titulo);
                                for($i = 0; $i < $a; $i++)
                                {
                                    ?><a href="<?php echo $url?>"><strong><?php echo utf8($titulo[$i])?></strong></a> |

                                    <?php
                                    if ($lg=='Ing'){
                                        $direc = str_replace(' e ',' and ',$direcao[$i]);
                                    }else{$direc = $direcao[$i];}

                                    if($direc != ""){
                                        ?>
                                        <span class="subItemListaMenor" style="font-size: 10px;"><?php echo isset($Dir) ? $Dir : '' ?>: <?php echo ($direc)?></span><br /><br />
                                    <?php }
                                }
                                unset($titulo);
                                unset($url);
                                unset($direcao);



                            } else if ($rowProg->CodProgEvento == 3138) {
                                echo $titulo;
                            } else { ?>
                                <a href="<?php echo $url?>"><strong><?php echo $titulo?></strong></a>
                                <?php if ($rowProg->CategoriaProg == 'FI' || $rowProg->CategoriaProg == 'SCE' || $rowProg->CategoriaProg == 'MO') { ?>
                                    |
                                    <?php
                                    if ($lg=='Ing'){
                                        $direcao = str_replace(' e ',' and ',$direcao);
                                    }
                                    ?>
                                    <span class="subItemListaMenor" style="font-size: 10px;"><?php echo isset($Dir) ? $Dir : ''?>: <?php echo $direcao?></span>
                                <?php }
                                ?>
                            <?php } ?>
                        </h6>

                        <!-- FAIXA ETÁRIAS -->
                        <?php

                        if($rowProg->infoAdicional != "" ){ echo "<span class='subItemListaMenor'><strong style='font-size: 11px;'>(".uft8_decode($rowProg->infoAdicional).")</strong></span>";}


                        $frase = $lg=='Ing' ? "Recommended for ages" : "* Faixa etária sugerida: a partir de";
                        $anos = $lg=='Ing' ? "older" : "anos";
                        $texto = "<br /><span class='subItemListaMenor'><strong style='font-size: 10px; font-style: italic;'>$frase ";
                        if(isset($faixaEtaria1) && $faixaEtaria1 != "" && $faixaEtaria1 != "0") {

                            if($rowProg->mostraClassificacao == 1 ){echo $texto . $faixaEtaria1 . " $anos</strong></span>";}

                        }

                        if($rowProg->CodProgEvento == 3156) {
                            echo $texto . "12 anos</strong></span>";
                        }



                        if($rowProg->CodProgEvento == 3157) {
                            echo $texto . "12 anos</strong></span>";
                        }


                        ?>

                    </td>
                </tr>
                <?php
                $horaAnterior = $horario;
                $localAnterior = $local;
                $horarioFim = "";
                $horarioFimImp = "";
                }
                ?>
            </table>
        </section>
    </div>
</main>