<?php
try {
    $pdo = new \PDO('mysql:host=162.243.253.29;dbname=universoprod2', "universoprod2", "ag51www", array(PDO::MYSQL_ATTR_INIT_COMMAND => "SET NAMES utf8"));
    $pdo->setAttribute(\PDO::ATTR_ERRMODE, \PDO::ERRMODE_EXCEPTION);
} catch(\Exeception $e) {
    echo 'ERROR: ' . $e->getMessage();
    exit;
}
function databr($valor)
{
    $valor = substr($valor,8,2) . "/" . substr($valor,5,2) . "/" . substr($valor,0,4);
    return $valor;
}

function databr2($valor)
{
    $valor = substr($valor,8,2) . "." . substr($valor,5,2) . "." . substr($valor,0,4);
    return $valor;
}

function data_USA($valor1){
    $valor1 = substr($valor1,6,4) . "-" . substr($valor1,3,2) . "-" . substr($valor1,0,2);
    return $valor1;
}
function hora($valor)
{
    if ($valor == '00:00:00') {
        $texto = "";
    } else {
        $texto = date('H:i', strtotime($valor));
        $texto = str_replace(':','h',$texto);
        $texto = str_replace('h00','h',$texto);
    }
    return $texto;
}
function formata_data_extenso($strDate)
{
    // Array com os dia da semana em português;
    $arrDaysOfWeek = array('domingo', 'segunda', 'terça', 'quarta', 'quinta', 'sexta', 'sábado');
    // Array com os meses do ano em português;
    $arrMonthsOfYear = array(1 => '01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12');
    // Descobre o dia da semana
    $intDayOfWeek = date('w',strtotime($strDate));
    // Descobre o dia do mês
    $intDayOfMonth = date('d',strtotime($strDate));
    // Descobre o mês
    $intMonthOfYear = date('n',strtotime($strDate));
    // Descobre o ano
    $intYear = date('Y',strtotime($strDate));
    // Formato a ser retornado
    return $arrDaysOfWeek[$intDayOfWeek];
}
function is_utf8($str)
{
    $c=0; $b=0;
    $bits=0;
    $len=strlen($str);
    for($i=0; $i<$len; $i++)
    {
        $c=ord($str[$i]);
        if($c > 128)
        {
            if(($c >= 254)) return false;
            elseif($c >= 252) $bits=6;
            elseif($c >= 248) $bits=5;
            elseif($c >= 240) $bits=4;
            elseif($c >= 224) $bits=3;
            elseif($c >= 192) $bits=2;
            else return false;
            if(($i+$bits) > $len) return false;
            while($bits > 1)
            {
                $i++;
                $b=ord($str[$i]);
                if($b < 128 || $b > 191) return false;
                $bits--;
            }
        }
    }
    return true;
}

function utf8($string)
{
    if (is_utf8($string))
    {
        return $string;
    } else {
        return utf8_encode($string);
    }
}

$mostra = 1076;
$lg = '';
$url = '';
$fc = $fl = $sub = $subMostra = $fSub1 = $fSub2 = $fSub3 = '';
//$limitCurta = 0;
$Dir = "Direção";
?>



<?php

$CodFilme = $this->idMovie;
//exit(var_dump($CodFilme));

$result		= $pdo->query("SELECT * FROM tb_obras WHERE codObra = $CodFilme");
$res = $result->fetchObject();

$TituloFilme	= utf8_encode($res->TituloObra);
$AnoProducao	= $res->AnoProducaoObra;
$UfProducao		= $res->ufProducaoObra;
$PaisProducao	= utf8_encode($res->paisProducao);
$Duracao		= $res->DuracaoObra;
$Formato		= $res->Formato;
$Cor			= $res->ColoracaoObra;
$Genero1		= $res->Genero;
$Direcao		= utf8_encode($res->DirecaoObra);
$Sinopse		= utf8_encode($res->Sinopseobra);
$Foto			= $res->fotoFilme;
$CreditoFoto	= utf8_encode($res->CreditoFoto);
$CineEscola		= $res->CineEscola;
$Mostrinha		= $res->ExibirMostrinha;
$ProgramacaoOficial	= $res->ProgramacaoOficial;
$Categoria		= $res->classeObra;
$CategoriaConv		= $res->CategoriaConvidado;
$FilmeConvidado		= $res->FilmeConvidado;
$faixaEtaria1	= $res->FaixaEtaria1;
$faixaEtaria2	= $res->FaixaEtaria2;
$ClassificacaoObra	= $res->ClassificacaoObra;

$elencoObra		= utf8_encode($res->ElencoObra);
$empresaProdutoraObra	= utf8_encode($res->EmpresaProdutoraObra);



if ($FilmeConvidado != 1) {

    $result2		= $pdo->query("SELECT * FROM tb_filmemostra WHERE CodFilme = $CodFilme");
    $result2 = $result2->fetchObject();
    $SubMostra		= $result2SubMostra;

    $cob = '0';
    switch($Categoria){
        case "1" : $cob = 'Longa'; break;
        case "2" : $cob = 'Media'; break;
        case "3" : $cob = 'Curta'; break;
    }

    $caminhoFoto1 = "http://cinemasemfronteiras.com.br/admin/imagens/filmes/inscritos/".$Foto;

} else {
    $SubMostra	= $res->SubMostra;
    $cob = $CategoriaConv;
    $caminhoFoto1 = "http://cinemasemfronteiras.com.br/admin/imagens/filmes/convidados/".$Foto;
}

if($Genero1 == 'animacao') $Genero1 = "Animação";
elseif($Genero1 == 'acao') $Genero1 = "Ação";
elseif($Genero1 == 'arte') $Genero1 = "Arte";
elseif($Genero1 == 'comedia') $Genero1 = "Comédia";
elseif($Genero1 == 'documentario') $Genero1 = "Documentário";
elseif($Genero1 == 'drama') $Genero1 = "Drama";
elseif($Genero1 == 'experimental') $Genero1 = "Experimental";
elseif($Genero1 == 'ficcao') $Genero1 = "Ficção";
elseif($Genero1 == 'videoclipe') $Genero1 = "Vídeo Clipe";
elseif($Genero1 == "") $Genero1 = "";
else return false;

if ($AnoProducao != ""){ $AnoProducao	= ", ".$AnoProducao; }
if ($UfProducao != ""){ $UfProducao		= ", ".$UfProducao; }
if ($PaisProducao != ""){ $PaisProducao	= ", ".$PaisProducao; }

if ($Duracao != ""){

    if ($FilmeConvidado != 1) {

        $h=substr($Duracao,0,2);
        $m=substr($Duracao,3,2);
        $s=substr($Duracao,6,2);

        $Duracao = $h*60+$m;

        $Duracao = ", ".$Duracao."min";
    } else {
        if (utf8($Duracao) == "até 45 min") {
            $Duracao = ", ".utf8($Duracao);
        } else {
            $Duracao = ", ".$Duracao."min";
        }

    }

}




if ($Formato != "" && $Formato != 0){
    $resultFmt  = $pdo->query("SELECT nomeFormato FROM tb_formatos WHERE codFormato = $Formato");
    $resultFmt = $resultFmt->fetchObject();
    $Formato	= $resultFmt->nomeFormato;

    if ($Formato != "35mm") {
        $Formato = "Digital";
    }


    $Formato	= ", ".$Formato;
}

if ($Cor == "1") {
    $Cor = ", Preto & Branco";
}
if ($Cor == "2") {
    $Cor = ", Cor";
}
if ($Cor == "0") {
    $Cor = "";
}
?>

<section class="main-wrapper main-content">
    <header class="main-header">
        <h1 class="main-title"><?php echo $TituloFilme; ?></h1>
    </header>
    <div class="filmedetalhe">
        <p class=""><strong>Direção: <?php echo $Direcao?></strong></p>
        <p style="font-size: 16px"><?php echo $Genero1?><?php echo $Cor?><?php echo $Formato?><?php echo $Duracao?><?php echo $AnoProducao?><?php echo $UfProducao?><?php echo $PaisProducao?></p>
        <?php
            $Faixa1 = $faixaEtaria1;
            $Faixa2 = $faixaEtaria2;
            if ($ClassificacaoObra == "livre") {
                $Class = $ClassificacaoObra;
            } else {
                $Class = $ClassificacaoObra." anos";
            }
            if (($Faixa1 == 0) && ($Faixa2 == 0)) {
                $FaixaEtaria = $Class;
            } else if (($Faixa1 == 0) && ($Faixa2 != 0)) {
                $FaixaEtaria = "até ".$Faixa2." anos.";
            } else if (($Faixa1 != 0) && ($Faixa2 == 0)) {
                $FaixaEtaria = "a partir de ".$Faixa1." anos.";
            } else if (($Faixa1 != 0) && ($Faixa2 != 0)) {
                $FaixaEtaria = "".$Faixa1." a ".$Faixa2." anos.";
            }
        ?>
        <p style="font-size: 16px">Faixa etária sugerida: <?php echo $FaixaEtaria?></p>
        <?php
        if ($Foto != ""): ?>
            <figure>
                <img src="<?php echo $caminhoFoto1?>" width="625" alt="<?php echo $TituloFilme?>" border="0" />
                <?php if ($CreditoFoto != ""): ?>
                    <figcaption>Foto: <?php echo $CreditoFoto?></figcaption>
                <?php endif; ?>
            </figure>
        <?php endif; ?>

        <div class="sinopse">
            <p><h2><strong>Sinopse:</strong></h2></p>

            <p><?php echo $Sinopse?></p>

            <?php if($elencoObra): ?>
                <p>Elenco: <?php echo ($elencoObra)  ?></p>
            <?php endif; ?>

            <?php if($empresaProdutoraObra): ?>
                <p>Empresa Produtora: <?php echo $empresaProdutoraObra?></p>
            <?php endif; ?>
        </div>
        <?php

        if ($cat == "CINE-ESCOLA") {
            $resultProg  = $pdo->query("SELECT count(*), CodItemProg, CategoriaProg, Local, Data, HoraManhaInicial FROM tb_programacaoevento WHERE CodItemProg = $CodFilme AND CategoriaProg = 'CE' AND CodMostra = '$mostra' order by Data, HoraManhaInicial");
        } else {
            $resultProg  = $pdo->query("SELECT count(*), CategoriaProg, Local, Data, HoraManhaInicial FROM tb_programacaoevento WHERE CodItemProg = $CodFilme AND (CategoriaProg = 'FI' || CategoriaProg = 'MO') AND CodMostra = '$mostra' order by Data, HoraManhaInicial");
        }

        $linhas = $resultProg->fetchAll(\PDO::FETCH_OBJ);

        if ( $linhas > 0 ){
            if ( $linhas == 1 ){

                $resPPP = $linhas[0];

                $dataOrig = $resPPP->Data;
                $data = databr($dataOrig);
                $data2 = explode("/", $data);
                $dataFinal = $data2[0]."/".$data2[1];
                $hora = hora($resPPP->HoraManhaInicial);
                $diaSemana = utf8(formata_data_extenso(".$dataOrig."));



                $local = $resPPP->Local;
                if ($local != "") {
                    $SqlLoc = "SELECT TitLocal FROM tb_local WHERE CodLocal = $local";
                    $resultLoc  = $pdo->query($SqlLoc);
                    $resultLoc = $resultLoc->fetchObject();
                    $linhas = $resultLoc->$resultLoc;
                    if ( $linhas > 0 ){
                        $local	= utf8($resultLoc->TitLocal);
                    }
                }
                ?>
                <p><h2><strong>EXIBIÇÃO</strong></h2></p>
                <p>
                    <?php echo $dataFinal?> | <?php echo $diaSemana?> • <?php echo $hora?><br />
                    <?php echo $local?>
                </p>
                <?php
            } else {
                ?>
                <h5>EXIBIÇÕES</h5>
                <?php
                $i=0;
                foreach ($linhas as $row) {
                    $dataOrig = $row->Data;
                    $data = databr($dataOrig);
                    $data2 = explode("/", $data);
                    $dataFinal = $data2[0]."/".$data2[1];
                    $hora = hora($row->HoraManhaInicial);
                    $diaSemana = utf8(formata_data_extenso(".$dataOrig."));


                    $local = $row->Local;
                    if ($local != "") {
                        $SqlLoc = "SELECT TitLocal FROM tb_local WHERE CodLocal = $local";
                        $resultLoc  = $pdo->query($SqlLoc);
                        $resultLoc = $resultLoc->fetchObject();
//                        $linhas = mysql_num_rows($resultLoc);
                        if ( $linhas > 0 ){
                            $local	= utf8($resultLoc->TitLocal);
                        }
                    }

                    ?>

                    <p style="margin-bottom: 6px;"><span style="color: #000;"><?php echo $dataFinal?> | <?php echo $diaSemana?> • <?php echo $hora?></span><br />
                        <?php echo $local?>
                    </p>

                    <?php
                }
            }
        }

//        mysql_free_result($resultProg);
        ?>

    </div>
</section>