<?php
/**
 * Created by PhpStorm.
 * User: Ricardo Viana
 * Date: 17/12/2017
 * Time: 11:09
 */

namespace Admin\Form\Seminar;

use Application\Entity\Event\Event;
use Application\Entity\Event\EventType;
use Application\Entity\Form\Form as EntityForm;
use Application\Entity\Registration\Options;
use Application\Entity\Registration\Registration;
use Application\Entity\Registration\Status;
use Application\Entity\Registration\Type;
use Application\Entity\Workshop\Workshop;
use Zend\Form\Fieldset;
use Zend\Form\Form;
use Zend\InputFilter\Factory as InputFilterFactory;

class SeminarSubscriptionForm extends Form
{
    private $entityManager;
    private $registration;
    private $event;

    public function __construct($em, $registration=null, $event=null)
    {
        if($em) {
            $this->entityManager = $em;
        }

        if($registration) {
            $this->registration = $registration;
        }

        if($event) {
            $this->event = $event;
        }

        parent::__construct('seminar-subscription-form');
        $this->setAttributes([
            'id' => 'seminar-subscription-search',
            'class' => 'default-form-actions form-reload'
        ]);

        $this->add([
            'type' => 'hidden',
            'name' => 'user',
            'attributes' => [
                'class' => 'input-sm',
                'id' => 'user'
            ]
        ]);

        $this->add([
            'type' => 'hidden',
            'name' => 'debates[]',
        ]);

        $this->add([
            'type' => 'Select',
            'name' => 'registration',
            'options' => [
                'label' => 'Regulamento',
                'empty_option' => 'Selecione',
                'value_options' => $this->populateRegulations(),
            ],
            'attributes' => [
                'required' => true,
                'class' => 'trigger-form-reload',
            ]
        ]);

    }

    public function populateRegulations()
    {
        $regulations = [];
        if($this->getEntityManager()) {
            $coll = $this
                ->getEntityManager()
                ->getRepository(Registration::class)
                ->findBy([
                    'type' => Type::SEMINAR
                ], ['startDate'=>'DESC']);

            foreach ($coll as $c) {
                $regulations[$c->getId()] = $c->getName();
            }
        }
        return $regulations;
    }

    public function setData($data)
    {
        if(!empty($data['user']) && is_object($data['user'])) {
            $user = $data['user'];
            $data['user'] = $user->getId();
        }

        return parent::setData($data); // TODO: Change the autogenerated stub
    }

    /**
     * @return mixed
     */
    public function getEntityManager()
    {
        return $this->entityManager;
    }

    /**
     * @param mixed $entityManager
     */
    public function setEntityManager($entityManager)
    {
        $this->entityManager = $entityManager;
    }

    /**
     * @return Registration
     */
    public function getRegistration()
    {
        return $this->registration;
    }

    /**
     * @param null $registration
     */
    public function setRegistration($registration)
    {
        $this->registration = $registration;
    }

    /**
     * @return null
     */
    public function getEvent()
    {
        return $this->event;
    }

    /**
     * @param null $event
     */
    public function setEvent($event)
    {
        $this->event = $event;
    }
}