<?php
/**
 * Created by PhpStorm.
 * User: Ricardo Viana
 * Date: 02/02/2016
 * Time: 09:57
 */

namespace Admin\Form\ExternalUser;

use Application\Entity\Phone\PhoneType;
use Zend\Form\Form;

class DependentForm extends Form
{
	public function __construct()
	{
	    parent::__construct('dependent');

		$this->add([
		    'name' => 'dependent_name',
            'options' => [
                'label' => 'Nome',
                'twb-layout' => 'horizontal',
                'column-size' => 'md-6',
                'label_attributes' => [
                    'class' => 'col-md-4'
                ]
            ],
            'attributes' => [
                'id' => 'dependent_name'

            ]
        ]);

        $this->add([
            'type' => 'select',
            'name' => 'dependent_gender',
            'options' => [
                'label' => 'Sexo',
                'twb-layout' => 'horizontal',
                'column-size' => 'md-6',
                'label_attributes' => [
                    'class' => 'col-md-4'
                ],
                'empty_option' => 'Selecione',
                'value_options' => [
                    'm' => 'Masculino',
                    'f' => 'Feminino'
                ]
            ],
            'attributes' => [
                'id' => 'dependent_gender'
            ]
        ]);

        $this->add([
            'name' => 'dependent_birth_date',
            'type' => 'TwbBundle\Form\Element\DatePicker',
            'options' => [
                'label' => 'Data de Nascimento',
                'twb-layout' => 'horizontal',
                'column-size' => 'md-6',
                'label_attributes' => [
                    'class' => 'col-md-4'
                ]
            ],
            'attributes' => [
                'data-inputmask' => "'alias': 'dd/mm/yyyy', 'placeholder':'_'",
                'id' => 'dependent_birth_date'
            ]
        ]);

        $this->add([
            'name' => 'dependent_identifier',
            'options' => [
                'label' => 'Documento',
                'twb-layout' => 'horizontal',
                'column-size' => 'md-6',
                'label_attributes' => [
                    'class' => 'col-md-4'
                ]
            ],
            'attributes' => [
                'id' => 'dependent_identifier',
                'placeholder' => 'CPF ou identidade'
            ]
        ]);
	}

	public function setData($data)
    {
        if(isset($data['name'])) {
            $data['dependent_name'] = $data['name'];
        }

        if(isset($data['gender'])) {
            $data['dependent_gender'] = $data['gender'];
        }

        if(isset($data['birth_date'])) {
            $data['dependent_birth_date'] = $data['birth_date'];
        }

        if(isset($data['identifier'])) {
            $data['dependent_identifier'] = $data['identifier'];
        }

        return parent::setData($data); // TODO: Change the autogenerated stub
    }
}