<main class="main">
    <?php if($this->breadcrumbs): ?>
        <?php echo $this->partial('cineop2017/partials/_breadcrumbs.phtml', ['breadcrumbs'=>$this->breadcrumbs]); ?>
    <?php endif; ?>

    <div class="main-wrapper">
        <section class="main-content">
            <header class="main-header">
                <h1 class="main-title"><?php echo $this->post->getTitle(); ?></h1>
            </header>
            <?php echo $post->getContent(); ?>
        </section>
    </div>
</main>