<main class="main">
    <?php if($this->breadcrumbs): ?>
        <?php echo $this->partial('cineop2017/partials/_breadcrumbs.phtml', ['breadcrumbs'=>$this->breadcrumbs]); ?>
    <?php endif; ?>

    <div class="main-wrapper">
        <section class="main-content">
            <header class="main-header">
                <h1 class="main-title"><?php echo $this->post->getTitle(); ?></h1>
            </header>
            <div class="news-list">
                <?php foreach ($this->events as $event): ?>
                    <p>
                        <header class="news-header">
                            <h1 class="news-title"><?php echo $event->getFullName(); ?></h1>
                        </header>
                        <a href="<?php echo $this->url("cineop2017/edition", ['id'=>$event->getId()]) ?>" class="btn"><span>Leia mais</span></a>
                    </p>
                    <hr>
                <?php endforeach; ?>
            </div>
        </section>
    </div>
</main>